### ISSUE TITLE
Different addresses shown by MyEtherWallet vs Metamask, Light Wallet (bip44)

### ISSUE THREAD

**Issue by Drabiv** [kvhnuke/etherwallet#1013]
MyEtherWallet shows different addresses using standard derivation path (m/44'/60'/0'/0) than Metamask and Light Wallet (bip44).

**Comment by tayvano** [comment]
can you give me test case please?

**Comment by tayvano** [comment]
e.g. I  get the same address for MetaMask & MEW using `brain surround have swap horror body response double fire dumb bring hazard`

**Comment by Drabiv** [comment]
I have create mnemonic on Metamask, when I opened that mnemonic in MEW I see different addresses. Then I tried Light Wallet (bip44) and I see the same addresses as on MetaMask. Mnemonic used - `any enhance sock blind enroll nut diagram pulse engine manage round illness` Password - "test123456789"

**Comment by Drabiv** [comment]
@tayvano I see different addresses for your mnemonic.
Here the first addresses:
0x7b4322B9ABe447cE86fAa6121b35C84EC36945ad - in Metamask
0x7b4322b9abe447ce86faa6121b35c84ec36945ad - in LightWallet (bip44)
0xa228ebe854aa073b0cf8506034c925ff13c065c4 - in LightWallet (Consensys)
0x114D92A15d9ccAD1c076Bc83cd5e9b287735c6C8 - in MEW

**Comment by Drabiv** [comment]
Funny thing, there might be a glitch on LightWallet also. When I loaded LightWallet first time in bip44 mode it showed addresses as for Consensys mode, after I changed the modes it started to show correctly.  Although I am not sure about this glitch, I might have just confused something.

**Comment by tayvano** [comment]
Metamask: `0xB1431CF82B417d63Af4F1f6F6ec7B105791293Ab`

MEW w/o PW: `0xB1431CF82B417d63Af4F1f6F6ec7B105791293Ab`

MEW w/ PW: `0xF831457D6E53593ccA95cBF32b9945eCC815f24e`

**Comment by Drabiv** [comment]
Ok, I see now, so the issue was in password. So the mnemonic with password is not the same as mnemonic without password.
I guess in MetaMask password is created for application, not for mnemonic. If this is correct, this is a bit confusing on MetaMask side.

**Comment by tayvano** [comment]
In MetaMask, I believe the password is a screenlock. In MEW / Trezor / ??? the password for mnemonics follows the BIP spec. 

Simply using the 12-words from MetaMask in MEW, sans password, should result in same address-group.

**Comment by tayvano** [comment]
Let me know if you want to discuss further or have any other questions. Thanks!

**Comment by mehranhydary** [comment]
> Ok, I see now, so the issue was in password. So the mnemonic with password is not the same as mnemonic without password.
> I guess in MetaMask password is created for application, not for mnemonic. If this is correct, this is a bit confusing on MetaMask side.

Does that mean that there is no way to get the addresses from the MEW with password to the MEW without password?

**Comment by tayvano** [comment]
The mnemonic phrase + password is different than mnemonic phrase alone (no password). Each of these will give you different addresses. 

The MetaMask password is not actual a password for your phrase, it's a screen lock of sorts for MetaMask.
