### ISSUE TITLE
When do new translations become included?

### ISSUE THREAD

**Issue by nogo10** [kvhnuke/etherwallet#1018]
I committed and (got) merged a new translation to the mercury branch recently and I was wondering: hows / when does it become part of release?

**Comment by tayvano** [comment]
About 24 hours after it's been merged, depending on what else was merged at the time and the extent of testing / security that needs to be done

**Comment by nogo10** [comment]
mmm.. yes it is in the mercury branch..  what I meant: when does mercury branch become current?

**Comment by tayvano** [comment]
Yes. That is my answer: once things have been merged into mercury there is approximately 24 hours between the time it was merged and it goes live, depending on what is being merged. 

gh-pages is the live branch
