### ISSUE TITLE
Source information for `js/qrcode.min.js` library

### ISSUE THREAD

**Issue by bignose-debian** [kvhnuke/etherwallet#1026]
The file `js/qrcode.min.js` is tracked in the VCS for this code base, but is not source code. So it's not feasible to inspect or change it — it isn't effectively free software.

Please put into the VCS:

* What specific version is used by the current MyEtherWallet code.
* The information about where the library comes from, where it is maintained.
  This should be sufficiently detailed to allow any MyEtherWallet recipient to get the corresponding source code for inspection and modification.
* The copyright information: copyright holders, years of copyright, grant of license.
  This should be sufficiently detailed for the MyEtherWallet recipient to know what license they are granted for the library, and to know how its license interacts with the license grant received for MyEtherWallet.

**Comment by kvhnuke** [comment]
https://github.com/davidshimjs/qrcodejs

**Comment by bignose-debian** [comment]
@kvhnuke, thanks for the brief response. Can you answer all the rest of the specific questions that make up this issue?

**Comment by kvhnuke** [comment]
Hi @bignose-debian 
Thank you for bringing this to our attention
Since they only released one version we are currently using that version it is also MIT license 
We will incorporate information about all of our libraries in upcoming versions of MEW

**Comment by tayvano** [comment]
@bignose-debian Sorry for the delay. I thought kvhnuke was handling this. 

I have added the relevant information to the source. Please let me know if there is something I missed or can be of more help. Thanks.

**Comment by bignose-debian** [comment]
@tayvano, thanks for taking action.

> I have added the relevant information to the source.

That is helpful.

> Please let me know if there is something I missed or can be of more help.

What's missing is the actual source file :-) Effective exercise of their rights in the license requires that the recipient of this source code receive the actual source files used for making modifications and building from modified source.

The `js/qrcode.min.js` is not source; it is compiled from some other source file(s). That source (maybe `js/qrcode.js`?) is what a recipient will need to effectively make changes to the library. So that's what is needed in the source distribution. 

Ideally, the compiled non-source version would not be in the VCS, and the source files would be used to build and distribute MyEtherWallet. That way, *everyone* is getting a MyEtherWallet built from the very same source files.

Removing the compiled library isn't strictly necessary (though it would make it much more clear to the developers that the source files are used to generate the end result). What's needed is adding the actual source file to this source distribution — along with the information you've helpfully written.

**Comment by bignose-debian** [comment]
> Removing the compiled library isn't strictly necessary (though it would make it much more clear to the developers that the source files are used to generate the end result). What's needed is adding the actual source file to this source distribution […]

An alternative, but more extensive, improvement would be to not have this library in the MyEtherWallet source at all; instead, alter the build process so that it gets the library's source specific version required from a canonical source location, and builds from that.
