### ISSUE TITLE
Add UBQ derivation path

### ISSUE THREAD

**Issue by kemo** [kvhnuke/etherwallet#1030]
![Error message](https://i.imgur.com/f7gt4mP.png)

**Comment by DblD** [comment]
+1

**Comment by DblD** [comment]
bump

**Comment by tayvano** [comment]
Is the UBQ derivation path 44'/108'/1/0? Is this for Ledger or all mnemonics?

**Comment by jyap808** [comment]
Hi @tayvano, actually "m/44'/108'/0'/0" is the HD path for Ubiq Ledger

Screen shot:
![screen shot 2017-10-20 at 11 21 57 am](https://user-images.githubusercontent.com/710537/31842265-fd0355a0-b588-11e7-8fe8-a485b4ae3965.png)

Commit in Pyrus:
https://github.com/ubiq/pyruswallet/commit/5eda413964135561dc57eabf07f062d832422ece

cc: @iquidus

**Comment by iquidus** [comment]
A pull request has been submitted addressing this issue.

**Comment by jyap808** [comment]
@tayvano this can be closed now. Thanks!
