### ISSUE TITLE
Social Media Icon Sizes

### ISSUE THREAD

**Issue by MysticRyuujin** [kvhnuke/etherwallet#1048]
Not sure why but my local node (3.10.3.7) looks like this on Chrome:

![image](https://user-images.githubusercontent.com/8877131/30657677-0d28e0b4-9dfe-11e7-8407-15e4bfc8bd1c.png)

**Comment by tayvano** [comment]
LOL. Your cached wasn't cleared. Fixing it so tit won't happen in the future
