### ISSUE TITLE
Response may discourage passwords

### ISSUE THREAD

**Issue by apertamono** [kvhnuke/etherwallet#1055]
When I open a keybase file, the response is: "Your wallet is encrypted. Please enter the password." 

I'm sure this is meant to be a neutral request, but I can't help interpreting it as: "_What are you making me do now, you annoying little twerp? I can't fucking read this!_" Maybe this interpretation is colored by following MEW on Twitter. But never mind my precious feelings. I think we should encourage inexperienced users to use passwords, even though it means taking one more step.

Proposed fix: please change the string ADD_Label_3 to 'Your wallet is encrypted. Good! Please enter the password. '

**Comment by tayvano** [comment]
I love this! The message was certainly not intended to be taken that way. I'm not sure if this messaging has ever been updated, so thank you for taking the time!
