### ISSUE TITLE
PLAY token not displaying correct values

### ISSUE THREAD

**Issue by socme** [kvhnuke/etherwallet#1059]
On Friday 22 Sept. I created a custom token ie. PLAY successfully. After a successful transaction with HeroCoin I received the due number of PLAY tokens, I saw them in MEW.
The next day the received tokens are not showing, PLAY=0. I know another user that is having the same problem and Herocoin says there are others.

In another MEW, free of custom tokens, I now see PLAY in the Token List. This was not the case when I created a custom token on 22 September.

**Comment by vvasic** [comment]
submitted PR #1064

**Comment by tayvano** [comment]
Fixed by PR #1064
