### ISSUE TITLE
Hacked account

### ISSUE THREAD

**Issue by vangugus** [kvhnuke/etherwallet#1068]
My account [0x243dF9AAF881B033F770c62A6733837a8C3DBc69] has been completely emptied.
My ethers [2.839558979 ETH] have been transferred to an unknown account [0x2cb7064b07bc9d1af8eff8b113507007eacd4a43].
Here is the TxHash: 0x95145a3ac7eddba9423769cae70cfd8ab76d606b3b41700769f01ac8504470f9
But I never ordered this transaction !!!
I think other users were victims because I can see that 7 other transactions to this address took place at the same time, and what seems odd is that the other 7 addresses are empty too ...
What happened ??? Who ordered these transactions ???
Help me please

**Comment by Zwilla** [comment]
https://etherscan.io/address/0x2cb7064b07bc9d1af8eff8b113507007eacd4a43#comments

**Comment by tayvano** [comment]
@vangugus I'm sorry to hear that. Please read here: https://myetherwallet.groovehq.com/knowledge_base/topics/hacks-thefts-and-stolen-funds-due-to-phishing-links-between-7-slash-5-slash-2017-slackbot-scambot-phishing-slash-reddit-dm-slash and email us at support@myetherwallet.com if you would like to discuss more. 

Thank you.
