### ISSUE TITLE
Cannot execute contract method with address[] parameter

### ISSUE THREAD

**Issue by maxvgi** [kvhnuke/etherwallet#1081]
It seems that assigning value of type `address[]` is not supported yet.

JSON values like `["0x123123...123213"]` lead to error in browser console: `new BigNumber() not a number`.

http://storage2.static.itmages.com/i/17/0929/h_1506693043_2285912_252719f46e.png

If I write there binary representation of array like ```0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000008000000000000000000000000acb13a64513678311b854962d2a64c19917549240000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c4140000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c4140000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c4140000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c4140000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c4140000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c4140000000000000000000000003cad746b0df357965f02dfa53b7bdd2b88c1c414```

then I get an error `RangeError: Invalid array length`

**Comment by tayvano** [comment]
Which contract are you interacting with? That shouldn't be a problem. I have read from an address type on the DAO contract -> balanceOf without issue. If I can recreate, I can attempt to fix. 

![Uploading Screen Shot 2017-10-02 at 10.22.11 PM.jpg…]()

**Comment by tayvano** [comment]
Ohh sorry. I understand now. Moving this to #1047

**Comment by maxvgi** [comment]
https://ropsten.etherscan.io/address/0xD48C9EA924e12940FE59De3eeD891E28172cff0B

ABI

`[{"constant":false,"inputs":[],"name":"kill","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"to","type":"address[]"}],"name":"share","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"got","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"mortal","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]`

I am trying to execute the method `share`

Thank you
