### ISSUE TITLE
Help pages down?

### ISSUE THREAD

**Issue by mikeyb** [kvhnuke/etherwallet#1099]
myetherwallet.com -> Help goes to https://myetherwallet.groovehq.com/help_center

This is now 404'ing.  Help system upgrades?

**Comment by tayvano** [comment]
Mitigating an attack. Getting back online over here. https://myetherwallet.github.io/knowledge-base/

**Comment by mikeyb** [comment]
Thanks a bunch.  Anything needing help?

**Comment by tayvano** [comment]
Can you take a shower for me? 😉

I'll make a to-do list as soon as it's "good enough" and get an announce post up. There's a lot of little things to do. Thinking of using https://lunrjs.com/ for search. Do you know any better static search methods?

**Comment by mikeyb** [comment]
One of those weeks huh? I will see what I can do... 
![image](https://user-images.githubusercontent.com/36461/31261198-95d740e4-aa07-11e7-85ea-59e59e0cc1f3.png)


As for static search I am not sure, lunr seems simple and straightforward.  Something people could make pull requests to contribute to easily.  Maybe that coupled with some sort of category/tagging properties in the files to create separation like on the groovehq docs.

I like simple.

I will check back for a todo list in the morning and see what I can help with before I get my day going.  Good luck!
