### ISSUE TITLE
Unable to conect to http: ....

### ISSUE THREAD

**Issue by migel12** [kvhnuke/etherwallet#11]
Hello i put my wallet key and pass and my etherwallet say accepted but then appear unable to conect to... what happen?

**Comment by tayvano** [comment]
Hi Migel,

What are you attempting to do when you get this error?

**Comment by migel12** [comment]
to watch the money in my wallet

**Comment by kvhnuke** [comment]
Hi Migel,

Server rebooted for maintenance, and I had to manually restart the geth service
it is back online now :) 

-----Original Message-----

**Comment by migel12** [comment]
ok, thanks i probe and its ok. 2 question
what is the best way to close the wallet when i finish
what is the fee for sending ether?

**Comment by migel12** [comment]
when i put 50 ether appear below 49435..... usd , the price in incorrect 
in that zone.

**Comment by migel12** [comment]
another time, no show me my ethers only say loading.... in 3 lines, what 
happen?

**Comment by migel12** [comment]
hello now, the wallet is accepted but no appear how many ethers i have only
loading
loading
loading

**Comment by migel12** [comment]
i attempting to send ethers but no appear only 
loading
loading
loading

**Comment by migel12** [comment]
what happen continue saying loading loading and loading , not appear the 
quantity of ethers that i have?
what happen?

**Comment by DimiFrederix** [comment]
Same story here, 
account balance
loading,... 
loading,... 
loading,...
and unable to transfer funds

**Comment by tayvano** [comment]
@kvhnuke is on a plane for like 24 hours or some craziness. When he lands and gets internet, he'll restart the server and fix it. Sorry. :(

**Comment by DimiFrederix** [comment]
ok thanksThumbs up 

Date: Thu, 17 Dec 2015 01:23:07 -0800

**Comment by kvhnuke** [comment]
sorry for the inconvenience, I just had the chance to fix it, let us know if you run into any other issues
