### ISSUE TITLE
jQuery upgrade to 3.x

### ISSUE THREAD

**Issue by bignose-debian** [kvhnuke/etherwallet#1115]
What is the feasibility to upgrade the jQuery dependency in MyEtherWallet, to use a [currently supported jQuery version](https://www.npmjs.com/package/jquery)?

Currently MyEtherWallet [‘mercury’ branch bundles an un-supported version 1.12.3 of jQuery](https://github.com/kvhnuke/etherwallet/blob/mercury/dist/js/jquery-1.12.3.min.js). The [‘master’ branch bundles jQuery version 1.11.3](https://github.com/kvhnuke/etherwallet/blob/master/js/jquery-1.11.3.min.js), also unsupported.

Something like [jQuery 3.2.1](https://github.com/jquery/jquery/releases/tag/3.2.1) would be desirable; is that a difficult thing to do?

**Comment by tayvano** [comment]
We only use jQuery for a single function and should be removed completely. It's something around printing the paper wallet or triggering something or something. I can't even recall. 

Moving forward, we will not have jQuery and are re-written in react / redux / typescript and the paper wallet is handled inline, which is better for all. Yay.

Check it out: https://github.com/myetherwallet/myetherwallet
