### ISSUE TITLE
Create a desktop app (osx and windows)

### ISSUE THREAD

**Issue by shaishf** [kvhnuke/etherwallet#1126]
I was wondering if there are any plans to wrap myetherwallet as a desktop app, using something like https://electron.atom.io/.
I think it would be very comfortable to use, and allow people to download it from the mac or windows app store in a signed, temper-proof way.

**Comment by tayvano** [comment]
Its in the works. If you have any experience with this or would like to assist, head over the github.com/myetherwallet/myetherwallet 😃
