### ISSUE TITLE
Change so ETH and ETC refer to currency itself, and 'ether' to refer to general.

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#113]
File en.js in some phrases uses acronym ETH to refer to ether in forked branch of Ethereum, while in other places the same acronym is used to refer to ether in general regardles of branch. Probably it would be better to use ETC for classic ether, ETH for forked ether and word 'ether' for general, branch-neutral cases.

**Comment by kevinmonahan** [comment]
Updated
