### ISSUE TITLE
Change Numbers to be consistent as well.

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#115]
Explicit numbers hardcoded into en.js are copied to other translation files, which makes such numbers hard to change consistently. Here are examples of phrases with hardcoded numbers:

DAO_Warning:            'If you are getting an "Insufficient balance for gas" error, you must have a small amount of ETH in your account in order to cover the cost of gas. Add .01 ETH to this account and try again. ',
ERROR_18:             'You need to have at least .001 ETH in your account to cover the cost of gas. Please add some ETH and try again. ',
TRANS_sendInfo:        'A standard transaction using 21000 gas will cost 0.000441 ETH. We use a slightly-above-minimum gas price of 0.000000021 ETH to ensure it gets mined quickly. We do not take a transaction fee.',

Some numbers start with 0. (zero point), while the other start with just . (point).

**Comment by kevinmonahan** [comment]
Updated

**Comment by tayvano** [comment]
done done
