### ISSUE TITLE
No private key and paper wallet

### ISSUE THREAD

**Issue by KitsuneNoBaka** [kvhnuke/etherwallet#1180]
In a v3.10.5.1 there is no private key option to view or paper wallet option to print at the "View Wallet Info" tab, which is made just for that, as help bubble suggest.

![zrzut ekranu 2017-10-24 o 23 25 16](https://user-images.githubusercontent.com/32077122/31969487-1305e7fc-b915-11e7-9f71-1f43f94fbf0d.png)

**Comment by tayvano** [comment]
You must unlock with your private key to view your private key, not the "via via address only" option. If you only view with your address you can only see the address fields.

**Comment by KitsuneNoBaka** [comment]
I unlock with keystore/JSON file. It works fine with v3.10.4.8

**Comment by KitsuneNoBaka** [comment]
Fixed in v3.10.6.0 - thanks
