### ISSUE TITLE
mewtopia.eth resolved as 0x0

### ISSUE THREAD

**Issue by ligi** [kvhnuke/etherwallet#1195]
When using (the suggested) mewtopia.eth at creating offline transactions:

![selection_179](https://user-images.githubusercontent.com/111600/32145289-1caa66c0-bcc6-11e7-9e60-dd6d0b0b3bb2.png)

it is resolved as 0x0:

![selection_177](https://user-images.githubusercontent.com/111600/32145241-60bf6bfe-bcc5-11e7-8208-191b438e1146.png)

and even a signed tx is created for this:

![selection_178](https://user-images.githubusercontent.com/111600/32145283-f3cc6cf8-bcc5-11e7-8abd-171da07859b9.png)

this is quite dangerous - I know not to send to 0x0 - but some other users might send without noticing.

**Comment by tayvano** [comment]
Shit thanks. I'll add a check there

**Comment by tayvano** [comment]
This was fixed. It's non-issue in v4
