### ISSUE TITLE
Account balance shows "Loading"

### ISSUE THREAD

**Issue by unimercio** [kvhnuke/etherwallet#12]
Hi,
I generated a wallet address and sent 100 finney to it. 

But, the account balance shows "Loading" after decrypting. I tried the same with my presale wallet and the account balance shows "Loading" as well.

![screen shot 2015-12-17 at 11 42 59 am](https://cloud.githubusercontent.com/assets/362412/11876840/a3e6dc4e-a4b9-11e5-8268-65dc0bdac24d.png)

![screen shot 2015-12-17 at 11 43 20 am](https://cloud.githubusercontent.com/assets/362412/11876633/db21429a-a4b8-11e5-9cf3-3bdcba31c393.png)

![screen shot 2015-12-17 at 12 21 58 pm](https://cloud.githubusercontent.com/assets/362412/11876643/e5e12254-a4b8-11e5-921d-3a9e4625628c.png)

Thanks

**Comment by unimercio** [comment]
The "generate transaction" button is unresponsive, I assume related to "loading" issue.

![screen shot 2015-12-17 at 12 32 48 pm](https://cloud.githubusercontent.com/assets/362412/11876994/97ee872e-a4ba-11e5-8f9a-09111698b06f.png)

**Comment by unimercio** [comment]
Account Address: 

0xb67ba1913fc90cd9b9befad1617757d6f7177ec9

**Comment by unimercio** [comment]
http://etherscan.io/address/0xb67ba1913fc90cd9b9befad1617757d6f7177ec9

**Comment by kvhnuke** [comment]
Thank you for bringing this into our attention, I was stuck on a several planes for 24 hrs and just had the chance to fix it. Let us know if you run into any other issues

**Comment by unimercio** [comment]
Thanks @kvhnuke ... and thanks for the lightning reply.  

Cheers

**Comment by Tobito19** [comment]
Hi,
I generated a wallet address and sent 0.10087901 ETHER 
[Документ Microsoft Word (2).docx](https://github.com/kvhnuke/etherwallet/files/103975/Microsoft.Word.2.docx)
to it.

But, the account balance shows "Loading" after decrypting. I tried the same with my presale wallet and the account balance shows "Loading" as well.
