### ISSUE TITLE
Small SVG Logo Typo

### ISSUE THREAD

**Issue by noameppel** [kvhnuke/etherwallet#1205]
I was looking at the /images/logo-myetherwallet.svg logo and noticed the browser tab displayed, "MyEtherWalelt Logo". I thought I had somehow landed on a phishing site.
<img width="1792" alt="screenshot 2017-11-01 17 16 02" src="https://user-images.githubusercontent.com/653153/32268179-f642b0a8-bebb-11e7-9d51-931b7e054a7d.png">

The domain typo is actually in the SVG file:
<img width="1792" alt="screenshot 2017-11-01 17 16 10" src="https://user-images.githubusercontent.com/653153/32268223-1dfe72e4-bebc-11e7-9544-b41780aa3af8.png">

**Comment by tayvano** [comment]
Fixed. Thanks for catching that
