### ISSUE TITLE
We do not know the correct path for this network. Please open a github issue so we can discuss / be enlightened.

### ISSUE THREAD

**Issue by rnkhouse** [kvhnuke/etherwallet#1212]
When I try to connect ledger nano s with Ubiq chain, I am getting below error:

    We do not know the correct path for this network.

m/44'/60'/0'/0
Jaxx, Metamask, Exodus, imToken, TREZOR (ETH) & Digital Bitbox

 m/44'/60'/0'
Ledger (ETH)

 m/44'/60'/160720'/0'
Ledger (ETC)

 m/44'/61'/0'/0
TREZOR (ETC)

 m/0'/0'/0'
SingularDTV

Your Custom Path
m/44'/60'/1'/0

 m/44'/1'/0'/0
Network: Testnets

 m/44'/40'/0'/0
Network: Expanse

**Comment by tayvano** [comment]
What path does UBQ have on on Ledger?

**Comment by tayvano** [comment]
@rnkhouse ??

**Comment by rnkhouse** [comment]
@tayvano I'll update this soon. Let me talk with Ubiq team.

**Comment by iquidus** [comment]
m/44'/108'/0'/0

https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L26

**Comment by xbach** [comment]
TREZOR will also use `m/44'/108'/0'/0`

**Comment by iquidus** [comment]
I had a quick look, and nothing stood out as to why this is occurring. If you could take a look @tayvano it would be much appreciated. 

everything is working fine in pyrus, the only significant difference is the default path is also set to ubiqs.

**Comment by iquidus** [comment]
A pull request has been submitted addressing this issue.
