### ISSUE TITLE
MEW does not work with Ledger Nano S on the new Firefox with internal u2f turned on

### ISSUE THREAD

**Issue by JanKalin** [kvhnuke/etherwallet#1282]
Today the new Firefox Quantum , 57.0 (64-bit) got installed on my PC with Windows 7 Pro. MEW appears not to be able to access Ledger Nano S.

Previously I used https://addons.mozilla.org/en-GB/firefox/addon/u2f-support-add-on/?src=api, which is no longer supported. Now, apparently, Firefox has u2f support built in.
![clipboard03](https://user-images.githubusercontent.com/18305372/32946157-b134fa6a-cb96-11e7-9b6f-202cce704c17.png)

However, turning it on causes MEW to malfunction:
![image](https://user-images.githubusercontent.com/18305372/32946233-fd89b4aa-cb96-11e7-9b07-d2c3c232eb19.png)

The `help` button works, but nothing else, neither the `<<` and `>>`, nor the `X` at the bottom. Turn u2f off, and MEW works normally - except that the Ledger Nano S cannot be accessed. It's not a panic situation - Chrome works just fine.

**Comment by tscs37** [comment]
Encountering this issue too on U2F-enabled Firefox 57 Release. Not sure why MEW is trying to write into the U2F Property;

![image](https://user-images.githubusercontent.com/1774339/33056097-d81d3ef4-ce83-11e7-9565-3ef5e8f8c50c.png)

**Comment by dagelf** [comment]
Yup, confirmed on Ubuntu 16.04 at least. It's most confusing to be met with MyEtherWallet showing just a blank page like that.

**Comment by tayvano** [comment]
#1410 and #1122
