### ISSUE TITLE
I switched the wrong bte up Contract Address: BTE Token information

### ISSUE THREAD

**Issue by tuanluan93** [kvhnuke/etherwallet#1285]
sorry about my english
i playing bitserial coin(BTE)
i want switch BTE from myetherwallet to BTE wallet
but switched the wrong bte up Contract Address: BTE Token information
i thinked this address is my BTE wallet address but wrong !
There is no way to get back bte ?

**Comment by tuanluan93** [comment]
Tx | 0x3fa3ae8ea8d920645099f8e997b5d1f40907ba8245b56a6ead5185a5f3c41d98
-- | --
Date | 2017-11-16 06:43:56 (GMT--8)
Block | 4563992 (5939 confirmations)
From | 0x94D132C78AC484F72E841BCC20f921d634902F83
To | Contract 0x6733D909e10DDedB8d6181b213dE32A30cEac7ed

this address BTE token:0x6733D909e10DDedB8d6181b213dE32A30cEac7ed
i thinked is my address BTE ;((

**Comment by Clipperone** [comment]
The BTE is an ERC20 smart contract that don't support the retrival for token sent to contract address. Unfortunately your tokens are loked in the contract address and can not be sent back to you address.

**Comment by tuanluan93** [comment]
There are so many people mistakenly like me, that is the problem, now my
life of the night is very hard, give it back to me, really thank you,good
luck to the project !!

**Comment by tuanluan93** [comment]
And good luck for you !!!
