### ISSUE TITLE
RPCClient

### ISSUE THREAD

**Issue by stefanrenne** [kvhnuke/etherwallet#13]
Hi,

In https://github.com/kvhnuke/etherwallet/blob/gh-pages/php_json_relay/api.php I see that you are opening an rpc connection to an ip address. Where can I find the rpc server implementation?

Stefan

**Comment by kvhnuke** [comment]
Hi Stefan
It is just a geth instance with rpc. You can get more info on how to start geth with rpc from the following link. https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options
On Jan 19, 2016 4:11 AM, stefanrenne notifications@github.com wrote:Hi,

In https://githubcom/kvhnuke/etherwallet/blob/gh-pages/php_json_relay/apiphp I see that you are opening an rpc connection to an ip address Where can I find the rpc server implementation?

Stefan
