### ISSUE TITLE
contact browser vendors (Shouldn't require SSL if running locally)

### ISSUE THREAD

**Issue by onpars** [kvhnuke/etherwallet#1300]
Has been discussed earlier here https://github.com/kvhnuke/etherwallet/issues/521.

> I've tried to run MEW locally (with a file:/// URL) with my Ledger Nano today, and I can't, because it tells me this message in red:

> `1. Re-open MyEtherWallet on a secure (SSL) connection`

> This check should only be there when running on-line, not locally from an index.html saved on the computer.

Running a local web server just to get SSL for localhost (which isn't really needed or adding any security [at least offline]) is a major complication.

Could you contact the browser vendors (Firefox, Chrome) please to report a bug or request a feature along the lines

* allow U2F connections to file:// without SSL
* add option to to allow U2F connections to file:// without SSL
* or something like that?

I would do it myself, but I don't understand this browser feature / limitation good enough. And it would add some weight if you would word/request it.

**Comment by tayvano** [comment]
We cannot control whether or not Google allows U2F to occur on file:// or locally served files. There are a number of issues open across Chromium and webkit discussing various issues in regards to localhost / files, not just in regards to U2F. Their stances are fairly strong on most of these issues as far as I've seen. 

You are more than welcome to comment on an issue and voice your opinion. I have voiced my opinion on a few already. It also doesn't help that U2F doesn't seem to be a high priority feature in general.

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
