### ISSUE TITLE
Help on how to view custom token on MEW

### ISSUE THREAD

**Issue by Adexbafo** [kvhnuke/etherwallet#1324]
I have been following this work trends ,  and I must say it is amazing and fascinating.  Concerning my caption.....I am new to cryptocurrencies,  I created a new wallet on MEW, now I am having a hard time in creating or even adding custom token.. Please I need your assistant oon this. Thsnk

**Comment by GavelCoin** [comment]
To add a custom token all you need to do is click "add custom token" in the bottom right menu bar. Once you have clicked it will ask you for contract address, Token Symbol and Decimals, file in the info and click add and you are good to go. Hope it helped

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
