### ISSUE TITLE
{"errorCode":5} when trying to connect Ledger Nano S

### ISSUE THREAD

**Issue by durbanpoison** [kvhnuke/etherwallet#1330]
I open https://myetherwallet.com in Chromium Version 62.0.3202.94 and try to open a wallet with my Ledger Nano S and the error `{"errorCode":5}` shows on the screen. No advice given on how to fix the error. I did a search and couldn't find anything about this so apologies if this has already been reported.

**Comment by BDenBleyker** [comment]
I had the same problem.  I uninstalled and reinstalled the app and it connects now.  Worth a try. Also, this may help. https://myetherwallet.github.io/knowledge-base/hardware-wallets/ledger-hardware-wallet-unable-to-connect-on-myetherwallet.html

**Comment by duggieblue** [comment]
Nano Ledger. (Hard wallet).  Error code 5. Problem Solved.(edited)
I had problems getting Ledger to connect in Mew (myetherwallet), when i clicked, "connect to ledger wallet, it would after a few seconds return with "Error code 5" and ....nothing.
I then went to Nano, went to "No"  in Browser support FROM Yes. ...,,,,then back to Yes and it loaded addresses, all good.

**Comment by hundredfold** [comment]
I solved this by using a different USB cable. It seems the error code 5 means it can't retrieve the private key from your ledger.

**Comment by voyager** [comment]
^ I also solved it by using a different USB cable :)
