### ISSUE TITLE
How to reveal a bid?

### ISSUE THREAD

**Issue by DarthJahus** [kvhnuke/etherwallet#1335]
I placed a bid on an ENS and was supposed to reveal my bid 15 minutes ago. Thing is… I have no idea how to do it and thought it would be somewhere in the interface.

**Comment by tayvano** [comment]
Just go to https://www.myetherwallet.com/#ens and type in the name. If its ready to reveal, it will display the reveal interface for you.

**Comment by DarthJahus** [comment]
Thank you. I think I just went there a bit early. Now it's working.

**Comment by tayvano** [comment]
Great to hear! Let us know if you have any other issues or questions.
