### ISSUE TITLE
send all ether - leave no dust behind

### ISSUE THREAD

**Issue by onpars** [kvhnuke/etherwallet#1336]
Mist can do that.

Is there such a feature yet in MEW? Is it a bug or missing feature?

It was send all but then complains about too little gas. A user asked this a few months ago. Exactly what I am wondering about here.

https://www.reddit.com/r/MyEtherWallet/comments/6v8ttv/how_do_i_remove_all_eth_from_myetherwallet/

**Comment by tayvano** [comment]
For now, you can tell your users to use Mist, or calculate it themselves:

(YOUR BALANCE - (gas price in gwei * gas limit )) / 1000000000

Example:

(0.123ETH) - (12GWEI * 21000GAS / 1000000000)ETH

0.123ETH - 0.000252ETH 

0.122748 ETH

Therefore, a user with a balance of 0.123 ETH sending with a gas price of 12 GWEI should send 0.122748 to send their total available balance.

---

I'm unsure if this is a bignumber.js thing, a gas price thing, or some of our nodes are out of sync thing. Here's what it's returning and what I'm logging in the console in case anyone has more brainpower than me to debug.

![2017-12-01 at 1 36 57 am](https://user-images.githubusercontent.com/7924827/33476823-33085d9c-d638-11e7-8c68-1f5850d7a81b.png)


![optimized](https://user-images.githubusercontent.com/7924827/33476760-01aff638-d638-11e7-98a8-f37a7641ec76.gif)

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
