### ISSUE TITLE
Getting tokens into an offline wallet

### ISSUE THREAD

**Issue by neilfaraway** [kvhnuke/etherwallet#1341]
I have a cold storage wallet (MEW on a live ubuntu usb stick that never sees the internet). I want to add some POWR tokens to the wallet so I have the option of selling them (these show up against the wallet address on etherscan.io).  I have been through the 'Add tokens' process using the latest release of MEW.  POWR is in the list of tokens, but the word 'loading' just stays static next to all the custom tokens in the list.  I imagine MEW is trying to talk to the blockchain to establish whether I have a balance...  Is there a way to load my balance into the wallet while keeping it completely offline?

I have looked up the help files on the MEW website, but they are unspecific about web connected vs offline methods of doing this.

Thanks
Neil

**Comment by tayvano** [comment]
I'm not sure. Off the top of my head I would say the *easiest* way would be to 

- Go to your unzipped files
- Open dist -> js -> etherwallet-master.js
- Scroll to ~line 14,337 (or do a CTRL/CMD+F for "ZRX"
- Copy & paste the following (replace with POWR info)
```
{
"address":"0xE41d2489571d322189246DaFA5ebDe1F4699F498",
"symbol":"POWR",
"decimal":18,
"type":"default"
},
```

So it'll look like 

...
```
},{
"address":"0xE41d2489571d322189246DaFA5ebDe1F4699F498",
"symbol":"ZRX",
"decimal":18,
"type":"default"
},{
"address":"0xe386b139ed3715ca4b18fd52671bdcea1cdfe4b1",
"symbol":"ZST",
"decimal":8,
"type":"default"
},{
"address":"0xE41d2489571d322189246DaFA5ebDe1F4699F498",
"symbol":"POWR",
"decimal":18,
"type":"default"
}]

},{}],97:[function(require,module,exports){
```
...

when all said and done.

Before:
![2017-12-01 at 12 41 03 am](https://user-images.githubusercontent.com/7924827/33474638-57fad5ec-d630-11e7-9c10-a36a8cb8693c.png)

After:
![2017-12-01 at 12 40 53 am](https://user-images.githubusercontent.com/7924827/33474646-5e0dd22c-d630-11e7-97ed-0d884b3751a5.png)

**Comment by tayvano** [comment]
Alternatively, you could do a PR so its included in the next release, or ask the creators of that token to: https://myetherwallet.github.io/knowledge-base/tokens/token-creators-add-your-token-to-myetherwallet.html

**Comment by neilfaraway** [comment]
Hey Tayvano,
Thanks for the advice.  POWR is already listed as a token, but getting my balance seems impossible.  Good idea on the PR.  Might also just get a Trezor so can be connected to the web - then all is easy :)
Thanks.
