### ISSUE TITLE
Move default tokens to another repo ? 

### ISSUE THREAD

**Issue by Asone** [kvhnuke/etherwallet#1348]
It might sound dumb, so if it is, please feel free to kick my ass and close this issue. 

However, i see many and many PR regarding implementing new default tokens in MeW. It even leads to some childish fights about the currency names sometimes. 

MeW is a great tool but PR list should be mainly focused onto its own development and not onto implementing new ERC20 tokens, moreover that we'll see more and more new tokens as time passes. 

In order to keep things clean, wouldn't moving the current default tokens file to a different repo from which people will be able to propose new tokens without affecting the PR pile of the main repo ? 

Also, at some point, listing hundreds of tokens overloads the main website. A solution that could be explored could be to build a tool that allow each user to build its own token list configuration from a website hosted on subdomain ( or another domain ) and then have a tool to allow import from user on MeW website. 

Any critics welcome, obviously ( mainly from main devs of the repo ). 

Much datalove

**Comment by DarthJahus** [comment]
Totally agreeing with this suggestion, especially that MEW doesn't load token balances by default anymore. Token creators may simply give instructions to users on how to add new tokens.

**Comment by tayvano** [comment]
Tokens will be moved to external repo upon migration to v4

https://github.com/myetherwallet/ethereum-lists

**Comment by tayvano** [comment]
You can see the new MEW v4 of tokens here: MyEtherWallet/MyEtherWallet#538

And provide any feedback here: MyEtherWallet/MyEtherWallet#494

**Comment by Asone** [comment]
Great news ! Thanks for the info, i had alreaddy digged into the v4 code but haven't been checking there how this specific topic was going to be handled. Sorry for the inconvenience ! 

I'll close the issue. 

Much datalove onto the magical MeW team
