### ISSUE TITLE
Cannot sweep wallet into Coinomi

### ISSUE THREAD

**Issue by nicmanism** [kvhnuke/etherwallet#1399]
Thanks for taking the time to write MyEtherWallet. 

I generated a paper wallet using your program. But when I attempt to sweep it into Coinomi, I get an error "could not recognize the private key format"

I've taken a look on the Coinomi support page and private keys need to be in: BIP38, WIF or mini format to be compatible with Coinomi's sweep function. 

I'm not really sure which format MyEtherWallet generates. I've tried to convert it to one of the other compatible formats using: https://www.bitaddress.org and https://coinomi.com/recovery-phrase-tool.html
but I haven't had much luck (please note that I am not a crypto expert).

I hope you have the time to re-release a version of your code that generates private keys in formats that Coinomi can sweep.

**Comment by andrewathalye** [comment]
Coinomi seems to only support bitcoin wallet sweeps?

**Comment by nicmanism** [comment]
Thanks for getting back to me.

I've found that I can sweep the wallet using Jaxx.

Regards

Mark

**Comment by jeanlp76** [comment]
Hi ! let me get it right !
did you sweep the wallet to jaxx , and the you sweep to Coinomi ? 
mi problem is that i haD all the ETC on myetherwallet at the moment of the snapshoot , but i can´t sweep the wallet to coinomi because it only acept : bip38, WIF or mini private key.

**Comment by nicmanism** [comment]
You can sweep your coins/ether into a jaxxx wallet and then send them to
your coinomi wallet.

Let me know if you have further questions.

**Comment by jeanlp76** [comment]
Thnx ! Right Now i don’t have any there , my situation is get the Callistos .
When you sweep the wallet to jaxx you lost the previous history of movements of the original wallet ? Basicly i need demostrate to coinomi that my etc was in the wallet at the moment of the snapshoot
