### ISSUE TITLE
Account balance shows "Loading"

### ISSUE THREAD

**Issue by Tobito19** [kvhnuke/etherwallet#14]
Hi,
I generated a wallet address and sent 0.10087901 ETHER to it.
[Документ Microsoft Word (2).docx](https://github.com/kvhnuke/etherwallet/files/103981/Microsoft.Word.2.docx)
But, the account balance shows "Loading" after decrypting. I tried the same with my presale wallet and the account balance shows "Loading" as well.

**Comment by kvhnuke** [comment]
can you please check again and let us know.
