### ISSUE TITLE
Importing paper wallet fails

### ISSUE THREAD

**Issue by pieterpoorthuis** [kvhnuke/etherwallet#1401]
I created an ethereum wallet in MEW and printed the paper wallet. So I have the unencrypted private key (128 characters).

I'm now using MEW on https://www.myetherwallet.com/ . When I try to import the private key (View Wallet Info -> Private Key), the interface keeps telling me 'Your wallet is encrypted. Good! Please enter the password.'

I'm pretty sure I previously imported the paper wallet private key previously without entering a password. I'm now unable to import the private key. Is it a a bug that MEW asks for a password?

**Comment by pieterpoorthuis** [comment]
The error I'm getting is:
"(error_07) Please enter a valid password. TypeError: Cannot read property 'length' of undefined"

When MEW creates a paper wallet, the private key is unencrypted right? So I should be able to import this key without a password?

**Comment by pieterpoorthuis** [comment]
Running on Chrome v63, on Mac OS 10.13.1

**Comment by pieterpoorthuis** [comment]
I could import the plaintext private key without a password using 'geth account import'. 
This means that MEW does something wrong.. MEW effectively locked me out, and geth let me back in.

**Comment by tayvano** [comment]
The paper wallets have never been encrypted and the length of the private key should be 64 characters. For a lot of my test accounts I use raw private keys and have had no issues.

Are you sure that the key being displayed on the paper wallet is 128 characters? because it has never been.

**Comment by pieterpoorthuis** [comment]
The length of my private key is 128 characters, in lowercase hexadecimal (0..9a..f).

In hexadecimal or bytes this would indeed be 64 characters.

**Comment by tayvano** [comment]
Private keys are (usually, long story) 64 characters / 32 bytes. (Occasionally you get a valid key on the curve that is 31 bytes or even 30 bytes.)

The reason it thinks it's encrypted is that the encrypted private keys that we had back in 2015 are 128 characters, but they were full alphanumeric, not hex.

Does your paper wallet look like this?

![2017-12-14 at 12 18 27 am](https://user-images.githubusercontent.com/7924827/33982154-51e8b0e6-e064-11e7-9a87-edc2bd857fbf.png)

**Comment by pieterpoorthuis** [comment]
aah.. I found out what went wrong.
My iOS QR Reader displayed the private key twice (concatenated), creating a 128 character string. When using this string MEW asks for a password.

I manually copied the first 64 characters and now I can import in MEW without a password.
