### ISSUE TITLE
Firefox U2F not working

### ISSUE THREAD

**Issue by semeano** [kvhnuke/etherwallet#1410]
If I set security.webauth.u2f = true, myetherwallet.com doesn't fully load.

Here's the console error:

TypeError: setting getter-only property "u2f"
Error: [$injector:modulerr] Failed to instantiate module mewApp due to:
[$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.5/$injector/nomod?p0=mewApp

And here is a screenshot: https://www.dropbox.com/s/tokli4k2ohlp2sy/Screenshot%202017-12-12%2018.37.23.jpg?dl=0

I'm using FirefoxNightly 59.0a1 (2017-12-12) (64-bit).

**Comment by tayvano** [comment]
#1282 and #1122
