### ISSUE TITLE
When offline, MEW tries to load tokens on adding a custom token

### ISSUE THREAD

**Issue by veox** [kvhnuke/etherwallet#1422]
### Versions

System: Linux, Fedora 26, 32-bit
Browser: Firefox 55.0.2
MEW: 3.10.10.1

### What am I trying to do?

Send a token (XENON) using an offline copy of MEW and a JSON keyfile.

### What steps do I take?

* Navigate to `index.html` in MEW's `dist` folder, double-click that.
* Select the "Send Ether & Tokens" tab - [this 5-month old Reddit thread](https://www.reddit.com/r/MyEtherWallet/comments/6iudl6/offline_transfer_new_eth_tokens/) suggests so; also, the "Send Offline" tab has no interface for token transfers, and seems to be deprecated anyway, as per #672.
* Load the key from a JSON file.
* Click the "Add Custom Token" button in the side menu, and populate the fields:

```
address: 0xab95E915c123fdEd5BDfB6325e35ef5515F1EA69
symbol: XENON
decimals: 18
```

* Upon confirmation, the symbol gets added to the currency selection drop-down in the main form (as expected). Unexpectedly, though, **MEW triggers loading of token balances**, which can be seen as the side menu getting populated with a list of all tokens, and a `loading` word indicating that the balance is loading. Note: XENON is not in the list.
* In the main form, put in the destination address (EIP55-checksummed), amount to be transferred, and 55555 gas.
* Clicking "Advanced: Add Data" seemingly does nothing, including nothing being printed to the browser console.
* Clicking "Generate Transaction" seemingly does nothing to the document window, but **the console prints**:

```
BigNumber Error: new BigNumber() is not a number: loading
```

It seems to me that the `loading` in-console is related to the `loading` balances of tokens in the side menu.

### Meta

May be related to issue #902.

I haven't tried this with any previous version.

Random OT suggestion: for offline use, would it make sense to provide an "Offline ETH" option in the network selection drop-down?

**Comment by tayvano** [comment]
@dternyak @HenryNguyen5 Any ideas on a quick fix for this one? Basically, need a good spot to put

If offline -> dont load tokens

Or 

If offline -> load token list but don't load their balances

**Comment by tayvano** [comment]
There have been 2 changes to how tokens load since this issue that should (hopefully) resolve this. However, in order to send offline, you are going to need to send via the offline tab, not the send tab. The dropdown for the offline tab for tokens does work, its just quite long as we are unable to filter which tokens have a balance or not without the internet.

**Comment by veox** [comment]
Thank you!

I'll close the issue after testing the changes (next year).

**Comment by veox** [comment]
Finally got to testing this: all good with MEW v3.11.2. Closing.
