### ISSUE TITLE
A myriad of addresses are produced after the introduction of a Mnemonic Phrase

### ISSUE THREAD

**Issue by techom** [kvhnuke/etherwallet#1426]
When I look at my wallet with Mnemonic, I can get numerous addresses after importing the Mnemonic of imtoken. How do I find the addresses I have used from so many addresses? Thanks.

**Comment by tayvano** [comment]
You can find answer here: https://myetherwallet.github.io/knowledge-base/hardware-wallets/multiple-addresses-on-hardware-wallet.html
