### ISSUE TITLE
Offline New Wallet Generation

### ISSUE THREAD

**Issue by Aethyr1** [kvhnuke/etherwallet#1428]
Offline generation of new wallet not working in Tails 3.3.

Issues with TOR browser.

**Comment by tayvano** [comment]
Please copy and paste the console /errors so I can attempt to debug

**Comment by bikra** [comment]
Yees

**Comment by dreadkrusher** [comment]
I think I might be having the same problem. When I extract and open "index.html" under my tor folder all that opens is the HTML.

**Comment by bikra** [comment]
Yes $,97665433344667

**Comment by krissebesta** [comment]
I had the same problem but found a way around it. The zip file you download is not complete. Go up a level in project (you should see the "dist" folder and other folders and files). Then click the green Clone or Download button on the right. Click on Download Zip and save the file. Unzip that file and inside the "dist" folder you can double-click the index.html file. Good luck!

**Comment by jfloodnet** [comment]
I get the same issue running tails 3.3. No javascript errors in the console. Styles tab says "could not load stylesheet".  No other errors I can find.

I've downloaded the latest Tor Browser and run on windows and it seems to work fine.

**Comment by jfloodnet** [comment]
Looks t be a tails 3.3 issue https://www.reddit.com/r/tails/comments/7g7lxh/mew_31076_doesnt_work_in_tails_33/

**Comment by gamalielhere** [comment]
Closing this for now. Don't hesitate to reopen if the issue persists.
