### ISSUE TITLE
No Ledger support when downloading MEW, running locally

### ISSUE THREAD

**Issue by NessDan** [kvhnuke/etherwallet#1429]
![image](https://user-images.githubusercontent.com/304269/34084478-402b4420-e34f-11e7-9859-d365eb50b928.png)

Because the URL is a `file` protocol, I can't go any further when connecting to my Ledger :(

**Comment by tayvano** [comment]
This is a limitation of the U2F protocol and not something we nor Ledger control. In order to use U2F the browser requires it to be over a secure connection.

You can read more about how to connect locally here: https://github.com/benjaminion/eth-parity-qnap/wiki/Connecting-to-MyEtherWallet

**Comment by NessDan** [comment]
Ah that makes sense. I don't know how often this question comes up, but if it's often enough, maybe updating the `You must access via a secure SSL connection` message with the link you provided?
