### ISSUE TITLE
Missing translation summary

### ISSUE THREAD

**Issue by ugilio** [kvhnuke/etherwallet#143]
This is a list of things that are still not translated (that is, there is no way for translator to translate ATM). At least, this is what I noticed.
- ~~Withdraw DAO:~~
  ~~"You are about to withdraw X DAO Tokens for Y ETH. " (no translation)~~
  ~~"You are about to withdraw X DAO Tokens to ADDRESS_IN_FIELD_ABOVE for Y ETC." (no translation)~~
  ~~"Where do you want your ETC to be sent to?" (no translation)~~
  ~~"Withdraw DAO Tokens for ETC" "Withdraw DAO Tokens for ETH" (buttons, no translation)~~
- ~~Help page:~~
  ~~"If you are on a PC" untranslated~~
- ~~The radio buttons under "Select the format of your private key:" don't have a matching translation string:~~
  "~~JSON or Keystore File", "Plain Text Private Key" (Select format of your private key:)~~
- DGD Page:
  Information under "DGD Crowdsale Information" have no translation:
  Centstotal: 0
  Weitotal: 0
  Share: 0
  Badges: 0
  Claimed? false
- On the footer, there are no translations for some sentences (minor):
  URLs:
  Also, one might want to translate "<username> on reddit" but maybe it's too much.
- The printed wallet is always in English
- ~~The placeholder "Private Key" when unlocking a wallet is not translated~~
- ~~When selecting a wallet file, the message is always in English "File selected: xxx" (no translation)~~
- Exceptions are not translated. Also, the resulting error message might be strange due to punctuation, also in English.
  E.g. try to unlock a wallet with a wrong password. The message will be: 
  "Invalid password. :Error: Key derivation failed - possibly wrong passphrase"
  (in Italian, only the first part is translated: "Password non valida. :Error: Key derivation failed - possibly wrong passphrase")
- ~~Error messages coming from geth:~~
  ~~"Account does not exist or account balance too low"~~
  ~~Maybe it's possible to lookup geth error messages and replace them with a translation, if myetherwallet does provide it?~~

**Comment by tayvano** [comment]
I'm going to stop saying we're done / close to done. This is never going to end. 😂

**Filed under Taylor is an idiot and will fix**
- Withdraw DAO
- Help page
- Radio buttons _(I can do all these as we have that translated already, just with extra stuff attached)_
- The placeholder "Private Key" when unlocking a wallet is not translated _(same as above)_
- When selecting a wallet file, the message is always in English "File selected: xxx" (no translation) 
  _I have no idea where this message comes from_
- May also need "Disclosure" that is now in footer
- May also need more items for DAO -> ETC and Deploy Contracts as we finish building those features. 

**Filed under deal with later**
- Paper wallet needs to be redone in angular or something. No way to currently translate (cleanly) at this time
- DGD stuff as it comes directly from their ABI
- Error messages / half error messages. The ones still in english come from geth or we added a bit of an error message and pull the rest from geth. No idea if we can translate them as they come in but will look into it for future

**Comment by tayvano** [comment]
Okay I think I've confirmed all the withdaw DAO, help page, radio buttons, placeholders are done. 

I just took a quick look and there are a few error or success messages that have add'l text. I'll do those later. :/

@kvhnuke will need to figure out how to get the translated message in them inline & the possibility of translatin geth messages

**Comment by ugilio** [comment]
New issues after last changes:
- ~~"Disclaimer" in the title on the popup is translated, but on the footer it is not.~~
- ~~Dao: in the popup, when withdrawing DAO, it says "ETC" also in the ETH case~~
- The "File Selected" message still displays in English

For the geth thing, an idea (in pseudocode) might be the following:

```
gethMsgsToKey = [{'Account does not exist or account balance too low' => 'GETH_NOBALANCE'},
    {'Some other error' => 'GETH_SOMEOTHERERROR'}]
gethMsgsTranslated = [{'GETH_NOBALANCE' => 'Account does not exist or account balance too low'}, ...]
```

gethMsgsTranslated is updated with the correct language. E.g. in Italian the value of GETH_NOBALANCE entry would be 'Il conto non esiste o il saldo è insufficiente'

When receiving an error message from geth, you do a double look-up using these two dictionaries:
`translatedMsg = gethMsgsTranslated[gethMsgsToKey[msgReceivedFromGeth]]`
which of course for English should not change anything

**Comment by ugilio** [comment]
Also: the disclaimer content is untranslated (but maybe it's on purpose?)

**Comment by tayvano** [comment]
Yeah. I need to get it approved first. It's going to change a bit. And I don't know how were supposed to handle it yet.

**Comment by ugilio** [comment]
Just noticed now that there is no translation for the title of the page ("MyEtherWallet: Open Source JavaScript Client-Side Ether Wallet")

**Comment by tayvano** [comment]
Closing this but moving not-done items to #195
