### ISSUE TITLE
Latest release (v3.11.1.2) doesn't work offline

### ISSUE THREAD

**Issue by descrip** [kvhnuke/etherwallet#1439]
Downloading the v3.11.1.2 zip and opening `index.html` in Firefox or Chromium gives a blank screen. Both consoles report some Javascript errors:

![screenshot from 2017-12-23 17 09 46](https://user-images.githubusercontent.com/6173806/34322982-23419b8e-e804-11e7-8d51-f3a7158e4f27.png)

Reverting to v3.10.10.3 works fine.
EDIT: Reverting to v3.11.1.1 also works fine.

On Firefox 57.0.1, Ubuntu 14.04, 64-bit. Thanks.

**Comment by rasputnik** [comment]
index_com.html usually works offline.

**Comment by Fretlon** [comment]
Confirmed broken in Firefox 57 on Linux Mint 18.2 as well.

**Comment by StevenJohnston** [comment]
Also good to note that the 3.11.1.2 dist is working too [located here](https://github.com/kvhnuke/etherwallet/tree/mercury/dist) Seems to only be a problem with the zip uploaded.

**Comment by krissebesta** [comment]
I had the same problem but found a way around it. The zip file you download is not complete. Go up a level in project (you should see the "dist" folder and other folders and files). Then click the green Clone or Download button on the right. Click on Download Zip and save the file. Unzip that file and inside the "dist" folder you can double-click the index.html file. Good luck!

**Comment by tayvano** [comment]
I believe I have resolved this. Please try again from any of the zips on the recent releases (that aren't labeled "broken")

Also, there is an unrelated issue due to inconsistencies in the Firefox and Chrome U2F spec that may be causing issues. The console errors are similar across both, but seems to only occur when attempting to connect to your Ledger hardware device in Firefox.

**Comment by tayvano** [comment]
lets continue any ongoing issues in #1449 so I can try to keep all this straight. I get an ungodly amount of notifications these days.
