### ISSUE TITLE
Address Identicon and Tokens Don't Load / Can't Select to Send

### ISSUE THREAD

**Issue by eyemaginative** [kvhnuke/etherwallet#1442]
Since the latest update, in (Chrome, Opera, and Firefox), the Address Identicon and Tokens for the drop down to select / send don't load on the page.

Unable to select / send tokens.

**Comment by eyemaginative** [comment]
Ok, I figured out how to get the tokens to show up in the drop down selector to be able to select and send them.  For some reason they are all showing up as 'Click to Load' on the right side.  So in order to send a token or get it to show up in the drop down selector, you have to actually click to load them first, then they show up in the drop down and can be selected to send.

**Comment by tayvano** [comment]
Yup. Unfortunately, having hundreds of thousands of people making 200+ requests for token balances was too much for the infrastructure to handle. It will remember the token balances you load and automatically load them the next time though, so you should only have to do this once.
