### ISSUE TITLE
Want to get started, but don't know how to.

### ISSUE THREAD

**Issue by mechamecho** [kvhnuke/etherwallet#1444]
How do I get the app running from the source? I have read the instructions in the README, but they don't work for me.
I am sorry if this is not the place to ask a question like this, but I didn't know where else to ask.

**Comment by tayvano** [comment]
How familiar are you with gulp / npm? Do you have node and npm installed? Trying to figure out where to start here.

**Comment by mechamecho** [comment]
I am very grateful for your response. I have node and npm installed.
I have a basic understanding of npm as the package manager for node, I have never worked with gulp before though.

**Comment by srmojuze** [comment]
Do see https://github.com/kvhnuke/etherwallet/tree/mercury/dist#users-non-developers

Follow those instructions. When using the "dist" folder, by convention in web stuff that means you use a "release" --> essentially you don't need node, npm, gulp, bower, etc.

You load the html and javascript directly in your browser from that "dist"/"release" so you don't need to install anything else. _(In Github terms it means using the gh-pages branch which doesn't have all the source code etc)_

**BE AWARE OF THE RISK OF BEING CONNECTED TO THE INTERNET WHILE USING IT, VIRUS/MALWARE/JAVASCRIPT/BROWSER RISKS ETC**

**Comment by gamalielhere** [comment]
@mechamecho are you still having trouble with the local version?
