### ISSUE TITLE
v3.11.1.2  - Offline mode of index.html is showing blank on Chrome 63.0.3239.84 (64-bit) and Firefox 57

### ISSUE THREAD

**Issue by melwong** [kvhnuke/etherwallet#1445]
![screenshot--2017-12-25-16-32-08-434](https://user-images.githubusercontent.com/15141389/34336342-40ebceaa-e991-11e7-905b-d87b405e4d09.png)

**Comment by marcio1973** [comment]
Same with me

**Comment by krissebesta** [comment]
I had the same problem but found a way around it.  The zip file you download is not complete.  Go up a level in project (you should see the "dist" folder and other folders and files).  Then click the green Clone or Download button on the right. Click on Download Zip and save the file.  Unzip that file and inside the "dist" folder you can double-click the index.html file.  Good luck!

**Comment by melwong** [comment]
It worked krissebesta. THanks so much!

**Comment by mazzma12** [comment]
Same problem, with same browsers version.  @krissebesta going to the `dist/` folder worked for me, but it is weird because it is unadvised in the README to touch it, and that is not the `index.html` you are suppose to call in the tutos. If a dev have some explanations, I am not very familiar with node

> Both the Chrome Extension and the MyEtherWallet.com are compiling from the same codebase. This code is found in the app folder. Don't touch the dist or chrome-extension folders.

**Comment by tayvano** [comment]
Fixed this and re-up'd all the only zip files. Looking into why Travis is building terrible zips. Sorry abotu that

**Comment by tayvano** [comment]
lets continue any ongoing issues in #1449 so I can try to keep all this straight. I get an ungodly amount of notifications these days.
