### ISSUE TITLE
v3.11.1.4 not working here with Chromium

### ISSUE THREAD

**Issue by repsorp** [kvhnuke/etherwallet#1447]
- chrome-extension and etherwallet not showing any of my watch-only account:

![a](https://user-images.githubusercontent.com/6297032/34364365-92414182-ea85-11e7-94a2-fc1f8babfa1c.png)

- Clicking on "My Wallets" or "Add Wallet" takes me to a blank page:

![b](https://user-images.githubusercontent.com/6297032/34364368-98828ee8-ea85-11e7-9f98-5dcfe9867e4d.png)

Same with v3.11.1.3, v3.11.1.2
Have to go back to v3.11.1.1 where everything's working fine

config:
Chromium 63.0.3239.84 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)
chrome-extension	Release: v3.11.1.4
etherwallet v3.11.1.4

**Comment by 7flash** [comment]
![screenshot_2017-12-27_13-19-01](https://user-images.githubusercontent.com/4569866/34378748-9042fef6-eb08-11e7-917d-d746b9891152.png)

Uncaught ReferenceError: baseUrls is not defined

**Comment by IKOBH** [comment]
Same issue on firefox

**Comment by repsorp** [comment]
- Chromium 63.0.3239.84 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)
- chrome-extension	Release: v3.11.1.4:

Uncaught Error: [$injector:modulerr] Failed to instantiate module mewApp due to: Error: [$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.6.8/$injector/nomod?p0=mewApp

Error
Uncaught ReferenceError: baseUrls is not defined

Error
Uncaught Error: [$injector:modulerr] Failed to instantiate module mewApp due to: Error: [$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.6.8/$injector/nomod?p0=mewApp

Error
Failed to load https://api.myetherapi.com/eth: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://hnilhihegimhefmjbeajlhlpoibhabhn' is therefore not allowed access. The response had HTTP status code 504.

Error
TypeError: _callbacks[i] is not a function

Error
Uncaught ReferenceError: baseUrls is not defined

Error
Uncaught Error: [$injector:modulerr] Failed to instantiate module mewApp due to: Error: [$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.6.8/$injector/nomod?p0=mewApp

Error
TypeError: Cannot read property 'setBalance' of undefined

Error
TypeError: _callbacks[i] is not a function

Error
Uncaught ReferenceError: baseUrls is not defined

Error
Uncaught Error: [$injector:modulerr] Failed to instantiate module mewApp due to: Error: [$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.6.8/$injector/nomod?p0=mewApp

Error
Uncaught ReferenceError: baseUrls is not defined

Error
Uncaught Error: [$injector:modulerr] Failed to instantiate module mewApp due to: Error: [$injector:nomod] Module 'mewApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.6.8/$injector/nomod?p0=mewApp

**Comment by tayvano** [comment]
Please try again using new zip file: https://github.com/kvhnuke/etherwallet/releases/tag/v3.11.1.4

**Comment by tayvano** [comment]
lets continue any ongoing issues in #1449 so I can try to keep all this straight. I get an ungodly amount of notifications these days.
