### ISSUE TITLE
How Do I Generate Keystore File - Etherium Wallet

### ISSUE THREAD

**Issue by mike24camposano** [kvhnuke/etherwallet#1456]
Hi

I would like to seek assistance on 'how to retrieve a keystore file'.
I created my wallet account through myetheriumwallet.com and I have my private key on hand.

I have read a previous post (Apr 2017) with same issue "How Do I Generate Keystore File (UTC / JSON) #449" and followed it but somehow I think the UI changes and I cant seem to find a feature where I could download my keystore file.

Prior to this I also tried checking it through "myetherwallet.com" under "view wallet info" menu using my private key. and seen none that would allow me to download my keystore file.

Please enlighten if I missed something. TIA.

![no-download-keystore-file-feature](https://user-images.githubusercontent.com/34994410/34465710-6ddb5af8-eef4-11e7-9b12-757d34b002dc.jpg)

**Comment by Varunram** [comment]
@mike24camposano Did you try downloading the Chrome extension and importing your private key?

**Comment by mike24camposano** [comment]
Hi Varunram - yes I did and followed the instructions.  Clicking "My Wallets" menu from Chrome Extension only leads me to the attached screenshot. I already added that concerned ETH account and I cant see it there

![no-download-keystore-file-feature-02](https://user-images.githubusercontent.com/34994410/34466698-36e930d2-ef18-11e7-99f6-e4b7d9a288df.jpg)

But if I go to PAGE's "send ether & tokens" - I could see my added wallet.

![no-download-keystore-file-feature-03](https://user-images.githubusercontent.com/34994410/34466708-b162c0a8-ef18-11e7-8687-40f275ca7dda.jpg)

**Comment by gamalielhere** [comment]
@mike24camposano Are you still having this issue?

**Comment by QuangThong81** [comment]
I like

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
