### ISSUE TITLE
Not receiving my ETH to myetherwallet from Bitstamp.

### ISSUE THREAD

**Issue by hernansaa** [kvhnuke/etherwallet#1477]
Hi! I have sent 1.6 ETH the 23rd of December 2017 from Bitstamp to myetherwallet. Today I have sent 0.46 and 0.24 ETH as well and NONE of these got to mytherwallet.

I am trying to contact bitstamp but they are not replying. Perhaps you could tell me what is happening or tell me what to do because i am desperate and i don`t know what to do. Perhaps is your problem and i am blaming bitstamp.

I am not an expert but i always do transactions from one place to another and i have never had a problem, is the first time i have a problem like this. 

This is my address 0x8cd144FBB602a61E729bFAF3ABcE4912A5f1d0E3 . 

I much appreciate your help in advance! Hernán.

**Comment by spinnak3r** [comment]
As you can see from [https://etherscan.io/address/0x8cd144FBB602a61E729bFAF3ABcE4912A5f1d0E3](https://etherscan.io/address/0x8cd144FBB602a61E729bFAF3ABcE4912A5f1d0E3) Bitstamp hasn't sent your ETH yet. 
  Try contacting them with your ticket number on their twitter account [https://twitter.com/bitstamp](https://twitter.com/bitstamp)

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
