### ISSUE TITLE
[v3.11.1.8] Full token list display in Watch-only account ?

### ISSUE THREAD

**Issue by repsorp** [kvhnuke/etherwallet#1483]
Is is working properly ?
Tried with other ETH networks, full token list keeps displaying in Watch-only account

![capture du 2018-01-06 08-59-46](https://user-images.githubusercontent.com/6297032/34637887-15f1b524-f2c0-11e7-8d2a-594f4b22a5a5.png)

config:
Chromium 63.0.3239.84, Ubuntu 16.04
chrome-extension Release: v3.11.1.8
etherwallet v3.11.1.8

**Comment by tayvano** [comment]
Obviously not working correctly. The Chrome Extension pages that aren't part of MEW have been sadly neglected these past few months. I sincerely apologize and will try to get it onto short-term fix list.

**Comment by repsorp** [comment]
[v3.11.2]
Watch-Only Accounts list is OK with Giveth.io ETH network (correct display, no full token list)
Other networks still stuck with full token list

(Please don't apologize, you're doing such an amazing work)

**Comment by tayvano** [comment]
Ohhhh. I bet you hit the limits 😬

email me your IP address and Ill whitelist you for the time being. taylor at myetherwallet

**Comment by repsorp** [comment]
Perfect ! 
Thanks
