### ISSUE TITLE
Offline Transaction files

### ISSUE THREAD

**Issue by unknown1235** [kvhnuke/etherwallet#1489]
I am trying out the offline transaction method of MEW.
Is there a way you can publish the MD5 or SHA256 of the offline myetherwallet files found here:
https://github.com/kvhnuke/etherwallet/releases/tag/v3.11.2

Would like to double check for security just to make sure.

**Comment by wparad** [comment]
Could make sense to publish that if it is a recommended way of interacting with the downloads, although I think the release data can change, so might not be the most secure.  A safer method is to clone the repo and checkout the tag or sha for the version you want to use:
```bash
git clone git@github.com:kvhnuke/etherwallet.git
cd etherwallet
git checkout v3.11.2
```
and then open the file `./dist/index.html`

**Comment by unknown1235** [comment]
I am kind of new to github.  Could you show me how that could be done?

**Comment by unknown1235** [comment]
I am not doing this on linux.  This is on windows.  Anyway I can download the file and check it some how?

**Comment by wparad** [comment]
Sorry that isn't linux specific:
* [Git for Windows](https://git-scm.com/download/win)
* Click the Green Clone button on the right hand side:
![image](https://user-images.githubusercontent.com/5056218/34652698-173111b4-f3e2-11e7-85fd-906c17a409e2.png)
* Copy the repository url there.
* you can open the resultant `dist` > `index.html` file via windows explorer.

Although, I'm worried suggesting additional tools to use, decreases the security unless you inherently trust those tools.  When downloading the zip and running it you are trusting:
* github
* travis-ci (zip creator)
* your browser
* your zip extraction software
* your file explorer

with git clone you are instead trusting:
* github to fetch the files
* git to extract the files
* file explorer to load the site
* your browser to load the site

So while it offers a way to ensure the files are correct, it is still another program you are risking private key exposure to.

A question might be how secure do you want to be?  MEW recommends a [hardware wallet](https://myetherwallet.github.io/knowledge-base/hardware-wallets/hardware-wallet-recommendations.html)

**Comment by unknown1235** [comment]
Thank you 
I will try that shortly.
So once I install that and get the dist/index.html?
Will that have the  tag or sha for the version you want to use?  

I was using Ethereum wallet with geth.  But syncing that wallet is nearly impossible these days.  I had an old laptop that I been trying to syncing and its been over an week now.  Still stuck.
So now I am trying this offline method.  

I heard about the hardware wallet but have never tried them personally.  Any particular one you tried? what happens if they get corrupted or broken? 

The Digital Bitbox one seems interesting.  Maybe I will buy that after reading some reviews.

**Comment by wparad** [comment]
Those are all really good questions, but require a variety of answers, we probably should avoid using this ticket to dive into them though.  For help on anyone of those questions, I suggest seeking out both the [MEW Knowledgebase](https://myetherwallet.github.io/knowledge-base) as well as [ethereum communities](https://myetherwallet.github.io/knowledge-base/diving-deeper/ethereum-list-of-support-and-communities.html) for help.

As a request for the SHA256 of the zip file makes sense, so leaving this open is the right thing to do.

**Comment by unknown1235** [comment]
Appreciate all your help.
I will try that github app and go from there.
Thanks again for all the advice.
