### ISSUE TITLE
V4 tracker Issue

### ISSUE THREAD

**Issue by TheAIExpert** [kvhnuke/etherwallet#1491]
Sent a transaction. It said failed, bad instruction and now I don't know how to get my tokens back. Is there anyway to get them back.

**Comment by tayvano** [comment]
Please email support@myetherwallet.com. You can check your balance here https://myetherwallet.github.io/knowledge-base/getting-started/checking-balance-of-my-account.html. If you TX failed, your ETH nor tokens never left your account
