### ISSUE TITLE
Account balance shows "Loading"

### ISSUE THREAD

**Issue by Tobito19** [kvhnuke/etherwallet#15]
No changes! Account balance shows "Loading" after decrypting!
![image](https://cloud.githubusercontent.com/assets/16759445/12588968/0962ec56-c464-11e5-95ae-06517e88936d.png)

**Comment by tayvano** [comment]
@Tobito19 I've checked this with a couple of my accounts and have no issues. If you would like to see your balance, please use a blockchain explorer such as https://etherchain.org/ or http://etherscan.io/
