### ISSUE TITLE
Last slide missing "Finish" button at bottom

### ISSUE THREAD

**Issue by jidanni** [kvhnuke/etherwallet#1506]
Last slide missing "Finish" button at bottom:
![df](https://user-images.githubusercontent.com/1230959/34806424-c805aa1c-f6bd-11e7-85d4-f955abef5100.jpg)

**Comment by mohamedmansour** [comment]
Yea this UX needs improvement. Does this fit right?
![image](https://user-images.githubusercontent.com/68524/36059967-47af091e-0e0d-11e8-877a-890dd6a308a0.png)

**Comment by jidanni** [comment]
Good!
