### ISSUE TITLE
Send Message button doesn't work

### ISSUE THREAD

**Issue by jidanni** [kvhnuke/etherwallet#1507]
I see I should have reported https://github.com/MyEtherWallet/meta/issues/2 here.
Chromium
Version 63.0.3239.84 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by wparad** [comment]
@jidanni, almost.  It actually belongs here: https://github.com/MyEtherWallet/knowledge-base/issues

**Comment by gamalielhere** [comment]
@jidanni is the issue still happening?

**Comment by jidanni** [comment]
@gamalielhere I don't know because I don't use that website currently.

**Comment by gamalielhere** [comment]
I see. I'll close this issue for now and reopen it if the issue still exists.
