### ISSUE TITLE
OMG transaction doesn't complete

### ISSUE THREAD

**Issue by anudeep26** [kvhnuke/etherwallet#1508]
Hello Team,

Trying to transfer OMG tokens from mew to my exodus wallet. Getting the following error

Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce

To 0x350392a6c291459EAd3D9Feb848105dd2E8eFFd0

**Comment by andrewathalye** [comment]
Do what it says. Go to adv settings and change the nonce and gas limit/gas to a higher value. That should help.
