### ISSUE TITLE
Will myetherwallet offline mode works on ubuntu and in firefox?

### ISSUE THREAD

**Issue by unknown1235** [kvhnuke/etherwallet#1509]
It works fine in chrome and window but would this work in firefox and ubuntu?

Anyone ever tried it?

**Comment by srmojuze** [comment]
I believe it works fine and IIRC I tried it once in Linux. I am currently downloading Fedora 27 to use it with Firefox there. Unless you hear back, I believe everything should be fine.

**Comment by gamalielhere** [comment]
It should work fine @unknown1235 I haven't read or heard any issue about it so far.
