### ISSUE TITLE
Myetherwallet hacked and all funds are stolen!

### ISSUE THREAD

**Issue by spartanec777** [kvhnuke/etherwallet#1520]
Despite the fact that I followed all safety rules all mine ethereum are stolen out from my wallet
My ex- wallet address:0xf58c52c9a13A19938119629d496A27Cb300790A3
The final thief’s address: 0x05EE546c1a62f90D7aCBfFd6d846c9C54C7cF94c

**Comment by andrewathalye** [comment]
I'm not seeing your point-the most recent TX from your wallet was over a month ago, and not to the address you listed.

**Comment by spartanec777** [comment]
Yes, it's happens month ago. But still I cannot refund my ether. The point is to warn everybody that myetherwallet is not safe place to keep crypto, and better to use other option. This adress what I listed its a final, here it is full history (everybody can check it, if just to trace thiefs adress):
0xC096f5D2548006F8e75dd0479E3ee2C7984aE656
0x511121AC9C5022c1f72225adD11D1E18B6970652
0x05EE546c1a62f90D7aCBfFd6d846c9C54C7cF94c
And by the way, after investigation my case in reddit was found problem in EAL addon for firefox...Developers: Github. I know maybe it was just a fake addon, but anyway this knowledge don't refund mine funds...

**Comment by NghiaSE** [comment]
I cry for you, it's best to create a wallet and sign transaction offline

I TRUST MEW but if you can't trust MEW for whatever reasons, then you can generate your account offline using geth (geth account new) then import it to MEW

Test send / receive a small amount of ETH before receiving a massive amount of it.

**Comment by numero41** [comment]
I have also a mismatch address issue, I made a post about it, you can check it out

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
