### ISSUE TITLE
Add Custom Token: "Not a valid ERC-20 token"

### ISSUE THREAD

**Issue by peterhaddad98** [kvhnuke/etherwallet#1522]
Address: 0x45245bc59219eeaaf6cd3f382e078a461ff9de7b

I added "BKX" as a token and it is saying "Not a valid ERC-20 token".

What am I doing wrong?

Thanks, Peter

Edit:
It worked fine in Firefox! I guess it's a bug.

![capture](https://user-images.githubusercontent.com/26935752/34912195-866e6106-f8a8-11e7-9e94-cb59cf263b2e.PNG)

![capture](https://user-images.githubusercontent.com/26935752/34912218-76097386-f8a9-11e7-9aa3-82df5db2adbd.PNG)

**Comment by gamalielhere** [comment]
Closing this as BKX has been added to defaults.
