### ISSUE TITLE
No "Refund" menu

### ISSUE THREAD

**Issue by syndrael** [kvhnuke/etherwallet#1527]
Hello,
i don't know if it's the right site to describe the issue.
On https://www.myetherwallet.com/#contracts, after typing Contract Address & ABI / JSON Interface and pressing Access, there is nothing in the "Choose function" menu.
On Gnome/Debian Firefox and Chromium, nothing.
May you help me ?
Regards.

**Comment by gamalielhere** [comment]
@syndrael can you provide the token address and abi you used?

**Comment by gamalielhere** [comment]
I'll close this for now. Feel free to open if the issue is still there.
