### ISSUE TITLE
Myetherwallet/Metamask

### ISSUE THREAD

**Issue by keitheisenberger** [kvhnuke/etherwallet#1534]
When i set up myetherwallet, it prompted me to create a metamask account. After doing so, i needed to create i sent my TRX to the account. It shows that the Tokens are in there, but there is no balance. When i click on the token, it takes me to etherscan. But i can not figure out how to sell, transfer, withdraw my Tokens. Am i doing something wrong. Are my Tokens on the line?

**Comment by keitheisenberger** [comment]
![picture1](https://user-images.githubusercontent.com/35533666/35050127-86a52d6a-fbbb-11e7-8ab6-573d50842321.jpg)
This is all i see.

**Comment by wparad** [comment]
If you want to transfer your tokens elsewhere you'll need to:
* 1) Add ether to this address for part 2.
* 2) Sign a transaction on MEW using metamask and the contract for TRX specifying the target address.

**Comment by keitheisenberger** [comment]
Thanks. So how do The transaction. I apologize, New to this so need it
broken down.

-- 
Keith Eisenberger, Jr

**Comment by keitheisenberger** [comment]
So I have Ether in my Metamask account now. How do I go about sending the Tokens from Metamask to MEW. I do not see them anywhere in MEW.

**Comment by wparad** [comment]
MEW doesn't support TRX out of the box yet, so we'll need to create a contract transaction manually.
* Validate this is the [TRX contact](https://etherscan.io/address/0xf230b790e05390fc8295f4d3f60332c93bed42e2#code)
* Copy the contract address and the contract ABI to [MyEtherWallet Contract](https://www.myetherwallet.com/#contracts)
* Specify the `transfer` method and then enter the new address and amount (as a uint256 number).  to get a unit256 number you want to `amt_in_decimal x 10^6` = uint256.  TRX according to the contract is 6 decimals that's why 10^6.

I suggest doing this with a very small amount of TRX first to make sure it gets.  For instance 1 TRX => `1,000,000`.

>On a side note I would recommend against TRX, since looking at the contract, there is a method which basically says `Prevent any transfers`, which gives the owner the ability to make the token worth nothing whenever they want.

**Comment by keitheisenberger** [comment]
So before I do this, a few questions:

1.  what is the best wallet to use for this. I ordered a Nano that is not
here yet, hopefully it will be here in a few weeks

2. My tokens are all in Metamask, that is linked to MEW, yet their are no
tokens on MEW (has a 0 when I created a custom for Tron).

3. Will I always have to jump through hoops to pull out if I keep it in
Metamask

4. Is there a way to have it in MEW and not in Metamask. (If so, what are
the steps). I tried uploading the private pin to MEW and it always gives me
a balance of 0.

 5. apologize for all of the questions, I am currently sitting in Dubai
(Army-deployed) and am heading to bed in a few. Wanted to get all of the
questions out while I can since when I wake up it will be night time in the
US.

6. You confused me on the "


   - Specify the transfer method and then enter the new address and amount
   (as a uint256 number). to get a unit256 number you want to amt_in_decimal
   x 10^6 = uint256. TRX according to the contract is 6 decimals that's why
   10^6."

I understand your comment on TRX, had some decent reviews at the time. I am
diversified in a few different ones (Stella, Litecoin, Etherum, OmesiGO,
Ripple and honestly since everything has tanked, trying to figure out what
else to move to.




Keith Eisenberger, Jr

On January 17, 2018 at 10:06:43 PM, Warren Parad (notifications@github.com)
wrote:

MEW doesn't support TRX out of the box yet, so we'll need to create a
contract transaction manually.

   - Validate this is the TRX contact
   <https://etherscan.io/address/0xf230b790e05390fc8295f4d3f60332c93bed42e2#code>
   - Copy the contract address and the contract ABI to MyEtherWallet
   Contract <https://www.myetherwallet.com/#contracts>
   - Specify the transfer method and then enter the new address and amount
   (as a uint256 number). to get a unit256 number you want to amt_in_decimal
   x 10^6 = uint256. TRX according to the contract is 6 decimals that's why
   10^6.

I suggest doing this with a very small amount of TRX first to make sure it
gets. For instance 1 TRX => 1,000,000.

On a side note I would recommend against TRX, since looking at the
contract, there is a method which basically says Prevent any transfers,
which gives the owner the ability to make the token worth nothing whenever
they want.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-358391226>,
or mute the thread

**Comment by keitheisenberger** [comment]
I attempted to do this numerous times, and if either says I do not have
enough funds. There is one area that asks for the unit 256 (I put in
1000000 as a test of 1 torn. Then I go to the next screen and it asks
me "Amount
to Send In most cases you should leave this as 0.*"* and “gas".    Once I
go through this it gives me a red error stating insufficient funds. All
want to do is move it from Metamask to MEW.

-- 
Keith Eisenberger, Jr

On January 17, 2018 at 10:26:14 PM, Keith Eisenberger, Jr (
keith.eisenberger@gmail.com) wrote:

1,000,000

**Comment by wparad** [comment]
What's your address?

**Comment by keitheisenberger** [comment]
Keith.eisenberger@gmail.com


-- 
Keith Eisenberger, Jr

On January 19, 2018 at 12:29:24 AM, Warren Parad (notifications@github.com)
wrote:

What's your address?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-358772012>,
or mute the thread

**Comment by wparad** [comment]
:), your ETH address

**Comment by keitheisenberger** [comment]
Can you hit me on email so that I am not publishing it to the world.   :)


-- 
Keith Eisenberger, Jr

On January 20, 2018 at 2:59:32 PM, Warren Parad (notifications@github.com)
wrote:

:), your ETH address

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-359163151>,
or mute the thread

**Comment by keitheisenberger** [comment]
Ether Address: 
0xEB8835E3f3FcaFE1C6E46C8BfCEF52636aD27161

Wallet Address on MEW where I would like to move it: 0x97EfD92D4D95CDb9230b188fd757afa73D5dF64b

**Comment by wparad** [comment]
Looking at the first address, it seems you definitely have enough ETH for a transaction, I suggest trying it again.  When you got to the MetaMask prompt what values for **gas price** and **gas limit** did you use?

**Comment by keitheisenberger** [comment]
Changed it to the minimum for each… never go the chance to actually send
it, as i could not figure out the values with decimals and what not. I
would like to do a test of 100 tokens… what would that look like as the
value for TRX



-- 
Keith Eisenberger, Jr

On January 20, 2018 at 3:37:08 PM, Warren Parad (notifications@github.com)
wrote:

Looking at the first address, it seems you definitely have enough ETH for a
transaction, I suggest trying it again. When you got to the MetaMask prompt
what values for *gas price* and *gas limit* did you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-359165080>,
or mute the thread

**Comment by keitheisenberger** [comment]
When it says “how would you like to access your wallet (and gives you a
bunch of selections) which one is it talking about


-- 
Keith Eisenberger, Jr

On January 20, 2018 at 3:40:36 PM, Keith Eisenberger, Jr (
keith.eisenberger@gmail.com) wrote:

Changed it to the minimum for each… never go the chance to actually send
it, as i could not figure out the values with decimals and what not. I
would like to do a test of 100 tokens… what would that look like as the
value for TRX



-- 
Keith Eisenberger, Jr

On January 20, 2018 at 3:37:08 PM, Warren Parad (notifications@github.com)
wrote:

Looking at the first address, it seems you definitely have enough ETH for a
transaction, I suggest trying it again. When you got to the MetaMask prompt
what values for *gas price* and *gas limit* did you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-359165080>,
or mute the thread

**Comment by keitheisenberger** [comment]
When I try, it keeps coming up with this error at the bottom. (I entered
unit256 as 1000000) and on the following screen where it asks value and
gas, I entered 0 "Amount to Send In most cases you should leave this as 0". ,
and 30000 for gas. And this screen shot pops up

-- 
Keith Eisenberger, Jr

On January 20, 2018 at 3:48:32 PM, Keith Eisenberger, Jr (
keith.eisenberger@gmail.com) wrote:

When it says “how would you like to access your wallet (and gives you a
bunch of selections) which one is it talking about


-- 
Keith Eisenberger, Jr

On January 20, 2018 at 3:40:36 PM, Keith Eisenberger, Jr (
keith.eisenberger@gmail.com) wrote:

Changed it to the minimum for each… never go the chance to actually send
it, as i could not figure out the values with decimals and what not. I
would like to do a test of 100 tokens… what would that look like as the
value for TRX



-- 
Keith Eisenberger, Jr

On January 20, 2018 at 3:37:08 PM, Warren Parad (notifications@github.com)
wrote:

Looking at the first address, it seems you definitely have enough ETH for a
transaction, I suggest trying it again. When you got to the MetaMask prompt
what values for *gas price* and *gas limit* did you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-359165080>,
or mute the thread

**Comment by wparad** [comment]
[Don't see a screen shot]
* For a test of 100 TRX use a value of 100 * 10^6 or `100000000`
> how would you like to access your wallet

is really asking: "How would you like to sign your transaction".  I.e. you need to sign the actual transaction with your private key, there are a bunch of ways to do this.  Since you are using MetaMask:
* Make sure that your are logged into the extension.
* choose `MetaMask / Mist`
* click `Access`, the menu should disappear
* then click `Write` and then `Generate Transaction`
* When the MetaMask popup window is created make sure to enter at least `60000` for the **Gas Limit**, 21000 will only work for transactions which are ethereum token transfer, since you are transfering TRX not ETH it will definitely cost more than `21000`.  For instance, looking at one of the TRX transfers in your account [this one](https://etherscan.io/tx/0x0c4171d5649a688c276bd7e8af2e2780548431ff77fc3f49ab83d21670ddc8e6) the gas used was `37155`.

Since you are refunded all the gas which isn't used, it will be safe to set it higher.  For the **gas price** it is up to you, but if you pick `1` it will take > 24 hours, I suggest 21~41.

**Comment by keitheisenberger** [comment]
<img width="1440" alt="screen shot 2018-01-20 at 3 59 08 pm" src="https://user-images.githubusercontent.com/35533666/35183580-03bb1a92-fe02-11e7-881f-fef5b2edc0fb.png">

**Comment by keitheisenberger** [comment]
when I do it with Metamash and click write, I now get an error that says it is an invalid wallet file. tried changing the destination wallet, and still the same thing.

**Comment by keitheisenberger** [comment]
ok, just had success. I believe it is because I was trying to do it from Safari instead of chrome. So I assume, when I want to send it out, it is the same process?

**Comment by wparad** [comment]
Congrats.  Yes, every time you want to transfer the tokens elsewhere you will need to complete the same process.  Hopefully, in the future TRX's contract will be listed on MEW so you can skip the first couple of steps.

Unless there is something else, I suggest closing this issue by clicking the button below.

**Comment by keitheisenberger** [comment]
Would you happen to have the contract link for DENT

-- 
Keith Eisenberger, Jr

On January 20, 2018 at 5:24:56 PM, Warren Parad (notifications@github.com)
wrote:

Congrats. Yes, every time you want to transfer the tokens elsewhere you
will need to complete the same process. Hopefully, in the future TRX's
contract will be listed on MEW so you can skip the first couple of steps.

Unless there is something else, I suggest closing this issue by clicking
the button below.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvhnuke/etherwallet/issues/1534#issuecomment-359171301>,
or mute the thread

**Comment by wparad** [comment]
The process I use to find contracts is (if they aren't in the MEW list) is usually google (or [EtherScan search](https://etherscan.io/tokens?q=DENT):
* Here's the first link: https://coinmarketcap.com/currencies/dent/ (not sure if it is the right coin)
* Since its coinmarketcap:
![image](https://user-images.githubusercontent.com/5056218/35183926-2775ffec-fdee-11e7-8c6b-d89454d7ac32.png)
* Which brings you to etherscan:
![image](https://user-images.githubusercontent.com/5056218/35183929-328bb584-fdee-11e7-9b47-452b7cb9a0ed.png)

One thing to notice is that the decimals here is 8, so you'll be multiplying by 100,000,000 in the `uint256 value` field.

=====
If you already have the tokens in the wallet, you can directly navigate to the contract in Etherscan, by clicking around starting at the transaction that transfer the tokens to you.

If you don't you'll have to jump through these hoops.

**Comment by keitheisenberger** [comment]
awesome, thanks for your help.. by closing this, are all records deleted, wondering if I should screen shot everything

**Comment by wparad** [comment]
Never gets deleted (not sure if you can even delete issues in github).  For instance the permalink is in the url: https://github.com/kvhnuke/etherwallet/issues/1534

And you can find all issues in etherwallet here: [etherwallet issues](https://github.com/kvhnuke/etherwallet/issues?utf8=%E2%9C%93&q=is%3Aissue)

**Comment by keitheisenberger** [comment]
thanks for the help!
