### ISSUE TITLE
MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider 

### ISSUE THREAD

**Issue by msx752** [kvhnuke/etherwallet#1536]
i want to access to wallet with **MetaMask / Mist**
i am using chrome browser and i got this error in the console tab what should i do, 
```
inpage.js:98 MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider 
https://github.com/MetaMask/faq/blob/master/detecting_metamask.md#web3-deprecation
get @ inpage.js:98
etherwallet-master.js:1611 Uncaught TypeError: Cannot read property 'slice' of undefined
    at etherwallet-master.js:1611
    at inpage.js:14330
    at inpage.js:14330
    at inpage.js:9933
    at completeRequest (inpage.js:9984)
    at inpage.js:735
    at replenish (inpage.js:1255)
    at iterateeCallback (inpage.js:1245)
    at inpage.js:1220
    at inpage.js:9861
```

**Comment by tayvano** [comment]
What exactly were you trying to do? Do you have a wallet in MetaMask? Was your MetaMask unlocked?

**Comment by Asone** [comment]
This is not an issue. The message you see is a warning for developpers that intends to develop applications compatible with metamask. 

The message that is displayed is thrown by metamask and not by Etherwallet. 

As there is a v4 of MeW on the rails in development, pretty sure the evolutions of metamask will be supported. 

For more information about this deprecation [you can check here](https://github.com/MetaMask/faq/blob/master/detecting_metamask.md#deprecation-of-global-web3js)

EDIT : 

Note that the etherwallet error and the Metamask notification are probably 2 differents things and might not be related with each other
