### ISSUE TITLE
Missing Ether Transfer

### ISSUE THREAD

**Issue by ajonl** [kvhnuke/etherwallet#1539]
Please help. I have MEW and Trezor. 
I set up a new My Ether wallet secured by a new passphrase on Trezor today. 

I then transferred 2 ether from my previous My Ether Wallet with an old tresor passphrase to my new My ether wallet with the new passphrase.

I copied the address for the new My Ether wallet and put it in my clipboard.

Then I had to log out of that new My Ether Wallet and log into the old My Ether wallet.
I then pasted that new address into the old my ether wallet and sent 2 ether. 

I worked and transferred on the Ether chain, but when I logged back into my new My ether wallet, I can't find the address that was previously there?
How can I get my ether back to this new account?

Please help.

https://etherscan.io/tx/0x59e197b89b6faa8c5853560046010f099734da898ef2581ec117ca6a8012fc53

**Comment by numero41** [comment]
#1528

**Comment by numero41** [comment]
Could it be a similar issue as this one : 
Can't access to my wallet anymore #1528

**Comment by ajonl** [comment]
Please Kvhnuke if you could help. I'd appreciate it.

**Comment by ajonl** [comment]
@kvhnuke hemachandra, Please help me!

**Comment by numero41** [comment]
hello, do you have the same issue as here?

https://www.reddit.com/r/ledgerwallet/comments/7rd798/should_we_be_concerned_about_the_ledger/

I did the post...

**Comment by numero41** [comment]
I don't know if it's related to Ledger and/or mew :(

**Comment by ajonl** [comment]
Yes its very similar except for me I used the TREZOR. They address was generated from My ether wallet and hooked up with my Trezor. When I went back to that trezor, the address it generated previously wasn't there any more.

**Comment by numero41** [comment]
did you select the same derivation path?

**Comment by ajonl** [comment]
I selected the new wallet address from MEW and send ether there. When I went back to MEW it the ether wasn't there and the wallet address that was there previously wasn't there either.

**Comment by numero41** [comment]
but when you connected to mew, do you select hardware wallet on the right, then check Trezor derivation path, then the first address in the list under it?

**Comment by ajonl** [comment]
Yes exactly that way. Connect to Trezor 1st, then select Ether which send my browser to Myetherwallet, I put in my code to unlock the myetherwallet from my trezor and that's where I saw that 1st address.

**Comment by numero41** [comment]
So we have the same issue....
I don't know what to say, I don't have any answer from anywhere, I am just freaking out...

**Comment by numero41** [comment]
please leave also a comment here : #1528
so the support can gather informations from all sides

**Comment by numero41** [comment]
https://github.com/kvhnuke/etherwallet/issues/1528

**Comment by numero41** [comment]
https://github.com/kvhnuke/etherwallet/issues/1528

**Comment by numero41** [comment]
#1528

**Comment by ajonl** [comment]
I was able to find my ether. Please close this thread. It had to do with passphrase and using lowercase instead of uppercase. Trezor is very specific with passphrases
