### ISSUE TITLE
how to change the chainid for local rpc ?

### ISSUE THREAD

**Issue by leochan007** [kvhnuke/etherwallet#1540]
when using myetherwallet connected to local geth rpc service, then deploy a new contract, the chainid is always set to 1 by default. how to changeit？

**Comment by tayvano** [comment]
You can set the chainid under "EIP-155" checkbox when you add a custom node. The chainid is hardcoded into the chain itself, so it's not an arbitrary number.

**Comment by leochan007** [comment]
@tayvano thx a lot .i find it now. in the past ,i always use eth by default. the chainid is always "1" no matter which network i connect to (main or test or local rpc).
