### ISSUE TITLE
Funds stuck in my ethereum wallet

### ISSUE THREAD

**Issue by wizzsleeve** [kvhnuke/etherwallet#1551]
Hi guys, somehow I managed to cut and paste in a UTC file(to do what , i dont know, i think it was just to get the public address). Anyway I have eth stuck in the account and when I try and withdraw it to put in my current account the send shows a completely different address in my etherwallet or ethereum wallet. I have the password to my original account so if there is anything you can do with the public address and password i would give 10% of what I have in the account. My original mined account number was 0x0095DdBF6B001065cA6C84D9b57DE1C51d5523A6, all mined at dwarfpool. I have sent 20 emails and they have no respect to even respond. If you can do something , please let me know and I will give the password. If i can create a JSON or UTC file from my public address and password,that would be the fix. Is there such a way to do this?

Dumb new miner of 4 months. Not a rich man so this money would really help us out, we have been down on our luck for a while now. Please help.Windows 10 64bit mining on GTX1070 cards.

Bob-wizzsleeve

**Comment by GriffGreen** [comment]
Bob, let me just warn you... you are probably fucked. 

But join the Giveth riot at https://giveth.io/join/ and send me your keystore file... I will see if it is recoverable... please do not include your password along with the file, please keep that password to yourself.

And send any tips to the MyEtherWallet Donation address: 0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8

**Comment by tayvano** [comment]
Thanks Griff. @wizzsleeve I would take Griff up on the offer as if there is a chance of recovery, the Giveth team can do it.

**Comment by wizzsleeve** [comment]
Found this also but pretty sure its just going to be ths same info. My address in the wrong Json file. Still cant remember how I did it, I have some more sitting in dwarfpool with this address to so would be good to get a solution.

bob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by numero41** [comment]
@wizzsleeve 
@tayvano 

I have another issue, but found your post trying to find out mine.

You can try a deep search on your computer with thekeyword "cipherparams".

if you find it next to your correct public address, you can see there is a dictionnary with all the data that needs to be in the json file. You just need to remove the escape characters (\").

If you find it and remember the password you'll be able to recover your wallet.

You can use the "Agent Ransack" search tool on your system harddrive (if on windows).

D.

**Comment by wizzsleeve** [comment]
Sorry, still don’t know what you mean. Sent u the file with all the parameters. Do I take the “ off “cipherparams” or the number following in the {} brackets. Have u had any luck at ur end4?

Bob

On Thu, 25 Jan 2018 at 7:17 am, DL <notifications@github.com<mailto:notifications@github.com>> wrote:

@wizzsleeve<https://github.com/wizzsleeve>
@tayvano<https://github.com/tayvano>

I have another issue, but found your post trying to find out mine.

You can try a deep search on your computer with thekeyword "cipherparams".

if you find it next to your correct public address, you can see there is a dictionnary with all the data that needs to be in the json file. You just need to remove the escape characters (").

If you find it and remember the password you'll be able to recover your wallet.

You can use the "Agent Ransack" search tool on your system harddrive (if on windows).

D.

**Comment by numero41** [comment]
you must get a string like this : 

{"version":3,"id":"3b579021-5cef-4967-b039-aa72238e6598","address":"df38dade9dsfdfh454653fc1d00ab296d412ba11a2","Crypto":{"ciphertext":"2b1f0a9452a907d3268fb588601e9bbf980c4e8b29ed9f64a48ad78873204882","cipherparams":{"iv":"63a2302f2010b2f8b50bb9ce7cba8e9e"},"cipher":"aes-128-ctr","kdf":"scrypt","kdfparams":{"dklen":32,"salt":"37c147ec165bae02d1e8b6830sdffds796b3ea1ac446bbc492ddc6baa5fd60cbf","n":1024,"r":8,"p":1},"mac":"74da4c4b7db2c4b06df9144095db1bacebe4320847591dacba1bcc4083838e40"}}

(with different numbers of course)

just copy the text you find from {"version to the last "}}, you'll have to remove any  \ " if you have
then open notepad, paste the text inside it, save it on your desktop with any name/no extension needed
then go back to Mew, select open wallet from json file, and select this file.

For my issue, it's related to Ledger, so I didn't find a string with my correct address...

**Comment by numero41** [comment]
Did you have any success?

**Comment by wizzsleeve** [comment]
still no good, what text am i copying?

**Comment by numero41** [comment]
Where you able to find a text beginning with   {"version":3    and ending with    "}}    ?
(like the example I gave you)
If so, copy this text in notepad, save the file on your desktop, go back to mew and select "open from json file". 
Then you'll have to type your password and access to your wallet.

**Comment by wizzsleeve** [comment]
Hi again bud,
Yes mate, I can read everything in notepad just need to be specific on what to remove and exactly where from.
Im just a dumb aussie but Ill ask the question again. Do you want me to remove every “ and every }}? Or just the ones around cypher params etc? I cant screw it up anymore but don’t want to be seen by MEW to be doing anything dodgy(in Australia that means, not quite right), I’m sure you knew that anyway. Were are u based?

FYI, I appreciate your time and patience with me. If I get access you will be getting a six pack at least from me.

Bob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wizzsleeve** [comment]
still no good, what text am i copying?

**Comment by wizzsleeve** [comment]
[test UTC--2017-07-05T06-29-14.987641300Z--0095DdBF6B001065cA6C84D9b57DE1C51d5523A6.txt](https://github.com/kvhnuke/etherwallet/files/1673521/test.UTC--2017-07-05T06-29-14.987641300Z--0095DdBF6B001065cA6C84D9b57DE1C51d5523A6.txt)


This is the contents of the file. version 3 comes at the very end with a } to finish it.There is no where else the words version 3 appear.Is this where you mean?

**Comment by numero41** [comment]
You don't have to put in the same order.
The file seems good, but did you try to load it?
You should never send such a file in a public forum, the only thing missing for a hacker is your password now. 
If you manage to open your wallet, I strongly advise you to create a new one and move your coins.

**Comment by GriffGreen** [comment]
Yeah Bob, come back to our chat in riot and we can do some video chat to just try an make this work

**Comment by wizzsleeve** [comment]
Hey bud, I don’t have a webcam but I can try with my phone. Problem is my screen is always artifacting cos I’m pushing 5 X GTX1070’s. They don’t like it too much but that’s gigabytes issue not mine. What time would suit and how do I get hold of you? Can u send me the link to riot again please.

Bob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GriffGreen** [comment]
#Griff-takes-a-Wizz:matrix.org is what i named the room.
Join at https://giveth.io/join/... and make it easy on me?  :-D

**Comment by wizzsleeve** [comment]
Ill give you a poke when I get home from work today. U didn’t say where you are based so I know what time it is where u r.

Bob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gamalielhere** [comment]
I'm gonna close this. Don't hesitate to reopen if needed.
