### ISSUE TITLE
Please add DGX 1.0 Token Contract 

### ISSUE THREAD

**Issue by tymat** [kvhnuke/etherwallet#1556]
From https://github.com/MyEtherWallet/MyEtherWallet/issues/866 

Our DGX 1.0 ERC-20 token contract has some additional functions and we would like the ABI to be available on the Interact With Contract page

The ABI can be found here.

The contract address for DGX 1.0 is 0x55b9a11c2e8351b4ffc7b11561148bfac9977855

This functionality would be useful for our users as we are looking to launch DGX 2.0 in the near future. This would allow them to verify their balances on the old ledger as well as do some calculations to help them transfer their full balances to different accounts before we 'freeze' and begin the migration.

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
