### ISSUE TITLE
click transaction hash link in success message doesn't work

### ISSUE THREAD

**Issue by dgobaud** [kvhnuke/etherwallet#1570]
after submitting a transaction clicking the hash in the green success message at the bottom doesn't work in Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by tayvano** [comment]
Which page were you sending from?

**Comment by dgobaud** [comment]
send offline

**Comment by gamalielhere** [comment]
@dgobaud is this still an issue?

**Comment by dgobaud** [comment]
not sure havent used this in a while

**Comment by gamalielhere** [comment]
I see. I'll close this for now and will reopen when the issue is still persistent.
