### ISSUE TITLE
Cert.pem and Key.pem Files Purpose

### ISSUE THREAD

**Issue by all-encrypted** [kvhnuke/etherwallet#1571]
Hi, what are the additional files in the zip packages for?
They are called Cert.pem and Key.pem.

Thank you for the support.

**Comment by tayvano** [comment]
Its to set up a local ssl server for use of Ledger locally. Knowledge base article coming soon. Sorry for the delay

**Comment by all-encrypted** [comment]
Thank you for the clarification. This will be a great feature.
