### ISSUE TITLE
Crypterium

### ISSUE THREAD

**Issue by davewilliamson** [kvhnuke/etherwallet#1581]
How can I get to my Crypterium balance on a Trezor wallet?

**Comment by tayvano** [comment]
https://myetherwallet.github.io/knowledge-base/send/adding-new-token-and-sending-custom-tokens.html

**Comment by davewilliamson** [comment]
Thanks for that, but how does that relate to the TREZOR WALLET?

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
