### ISSUE TITLE
Save (list of) Transaction Hashes longer

### ISSUE THREAD

**Issue by dec1** [kvhnuke/etherwallet#1584]
Hello,

Thanks for making such a great tool. 

After sending a transaction a pop up appears briefly with a message with a transaction hash at the bottom of the browser window.
It would be nice if this information didn't disappear so fast. You have to be very quick to copy and paste it somewhere else if you want to keep it. It can easily happen that the transaction doesn't happen to show up any time soon in your account (public key) in etherscan.io and this transaction hash is the only thing you have to confirm that it should at least be pending soon.
Ideally the sent transaction hashes should be saved in a list somewhere at least until the browser tab is closed, but at the very least several times longer than the popup is currently shown.
Thanks in Advance.

**Comment by gamalielhere** [comment]
@dec1 Is this still an issue?

**Comment by dec1** [comment]
yes.

**Comment by gamalielhere** [comment]
@dec1 with version 3.21.07, it looks like the pop up doesn't close unless you click on the `x` at the bottom right of the screen. I'm gonna go ahead and close this issue for now. If you have any question or you want to reopen the issue, don't hesitate to reach out.

**Comment by dec1** [comment]
This is not fixed. The popup disappears on its own (in a second or two) - at least if you paste a signed (offline) transaction and send it
