### ISSUE TITLE
please allow specifying gas price in GWEI

### ISSUE THREAD

**Issue by dec1** [kvhnuke/etherwallet#1589]
Hello.
Currently one must enter a gas price in WEI, whihc generally entails ensuring you have about 9 zeros.
It would be much more comfortable and less error prone if one could enter a GWEI price instead Generally one enters a value from 1-100 GWEI.
Its easy to enter a zero too many or too few.

Maybe the choice of WEI or GWEI from a dropdown menu like one can choose ETH or a different token in "Value / Amount to Send".

Thanks

**Comment by NghiaSE** [comment]
I am with you @dec1 

https://ethgasstation.info/ uses GWEI

We should use GWEI too

**Comment by gamalielhere** [comment]
@dec1 @NghiaSE We just added a dropdown on the gas price  where you can pick whether you want to use WEI or GWEI! Thanks for the recommendation and keep em coming. You can take a look at the PR here: #1723

**Comment by dec1** [comment]
Thank you!
