### ISSUE TITLE
ETZ tx: unable to send entire balance

### ISSUE THREAD

**Issue by osnwt** [kvhnuke/etherwallet#1592]
I am trying to send entire balance of ETZ fork to another address. ETZ uses zero fees, so entire balance should be sendable.

Not being familiar with MEW, I tried to play with some addresses first. As far as I understand, I can set gas limit to X and gas price to Y. So amount to be sent should be the account balance - limit * price. If limit * price > 0, but fee will be 0, this amount will be returned back to account, so entire balance can't be sent.

Ok, I set limit = 0 (no fee anyway), and it did not allow me to send such tx.

Next I tried to set limit to 21000 and price to 0, and SOMEHOW I was able to send part of balance few times. The tx was mined with zero fee.

Now I am trying to send entire balance the same way, but even if I set price = 0 and entire account balance as amount to be sent, it tells me "Insufficient funds". Why if gas limit * fee = 0 I can't send entire balance?

Finally I decided to send all as is using "Send entire balance" function. But no go, it calculated amount to be sent (balance - limit*fee), but still tells me "Insufficient funds".

I use custom ETZ network (rpc.etherzero.org:443, id:88), and it worked for me yet 2 days ago.

**Comment by kvhnuke** [comment]
@osnwt this is actually due ETZ network currently sending a value for `eth_gasPrice` call. This is the result, I obtained just now `{"jsonrpc":"2.0","id":"d7f43308486dc917cca350937aa020de","result":"0x98bca5a00"}`

**Comment by kvhnuke** [comment]
hi @osnwt based on a quick research it seems like `eth_gasPrice` call sends an actual gas price value. 
`{"jsonrpc":"2.0","id":"d7f43308486dc917cca350937aa020de","result":"0x98bca5a00"}` I am not familiar with how ETZ gas price work but, seems like the node is rejecting your tx because you dont have the min gasprice*gaslimit

**Comment by osnwt** [comment]
Weird since they claim no-fee txes, and they actually are. But this means there is no way to send whole balance from an account...

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if you need to.
