### ISSUE TITLE
Offline erc20 tokens wont load

### ISSUE THREAD

**Issue by protecj** [kvhnuke/etherwallet#1596]
Hi, 

I've a problem and don't know how to fix it.. I've created a offline wallet and that works perfect but when i want to add different tokens and press: "load token" it keeps "loading". Is that normal or does that take ages to load? Or can i download other tokens on a different way? Or can i just send erc20 tokens to my eth address? 

Sorry for the noob questions but if someone can help me, that would be awesome.

Thanks anyways

**Comment by kvhnuke** [comment]
Hi when you say offline, do you mean  your computer is not connected to internet? In order to load token balances you have to be connected. I would use https://www.myetherwallet.com/#view-wallet-info and view with address only option to see the token balance as it is the most secure approach
