### ISSUE TITLE
MyEtherWallet.com vs MyCrypto.com

### ISSUE THREAD

**Issue by sgarciafer** [kvhnuke/etherwallet#1602]
I though it was just another phishing website, until I arrive at Twitter and noticed the prior account MyEtherWallet changed it's logo and info.

One thing is clear, I won't use MyCrypto.com until this get clarified, all I can say is the situation is confusing and will produce a loss of trust if there is not a clear explanation.

Can someone give some details about it?

**Comment by numero41** [comment]
+1

**Comment by jderocher** [comment]
I suggest checking out ethtrader's subreddit for some information - there is clearly a power struggle going on right now: https://www.reddit.com/r/ethtrader/comments/7wcyrm/sothe_mew_drama/?utm_content=title&utm_medium=new&utm_source=reddit&utm_name=ethtrader

**Comment by jderocher** [comment]
This is the statement from the "forked" MyCrypto, but I haven't seen anything from the one who is remaining on the side of MEW. https://twitter.com/mycrypto/status/961885331183185924

**Comment by sandakersmann** [comment]
Statement from @kvhnuke: https://twitter.com/myetherwallet/status/962071670562279425

**Comment by mohamedmansour** [comment]
Here is the lawsuit https://drive.google.com/file/d/1CHz_Fe5DqM7Aszsr5LwTdol85YsEJaaZ/view

**Comment by kvhnuke** [comment]
MEW and MyCrypto are completely different entities. MEW team will continue to develop MEW and continue to be the community oriented client side wallet
