### ISSUE TITLE
Mobile Top Header Buttons Not Friendly

### ISSUE THREAD

**Issue by mohamedmansour** [kvhnuke/etherwallet#1603]
When you launch the homepage, the current design looks like the following, the buttons on the right are cropped.
![image](https://user-images.githubusercontent.com/68524/36059641-31660b56-0e0a-11e8-9399-03fcfe65588d.png)

We can do better, what I propose is that we make the logo vertical, what do you say?
![image](https://user-images.githubusercontent.com/68524/36059906-1e4efa76-0e0c-11e8-96f9-1dee3fdf0553.png)

**Comment by mohamedmansour** [comment]
Even better, I believe we should redesign the buttons to be column based, if you would approve such request, I can help contribute code for it.

**Comment by gamalielhere** [comment]
This has been fixed recently. I'll close this issue. Don't hesitate to open it if you believe it's still not fixed.
