### ISSUE TITLE
ajaxReq is empty function

### ISSUE THREAD

**Issue by scientistnik** [kvhnuke/etherwallet#1609]
I want to create some application based on `myetherwallet`. But I don't send some requests because ajaxReq is empty function. Where in code this object init? Or maybe need install some package?

**Comment by syAlbert** [comment]
Hhh

**Comment by scientistnik** [comment]
if I start some local server, MeW work well, and ajaxReq not empty!!

**Comment by gamalielhere** [comment]
@scientistnik the ajaxRequest function is set in globalService.js with angular services and node functions. It's line 5 to 8 in that file. Let me know if you need anything else. I'll close this for now.
