### ISSUE TITLE
Where has my NEO gone?

### ISSUE THREAD

**Issue by davidmoldenchen** [kvhnuke/etherwallet#1622]
I have 189 NEO. I checked my NEON wallet just now and the balance is zero. I updated to the latest Mac version of NEON wallet but still will not show my NEO. Is there a bug or something?

**Comment by kvhnuke** [comment]
@SteveMieskoski

**Comment by gamalielhere** [comment]
Hey @davidmoldenchen you might be in the wrong Github repo. This is MyEtherWallet's repo. We don't handle NEON wallets.

**Comment by gamalielhere** [comment]
@davidmoldenchen closing this for now.
