### ISSUE TITLE
Wrong smart contract address for RVL Token

### ISSUE THREAD

**Issue by allquantor** [kvhnuke/etherwallet#1624]
```
address: "0x41f615e24fabd2b097a320e9e6c1f448cb40521c",
symbol: "RVL",
decimal: 18,
type: "default"
```
The given address seems to be wrong. It was a fund by accident, I assume they could be more. It would be nice to run a script and validate all addresses given the pattern
- Does this address contain a smart contract?
- Does this address contain at least a single ERC20 transaction

To clean it up. 

WDYT?

**Comment by gamalielhere** [comment]
@allquantor sounds like a good way to validate them. I'm unsure how to achieve the second part at the moment but I've created a nodejs script that checks whether the address is a smart contract or not. [Here's the checker](https://gist.github.com/gamalielhere/c31796aa45d10af33e0de0d8a6664344). Let me know what you think.

**Comment by allquantor** [comment]
@gamalielhere There is a way to approximate the second. 

a.) Fetch the `ABI` from Etherscan (if available) and check if `Transfer, Approval..` events are included.
b.) If no `ABI` get a couple of Transactions from the `smart-contract`, get the TxReceipts, look into the logs of TxReceipts if they contain valid data e.g `keccak256("transfer(address,amount)"`...

Although this still does not give a 100% probability because it does not cover ERC20 contracts without transactions. Well than you can redeploy the bytecode on your private chain and try to fuzz the VM traces. 

We developed an app that does it at @toknapp, I will look for a way to make it opensource.

Cheers
