### ISSUE TITLE
Offline ETH Is not Loading

### ISSUE THREAD

**Issue by bazredhat** [kvhnuke/etherwallet#1626]
I have a offline Wallet that i use for almost a year now. Suddenly My ETH Balance wont load. This is a serious matter. I have 94.924 ETH in the Wallet. 
Please Help.

**Comment by bazredhat** [comment]
Anyone?

**Comment by bazredhat** [comment]
WTF is going on. How is it possible that no one answers. I posted 2 days ago. Please Someone Help. Why is this happening. What do you need me to send you so you can investigate the situation?

**Comment by gamalielhere** [comment]
Have you tried checking your balance on [MeW](https://www.myetherwallet.com/)?  
Also, this might be a similar case #1596
