### ISSUE TITLE
Not a valid ERC-20 token

### ISSUE THREAD

**Issue by czwei86** [kvhnuke/etherwallet#1637]
(error_21) Not a valid ERC-20 token
 created an ERC20 contract, verified by EtherScan, and I can't add it to MEW.

Address: 0x164E45D38ab8e97B247E1e75d17A2f01EA20b395
Symbol: B2BX
Decimals: 18

**Comment by kvhnuke** [comment]
You have to use the address of the contract, which is 0x5d51FCceD3114A8bb5E90cDD0f9d682bCbCC5393

**Comment by czwei86** [comment]
try already but show nothing 
amonut 0 please check

**Comment by kvhnuke** [comment]
what is your address?
you can also email it to me kvhnuke @ myetherwallet . com

**Comment by czwei86** [comment]
Problem solved
