### ISSUE TITLE
[Request] Sign releases with your PGP key and include hashes

### ISSUE THREAD

**Issue by leafcutterant** [kvhnuke/etherwallet#1651]
In order to increase the reliability of MEW, I suggest you create a PGP key for MEW, publish it, sign releases and include the signature file in the release downloads. As an additional measure and for easier verification, you could also include hashes (e.g. MD5, SHA-256) of the files.

**Comment by kvhnuke** [comment]
@gamalielhere @SteveMieskoski this is actually a good feature to have, can you look into travis and check whether we can automate this

**Comment by kvhnuke** [comment]
`gpg --keyserver keyserver.ubuntu.com --recv-key 7B9A12F0`

download a file and appropriate signature file [FILE].asc 
https://github.com/kvhnuke/etherwallet/releases/tag/v3.20.03-GPG

then
do 
`gpg --verify [FILE].asc [FILE].zip`

let me know how it goes

**Comment by kvhnuke** [comment]
also thanks @gamalielhere for getting this to work!

**Comment by xsmile** [comment]
@kvhnuke Works fine, thank you.
```
% gpg etherwallet-v3.20.03.zip.asc 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: assuming signed data in 'etherwallet-v3.20.03.zip'
gpg: Signature made Do 08 Mär 2018 02:15:16 CET
gpg:                using RSA key 7F059C0F7B9A12F0
gpg: Good signature from "MyEtherWallet Inc <support@myetherwallet.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2FCA 4A1E 3AF4 278F 7AD3  B763 7F05 9C0F 7B9A 12F0
```

**Comment by gamalielhere** [comment]
Closing this.

**Comment by leafcutterant** [comment]
For easier verification, I further suggest displaying a link to the PGP key somewhere in README.md or even including it in the release packages.
