### ISSUE TITLE
problem claiming Callisto

### ISSUE THREAD

**Issue by dsr1001** [kvhnuke/etherwallet#1659]
I tried to add Callisto to www.myetherwallet.com using
contract address:
0xC83872d11C2B9C30E58029B025De5c1294E36541
decimals: 0
symbol: CLO
but I get:
(error_21) Not a valid ERC-20 token     CLO
Can you please tell me what I am doing wrong?
Thanks
Pavel

**Comment by adewyn** [comment]
If you're referring to the new CLO fork of the classic ethereum chain, this is actually not an erc-20 token. This is a completely different kind of currency, on a different blockchain. 

At the moment, we have not been reached out to support the Callisto fork network. Do not worry though, your CLO is safe! These funds are not stored on any site, but on the blockchain itself.

We are working on getting the network/node under way, but for now www.classicetherwallet.com says they support the Callisto fork. It should be accessible under the CLO Testnet Network under the Network/Node option in the upper right of their interface.

Our sites are interchangeable, so feel free to unlock your wallet in the same way there as you would on our site, and access your Callisto in this way.

*Disclaimer: We are not affiliated with ClassicEtherWallet in any way, but they claim to support this fork*

Let me know how it goes! :)

**Comment by gamalielhere** [comment]
Closing this for now. Please reopen if it's still an issue @dsr1001
