### ISSUE TITLE
Phishing site https://xn--myethewallet-kjc.com/

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#1660]
The phishing site

https://xn--myethewallet-kjc.com/

which will appear in your web browser's address bar as 

https://myetheŕwallet.com/

is designed to look like MyEtherWallet, and will presumably steal keys. I saw this in a phishing email that asked users to immediately load their private keys into the above phishing site to save them from some alleged Ethereum flaw.

I entered a web spam (phishing) report to Google at https://safebrowsing.google.com/safebrowsing/report_phish/ so their Chrome browser can then block it, but I have seen no result from this.

NOTE: Please do not go to the URLs above and enter your real private keys into them.

**Comment by kvhnuke** [comment]
Thanks for the heads up, I also reported and included it in https://github.com/409H/EtherAddressLookup/blob/master/blacklists/domains.json#L5997

**Comment by fortran77** [comment]
Can you also please post this warning somewhere where more people will see it? E.g., maybe via your Twitter or Reddit account. The phishing email that I saw looked very real and I think people will be taken in and lose their Ether.
