### ISSUE TITLE
BKX decimal value should be 18 instead of 8

### ISSUE THREAD

**Issue by aquarius777** [kvhnuke/etherwallet#1662]
https://github.com/kvhnuke/etherwallet/blob/440e3524e24e51df18451d842bc82152915888d1/app/scripts/tokens/ethTokens.json#L299

Line 299 should look like this: 

"decimal": 18,

See:

https://blog.bankex.org/how-to-add-your-bkx-tokens-to-your-wallet-a312866e5ef

**Comment by gamalielhere** [comment]
It's been updated on our master list: https://github.com/MyEtherWallet/ethereum-lists/commit/5499da755d3836f005384badbfbeda63cc0947e5

Live list should reflect this when a new release is made @aquarius777
