### ISSUE TITLE
Invalid private key input

### ISSUE THREAD

**Issue by qoire** [kvhnuke/etherwallet#1664]
![screen shot 2018-03-09 at 11 35 23 pm](https://user-images.githubusercontent.com/4521292/37238350-985decfe-23f2-11e8-8244-d6bcc8ae5b0b.png)

Private key was invalid (out of bounds) and console rightfully logged an exception, however the popup still indicates the wallet was successfully unlocked

**Comment by kvhnuke** [comment]
Fixed
