### ISSUE TITLE
Add well-known contract -- Su Squares

### ISSUE THREAD

**Issue by fulldecent** [kvhnuke/etherwallet#1706]
Hello, can you please add a well-known contract to MyEtherWallet.

Su Squares
Mainnet / 0x6731560e455537c9f088EA02A47a0ECFa28a9231
ABI: https://etherscan.io/address/0x6731560e455537c9f088ea02a47a0ecfa28a9231

This is an ERC-721 contract. You can confirm this is the correct address by seeing:

* https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md
* Which points to Su Squares. https://tenthousandsu.com
* Which has a white paper showing the above address and also susquares.eth

I am the lead author of the ERC-721 standard. This standard is in the ACCEPTED stage of the EIP process.

---

The Explore 721 conference is happening this weekend. It will be very nice to have this standards-compliant ERC-721 contract in MEW by then if possible.

**Comment by gamalielhere** [comment]
Moved to: [#554](https://github.com/MyEtherWallet/ethereum-lists/pull/554)
Please check back when a release is made to see the contract on the website.

**Comment by fulldecent** [comment]
Excellent, thank you, much appreciated.
