### ISSUE TITLE
RCN (Ripio Credit Network) Token

### ISSUE THREAD

**Issue by extrimexxx** [kvhnuke/etherwallet#1712]
Please add RCN (Ripio Credit Network) token

  {
    "address": "0xf970b8e36e23f7fc3fd752eea86f8be8d83375a6",
    "symbol": "RCN",
    "decimal": 18,
    "type": "default"
  },

**Comment by gamalielhere** [comment]
Moved [#553](https://github.com/MyEtherWallet/ethereum-lists/pull/553).
Please wait for a release cycle to see your tokens in the defaults.
