### ISSUE TITLE
Tokens list ends at BCPT (v.3.21.04 )

### ISSUE THREAD

**Issue by repsorp** [kvhnuke/etherwallet#1737]
Only some of the first 560 Tokens are listed
List stopped at BCPT

MyEtherWallet 3.21.04
Chromium Version 65.0.3325.181
Ubuntu 16.04 (64 bits)

![capture du 2018-04-04 01-51-15](https://user-images.githubusercontent.com/6297032/38281730-6105e860-37ac-11e8-98ea-85b9339df073.png)

**Comment by repsorp** [comment]
stuck with never ending spinning wheel
"Inspect" command in Chromium gives the full 560 list though
![capture du 2018-04-04 09-37-35](https://user-images.githubusercontent.com/6297032/38296996-63369606-37f3-11e8-9ee5-1d887c347624.png)

**Comment by gamalielhere** [comment]
@repsorp do you get any console errors when stuck on the loading wheel?

**Comment by repsorp** [comment]
It's working now...
Full 560 tokens list scrolling fine
Don't know what happened

**Comment by gamalielhere** [comment]
Ahh. I see. Thanks for reporting back. I'll close this issue for now.

**Comment by gamalielhere** [comment]
#1744
