### ISSUE TITLE
Chrome extension required to read browsing history

### ISSUE THREAD

**Issue by siutsin** [kvhnuke/etherwallet#1738]
Hi, any particular reason why the Chrome plugin required to read my browsing history?

![photo_2018-04-04_09-42-28](https://user-images.githubusercontent.com/904442/38284194-96507c02-37ec-11e8-938a-248b9c62d4aa.jpg)

**Comment by kvhnuke** [comment]
We added a new feature where Chrome extension will check the page you visit to make sure it is not a known phishing address

Currently the extension will require following permissions

"permissions": ["storage", "tabs"]

**Comment by mikz0rz** [comment]
Isn't this a bit too much of a tradeoff, I mean potential value of being protected vs. giving away complete browsing history?
Would be great if that'd be optional.

**Comment by kvhnuke** [comment]
Google message is too generic. "tabs" permission is not same as "history"
https://developer.chrome.com/apps/permission_warnings

**Comment by siutsin** [comment]
Had a quick look at [permission_warnings](https://developer.chrome.com/apps/permission_warnings), the `tabs` permission should indicate `Access your browsing activity` instead of `Read your browsing History`. The closest one is `Read and modify your browsing history` which should be `history` and `topSites`.

Indeed, in https://github.com/kvhnuke/etherwallet/blob/29bd27b268557c9cc394b07cc6b70d42d6740a79/chrome-extension/manifest.json#L22 it is showing `tabs` which is very confusing.

I believe the intention is great, but this looks a bit off as a wallet. Should this feature be decoupled as another plugin?
