### ISSUE TITLE
MEW CX trying to add tokens

### ISSUE THREAD

**Issue by nolannj** [kvhnuke/etherwallet#1744]
Tokens list ends at BCPT , and before this issue it did not finish downloading token list was incomplete.
  I removed MEW CX and reinstalled it and added my accounts but same problems

**Comment by jeffro84** [comment]
I found that resizing the window (making it wider) made the token list stop getting stuck at BCPT.  But I agree this is a bug, I wasted a bunch of time waiting for it to load as well.  

Also, GTO is not in the new list for some reason

**Comment by gamalielhere** [comment]
@nolannj Thanks for submitting the issue. I'll try and fix this today and hopefully get it released soon.

@jeffro84 Thanks for pointing out the screen width thing. There was an issue about this yesterday but the other person mentioned it fixed it self. I did replicate it successfully just now so I'll look into this.

**Comment by gamalielhere** [comment]
The fix has been merged. Will be in the live extension after a release.

**Comment by nolannj** [comment]
Is there a way to add tokens ? only 560 tokens added BLZ, Ncash not listed.

**Comment by gamalielhere** [comment]
@nolannj Unfortunately, we don't have a direct Add custom token.
On the upcoming release, you can add a custom token the same way on the web
```
1. Go to send token
2. Unlock wallet
3. Add custom token on lower right hand side of the screen
```
You can then search the token on the myWallets tabs and add it there.
That feature will be added in this PR: #1747

**Comment by QuangThong81** [comment]
Mau xanh luc
