### ISSUE TITLE
Adding Musicoin back to MEW

### ISSUE THREAD

**Issue by Varunram** [kvhnuke/etherwallet#1749]
Musicoin recently had a hardfork which enables EIP 155 and that should ideally make it work with MEW .(ref. #912) I can PR back with the code if the MEW devs are okay with adding Musicoin back, so do let me know reg this. Thanks!

**Comment by gamalielhere** [comment]
@Varunram go ahead and make a PR for it. I'll close this issue now. Don't hesitate to open it.
