### ISSUE TITLE
Add custom Token -Token Symbol problem

### ISSUE THREAD

**Issue by keithofaptos** [kvhnuke/etherwallet#1750]
I wrote a coin on Erc20 blockchain.
token symbol : B!
created : 0x51aFAF65886Dd5B9Dcd9F022AAF69e03Cd187eAa 
i see other tokens on your click to download list with symbols
that are not letters or numbers.
Why am i not able to add my custome token with a "!" ,or are
there limitations i'm not aware of with MEW ?

If so could you send me a link to that intel pls ty ?

**Comment by gamalielhere** [comment]
@keithofaptos this should be working now. 
<img width="403" alt="screen shot 2018-04-25 at 10 27 04 am" src="https://user-images.githubusercontent.com/16236741/39262089-41c19ca6-4873-11e8-8670-294f3d5dd43d.png">
