### ISSUE TITLE
ENS resolving doesn't works on Ropsten

### ISSUE THREAD

**Issue by nosuchip** [kvhnuke/etherwallet#1762]
- Open "Send Ether & Tokens".
- Input "mewtopia.eth".
- Wait.
- Address resolved is zero.

**Comment by gamalielhere** [comment]
@nosuchip mewtopia.eth ens is in the main net and it should resolve to zero since it's not on the test net. The test net is a different entity. It doesn't contain the same data the main net has.

**Comment by nosuchip** [comment]
@gamalielhere I found strange thing. I have 2 domains in Ropsten network: `coinbet.eth` (namehash `0x42a5ebe68c0e702c984d8f85c878ae0089752a649fd8c1740ee6cba2b3704607`) and `iddqdidkfa.eth` (namehash `0x3dd04d4e58201bbf0c5698e03e8f28a5f0775a8e1e8dc899ac7ba877f26029de`). Both served by the same Ropsten ENS `0x112234455c3a32fd11230c42e7bccd4a84e02010`. Both are set to be resolvable to address (not reverse one).

For `coinbet.eth`  used resolver address `0x4c641fb9bad9b60ef180c31f56051ce826d21a9a` and this address doesn't resolved via MEW.

For `iddqdidkfa.eth` used anther resolver address: `0x5ffc014343cd971b7eb70732021e26c35b744cc4` and it works (i.e. when I putting this domain name it is resolved to my address).

**Comment by gamalielhere** [comment]
@nosuchip I tried it just now. Looks like `coinbet.eth` resolves to `0x4c641fb9bad9b60ef180c31f56051ce826d21a9a`?  

and `iddqdidkfa.eth` resolves to `0xF011B485DF2A66A3019dEa82E1EBbf7C716443A1` on the Ropsten network on MEW.
You're certain you set the proper resolver addresses?

<img width="843" alt="screen shot 2018-04-16 at 9 20 44 am" src="https://user-images.githubusercontent.com/16236741/38822248-b1b4e4fa-4157-11e8-94d5-4e6008c33105.png">
<img width="844" alt="screen shot 2018-04-16 at 9 21 20 am" src="https://user-images.githubusercontent.com/16236741/38822249-b1e2e60c-4157-11e8-86db-dae6aedc6c15.png">

**Comment by gamalielhere** [comment]
Closing. If the issue persist, don't hesitate to reach out.
