### ISSUE TITLE
poa into erc20 wallet

### ISSUE THREAD

**Issue by mickgearty** [kvhnuke/etherwallet#1763]
can you help with this please
below is a transaction showing my poa tokens 

the tokens are showing in my wallet now but do i need to do anything else or just keep them there

Your Address | Balance | Token Balances
-- | -- | --
0xeAF89788D3f67628E2dB37f2C1E82be49DE4A041 | 26536.99 POA |  
0x62a7817EDD68E6DFbe386Be339Ca3b862c44aA38 | 0 POA |  
0xb35E46D1986dF065C3C681cA90c623ACE0a3a5a5 | 0 POA |  
0x01B69f56992CB561839a9F03A5C55102D3d1815B | 0 POA |  
0xa7520D50D1f35fE3c0fd58A5de74540297194097 | 0 POA |  
  |   | More Addr

Hash: | 0xb675734f1cf3503f34f95a5f16424364f866b754f24d65f758a2605c8f425dae
-- | --
1961790 (64003 block confirmations)
3 days - 4-8-2018 19:35:25 (UTC)
Success
0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be
0xeaf89788d3f67628e2db37f2c1e82be49de4a041
26536.99 POA
21000
0.000000001 POA (1 GWEI)
0.000021
1612
0x

**Comment by gamalielhere** [comment]
@mickgearty what do you mean "do anything else"? What are you trying to do exactly?

**Comment by gamalielhere** [comment]
@mickgearty Closing this for now. Let me know if I can help you with something else.
