### ISSUE TITLE
Unknown Correct Path Error

### ISSUE THREAD

**Issue by decapod1234204** [kvhnuke/etherwallet#1791]
How do I fix this? I'm receiving the following message when trying to access my ledger through myetherwallet: 

We do not know the correct path for this network. Please open a github issue so we can discuss / be enlightened.

**Comment by gamalielhere** [comment]
@decapod1234204 can you try hard refreshing your browser and retrying?

**Comment by decapod1234204** [comment]
@gamalielhere Thanks for the help. I hard refreshed my browser and it worked. I also updated my firmware on the ledger to 1.4.2 from 1.3.1 today.

**Comment by gamalielhere** [comment]
I'm glad it worked! As always, if you have any other trouble, don't hesitate to open a new issue.
