### ISSUE TITLE
Cannot connect to TREZOR - "We do not know the correct path for this network."

### ISSUE THREAD

**Issue by vfedorovsky** [kvhnuke/etherwallet#1792]
Hello everyone.  This is my first time posting here.  I have no idea what's going on w/ My Ether Wallet but I cannot access my wallet and I am concerned.

I keep getting this error: "We do not know the correct path for this network."

Please help.  Thank you. 

<img width="779" alt="screen shot 2018-04-24 at 7 24 24 pm" src="https://user-images.githubusercontent.com/38707472/39218919-5389939a-47f5-11e8-8153-0e450063afe1.png">

**Comment by vfedorovsky** [comment]
I am really concerned with what's going on here...

**Comment by gamalielhere** [comment]
@vfedorovsky can you try hard refreshing your browser and retrying?

**Comment by vfedorovsky** [comment]
Will you please tell me how to do a hard refresh?  Thank you.

**Comment by gamalielhere** [comment]
@vfedorovsky What OS are you running? And what browser are you using?

**Comment by vfedorovsky** [comment]
Mac and Google Chrome

**Comment by gamalielhere** [comment]
command + shift + R should hard reset your browser. So go to myetherwallet website and hard refresh it there. And try using the trezor again

**Comment by vfedorovsky** [comment]
Yes, that worked! Thank you 😃

**Comment by gamalielhere** [comment]
Sounds good. Let's close this issue. Don't hesitate to reopen if it still persists.

**Comment by vfedorovsky** [comment]
@gamalielhere thanks so much for helping me.  I see you are a full stack developer.  I have some very general questions about your work.  Would it be okay to contact you directly about this?  Thanks again 😄
