### ISSUE TITLE
Select HD derivation path We do not know the correct path for this network. Please open a github issue so we can discuss / be enlightened.

### ISSUE THREAD

**Issue by allycatD** [kvhnuke/etherwallet#1793]
Unable to unlock wallet.  Error message "Select HD derivation path -
We do not know the correct path for this network. Please open a github issue so we can discuss / be enlightened."

**Comment by vfedorovsky** [comment]
Same here, Allycat.  Not sure what's going on...

**Comment by decapod1234204** [comment]
Same here, but with my ledger.

**Comment by vfedorovsky** [comment]
I hope we can get this figured this out!

**Comment by Kanaka23** [comment]
@allycatD  Not sure what wallet you are referring to but there has been a problem of changing public addresses with Ledger Nano users.  There are a couple of threads going on Reddit & Github.
https://github.com/kvhnuke/etherwallet/issues/1528  https://www.reddit.com/r/ledgerwallet/comments/8e30jt/warning_to_ledger_users_this_issue_is_still_not/dxsky04/?st=jgczik5y&sh=523feb35

**Comment by vfedorovsky** [comment]
I am using Trezor

**Comment by allycatD** [comment]
Thanks @Kanaka23.
I'm using Ledger Nano S.
Since @vfedorovsky is using Trezor, the error is probably not related to the hardware wallet but maybe due to MEW???
Not sure if MEW being hacked has anything to do with it:  https://cointelegraph.com/news/myetherwallet-warns-that-a-couple-of-its-dns-servers-have-been-hacked
I just upgraded to Ledger fimware 1.4.2 and this happened.  I'm going to reset Ledger and see if it resolves the issue.

**Comment by tanthon53** [comment]
Happening here too with my Ledger. I'm able to get in to my wallet but balances will not load and unable to send any ETH or tokens. Seems to me like a MEW issue.

**Comment by gamalielhere** [comment]
@allycatD have you tried hard refreshing your browser? I can't seem to replicate it on my end.

**Comment by tanthon53** [comment]
Update - I was receiving this error using a Mac/iOS. I just tried using another computer with Windows and I was able to access MEW using my ledger with no issues.

**Comment by gamalielhere** [comment]
@tanthon53 Can you try using your Mac/iOS and hard refresh the browser and see if that works?

**Comment by vfedorovsky** [comment]
Yes, that worked!  Thank you 😃

**Comment by vfedorovsky** [comment]
@gamalielhere thanks so much for helping me. I see you are a full stack developer. I have some very general questions about your work. Would it be okay to contact you directly about this? Thanks again 😄

**Comment by tanthon53** [comment]
@gamalielhere I tried the browser refresh on my end and was unable to get it to work.. but great news that it's working for others. I'll just continue to use my other computer for now. Thanks for your help.

**Comment by gamalielhere** [comment]
@tanthon53 Sure thing. but if you can, try command + shift + R on the Mac and see if that works.

**Comment by tanthon53** [comment]
@gamalielhere Tried that and it definitely worked! Everything seems to be back to normal. Thanks so much for your help.

**Comment by gamalielhere** [comment]
Sure thing! I'll close this issue for now. Please don't hesitate to reopen it.

**Comment by allycatD** [comment]
THANK YOU! @gamalielhere  You're a genius!!!
I tried on my MAC and didn't have the same problem.  So I hard refreshed the browser on my Windows and it worked!

**Comment by gamalielhere** [comment]
I'm glad it worked. As always, don't hesitate to open an issue when you run into troubles.
