### ISSUE TITLE
Could not connect to this node

### ISSUE THREAD

**Issue by Troppo1971** [kvhnuke/etherwallet#1795]
Hi there
I was just looking for a bit of advice ,i have a trezor wallet and have been using it for a few months now and when go to go to myther wallet through the trezor option i am getting error33 COULD NOT CONNECT TO THIS NODE and all the drop menus are all down ,then i click connect to trezor and the HD Path option comes up which i havent changed and it is set on 

m/44'/60'/0'/0
Jaxx, Metamask, Exodus, imToken, TREZOR (ETH) & Digital Bitbox

then i click on open wallet and it goes to the wallet but all the drop menus are still down and there is no balance for my ETH and TOKENS ,when i click transaction history for both it takes me into ethplore where i can see my ETH and TOKENS ,it wont let me send either .If someone could help that wouold be great .Thanks

**Comment by gamalielhere** [comment]
@Troppo1971 Have you tried hard refreshing your browser?

**Comment by gamalielhere** [comment]
Closing this for now. If the issue persist, refer to: [#1793](https://github.com/kvhnuke/etherwallet/issues/1793)
