### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by Saab104** [kvhnuke/etherwallet#1796]
Is there a way I can decode the parameters

params:[{to: "0xEc97f8d63867DD6ced28906bDa709C5ba04F25dF", data: "0xce6d41de"}, "pending"] 
1.0:{to: "0xEc97f8d63867DD6ced28906bDa709C5ba04F25dF", data: "0xce6d41de"}
2.1:"pending"

**Comment by kvhnuke** [comment]
to is the address field, data will contains the ABI encoded parameters.
https://web3js.readthedocs.io/en/1.0/web3-eth-abi.html

**Comment by jmacwhyte** [comment]
@kvhnuke Let's close this issue as it is resolved.

Is it helpful for me to flag issues that need to be closed? I hate seeing so many open tickets. If you can give me permissions to close issues I will help prune them for you. You can @jmacwhyte me on twitter if you want to discuss more.
