### ISSUE TITLE
Ledger Path issue

### ISSUE THREAD

**Issue by freemarket** [kvhnuke/etherwallet#1798]
When I try to connect my Ledger Nano S, which is up to date on firmware, I get the following message:

We do not know the correct path for this network. Please open a github issue so we can discuss / be enlightened.

Would appreciate some help! Thanks!

**Comment by gamalielhere** [comment]
@freemarket Have you tried hard refreshing the browser?

**Comment by freemarket** [comment]
@gamalielhere No, I hadn't tried that. I just did and the message went away after trying again. Think it's all good. Thank you!!!
