### ISSUE TITLE
"We do not know the correct path for this network"

### ISSUE THREAD

**Issue by steveyang24** [kvhnuke/etherwallet#1799]
Hi,

I use a Trezor to access MEW and it has worked great. However, I tried logging onto my account today after 2-3 weeks of inactivity and "We do not know the correct path for this network" show up in the "Select HD derivation path" option. It led me to this link where it suggested I should report to Github. Can you please help? I have installed the latest Trezor firmware, tried different USB plug and restarted computer. Still no luck.

Thanks
S

**Comment by wheeliespeedy** [comment]
Yeah I'm getting it too tried logging in again but now it shows up all the time blocking access. I think it's a fault in MEW website I guess it's wait n see mate.

Wheeliespeedy

**Comment by gamalielhere** [comment]
@steveyang24 @wheeliespeedy Can you guys try to hard refresh your browser windows?

**Comment by sparker90** [comment]
same problem with ledger, help please

**Comment by steveyang24** [comment]
Update: I still don't know what it is, but when I try to use another device (i.e. if I use my laptop instead of my desktop), I was able to unlock my account successfully.

**Comment by gamalielhere** [comment]
@steveyang24 @sparker90  Can you try hard refreshing your browser?

**Comment by wheeliespeedy** [comment]
Hey thanks gamaliehere doing the hard reset of browser fixed my MEW problem

**Comment by gamalielhere** [comment]
Closing this for now. If the issue persist, refer to: [#1793](https://github.com/kvhnuke/etherwallet/issues/1793)
