### ISSUE TITLE
Sign Message results diff then using private key and connects to metamask

### ISSUE THREAD

**Issue by dryruner** [kvhnuke/etherwallet#1801]
![image](https://user-images.githubusercontent.com/1220361/39305053-a1b23402-4910-11e8-8a8d-ff7412b0dec3.png)
![image](https://user-images.githubusercontent.com/1220361/39305076-adf6adba-4910-11e8-84f2-632208ba54ed.png)
![image](https://user-images.githubusercontent.com/1220361/39305102-c1f052e4-4910-11e8-9782-7af293c5acf0.png)

It seems using private key directly matches what geth signes.

**Comment by kvhnuke** [comment]
This might be related to how we handle "0x" prefix 
Similar issue was fixed in https://github.com/kvhnuke/etherwallet/pull/1788/commits/c692b1aeb548247e95f0bf7b6674e450adc91736
