### ISSUE TITLE
nano ledger not connecting to MEW

### ISSUE THREAD

**Issue by sparker90** [kvhnuke/etherwallet#1802]
hi guys, can anyone help, my nano does not connect with MEW anymore, everything is updated  and was workin fine, but now i get this message.:

We do not know the correct path for this network. Please open a github issue so we can discuss / be enlightened

any help will be appreciated

**Comment by gamalielhere** [comment]
@sparker90 can you try hard refreshing your browser?

**Comment by gamalielhere** [comment]
Closing this for now. If the issue persist, refer to: [#1793](https://github.com/kvhnuke/etherwallet/issues/1793)
