### ISSUE TITLE
Cannot make a withdraw using ledger nanoS.  

### ISSUE THREAD

**Issue by DTDITT** [kvhnuke/etherwallet#1815]
Then error message I get when I try to make a withdraw says "Error_33 Cannot connect to the node".  
I have 1.3 Etherum in the following address:   0x90E78Ac1cCdCE889DD1C0559bCB38541507357a5
When I open my wallet I don't see the address icon.  The account address shows up but the round icon is empty.  This happens on all 5 of my account addresses on my ether wallet.

**Comment by gamalielhere** [comment]
@DTDITT Try hard refreshing your browser

**Comment by gamalielhere** [comment]
Please reference https://github.com/kvhnuke/etherwallet/issues/1793 if the problem still persists.
