### ISSUE TITLE
QR code transfers

### ISSUE THREAD

**Issue by jeee** [kvhnuke/etherwallet#1821]
Generate a QR code for a signed transaction that then can be imported on the 'Generate & Send Offline Transaction' page (or a small phone app to send the transaction). This way using an offline device becomes even easier.

**Comment by gamalielhere** [comment]
@jeee We are in the process of creating a phone app that is similar to what you are recommending. You can find out about it more [here](https://mewconnect.myetherwallet.com/#/)
