### ISSUE TITLE
Can't Access Ledger Wallet with Local copy of MEW

### ISSUE THREAD

**Issue by nycbrian** [kvhnuke/etherwallet#1826]
Hi,

I downloaded the latest v3.21.09 version of MEW and I am trying run a local copy to view my  erc-20 tokens on my ledger nano s.

I click on: view wallet info > Ledger Wallet

I then click on the "connect to ledger wallet" button and nothing happens. I have my ledger hooked up with the Ethereum app running and browser support on.  Is there something else I need to be doing?

Thanks

**Comment by Kanaka23** [comment]
Try this link: https://www.myetherwallet.com/

**Comment by nycbrian** [comment]
I was hoping to run this off my computer locally on my machine.

**Comment by gamalielhere** [comment]
The API used to access the Nano S only works when started from an HTTPS connection as a policy - you can choose to run it on a local server though. Also: [Reddit comment about the same issue](https://www.reddit.com/r/ledgerwallet/comments/7glnzy/ledger_nano_s_on_mew_offline/dqjxyps)
