### ISSUE TITLE
I withdrew my POA from Binance on to myetherwallet because I thought it was a ERC20 Tooken

### ISSUE THREAD

**Issue by CryptoGirl3** [kvhnuke/etherwallet#1828]
Hello, I withdrew my POA Tokens from Binance to myetherwallet, however the token never loaded into my ethereum wallet. I did some research and found out that POA is Not an ERC20 token, how ever it is compatible with the ethereum wallet. So I changed the HD Derivation path in the top right hand corner of my ether wallet to Network P0A Core. poa network , and all of my tokens in this area. But what concerns me now is a  red warning sign comes up over the myetherwallet and it says , "We do not know the correct path for this network."  Should I be concerned about this? Can I send my tokens safely back to the Binance exchange.  I'm just checking to see if my coins are safe in the "NetworkPOA Core.POA network HD Derivation path? Are my tokens on the POA Blockchain? I also used my ledgerNanaoS are my private keys safe? Please let me know if I should just send my POA coins back to Binance for safe keepings. I am very new to the crypto space and I appreciate all of your help. Thank you.

**Comment by mgarciap** [comment]
Following these instructions: https://github.com/poanetwork/wiki/wiki/POA-Network-on-Ledger I was able to connect to POA core network with my Ledger Nano S and get my Account Address. Then I sent POA tokens from binance to this address and it worked (checked balance in `View Wallet Info` menu)

**Comment by CryptoGirl3** [comment]
Hi  Manuel, Thank you for your help. I was able to see the balance of my POA coins. I appreciate your help.
