### ISSUE TITLE
Where is the ajaxReq module source code 

### ISSUE THREAD

**Issue by tecoLai** [kvhnuke/etherwallet#1841]
Hi,

I am try to review the myEtherWallet source code.
I notice that there have a lot of place will use ajaxReq.getTransactionData function but I can not find the source code. 

the ajaxReq code I can find in the mercury branch is like below:

[https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/ajaxReq.js](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/ajaxReq.js)

Does anyone know where is the source code of ajaxReq.getTransactionData function?

thanks

**Comment by gamalielhere** [comment]
If you console log ajaxReq in the dev console, it will show the source code for the functions which is in https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/nodeHelpers/customNode.js

customNode is then looped through and assigned to ajaxReq: https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/tabsCtrl.js#L87

Also, refer to #1609 

closing this for now. Don't hesitate to reach out if you need anything else.
