### ISSUE TITLE
Incorrectly listing EOSToken address as scam address

### ISSUE THREAD

**Issue by dskvr** [kvhnuke/etherwallet#1842]
EOS ERC20 Token Address: `0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0`

![screen shot 2018-05-11 at 2 06 10 pm](https://user-images.githubusercontent.com/299465/39923559-7be515ee-5524-11e8-9120-fa34674b416a.png)

Sounds like someone at MEW was duped.

**Comment by gamalielhere** [comment]
Removed the token from the darklist in #1843. Should reflect it once we make a release. Thanks for catching this.
