### ISSUE TITLE
Transfered Tomo from Idex.market but in myetherwallet balance is 0

### ISSUE THREAD

**Issue by StirlinCastle** [kvhnuke/etherwallet#1847]
Hi there,

When I Checked the transaction history, I can see my 45 Tomo however in myetherwallet the balance is 0.

Could anyone help me with this?

**Comment by gamalielhere** [comment]
@StirlinCastle can you give me your public address?

**Comment by jmacwhyte** [comment]
@kvhnuke This issue should be closed.
