### ISSUE TITLE
3.21.11 not working offline with ledger nano s

### ISSUE THREAD

**Issue by InterestedInterloper** [kvhnuke/etherwallet#1861]
Hi,

I downloaded this most recent version and using both Chrome and Firefox tried to access my Ledger nano s but the "Connect to Ledger Wallet" button doesn't do anything.  Using the online version the wallet popup displays and everything works fine.  Any ideas on why this might be?

Thanks.

**Comment by b10c77** [comment]
You need to run MEW though SSL for the Ledger Nano S to work.

**Comment by InterestedInterloper** [comment]
How the hell do you do that when offline?


On Thu, Jun 14, 2018, at 7:58 AM, Steven Martins wrote:
> You need to run MEW though SSL for the Ledger Nano S to work.


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/kvhnuke/etherwallet/issues/1861#issuecomment-397268837

**Comment by b10c77** [comment]
nginx or caddy allow you to run a reverse proxy and attach an ssl certificate effectively providing a local server with ssl capabilities.

Please see: https://github.com/kvhnuke/etherwallet/issues/1429

https://github.com/benjaminion/eth-parity-qnap/wiki/Connecting-to-MyEtherWallet

**Comment by InterestedInterloper** [comment]
Thanks!


On Thu, Jun 14, 2018, at 8:16 AM, Steven Martins wrote:
> nginx or caddy allow you to run a reverse proxy and attach an ssl
> certificate effectively providing a local server with ssl
> capabilities.> Please see: #1429[1]


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/kvhnuke/etherwallet/issues/1429
  2. https://github.com/kvhnuke/etherwallet/issues/1861#issuecomment-397273149
