### ISSUE TITLE
ENS lookup says "Requires --pruning=archive" even though it's not needed

### ISSUE THREAD

**Issue by andrewheadricke** [kvhnuke/etherwallet#1864]
I run a private Parity node, and point MEW to use it.  When trying to lookup an ENS name it throws an error about needing to run with `--pruning=archive`.  But I am able to resolve ENS domains without that doing it manually.

**Comment by kvhnuke** [comment]
this is due to the fact that we used to have 'pending' as the last parameter of eth_call now we switched to 'latest' you no longer need --pruning=archive
