### ISSUE TITLE
Change validation for existing passwords > 0

### ISSUE THREAD

**Issue by GilAlexander** [kvhnuke/etherwallet#187]
The button "Unlock" under "Unlock your Wallet:" appears only when you typed 4 or more symbols of your password. My keystore was created on an old version of Mist and my password is consist of 1 symbol so I'm unable to use your service with my keystore file. It's also quite difficult to export the private key from keystore since there're no official way to do so.

**Comment by tayvano** [comment]
😂 Sorry about that! I will update the validation on the password field to be one character required.

**Comment by tayvano** [comment]
Sorry for the delay - this is fixed now.
