### ISSUE TITLE
(error_21) Not a valid ERC-20 token	AIT

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#1898]
I deployed contract by myetherwallet and 
see it(and find by search) in Ethplorer and Etherscan 
https://ethplorer.io/address/0x73ce0199ad8df2eb387a5240429380454ecd2548
https://etherscan.io/token/0x73ce0199ad8df2eb387a5240429380454ecd2548

can add custom token but when click "Click to load" get error 
(error_21) Not a valid ERC-20 token

**Comment by ghost** [comment]
?Anybody answer here

**Comment by Simon0x** [comment]
Maybe it's a problem with your contract code.
But you have not verified your code on Etherscan, so we are not able to view the code.

**Comment by ghost** [comment]
THe issue can be closed, for full ERC-20 support it was neccessary also to write all variables, not only methods
