### ISSUE TITLE
[Feature request] add data field to send transaction

### ISSUE THREAD

**Issue by wildbunny** [kvhnuke/etherwallet#19]
This wallet is great, but it would be even better if you allowed users to specify an optional 'data' field when they send a transaction, it should have the same effect as the data field you specify in eth.sendTransaction() in geth.

**Comment by kvhnuke** [comment]
thank you for the suggestion, we are planning to implement a send transaction section for advance users which will also allow them to sign them offline. I'll make sure  we add the data field :+1:

**Comment by tayvano** [comment]
@kvhnuke The advanced tab is the main thing I want to implement this weekend/week. Plus typos.

**Comment by kvhnuke** [comment]
https://www.myetherwallet.com/#offline-transaction

**Comment by wildbunny** [comment]
Hey that's great! My only suggestion would be if it were possible to take the data field from that form and put it on the regular send page as an optional, because the advanced tab is super complex looking for everyday users :)

**Comment by tayvano** [comment]
@wildbunny FYI - we are looking to implement an optional gas / data field on the standard send transactions tab in the near future. Specifically, it's #3 on our to do list. Keep your eyes open in the next week or so.

**Comment by tayvano** [comment]
WIll launch with v2.
