### ISSUE TITLE
Set default gas to 23300 instead of 21000

### ISSUE THREAD

**Issue by Arachnid** [kvhnuke/etherwallet#191]
This would allow wallet contracts to receive without going out of gas by default, and won't cost standard transactions anything more than it already does.

**Comment by tayvano** [comment]
@Arachnid 

Rawr. I hate the gas situation right now. Do you know if there is an easy way to detect if something is a wallet contract vs standard account? Is estimateGas() fairly consistent with detecting wallet contracts? 

The reason we don't use the estimate function currently is that it doesn't seem very reliable and wildly increased the number of support requests when we last tried to implement it. However, if we arbitrarily change the default gas to 23300, people will be emailing that "Send entire balance" was actually "Send almost the entire balance". 😝

Any advice? We simply aren't super familiar with wallet contracts at this point.

**Comment by Arachnid** [comment]
> Do you know if there is an easy way to detect if something is a wallet contract vs standard account?

Yes; if `eth_getCode` returns nothing, it's an external account; otherwise, it's a contract.

> The reason we don't use the estimate function currently is that it doesn't seem very reliable and wildly increased the number of support requests when we last tried to implement it.

It's been improved of late, though it's difficult to say what might have been wrong when you tried it last.

> However, if we arbitrarily change the default gas to 23300, people will be emailing that "Send entire balance" was actually "Send almost the entire balance". 😝

Oh dear. Well, sending 23,300 if it's a contract and 21,000 if it's not would work, although I'd be happy to work with you to figure out any problems you're having with estimateGas.

**Comment by kvhnuke** [comment]
@Arachnid 
I've been playing with the estimate gas for a while now. However, everytime i tried i never received the desired results. for example

`ajaxReq.getClassicEstimatedGas({"from":"0x26588a9301b0428d95e6fc3a5024fce8bec12d51","to":"0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444","value":"0x01","data":"0x0f2c932900000000000000000000000049e1cb970a4123d5a1c716c04d37332b10cda3c000000000000000000000000026588a9301b0428d95e6fc3a5024fce8bec12d51"},function(data){console.log(new BigNumber(data.data).toString());})`

thats a transaction to splitContract. and it returns the estimatedGas as 32134. When you look at etherscan.io for the actual gas used it is 31561.  In this case the estimate is larger than the actual. However, Ive came across cases where it is the opposite. Actual is lot larger than the estimate. Any help in pointing me int he correct direction will be greatly appreciated.

**Comment by Arachnid** [comment]
>  it returns the estimatedGas as 32134. When you look at etherscan.io for the actual gas used it is 31561

So, that's going to be the case sometimes, and is expected, because it's possible for a transaction to _require_ more gas than it uses. There are two main ways this happens; the first is because there are gas refunds due to deleting storage elements, which only happens at the end of the transaction. The second is that a contract makes a call to another contract, specifying a fixed amount of gas, only some of which is used.

> However, Ive came across cases where it is the opposite. Actual is lot larger than the estimate.

There's a couple of bugs around that which have since been patched, though I don't think they've made it into a release yet. If you can reproduce it on geth develop, please do send me a transaction that causes it.

**Comment by kvhnuke** [comment]
Hi @Arachnid 
Ive been playing around the estimate gas more, found another problem
http://etherscan.io/tx/0xaa057666d69cb8ea73c712df553149d4e8a2fc9c618b37ca82deb0941364a51d
that transaction went through with 60000 gas, and used gas shows 31561 and then I used 31561 as the gas limit and sent another transaction.
http://etherscan.io/tx/0xd8a7c7a6d135a3198c9aa2acce44da1f5be0c1fefd273806885ce832d8f117c2
which failed, then I tried another one at 40000 gas which is more than the amount returned by the estimate gas function
http://etherscan.io/tx/0x7421b09389df3193321745487efbe361d0e1c7b7bf46e394b61561bcbbe07b86
which also failed. Im super confused :( 

Note:
brute forcing the gasLimit let me figure out replaycontract requires minimum 49599

**Comment by Arachnid** [comment]
So, as you observe, it's pretty common for a transaction to require more gas than it consumes; either due to refunds or because it calls another contract whilst specifying some amount to send. That last makes gas estimation even harder, since the code may use the amount remaining to estimate how much it can send to the callee!

How much gas did estimateGas say that transaction needed? If it's less than what it actually needed, can you open a bug on geth?

**Comment by kvhnuke** [comment]
Thanks @Arachnid I think I finally understood how things work. I was able to implement estimateGas function using the vmTrace in parity and it can estimate the absolute minimum for a transaction to fully process through the vm. I'll open tickets in both geth and parity as geth estimate gave 32134 and parity estimate was 31561. However, replay contract requires minimum 49599 to get fully processed, way I implemented it can actually estimate 45599. code is at https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/ethFuncs.js#L66

**Comment by Arachnid** [comment]
That looks like a great start. How does it work with the amount of gas provided to a call? I realised last night that this gets really complicated with unqualified calls to other contracts; in that situation, Solidity sends all but a small amount of the gas - meaning that the 'high water mark' depends on the value of msg.gas, which makes estimating even harder. No matter what you set the gas limit to, you'll get a high water mark of almost that much.

**Comment by kvhnuke** [comment]
Now that I am revisiting the trace I think I took the harder way to estimate the gas using vmTrace, you can use the trace function and come up with the same results with less annoying loop 😉 
`"trace": [
            {
                "action": {
                    "call": {
                        "callType": {
                            "call": []
                        },
                        "from": "0xa7deff12461661212734db35ade9ae7d987d648c",
                        "gas": "0x02fa9268",
                        "input": "0x0f2c93290000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a8000000000000000000000000a7deff12461661212734db35ade9ae7d987d648c",
                        "to": "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444",
                        "value": "0x06f05b59d3b20000"
                    }
                },
                "result": {
                    "call": {
                        "gasUsed": "0x1d31",
                        "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
                    }
                },
                "subtraces": "0x02",
                "traceAddress": []
            },
            {
                "action": {
                    "call": {
                        "callType": {
                            "call": []
                        },
                        "from": "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444",
                        "gas": "0x02fa2f86",
                        "input": "0x16c72721",
                        "to": "0x2bd2326c993dfaef84f696526064ff22eba5b362",
                        "value": "0x00"
                    }
                },
                "result": {
                    "call": {
                        "gasUsed": "0xc5",
                        "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
                    }
                },
                "subtraces": "0x00",
                "traceAddress": [
                    "0x00"
                ]
            },
            {
                "action": {
                    "call": {
                        "callType": {
                            "call": []
                        },
                        "from": "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444",
                        "gas": "0x08fc",
                        "input": "0x",
                        "to": "0x7cb57b5a97eabe94205c07890be4c1ad31e486a8",
                        "value": "0x06f05b59d3b20000"
                    }
                },
                "result": {
                    "call": {
                        "gasUsed": "0x00",
                        "output": "0x"
                    }
                },
                "subtraces": "0x00",
                "traceAddress": [
                    "0x01"
                ]
            }
        ]`

that is the trace call to replay contract. so the way im using to estimate is by pretty much trying to figure out the most expensive call. In that case it is 50000000-(0x02fa2f86-0xc5) = 49599 or if you do all in decimal 50000000-(49950598-197) = 49599.

**Comment by tayvano** [comment]
Alright it works! If you enter a contract address, it now auto updates the gas via estimate gas. Prety much the best thing ever. Thank you so much for your help here!

![screen shot 2016-09-16 at 12 33 05 am](https://cloud.githubusercontent.com/assets/7924827/18578525/58e8009c-7ba5-11e6-99c4-021225b28636.jpg)

**Comment by Arachnid** [comment]
That's awesome news!
