### ISSUE TITLE
How to generate offline transaction for new token?

### ISSUE THREAD

**Issue by kostepanych** [kvhnuke/etherwallet#1913]
Is there possibility to generate offline transaction on offline PC for new token that is not present in the select list yet?
Maybe I should add something to sources?

**Comment by kostepanych** [comment]
I found this in the etherwallet-master.js file:

`module.exports={
  "tokens": {
    "OMG": {
      "name": "OmiseGO",
      "decimals": 18,
      "address": "0xd26114cd6EE289AccF82350c8d8487fedB8A0C07"
    },`
And this:
`121:[function(require,module,exports){
module.exports=[
	{
		"address": "0xa024e8057eec474a9b2356833707dd0579e26ef3",
		"symbol": "$FYX",
		"decimal": 18,
		"type": "default"
	},`
If I add here new token, will it work?

**Comment by gamalielhere** [comment]
@kostepanych adding your to there would add the token. You can also try using the add custom token feature on the lower right when you unlock your wallet. I'm closing this issue. Don't hesitate to reopen it.
