### ISSUE TITLE
Can't transfer musicoin from trezor

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#1919]
Hi guys, i have error "insufficient funds for gas * price + value" when trying send musicoins. I have more than i want to send but i have that error. When im using wallet from JSON File everything working fine . Error is only on trezor.

**Comment by jmacwhyte** [comment]
@bartgb This has nothing to do with MEW. Please contact trezor support.

@kvhnuke This issue should be closed.

**Comment by hackmod** [comment]
@bartgb problem resolved by https://github.com/trezor/trezor-mcu/pull/381
