### ISSUE TITLE
Offline Transactions and Ultra-High Gas Price

### ISSUE THREAD

**Issue by TheCookieLab** [kvhnuke/etherwallet#1959]
When generating offline transactions, the Gas Price in step 1 looks like it's denominated in wei. However in step 2, the Gas Price is denominated explicitly in gwei and thus you get a ridiculous Gas Price auto-filled. This easily leads to huge, disproportionate transaction fees.

For example, my transaction from this morning estimated a gas price of 41000000000 wei in the first step. A problem here is the Gas Price is not explicitly called out to be wei. 

When I click Generate Information, the value of 41000000000 is auto-populated into Step 2's Gas Price which is denominated in gwei. If I now go through with the transaction, I've just specified a transaction fee of 41 ETH. Not cool.

**Comment by gamalielhere** [comment]
This should be fixed now with https://github.com/kvhnuke/etherwallet/issues/2133
