### ISSUE TITLE
Add custom token offline

### ISSUE THREAD

**Issue by avirdoz** [kvhnuke/etherwallet#1975]
Looking for opportunity to add a custom token for offline mode. It's hard to edit etherwallet-master.js file for new tokens, maybe there is some constructor? 
P.S. I'm trying to add AURORA DAO token - 0xCdCFc0f66c522Fd086A1b725ea3c0Eeb9F9e8814 contract address.

**Comment by gamalielhere** [comment]
@avirdoz have you tried adding a custom token on the lower right of the screen after unlocking your wallet?

**Comment by avirdoz** [comment]
I don't have such option on "Send-Offline" page. It's like a template for all tokens in file which i specified on 1st message.

**Comment by gamalielhere** [comment]
@avirdoz My apologies for misunderstanding. Adding custom token offline isn't a feature at the moment. Although, you can make a PR here: https://github.com/MyEtherWallet/ethereum-lists and we can add that to the defaults
