### ISSUE TITLE
Migrate to Trezor Connect v5

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#1978]
TREZOR remade the whole library from scratch

https://github.com/trezor/connect/tree/v5

@kvhnuke @gamalielhere @karel-3d @prusnak @szymonlesisz

**Comment by prusnak** [comment]
v5 API is much easier to use. Let's use this issue to ask for any questions you might have.

**Comment by ghost** [comment]
@prusnak  If v5 is much easier to use, why not we've implemented them on MyEtherWallet, the 2nd large platform for Trezor wallet users yet??

![default](https://user-images.githubusercontent.com/35648187/43356694-6a3b36e2-92b0-11e8-9af0-31d6b3da7be3.PNG)

I hope the next version of MyEtherWallet comes with new v5 API!! Let's go! 🚀

**Comment by prusnak** [comment]
Because it was released yesterday

**Comment by ghost** [comment]
@prusnak So you are going to work for myetherwallet integration right?? 😄

**Comment by kvhnuke** [comment]
@SteveMieskoski we should use v5 for mew v5 https://github.com/MyEtherWallet/MyEtherWallet

**Comment by eosclassicteam** [comment]
May I ask for process on this issue?? @kvhnuke @gamalielhere
