### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by myalcin81** [kvhnuke/etherwallet#201]
myetherwallet.com ETH, ETC , bla bla.. All Informations doesn't load on API Call . It has an error 

XMLHttpRequest cannot load https://rpc.myetherwallet.com:8443/api.mew. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.myetherwallet.com' is therefore not allowed access. The response had HTTP status code 524.

Update

**Comment by tayvano** [comment]
Our ETC node was down for a few minutes due to high volume - can you refresh and let me know if you are still receiving this error? Thank you.

**Comment by myalcin81** [comment]
Its look like okay.
