### ISSUE TITLE
[Feature Request] - Join keybase and sign signatures with your verified key

### ISSUE THREAD

**Issue by nmurthy** [kvhnuke/etherwallet#2012]
[Hi!
Thanks so much for working on this project. I use it all the time, and it's awesome! With all of the recent DNS hacks and other concerns though, I really like to run a locally hosted version with the latest verified releases.

I really appreciate that you already put your signatures up with the release, so I'm able to easily verify that they've not been tampered with.

Have you heard of [keybase](http://keybase.io)? It's fantastic, and I've been using it for a while now to easily distribute and share public keys with other colleagues and friends. You should consider making an account and connecting it with your Github account, and signing your releases with that key. That way, the keyserver is trusted as well, and it's easy for people to get your latest verified public keys.

You should really check it out! The CLI tooling is fantastic too.

**Comment by gamalielhere** [comment]
@nmurthy Thanks for the feature request! Please direct new feature requests to: https://github.com/MyEtherWallet/MyEtherWallet
