### ISSUE TITLE
Can't send entire balance when using 'Only ETH'

### ISSUE THREAD

**Issue by octocat-mona** [kvhnuke/etherwallet#202]
I want to send the entire ETH and ETC balance of my account to another account (basically because I was warned about the replay attack on gastracker).

So when I click 'Send Entire Balance' and switch radio box to 'Only ETH' and send the transaction it shows an error:

> 'Insufficient funds for gas \* price + value'

When I substract the 0.000441 fee from my total balance which is mentioned below:

> A standard transaction using 21000 gas will cost 0.000441 ETH.

I still get the same error.
So how can I send my entire ETH (and ETC) balance? Is there a different transaction cost involved?

**Comment by tayvano** [comment]
The gas for the "Send Only" functions is greater than the default 21000. It ranges somewhere between 30k and ???. I've seen 32k, 56k, etc. 

We use 300k as a safety to prevent it from ever failing as all excess gas gets returned to you. So, at this time, there is no easy way to "send all" via the Reply contract. 😞

We hope to fix this moving forward but for now, the estimate gas function isn't reliable and we would rather overestimate and have no errors than have people emailing every 2 seconds saying their transaction failed. 

So the minimum you need to leave for gas to use the "Only" function is 300000\* 0.000000021  = 0.0063 ETH/ETC

This is also what is being discussed in #64 and #63 and we will also be updating the gas price to 23300 (as discussed in #191)

**Comment by tayvano** [comment]
Sorry - going to update to 60k gas in like 10 minutes

so it'll be .00126 ETH/ETC for gas

**Comment by tayvano** [comment]
Just changed to 60k and updated messaging under TX to read:

We use a gas price of 0.000000021 ETH to ensure your TX gets mined quickly. Multiply 0.000000021 by the gas of your TX and you get the cost of the TX in ether. We do not take a transaction fee.

Standard TX: 21000 gas (0.000441 ether) 
TX to Wallet Contract: 23300 gas (0.0004893 ether) 
Only ETH / ETC TX: 60000 gas (0.00126 ether)

**Comment by octocat-mona** [comment]
Thanks for the update, managed to move my ETH now.
Still having trouble with ETC, hope that you can fix the gas estimation soon :)
