### ISSUE TITLE
crash on load in Firefox when U2F is enabled

### ISSUE THREAD

**Issue by msuess** [kvhnuke/etherwallet#2038]
* **I'm submitting a ...**
    - [ ] Feature request
    - [x] Bug report

* **Bug Report**
    - What is the current behavior?
Blank page on load
    - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
      1. open firefox
      1. go to `about:config`
      1. set `security.webauth.u2f` to `true`
      1. open MEW
    - What is the expected behavior?
MEW starts up
    - Please tell us about your environment:
        - Operating system
OSX High Sierra
        - Firefox Developer Edition 62.0b19 (64-Bit)
    - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
TypeError: setting getter-only property "u2f"[Weitere Informationen] etherwallet-master.js:15614:3
	[82]< https://www.myetherwallet.com/js/etherwallet-master.js:15614:3
	s https://www.myetherwallet.com/js/etherwallet-master.js:1:246
	e https://www.myetherwallet.com/js/etherwallet-master.js:1:425
	<anonym> https://www.myetherwallet.com/js/etherwallet-master.js:1:11

```

**Comment by msuess** [comment]
Moved from MyEtherWallet/MyEtherWallet#59

**Comment by kvhnuke** [comment]
this should be fixed

**Comment by msuess** [comment]
Confirmed, the issue is gone for me. Thank you for all the hard work <3
