### ISSUE TITLE
Ability to change nonce

### ISSUE THREAD

**Issue by gkucmierz** [kvhnuke/etherwallet#2058]
Sometimes when I want to send transaction to network. I have unconfirmed last transaction and I don`t want to overwite it by next transaction, but I want to increase nonce and push it to the network than.
I think It can be added in advanced section.

**Comment by ghost** [comment]
+1 for this issue we need this feature asap @kvhnuke @gamalielhere

**Comment by gamalielhere** [comment]
@gkucmierz thanks for the request! Please direct new features here: https://github.com/MyEtherWallet/MyEtherWallet

Closing this issue.
