### ISSUE TITLE
Cannot send from MM

### ISSUE THREAD

**Issue by mr2money** [kvhnuke/etherwallet#2066]
I have a number of pending transactions that are not showing up when I check the status on the blockchain.  I am not able to send ether any where at this point. They all hang and nothing happens and I just accrue more NONCE at this point. I have tried to clear the pending with out any success. What can I do to reset my meta mask so it works

**Comment by gamalielhere** [comment]
You might want to open an issue here instead: https://github.com/MetaMask/metamask-extension/issues
