### ISSUE TITLE
Verify Error Need Help

### ISSUE THREAD

**Issue by rupanand** [kvhnuke/etherwallet#2070]
I need Help since im new ..

Sorry! The Compiled Contract ByteCode for 'BKKCoin' does NOT match the Contract Creation Code for [0x7b09#######################].

Contract name(s) found: 'BKKCoin' , 'StandardToken' , 'Token' 
Unable to Verify Contract source code.

What  does it mean?

**Comment by kvhnuke** [comment]
I believe this is related to etherscan
