### ISSUE TITLE
(error_21) Not a valid ERC-20 token

### ISSUE THREAD

**Issue by DreamXofficial** [kvhnuke/etherwallet#2085]
(error_21) Not a valid ERC-20 token
created an ERC20 contract, verified by EtherScan, and I can't add it to MEW.

Address: 0x92151A093B6984e93150dd43aff9d8d251f00845
Symbol: DRX
Decimals: 18

**Comment by gamalielhere** [comment]
@DreamXofficial It doesn't seem to be confirmed by etherscan:  
https://etherscan.io/address/0x92151A093B6984e93150dd43aff9d8d251f00845  
https://ropsten.etherscan.io/address/0x92151A093B6984e93150dd43aff9d8d251f00845  
https://kovan.etherscan.io/address/0x92151A093B6984e93150dd43aff9d8d251f00845  
https://rinkeby.etherscan.io/address/0x92151A093B6984e93150dd43aff9d8d251f00845 .

**Comment by gamalielhere** [comment]
Closing this issue.

**Comment by DreamXofficial** [comment]
Thanks my problem is solved
