### ISSUE TITLE
Address not checksummed link is 404

### ISSUE THREAD

**Issue by kitblake** [kvhnuke/etherwallet#2125]
When inputting a non-checksummed address in MEW, a js error message appears at the bottom of the page:
```(error_36) Input address is not checksummed. What does that mean?```
"What does that mean?" is a link which 404s:
https://myetherwallet.github.io/knowledge-base/addresses/not-check
The correct URL is:
https://kb.myetherwallet.com/addresses/what-does-checksummed-mean.html

**Comment by gamalielhere** [comment]
Closing since it will be included in #2126. Changes should show up when a release is made.
