### ISSUE TITLE
Adding Support to upcoming Hardware Wallet.

### ISSUE THREAD

**Issue by GYMRewards** [kvhnuke/etherwallet#2127]
We will be launching our Hardware Wallet in December, How do we go about getting you guys to support the hardware wallet? Htttps://gymledger.com 

![ad](https://user-images.githubusercontent.com/35646159/47591253-f535a980-d93c-11e8-9a8a-72e7b7893800.jpg)

**Comment by kvhnuke** [comment]
please refer to our v5 repo for all future development
https://github.com/myetherwallet/MyEtherWallet
