### ISSUE TITLE
Error in gas price value, could lead to funds loss because of extremely high gas price

### ISSUE THREAD

**Issue by un1t** [kvhnuke/etherwallet#2133]
How to reproduce:

Go to "Send Offline" page
Switch gas price unit to "gwei".
Enter from address and push "Generate Information" button
Check gas price value. I my case it should be 4 gwei, but instead it is 4000000000 gwei.
After gas price unit is switched to gwei you can refresh page, enter address and push "Generate Information" button, price again will be 4000000000 gwei.

Expected behaviour - gas price should be billion times less in gwei.

My environment - Chrome, Ubuntu 16.04

**Comment by kvhnuke** [comment]
@gamalielhere please reset the drop-down back to Wei when generate information button pressed, or detect which unit it is in and calculate the correct value

@un1t thank you for bringing this to our attention

**Comment by un1t** [comment]
> please reset the drop-down back to Wei when generate information button pressed

I don't like price in wei, there are too many zeros. Very easy to make mistakes.

> or detect which unit it is in and calculate the correct value

I think, this is right behaviour

**Comment by gamalielhere** [comment]
@un1t @kvhnuke  I sent up a fix on #2134 . Let me know what you guys think

**Comment by gamalielhere** [comment]
Closing this. Please feel free to open if it's still an issue.
