### ISSUE TITLE
Ether gone missing

### ISSUE THREAD

**Issue by uchiha345** [kvhnuke/etherwallet#2137]
Hello there I sent 2 Eth yesterday and the recipient has said it didn't arrive i checked the block explorer and it said transaction complete the recipient said that sometimes it gets stuck if it has been caught up in the blockchain could you please send it back to the origin wallet. transaction ID details below.

0x9abeb6a5884eaea1e9c6a60e5a5bdbe5084cfa28c28b0f52fc0a40ce5fd87328

Thank you.

**Comment by gamalielhere** [comment]
@uchiha345 unfortunately, there's no way to retract transactions. Closing this issue.
