### ISSUE TITLE
This token is already added as a default token. Try clicking the "Load Tokens" button to see it. :)

### ISSUE THREAD

**Issue by CryptoDreamToken** [kvhnuke/etherwallet#2140]
This token is already added as a default token. Try clicking the "Load Tokens" button to see it. :)
I created a ERC20 contract, verified by EtherScan, and i can't add it to MEW
This is our contract  : 0xe831B0597f7817dF6B72cE634F46D8B9A604e42A
Symbol : CDT
Decimals : 18

**Comment by kvhnuke** [comment]
it is because CDT symbol is already in use, when you add it to MEW name is CDT2 or something unique. It will let you add it! cheers! 

closing but feel free to reopen if necessary
