### ISSUE TITLE
WebChain is using a non-unique Chain ID

### ISSUE THREAD

**Issue by suryanshkumr** [kvhnuke/etherwallet#2145]
Webchain is using ChainID 101 which is not unique because EtherInc is using ChainID 101.

EtherInc first block was created on 2018-02-13 21:59:01 +0530 (https://explorer.einc.io/block/1)

WebChain first block was created on 2018-05-08 14:12:10 +0530 (https://explorer.webchain.network/block/1)

so as you can see EtherInc was running chainID 101 from Feb and WebChain using same chainid from May.

**Comment by hackmod** [comment]
webchain chainId `101`: from https://github.com/webchain-network/webchaind/blob/master/core/config/mainnet.json#L33

Etherinc chainId `101`: from
https://github.com/etherinc/go-etherinc/blob/master/params/config.go#L34

**Comment by hackmod** [comment]
why don't you open an issue at webchain? https://github.com/webchain-network/webchaind/issues
it seems very problematic

**Comment by suryanshkumr** [comment]
https://github.com/webchain-network/webchaind/issues/1

**Comment by suryanshkumr** [comment]
https://github.com/webchain-network/webchaind/issues/1#issuecomment-437853320
