### ISSUE TITLE
Sign release tags / commits

### ISSUE THREAD

**Issue by jonathancross** [kvhnuke/etherwallet#2147]
I see that `.sig` files are included in each release -- which is great!

However the key [0x7F059C0F7B9A12F0](https://sks-keyservers.net/pks/lookup?op=vindex&search=0x7F059C0F7B9A12F0) is not signed by anyone in the [PGP WOT Strong Set](https://pgp.cs.uu.nl/mk_path.cgi?FROM=c0c076132ffa7695&TO=0x7F059C0F7B9A12F0&PATHS=trust+paths), so there is no possible way to verify it is real.  Also, this key is not used to sign commits, so we can't even establish that this key is controlled by the people building the project.

Please consider signing commits, signing github release tags and getting others in the community to cross-sign the key `0x7F059C0F7B9A12F0`.

**Comment by kvhnuke** [comment]
Hi @jonathancross 
Thanks for inquiring about this, please refer to this issue https://github.com/kvhnuke/etherwallet/issues/1651

also, the main purpose of signing the releases are to verify the release is signed by MEW. We publicly accepted the ownership of 0x7F059C0F7B9A12F0. Which I believe is enough to sign the releases on behalf of MEW

@gamalielhere can you please add verification instructions from #1651 to the v3 readme

closing this, but feel free to reopen it if necessary

**Comment by jonathancross** [comment]
It is unfortunate that anyone trying to verify the authenticity of the key must completely trust GitHub.
This is why I was requesting these other measures:
> Please consider signing commits, signing github release tags and getting others in the community to cross-sign the key `0x7F059C0F7B9A12F0`.

At the very least, it would help to have `0x7F059C0F7B9A12F0` on [your Twitter profile](https://twitter.com/myetherwallet).
