### ISSUE TITLE
Stuck TX in REOSC network (2894)

### ISSUE THREAD

**Issue by REOSC** [kvhnuke/etherwallet#2181]
When using REOSC custom node some wallets can not send or receive coins by MEW.
Wallet made by MEW. Coins from STEX accepted by wallet.

MEW show TX is pending.
TX Hash | 0xcac35f55436413a80edf4bd2c61f383d2c4ae75042f4b733005781baab5358c5
from | 0x6B898B7433C789C2f78638FC6C6631902cBbb1D5
to | 0x6B898B7433C789C2f78638FC6C6631902cBbb1D5

Explorer shows TX not found
https://explorer.reosc.io/err404/tx/0xcac35f55436413a80edf4bd2c61f383d2c4ae75042f4b733005781baab5358c5

Custom (REOSC) Node
URL : https://remote.reosc.io
Port : 3000
Yes for Supports EIP-155
Chain ID : 2894

How to avoid pending TXs? I tried any gas prices and so on. No luck.

**Comment by REOSC** [comment]
Additional info:
same TX by geth 0x0ce0e5182b1ccd69c6f52bf5fe10493e08300a3a30bdefe8cc215691e01881f2
was successfully mined and is on the blockchain

we use MEW more than month with REOSC network. And only 2 addresses were stuck.

**Comment by ghost** [comment]
@REOSC That is a problem with your node, not with MEW
