### ISSUE TITLE
Desktop Download Links on Homepage?

### ISSUE THREAD

**Issue by zach-is-my-name** [kvhnuke/etherwallet#2204]
Earlier I downloaded MyEtherWallet to the Linux desktop.  I cannot find a reference to the desktop client on the site.  Is that deliberate?

**Comment by gamalielhere** [comment]
@zach-is-my-name we actually don't have a desktop client. You can download MEW through here: https://github.com/kvhnuke/etherwallet/releases/tag/v3.29.0.

When the download is done, you can extract the files, double click on `index.html` and that should open MEW on your browser. Let me know if that helps!

**Comment by zach-is-my-name** [comment]
Thanks.  I got crossed up.
