### ISSUE TITLE
Still NOT working when using a HTTP proxy

### ISSUE THREAD

**Issue by federicoon** [kvhnuke/etherwallet#222]
Bug #180 should be reopened, as the issue is not solved, moreover when using a proxy both online and offline transactions will fail.
All command buttons ("Generate information", "Send Entire Balance", "Generate Transactions", etc.) do NOT work, neither with Firefox nor with Chrome, so the procedure cannot be completed.

**Comment by tayvano** [comment]
I need you to provide me with more details. There were numerous people that confirmed it was now  working after we pushed the update.

**Comment by federicoon** [comment]
This is what I get after entering the password:

![schermata da 2016-09-19 13-24-01](https://cloud.githubusercontent.com/assets/4541039/18631199/cd5c02e8-7e70-11e6-88ac-0e2ebd343c31.jpg)
Notice the account balance is not shown, so clicking the link "Send Entire Balance" has no effect.
If I manually set an amount to send instead, when I click "Generate Transactions" nothing happens.
What more details would be helpful?

**Comment by tayvano** [comment]
Please right click, click "Inspect" or "Inspect Element" and click on the "Console" tab and either copy/paste the red text in there or take a screenshot. I just got another report of this with details and so we're looking into the cause further.

**Comment by tayvano** [comment]
Internal note:

**Change the ETH / ETC / BTC / USD to say "loading" like tokens do instead of just being blank**

**Comment by federicoon** [comment]
What element shall I inspect? The "Generate Transaction" button?

EDIT: I tried, but when clicking the button, **nothing** is displayed on the console

**Comment by tayvano** [comment]
It doesn't matter --- the console will show any errors on the page. Do it once you have unlocked your wallet and seeing no loaded balances for best results.

**Comment by federicoon** [comment]
The only console output is on the CSS tab (JS and others are empty):

Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.etherwallet-master.min.css:2:155
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.etherwallet-master.min.css:2:1425
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.etherwallet-master.min.css:2:1600
Unknown property ‘orphans’.  Declaration dropped.etherwallet-master.min.css:3:577
Unknown property ‘widows’.  Declaration dropped.etherwallet-master.min.css:3:586
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.etherwallet-master.min.css:3:1419
Error in parsing value for ‘margin-top’.  Declaration dropped.etherwallet-master.min.css:3:21564
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.etherwallet-master.min.css:3:21811
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.etherwallet-master.min.css:3:22413
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.etherwallet-master.min.css:3:22464
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.etherwallet-master.min.css:3:22873
Error in parsing value for ‘margin-top’.  Declaration dropped.etherwallet-master.min.css:3:24032
Unknown property ‘touch-action’.  Declaration dropped.etherwallet-master.min.css:3:26514
Unknown property ‘user-select’.  Declaration dropped.etherwallet-master.min.css:3:26833
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.etherwallet-master.min.css:3:26965
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:27346
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:37132
Expected color but found ‘solid\9 ’.  Expected end of value but found ‘solid\9 ’.  Error in parsing value for ‘border-top’.  Declaration dropped.etherwallet-master.min.css:3:37323
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:38595
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:48147
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:48256
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:49095
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.etherwallet-master.min.css:3:49149
Unknown property ‘user-select’.  Declaration dropped.etherwallet-master.min.css:3:58128
Error in parsing value for ‘display’.  Declaration dropped.etherwallet-master.min.css:3:59779

**Comment by kvhnuke** [comment]
can you send us a screenshot of the network tab, open the site then open developer tools click on network tab and refresh the page, this will show us all the network calls it makes.  Thank you for helping us figure out the issue

**Comment by tayvano** [comment]
Here's one that someone sent me earlier. Not sure if same issue.

etherwallet-master.js:27480 POST https://rpc.myetherwallet.com/api.mew 400 ()

**Comment by federicoon** [comment]
Here is the screenshot, with the above mentioned POST highlighted:
![Uploading Schermata da 2016-10-01 17-44-14.jpg…]()

WTF?? can't upload the screenshot:
"Something went really wrong, and we can’t process that file. "

**Comment by tayvano** [comment]
Try uploading/linking to imgur or https://ipfs.pics/?

**Comment by federicoon** [comment]
ok, let's give it a try:
[screenshot](https://ipfs.pics/Qmchv2UWWAH8Ra47HyvendDyqxqQu9cBv6MRToLKncA4fc)

**Comment by tayvano** [comment]
Another similar report:

> Unfortunately they're not loading again and it cost me from taking advantage of an accidental sell order at a really low price. Here's what my wallet looks like when I go to "View Tokens": http://imgur.com/a/FLJvj
> Here's the error I see when I go to "Inspect Element" on that page and click console: http://imgur.com/a/V3gS3

Error for this case is: ERR_NAME_NOT_RESOLVED for https:rpc.myetherwallet.com/api.mew
