### ISSUE TITLE
MyEtherWallet new template ?

### ISSUE THREAD

**Issue by prodnet** [kvhnuke/etherwallet#2260]
Hello,
Where can I find the new version with the new template, so is it in the official site?

![image](https://user-images.githubusercontent.com/43401428/56034308-4a1c7f00-5d27-11e9-903a-67f81e38706d.png)

**Comment by gamalielhere** [comment]
@prodnet you can visit `https://www.myetherwallet.com/` for the the most recent version

**Comment by prodnet** [comment]
I would like to run the new template directly on my PC, without using your online version, how can I do it?
