### ISSUE TITLE
FAQ/Security no longer up-to-date

### ISSUE THREAD

**Issue by SjonHortensius** [kvhnuke/etherwallet#227]
The security section of your FAQ seems to be out of date:
- It explains how to verify the site is running on GH; but it runs on Cloudflare instead
- It explains how to verify there is no network traffic; but it it continuously polls rpc.myetherwallet.com

**Comment by tayvano** [comment]
> It explains how to verify there is no network traffic; but it it continuously polls rpc.myetherwallet.com

We need to partially solve this by removing latest block thing from offline / generate wallet / help / deploy pages. 

aka - we should only attempt to get the latest block on send trans & send tokens & withdraw & claim. Or maybe make a dedicated page for that or something?

**Comment by SjonHortensius** [comment]
You could include https://www.gavick.com/blog/detect-offline-browser to detect the state and disable the checks (for the offline implementation); but it seems to me in this case you could also ignore any errors from the request itself and simply update the FAQ.

**Comment by tayvano** [comment]
Slowly got around to updating all this. Let me know if I missed some.
