### ISSUE TITLE
Master Security Update List

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#229]
1. No more Cloudflare, get an EV Cert (https://github.com/kvhnuke/etherwallet/issues/199) 
2. Easier way to have "average" user run locally - this may mean a lightweight version with everything in a single page too.
3. Sign that shit ;) (https://github.com/kvhnuke/etherwallet/issues/21)
4. ~~Bring back the http://kvhnuke.github.io/etherwallet/ link too (https://github.com/kvhnuke/etherwallet/issues/66)~~ Apparently we can't do this bc Github doesn't let you if you have a custom domain. 😞
5. ~~Nail down some small outstanding items on Chrome Extension and promote that too. (ie: Remove permissions from Chrome Extension)~~
6. ~~View Wallet Info will primarily for address rather than a private key for viewing balance and info. User can choose to use private key if they want to re-print paper wallet and stuff. (Way too many people use us instead of etherscan to check their balance).~~
8. Maybe some nifty oldschool "generate an icon" or "set your greeting" or something that we could throw in localstorage that a consistent user would miss if they were on a phishing site.
9. ~~FAQ/Security no longer up-to-date  https://github.com/kvhnuke/etherwallet/issues/227~~

**Comment by fortran77** [comment]
Could item 4 (#66) be implemented on a forked repository?

**Comment by mrdomino** [comment]
I notice that the Chrome extension requests permission to read and modify data on all websites. Is there any way to restrict this? (Posting here rather than a new issue since it seems like consolidation into one thread is desirable.)

**Comment by tayvano** [comment]
@mrdomino Thank you for forcing me to do this. It's been on the list for a while. 

I just removed a bunch of stuff and will test to make sure it works. We used a standard framework / starter kit for the chrome extension so I just spent way too much time trying to figure out what can be removed safely. I know we aren't using any data for any page at any point so there is no need for it, I just have to make sure I don't screw up the Chrome Extension / manifest file. 

If you have any insights into Chrome Extension stuff, maybe you could take a look?

Current Manifest: https://github.com/kvhnuke/etherwallet/blob/mercury/chrome-extension/manifest.json

Previous Manifest: https://github.com/kvhnuke/etherwallet/blob/96c25f691593547ac326f4bb6c06e2bd8f72bbc0/chrome-extension/manifest.json

**Comment by tayvano** [comment]
@fortran77 I just emailed github pages support to see if they could offer any insights into our unique situation. We are also moving off of Cloudflare in order to get the EV Certificate so maybe that will make a difference? Or maybe we set up another repo as you said. Just gotta figure out an easy way to commit to both.

**Comment by mrdomino** [comment]
@tayvano That change looks reasonable to me. It's been a long time since I did anything with Chrome extensions, but if it builds and works then that's probably good.

**Comment by tayvano** [comment]
Unfinished items all have their own issues now.

Main things that changed in response to this issue:

- No more chrome extension permissions
- View wallet now has option for viewing info with just your address
- UI/Copy updates with security in mind

**Comment by spundot** [comment]
@tayvano wrote:
> No more chrome extension permissions

Current Chrome extension (v3.10.4.4) in Chrome Web Store requests clipboard access, which looks scary. Can this be removed?
<img width="261" alt="2018-02-01 05_02_29-" src="https://user-images.githubusercontent.com/3210002/35644882-8f3c1256-070d-11e8-979b-3d4dddb47353.png">
