### ISSUE TITLE
Estimate gas isn't estimating enough gas for Send Only ETC?

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#236]
Example TX: https://gastracker.io/tx/0x3387cebe2f0686ed83168f92fed638d376219704c16b5aa003a72c721dcceced

I can get it to go through with 60000. 

WTF.

**Comment by kvhnuke** [comment]
i added the new estimate gas to both gh-pages and mercury, it should fix the issue.

**Comment by tayvano** [comment]
Verified only etc and only eth are going thru successfully with estimate gas to brand new accounts and existing accounts. If anyone is still having TX's fail for only etc or only eth, please comment here.
