### ISSUE TITLE
Allows calling of contract method given ABI

### ISSUE THREAD

**Issue by uzyn** [kvhnuke/etherwallet#240]
There is a Data field at Send Ether tab, but no simple means to obtain the data.

Just thought it would be nice to have the ability to interact with contracts right from MyEtherWallet given contract ABI.

**Comment by tayvano** [comment]
We agree 100%.

We actually have an old branch with a generic contract frontend - it just hasn't been set up yet. This would allow you to interact with a contract, similar to Mist. You provide address / ABI and you can see all the read/write functions and then interact with that contract with any account of yours.

It's a lot of work and testing and we will get there eventually. 😄

**Comment by tayvano** [comment]
live as of 3.4.7
