### ISSUE TITLE
Does not work on Windows XP 32-bit

### ISSUE THREAD

**Issue by chiwalfrm** [kvhnuke/etherwallet#242]
Tested with latest version of Chrome (49.0.2623.112m) and Firefox (49.0.1).
Tested with both the downloaded version to local PC and the website version.
First step: "Generate Wallet" function works fine.
Second step: Attempted "Send Ether" function but nothing happens when clicking "Generate Transaction".  No error message, but button does nothing.

**Comment by tayvano** [comment]
This typically happens when you are offline or behind a firewall where the Send Ether tab cannot communicate with the node in order to grab information like gas price and nonce of an account. 

Are you seeing your ETH / ETC balances on the Send Ether tab?
