### ISSUE TITLE
Add ICONOMI/ICN asset

### ISSUE THREAD

**Issue by danimesq** [kvhnuke/etherwallet#249]
ICONOMI was one of the biggest ICOs in this year, and is one of the more succesfull Ethereum assets. Why not add it?

**Comment by Paxxil** [comment]
It will be released next week, so it would be great if you added support for ICN tokens to your wallet.

**Comment by danimesq** [comment]
ICONOMI is so great like Augur REP's. The genesis block is to be launch in october 25th.

**Comment by tayvano** [comment]
Ugh. I don't know how many times I have to say this. 

WE CANNOT ADD ANY TOKEN WITHOUT THE ADDRESS AND DECIMALS. 

If you provide us with those two pieces of information we can add it.

**Comment by jani8x** [comment]
@tayvano here people are just making sure to notice ICONOMI (but yeah, I know how annoying that can be to hear repeatedly same requests).
We'll provide address and decimals (18 decimals there will be) within few days (once contract is deployed and values assigned to designated addresses).

**Comment by tayvano** [comment]
I understand that but I'm getting 20+ emails / tweets / reddit message a day right now asking the same question about ICO. We typically receive around 30-40 messages a day with legit support requests. 

Raving about how great a token is in my support inbox is not going to prompt us to add the token any faster. We do not add tokens based on emails or our personal feelings on a token. We add them when someone requests them to be added and _includes the address and decimals needed so we can easily add them._ 

I see some of my replies are making in the bitcointalk.org thread. Hopefully this one can too so we can focus on helping people who are having issues with the site and writing code.
