### ISSUE TITLE
PW to complex?

### ISSUE THREAD

**Issue by martinkrung** [kvhnuke/etherwallet#25]
Hi, I have a password like this:

@Z-7iXe1_>;Erf0-L9+QvrZGQ5tlU!Q)}C=QUH8{{U9nY}Yh

I cannot open my json file with your tool. But with 

https://www.kraken.com/ether

this kind of pw works on the same wallet.

any idea?

thanks

**Comment by tayvano** [comment]
@martinkrung We haven't had any issues with this. I just created a new wallet using the example password you entered and it worked fine. I can't see any reason why it wouldn't work. Is it your presale Json?
