### ISSUE TITLE
Address checksum encoding

### ISSUE THREAD

**Issue by romanoza** [kvhnuke/etherwallet#26]
The address generated by the page is not checksum encoded (https://github.com/ethereum/EIPs/issues/55)

**Comment by JonasOlson** [comment]
Specifically, the checksum is missing on the print page. I'm guessing that `toChecksumAddress` needs to be used in this line: https://github.com/kvhnuke/etherwallet/blob/15f9009bcce8b499d6fc7f35a89320e435af4770/js/etherwallet-master.min.js#L1082

**Comment by tayvano** [comment]
We've been slowly adding checksums to all the different places on this site. Will update print page ASAP.
