### ISSUE TITLE
Trezor support

### ISSUE THREAD

**Issue by acvanzant** [kvhnuke/etherwallet#262]
Now that Trezor supports Ethereum in its actual release version could we add support for it to this wallet? Would be happy to test with my Trezor.

**Comment by tayvano** [comment]
The Ledger team added their own support. (see https://github.com/kvhnuke/etherwallet/pull/248) I'm not sure if Trezor has this functionality, let alone where to even start to implement it. 

Do other wallets have Trezor support?

**Comment by acvanzant** [comment]
I don't believe any wallets have Trezor support. They're working to get it into Mist but this is the most convenient tool out there, currently.

hey, @trezor

**Comment by karelbilek** [comment]
Hello there

I am from SatoshiLabs, working on trezor support right now. Soon-ish.

**Comment by karelbilek** [comment]
https://github.com/kvhnuke/etherwallet/pull/330

**Comment by tayvano** [comment]
Live...finally
