### ISSUE TITLE
Sometimes Account Balance, Equivalent Values show permanent loading

### ISSUE THREAD

**Issue by vikulin** [kvhnuke/etherwallet#276]
Sometimes Account Balance, Equivalent Values show permanent loading:

![Loading](http://i.piccy.info/i9/aa0876137b165e0831d5c3163e8a9a27/1478425417/12731/1086894/Selection_042.jpg)

**Comment by vikulin** [comment]
Not reproduced on v 3.0. Reproduces on v 3.2.

**Comment by ithinuel** [comment]
Reproduced on v3.2 and got

```
XMLHttpRequest cannot load https://rpc.myetherwallet.com/api.mew. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.myetherwallet.com' is therefore not allowed access. The response had HTTP status code 524.
```

in chrome's console.

**Comment by tayvano** [comment]
fixed in new nodes that will be primary nodes in ~2wks.
