### ISSUE TITLE
Paste / type your private key on view wallet and send transaction not working

### ISSUE THREAD

**Issue by thegarn** [kvhnuke/etherwallet#28]
button missing to submit

**Comment by tayvano** [comment]
@thegarn What browser are you using?

**Comment by thegarn** [comment]
tried it on firefox and chrome. The button just isnt there but was a 
couple of days ago.
regards
Anthony

**Comment by thegarn** [comment]
also just tried on IE - same result: no decrypt button

**Comment by tayvano** [comment]
If the decrypt button isn't appearing then you aren't entering a private key. Be certain that whatever you are pasting matches one of these lengths:

encrypted: `U2FsdGVkX18Wi8eFCEOYOth9feZiVsUsjUZvBe353zlgS0vrv71khVdW8mBy1XPnj7E6q7FMaYlDB4WLs4YJIAlrrWDydgMWWySx//4A4wV7Ucy3Aq1PkPkOwaWpIB/9eda5`

unencrypted: `c66b5346d5cf8c68c382a1abd5f71adc7b6db2abe6d86b05b171c724997f5bdc`

See if using one of the above shows the decrypt button as well.

**Comment by thegarn** [comment]
Sorry schoolboy error! was using my public key. Panic over!
Thanks for your help.

regards
Anthony
