### ISSUE TITLE
Invalid status 6a80 when trying to generate a transaction

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#280]

**Comment by tayvano** [comment]
### Solution(s)

When you are connected via a Ledger you will sometimes encounter this error when attempting to generate a transaction. It may be because....
- You are not using a secure (SSL) connection
- You are not using Chrome/Opera
- You are attempting to send a transaction that has data without first turning "contract data" ON in your ledger settings (it's right above 'browser support')
- ??? 

_please comment and reopen if you have checked all the above and are still getting this error_

**Comment by kevinday** [comment]
I am still seeing this error occasionally despite satisfying all the conditions listed above.

**Comment by tayvano** [comment]
You are absolutely positive your contract data is switched to the ON position?

**Comment by kevinday** [comment]
Hmm, I can't reproduce this anymore. Unplugged/plugged back in the Ledger and everything seems to be working fine now. Ignore this for now - I will post back if I encounter this again. Thanks!

**Comment by stewface** [comment]
Looks like I am running into the same error... trying to transfer Vslice tokens to Liqui

**Comment by stewface** [comment]
Found it it was a setting about the contract data set to off...  as the post two up.. 

*face palm*

**Comment by jamesyoung** [comment]
Apologies in advance for not being relevant to the ticket :

I have 'contract data' turned on, created an ethereum txn object that I am trying to hash using rlp.encode similar to [MEW](https://github.com/kvhnuke/etherwallet/blob/b5e1b75beb7c393e06e5ffd7e540c6bccd9eface/app/scripts/uiFuncs.js#L62). 

This [code](https://gist.github.com/jamesyoung/5f7b1435093a22e9ba791d247bad1ce1) returns `Invalid status 6a80`. Any insight would be greatly appreciated. Thanks!

**Comment by osascruz** [comment]
I experience the same problem with PPT tokens.
I am using ledger nano S, sending PPT token, it says "invalid status 6a80" when I click generate transaction.

**Comment by mswezey23** [comment]
Thanks! You're awesome - quick google search and I resolved my error.
