### ISSUE TITLE
Add Ropsten node. Remove ETC node. Add dropdown to switch between the two globally

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#299]

**Comment by hyugit** [comment]
hey @tayvano,

Would you mind explaining a bit more what "remove ETC node" means? Does it mean you are stopping supporting ETC? Or are you just removing ETC node to lower operation cost?

Thanks,

**Comment by tayvano** [comment]
We will be removing ALL ETC functionality. You can use an older repo (i will make a post with which one) to have ETC functionality but since there will be no ETC node for it to talk to, you will need to point it to your own node in order for it to work.

Again, I'll be making a post explaining how to do all of this.

This is to eliminate both server costs (we will be starting a swarm node and ropsten node in the coming weeks as well) as well as the time spent supporting ETC and the messy code that supporting both requires.

**Comment by hyugit** [comment]
hi @tayvano I'm sorry to hear that. Would you be willing to maintain an 'etc' branch for 'etc' functionalities? I'm sure people will want to send you PRs to help you maintain it.

**Comment by hyugit** [comment]
hey taylor,

if I understand it correctly, the way you are supporting both chains is to have a `isClassic` argument passed to all the functions that have blockchain operations. do you think we could create some kind of global constant that determines the underlying chain, and rely solely on that constant? We can still support both chains in the codebase with minimum code, or maybe on a separate branch if you want.

I would be happy to help you maintain it.

let me know what you think.

thanks,

**Comment by hyugit** [comment]
hey guys, I see that you are busy working right now. I just want you to know that the latest etc geth 3.2.3 supports EIP 155 now (here: https://github.com/ethereumproject/go-ethereum/releases). thank you again for this amazing project.

**Comment by tayvano** [comment]
ETC is still enabled. We will be removing our ETC node so users will have to add their own in teh coming days. Launching this tonight.
