### ISSUE TITLE
[Feature request] Allow sending to more than one address/Allow specifying "change" address

### ISSUE THREAD

**Issue by odotan** [kvhnuke/etherwallet#31]
for example, I have 100 ether at address A and I would like to send 10 to address B and 20 to address C.

So I need to be able to add addresses to send to, and everything remaining in the address (70 minus gas), if not explicitly specified, should return to address A.

If the change address is specified, then everything remaining should be moved to the change address.

**Comment by tayvano** [comment]
This is a holdover from Bitcoin and does not apply to Ethereum transactions, sorry. If you want to send to two addresses, you do it via two separate transactions.

**Comment by odotan** [comment]
Would still be nice to have it as an option in the UI. The UI should allow you to send to multiple addresses, and allow you to select a "change address", like in bitcoin, while in the background it should actually send multiple transactions. In the above example, three transactions should take place. One sending 10 from A to B, another sending 20 from A to C, and a third transaction sending the remaining 70 minus gas to the "change address" which the user selects. This would allow for higher security, since sending any transaction potentially exposes the private key, and moving the change to a new "cold" address would keep the change in a secure address.
