### ISSUE TITLE
Safari does not download the keystore file

### ISSUE THREAD

**Issue by khovratovich** [kvhnuke/etherwallet#311]
When generating a new wallet in Safari, click the "Download" button. Then Safari shows the file contents instead of saving it with a proper filename.

It then becomes non-trivial to assign it a Mist-readable name.

**Comment by tayvano** [comment]
UGH! Fix that worked in 8.x doesnt working in 9.x. 

from https://github.com/eligrey/FileSaver.js

> Safari 6.1+

> Blobs may be opened instead of saved sometimes—**you may have to direct your Safari users to manually press ⌘+S** to save the file after it is opened. Using the application/octet-stream MIME type to force downloads can cause issues in Safari.

FUCK YOU SAFARI. YOU ARE THE NEW IE.

@kvhnuke I need a isSafari, isChrome, isFirefox, isIE specifically to deal with bullshit like this

Safari has been attempting (and utterly failing) at getting this feature properly implemented for **4+ years now**. 😣  https://bugs.webkit.org/attachment.cgi?id=275269&action=review

**Comment by khovratovich** [comment]
The problem is that if you save manually it does not seem to provide a proper Geth-readable filename. But MyEtherWallet could provide a proper filename on the webpage that generates the wallet.

**Comment by tayvano** [comment]
https://developers.google.com/web/updates/2012/06/Don-t-Build-Blobs-Construct-Them

https://github.com/eligrey/FileSaver.js/#supported-browsers

-->   **https://stuk.github.io/jszip/**

**Comment by gamalielhere** [comment]
@khovratovich Hey, can you check the most recent release if it fixes this?

**Comment by khovratovich** [comment]
Seems it works! Thanks!!

**Comment by gamalielhere** [comment]
Cool. Closing this issue now. @khovratovich
