### ISSUE TITLE
offer an actively managed etc node with long term support

### ISSUE THREAD

**Issue by hyugit** [kvhnuke/etherwallet#314]
hi myetherwallet team,

thank you very much for keeping etc in your amazing project.

I just got more great news: on behalf of etc community, @etherninja [here](https://www.github.com/etherninja) is offering an actively managed etc node with long term support. if you are looking to use a **dedicated** etc node with active support for MEW, feel free to switch to it. it's a parity node in geth mode: [mewapi.epool.io:7001](https://mewapi.epool.io:7001)

sample request:
```sh
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' mewapi.epool.io:7001
```
response:
```sh
{"jsonrpc":"2.0","result":"0x18d993","id":83}
```

let me know what you guys think.

thanks,

huang

**Comment by kvhnuke** [comment]
it'll be awesome, now we just need that url to be https

**Comment by tayvano** [comment]
Thank you!

I literally was in the process of writing a post about our new node switching functionality:
https://www.reddit.com/r/ethereum/comments/5lqx90/announcing_myetherwallet_v34_the_node_switcher/

We can all test it out a bit and if everything looks good, we can replace the current *ETC (MyEtherWallet)* with this one when the time comes. 

for ref, here is where the nodes are set up: https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/nodes.js

**Comment by ghost** [comment]
@tayvano @kvhnuke Hey guys :-) I just set up the parity instance in geth mode. Do I need to serve it though nginx for ssl cert? I have a cloudflare cert but it would need to proxy through there to use it. Sorry haven't looked at the code for a long while.

**Comment by ghost** [comment]
Okay, served through cloudflare ssl. disregard 7001 port. standard 443 port used. 

```
secure@miner2:/etc$ curl  -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' https://mewapi.epool.io
{"jsonrpc":"2.0","result":"0x2cd371","id":83}
```

**Comment by hyugit** [comment]
hi everyone, I just created a provisional PR for the node -- https://github.com/kvhnuke/etherwallet/pull/318

the only files that matters are **nodes.js** and **nodeHelpers/mewEtc.js**, and I used `customNode` class to implement the etc node

let me know what you think.

**Comment by hyugit** [comment]
thank you everyone for doing this. I guess this ticket can be closed now.
