### ISSUE TITLE
Encryption key recovery plan

### ISSUE THREAD

**Issue by raineorshine** [kvhnuke/etherwallet#32]
Is there any documentation about how to encrypt/decrypt the private key on our own? I'm considering the case where I have stored the encrypted private key (and have memorized the password) and myetherwallet disappears for some reason. How would I recover my private key in that case?

Great wallet, btw, love the simplicity and ease-of-use. :+1:

**Comment by tayvano** [comment]
The easiest way is to download the repo and save it along with your backups. You can run it locally and do everything you would normally do on myetherwallet.com.

Honestly, it costs us almost nothing to keep it online though. It's hosted by Github. Even if we stop don't renew the myetherwallet.com domain, it'll still be available here on Github and on the default github URL http://kvhnuke.github.io/etherwallet/

**Comment by tayvano** [comment]
There is also this library that may interest you. https://github.com/axic/ethereumjs-wallet

**Comment by raineorshine** [comment]
Okay, I will try to run it locally. If that works that should be
sufficient. In some sense it would be nice to isolate that encryption
component or have it documented somewhere so I know what exactly is
happening to my private key. I may submit a pull request if I find the
corresponding code and have time to write up some documentation. Thanks.

**Comment by tayvano** [comment]
I wanted to give an update on this issue before we close.

Starting this weekend, we will be moving to the same type of encryption geth / Mist uses. This means that if MyEtherWallet goes down for any reason (and even if it doesn't) you can easily move your encrypted key to Mist / geth without needing to do anything further.

**Comment by raineorshine** [comment]
@tayvano Does this change affect previously encrypted keys?

**Comment by tayvano** [comment]
If you have an encrypted key from V1 you will be able to use it to create a new geth / mist version of the encrypted key on V2. 

You will always be able to access your original encrypted V1 keys via MyEtherWallet no matter what.

**Comment by raineorshine** [comment]
Okay, thanks!
