### ISSUE TITLE
error on clicking "view wallet info">"connect to ledger nano s"

### ISSUE THREAD

**Issue by cosmicscr** [kvhnuke/etherwallet#322]
I'm running the MEW site locally with `file:///path/to/dist/index.html`

Not running ssl or https but not sure yet why that necessary or why that would correlate with jquery not being defined.

Thanks for any help

```
Error: $ is not defined
[61]</u2f.isIosChrome_@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:5853:3
[61]</u2f.getMessagePort@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:5830:14
[61]</u2f.getPortSingleton_@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:6189:7
[61]</u2f.getApiVersion@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:6318:3
[61]</u2f.sign@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:6235:5
[60]</</Ledger3.prototype.exchange@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:5626:2
[59]</</LedgerEth.prototype.getAddress@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:5476:2
decryptWalletCtrl/$scope.scanLedger@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:1023:5
anonymous/fn@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js line 32232 > Function:2:147
callback@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:43654:17
$eval@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:34996:18
$apply@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:35096:22
ngEventHandler/<@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:43659:17
defaultHandlerWrapper@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:20967:5
eventHandler@file:///Users/myusername/projects/etherwallet/dist/js/etherwallet-master.js:20955:11
```

**Comment by tayvano** [comment]
Hmmm... I'm not sure why that would be happening either. However, I do know that **you must be using SSL in order to connect to the Ledger. If you aren't connected via SSL, the Ledger will not connect to the interface.**

If you are running locally you can use a self-signed certificate. There are a few tutorials on how to do this online if you google `local development ssl YOUR_OS_HERE`

I personally use AAMPS for Wordpress development on my mac which gives you the ability to turn on SSL locally and is a GUI: http://www.ampps.com/

If you get SSL up and running and are still encountering this issue, let me know. I'll test when I'm finished with work tonight to ensure it's working with SSL.

**Comment by cosmicscr** [comment]
Thanks!  Okay I'll let you know if the problem is there once I test it with ssl.  Feel free to close the issue as desired.

**Comment by cosmicscr** [comment]
Okay, so I got the dist running over SSL using what I thought was a really great tutorial:  https://certsimple.com/blog/localhost-ssl-fix.

Now the issue is that I can't set up a custom node.

The message is `Enter valid url, if you are on https your url must be https`.  
![screen shot 2017-01-15 at 1 05 35 pm](https://cloud.githubusercontent.com/assets/6118944/21965737/5b626b40-db23-11e6-963e-5581912c20a4.png)

So the whole thing currently doesn't make sense to me.

1.  In order to connect to the ledger nano s, you have to be running the tool over ssl
2.  If you are running over ssl, then connecting to a custom (local) node requires you provide an https link
3.  geth does not appear to support ssl or https in any way and always starts up with http.  https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

I must be missing something.

Thanks for any ideas

**Comment by tayvano** [comment]
Okay so now there are 2 more steps (SORRY!)

- You need to allow mixed-content in Chrome. I recommend you do this when you are running this MEW/Ledger set up, and then disable it when you aren't. If you frequently use Chrome & your Ledger, I recommend installing Chromium. Then you can set mixed-content ON for Chromium and use Chrome for your day-to-day browsing. That way you don't have to go and switch all the time.  http://stackoverflow.com/questions/18321032/how-to-get-chrome-to-allow-mixed-content (Please let me know which one works so I can turn this into a guide)

- @kvhnuke is going to push an update in about 30 minutes that removes the validation for http: in that URL field. It will still show the warning and be red but it'll enable you to click the "Save and Use Custom Node" button anyways. With that update - it should work!

**Comment by kvhnuke** [comment]
hi its ready, please download the latest version from https://github.com/kvhnuke/etherwallet/archive/mercury.zip and copy the dist folder fromt he archive  to your localhost server

**Comment by kvhnuke** [comment]
https://pearsonnacommunity.force.com/support/s/article/How-to-display-mixed-content-with-Google-Chrome-Internet-Explorer-or-Firefox-1408394589290

this seems to be a good tutorial on how to enable mixed content

**Comment by cosmicscr** [comment]
Thank you!  

Okay got past the latest issues... still trying to connect to geth... will update you.  

Nope... back to the original.   Open dev tools> right click> empty hard cache and reload and I get this:

![screen shot 2017-01-15 at 6 24 21 pm](https://cloud.githubusercontent.com/assets/6118944/21968815/31a93490-db56-11e6-898b-ef559140876a.png)

**Comment by kvhnuke** [comment]
can you try again once more, i converted the JS to es5 (usually this is an issue on safari) make sure you download a fresh new copy. Thank you!. If it still doesnt work can you send us a screenshot of your chrome console.

**Comment by tayvano** [comment]
FYI, you can download dist from https://github.com/kvhnuke/etherwallet/releases/tag/v3.4.5 now. I dunno if kvhnukes compiling fixed it, by mine definitely should have. I usually compile for releases. No idea why his wouldn't but...stranger things have happened.

**Comment by tayvano** [comment]
This may help folks: https://github.com/benjaminion/eth-parity-qnap/wiki/Connecting-to-MyEtherWallet

**Comment by tayvano** [comment]
Let me know if this wasnt resolved

**Comment by cosmicscr** [comment]
Hi,

I'm back at it and still running into problems.  I'm trying to run MEW locally and connect to ledger wallet.

Here is what I have done so far:

1.  Running latest geth.  Geth does not support HTTPS directly with its rpc server, so I set a quick node https proxy server on port 3000 pointing to geth for MEW to attach to.  Using a curl statement proves that this https proxy works fine for interacting with my node.

2.  Running latest MEW by running `npm install` and  `gulp` and `gulp clean` against the tip of the mercury branch.  MEW is being served up by a node https server on port 4433.

3.  Both #1 and #2 servers are using a self-signed ssl certificate that has been added to my OSX keychain > system > certificates and trust = always trust.

4.  I use Firefox because it's smarter about handling security exceptions and remember choices.  I'm using the "CorsE" firefox plugin to bypass cors errors trying to access port 3000 from port 4433.  

5.  I load up MEW on https://127.0.0.1:4433  and works great!

6.  I add a 'custom node' pointing to https://127.0.0.1:3000... and NO errors !!  woohoo!  Presumably it's connected to my local node just fine.  (is there a way to confirm that it's talking to my local node?  Is there an action that I could perform to see some sort of entry in the geth console?)

7.  My nano is verified for both contract and browser support.  I connect the nano, enter the eth app, and click connect in MEW but run into the exact same error as in the initial post above:

```
ReferenceError: $ is not defined
Stack trace:
[67]</u2f.isIosChrome_@https://127.0.0.1:4433/js/etherwallet-master.js:7004:3
[67]</u2f.getMessagePort@https://127.0.0.1:4433/js/etherwallet-master.js:6981:14
[67]</u2f.getPortSingleton_@https://127.0.0.1:4433/js/etherwallet-master.js:7340:7
[67]</u2f.getApiVersion@https://127.0.0.1:4433/js/etherwallet-master.js:7467:3
[67]</u2f.sign@https://127.0.0.1:4433/js/etherwallet-master.js:7384:5
[65]</</Ledger3.prototype.exchange@https://127.0.0.1:4433/js/etherwallet-master.js:5987:2
[64]</</LedgerEth.prototype.getAddress@https://127.0.0.1:4433/js/etherwallet-master.js:5837:2
decryptWalletCtrl/$scope.scanLedger@https://127.0.0.1:4433/js/etherwallet-master.js:1157:9
fn@https://127.0.0.1:4433/js/etherwallet-master.js line 43502 > Function:2:147
callback@https://127.0.0.1:4433/js/etherwallet-master.js:55138:17
$eval@https://127.0.0.1:4433/js/etherwallet-master.js:46305:16
$apply@https://127.0.0.1:4433/js/etherwallet-master.js:46405:20
ngEventHandler/<@https://127.0.0.1:4433/js/etherwallet-master.js:55143:17
defaultHandlerWrapper@https://127.0.0.1:4433/js/etherwallet-master.js:31878:3
eventHandler@https://127.0.0.1:4433/js/etherwallet-master.js:31866:9
```

This is the exact error that was originally reported and was never investigated because we got caught up side matters of running HTTPS and cors issues etc.  Those issues weren't directly related to this error I'm seeing in the browser.  This error is in firefox, and the original error above was happening in Chrome.  This appears to be some sort of MEW error that is not being caused by our speculations in the above thread.

**Comment by crptm** [comment]
No other errors in console prior? Can you attach your etherwallet-master.js ?

**Comment by cosmicscr** [comment]
From a fresh reload, there are hardly any further messages... only these seemingly benign warnings:

```
This site makes use of a SHA-1 Certificate; it’s recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] 127.0.0.1:4433
unreachable code after return statement[Learn More] etherwallet-master.js:2897:4
This site makes use of a SHA-1 Certificate; it’s recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More]
```
uploading soon...

**Comment by cosmicscr** [comment]
[etherwallet-master.js.zip](https://github.com/kvhnuke/etherwallet/files/945284/etherwallet-master.js.zip)

Here is the file from the dist folder.  Presumably it's precisely what you would get by doing:

1.  git pull latest mecury branch
2.  npm install
3.  gulp
4.  gulp clean

**Comment by crptm** [comment]
Can you try doing it in chrome?

**Comment by crptm** [comment]
Better yet, can you join slack so we wont spam email %)

**Comment by cosmicscr** [comment]
Failed! invite_limit_reached

**Comment by crptm** [comment]
:( How is chrome going? :)

**Comment by cosmicscr** [comment]
I was able to add an extension to bypass cors errors in Chrome.  

1.  I load up MEW successfully over HTTPS (even though google complains a bit and doesn't handle trusted self signed certs as cleanly)

2.  I create a custom node to my https proxy and it seems to work!  no errors

3.  Then I attach nano and start the eth app

4.  Click connect and nothing happens.  Hmmm.  I then open dev tools and this is all I see in the console:

```
This site does not have a valid SSL certificate! Without SSL, your site's and visitors' data is vulnerable to theft and tampering. Get a valid SSL certificate before releasing your website to the public.
etherwallet-master.js:7386 Extension JS API Version:  1.1

```

**Comment by cosmicscr** [comment]
I also disabled all chrome extensions except the needed cors plugin and got the same results, so I don't think it's plugin interference.

Will you please test the issue on your side?  I can reproduce the error extremely simply:

1.  It doesn't matter whether I'm on HTTPS or file, I get the same error.
2.  It doesn't matter whether I connect to myetherwallet default node or custom node, I get the same error.
3.  It doesn't matter whether I plug in the nano or not, I get the same error.
4.  It doesn't matter if I disable (almost) all of my extensions, I get the same error.

So to reproduce:

1.  Open the index.html file in firefox
2.  Click Send Ether tab
3.  Click connect to ledger nano s
4.  Open dev tools so see the error in the console

**Comment by crptm** [comment]
1) is it working for you on mew.com?

2) go to app/scripts/controllers/decryptWalletCtrl.js:ledgerCallback and console.log(error) there, then rebuild and come back with error code :)

**Comment by tayvano** [comment]
Have you guys looked at this before? https://github.com/benjaminion/eth-parity-qnap/wiki/Connecting-to-MyEtherWallet (Not sure if helful...)

**Comment by crptm** [comment]
firefox issue is unrelated, we can fix it once chrome flow is working.

**Comment by cosmicscr** [comment]
Okay I'll need some time to troubleshoot.  thx

**Comment by cosmicscr** [comment]
Okay, most of the issue I think is resolved by one of the following:  updating to the latest firmware, or updating to the latest ethereum app on the nano device.

1.  The bug still exists on Firefox.  I think that is actually a bug.

2.  Connecting the nano to MEW is extremely intermittent and I mean extremely.  If one clicks on connect, then clicks cancel, it seems they can never reconnect unless they restart the hardware device.  Why not?  Seems non-intuitive considering there is a connect button.  I have to restart the device and click on connect many times in either the 'send' tab or the 'info' tab, or I have to open up MEW in an entirely new tab to get connectivity as sometimes merely refreshing the tab was not enough.   Consistent and expected connectivity upon pressing the connect button would have helped me a lot while going through hours of troubleshooting and I probably got many false negatives on fail to connect.  So it seems work could be done to help make connecting more robust and intuitive.  I verified that my system never once failed to recognize that the device was either connected or disconnected, nor did geth fail to do so which reported every time the device was connected in browser support mode.

I'll be extremely delighted if this can work for now since I've spent so much of my time just trying to get this up and running with a local node (knowing that I'll just need to try to connect a bazillion times to get it to work properly)

I have one final question which I would be very grateful to receive any guidance on:  How can I ensure or verify that MEW is actually connected to my custom node?  Is there any action I can take on the MEW side to see in the geth console that geth is actually being interacted with by MEW?

Thanks you both for your time and troubleshooting ideas.

**Comment by crptm** [comment]
1. Yep, i'll take a look. Maybe on a weekend.

2. Yep, it should at least display error codes to have some sort of feedback from user actions.

> I have one final question which I would be very grateful to receive any guidance on: How can I ensure or verify that MEW is actually connected to my custom node? Is there any action I can take on the MEW side to see in the geth console that geth is actually being interacted with by MEW?

You can open network tab in chrome devtools and ensure that it calls your node. Simply unlocking wallet should prompt multiple queries to check eth and token balances.

**Comment by cosmicscr** [comment]
Ah thanks good idea!  That makes perfect sense... I'll watch in devtools.

However, I've noticed that MEW errors if devtools is opened.  Please try to open devtools and refresh the page and you'll see a bunch of errors.  Screenshots of it are above in the thread.  But perhaps I can load it and get the process all set up and then load devtools and it all may still work.   I suppose in the worst case I can use wireshark to pick it up.

Thx again

**Comment by crptm** [comment]
> However, I've noticed that MEW errors if devtools is opened.

If you are talking about cert messages - these are just warnings, everything should work just fine with devtools open.

**Comment by cosmicscr** [comment]
No I'm talking about the screenshot above related to devtools.  Here's a new screenshot performing the exact steps I just described... and this is with all extensions disabled.  Perhaps it's from a devtools plugin?:

![screen shot 2017-04-20 at 4 55 20 pm](https://cloud.githubusercontent.com/assets/6118944/25255825/30a39340-25ea-11e7-9ccb-89cbd851ead0.png)

**Comment by crptm** [comment]
I see, would visiting your node url and adding cert exception help?

**Comment by tayvano** [comment]
The latest screenshot looks like you have Javascript turned off, or something didn't get compiled correctly....

**Comment by cosmicscr** [comment]
@crptm Hi sorry, see new screenshot above.  The old was due to an extremely annoying behavior of chrome:  if it connects to a custom node that it considers not secure then it appears red.  If you switch to a good node it's still red.  If you refresh the browser it's still f*cking red.  If you duplicate the damn tab it's still red.  you have to actually create a new tab and go to MEW for it to be green again.  Again, so annoying.  I took a better fresh screenshot above.

**Comment by cosmicscr** [comment]
@tayvano Hi,  

1.  Load MEW.  See that it looks nice.
2.  Open devtools.  See that it still looks nice
3.  Refresh the browser, see that it doesn't look nice anymore.  This is not about having javascript turned off.

**Comment by tayvano** [comment]
Hmmmm....that is extremely strange. I haven't been 100% following this thread, I'm just sharing what I know from past experience. I wonder if it's unable to load the JS for some reason - https vs non-https or something?

> I have one final question which I would be very grateful to receive any guidance on: How can I ensure or verify that MEW is actually connected to my custom node? Is there any action I can take on the MEW side to see in the geth console that geth is actually being interacted with by MEW?

I believe in the devtools console, if you click on the network tab, it should show your local 127..... instead of myetherapi.com or whatever it normally is.

I'm trying to get @kvhnuke in here as he knows much better than me.

**Comment by cosmicscr** [comment]
I just installed Chrome on a separate ubuntu image and I could NOT reproduce the devtools problem shown above.   It seems to only happen on OSX for some reason.  It happens even when I disable all extensions including extra devtools extensions like for react and redux.  Not sure what's going on.  If you can reproduce it and see it for yourselves then maybe you can troubleshoot it.  Otherwise I suppose it could be environmental.

**Comment by kvhnuke** [comment]
Yea if you are using the local node devtools network tab should show the local node ip for all outgoing requests, it definitely seems like a broken just error, check the devtools console

**Comment by cosmicscr** [comment]
Just a note for anyone coming across this thread, I switched over to using the parity client and it works way more consistently.
