### ISSUE TITLE
Ledger Nano using wrong paths with Ethereum Classic

### ISSUE THREAD

**Issue by karelbilek** [kvhnuke/etherwallet#327]
Ethereum Classic should use 44'/61'/... path, but ledger is using 44'/60'/... path for both ETH and ETC. ( https://github.com/satoshilabs/slips/blob/master/slip-0044.md )

Unfortunately I cannot "just" fix it in the code right now, since that would prevent people from accessing their ETC wallets.

**Comment by karelbilek** [comment]
I am now writing support for trezor into etherwallet and I will use the correct paths from the start, if possible

**Comment by tayvano** [comment]
The path for accessing ETC vs ETH for Trezor should have it's own variable / path regardless. So your code shouldn't affect what Ledger does / supports.

I can't remember where it is, but there is a way to detect if a person is on an etc chain. 

So then it should be 

is_ETH ?  trezorPath == 44/61 :  trezorPath == 44/60

or whatever. 

@kvhnuke Can you please let him know what the ETC variable or whatever it is. I would look it up but I need to get in bed - I have an 8am with Coke. 😞

**Comment by karelbilek** [comment]
> The path for accessing ETC vs ETH for Trezor should have it's own variable / path regardless. So your code shouldn't affect what Ledger does / supports.

Well, not really, since the code is very similar for Ledger and Trezor, I reuse some of their code. And Trezor and Ledger use the same BIP44 paths.

Actually, TREZOR and Ledger initialized with the same seed return the same addresses. (Except now for the ETC addresses, which will differ.)

**Comment by karelbilek** [comment]
cc @btchip

**Comment by tayvano** [comment]
That's fine. We should probably update any shared functions to accept a path parameter if they don't do so already. Here are the paths used for Jaxx / Metamask and Ledger. We don't know what is going to happen in the future and the paths are obviously different currently, so I still think it's most prudent to set it up in that way instead. If the paths end up being the same later, they end up being the same. If in 2 years we need to update them to be different, then they can easily be different again.

https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L17-L18

**Comment by karelbilek** [comment]
Hm, but the actual path, that gets sent to Ledger (and therefore the more important one :) ), is hard-coded on this line anyway and not reused from that object

https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L154

edit: I will move it out when I am now at it when I am editing the code there

**Comment by kvhnuke** [comment]
ajaxReq.type is a global variable itll let  you know whether it is "ETH","ETC","ROP"

**Comment by karelbilek** [comment]
(and I think Jaxx / Metamask have the same issue?)

**Comment by karelbilek** [comment]
This causes another issue though

Ledger and Trezor have the same mnemonics.

You have a logic, where when pasted mnemonic looks like Ledger seed, it recreates the wallet using ETH paths, always.

But when Trezor will use correct paths for ETC and ROP, I cannot distinguish if it is a ledger seed and should, therefore, use `60'` in cointype, or trezor seed and I should use `61'` (or `1'` with ROP).

edit: I have added checkbox for that.

**Comment by tayvano** [comment]
v3.6.6 allows you to choose any path, on any chain, for TREZORs and LEDGERs, which hopefully will resolve some of the issues were seeing with people sending ETH to ETC addresses and vice versa, as well as the folks who are just sparkly little diamonds who use their own custom path for everything. 👍

**Comment by btchip** [comment]
Great, thanks for the extra work put into that.

**Comment by karelbilek** [comment]
Great!
