### ISSUE TITLE
I can't view my address without also having my unencrypted private key appear on the screen.

### ISSUE THREAD

**Issue by peterjoel** [kvhnuke/etherwallet#33]
It should be possible to load a wallet file and view public information about it, without exposing private keys on the screen.

**Comment by tayvano** [comment]
If you would like to see publicly available information, I recommend using a blockchain explorer like https://etherchain.org/ or http://etherscan.io/ or http://live.ether.camp/. We are not looking to spend a lot of time developing this sort of stuff when there are already these 3 excellent services that do a far better job than we could ever do.

Thank you.

**Comment by peterjoel** [comment]
For example, I would like someone to send ether to an address that I already own. If I open the wallet file to discover the address, I cannot avoid displaying the private information on the screen.

**Comment by tayvano** [comment]
Ah. 

Is there a reason that you aren't saving your address in a text document along with your private key? In general, you should minimize the number of times you upload/access your private key, online and offline.

**Comment by peterjoel** [comment]
I _am_ saving the address in a text document along with my private key. But isn't part of the point of a graphical interface so that users don't have to open json files in a text editor? 

I'm used to using deterministic Bitcoin wallet clients and (perhaps misguidedly) expected a similar experience from an Ethereum client. I understand that most of the software around Ethereum is quite unpolished.

This issue may not be super high priority but I think it's worth tracking, and maybe I'll have time to look at it myself.

**Comment by tayvano** [comment]
Here is the [text file](http://i.imgur.com/XHV2BDx.png) that I keep on my desktop. I also bookmark the corresponding etherchain page (ie: https://etherchain.org/account/0x7cb57b5a97eabe94205c07890be4c1ad31e486a8) so I can check the account whenever I want.

The address is public. It should be saved along with the private keys, etc. but it should _also_ be saved separately in an easily accessible place so you can copy and paste and check the balance whenever you want. Your bookmarks bar is a great place for this. 

> But isn't part of the point of a graphical interface so that users don't have to open json files in a text editor?

I'm confused by this. Is uploading a JSON file easier than just double clicking it?

You could also use the [Chrome Extension](https://chrome.google.com/webstore/detail/myetherwallet-cx/nlbmnnijcnlegkjjpcfjclmcfggfefdm/) if you would like to save addresses for easy access later. You can add a watch only account in which you paste the address and it displays your address and balance whenever you visit that page. Or you can save the json/private key so you don't have to reupload all the time.

You may also want to look into Jaxx which has a multipurpose wallet and prides itself on it's user interface. 

We will add this to the todo list but it'll be a very low priority. We currently have a number of large features and changes that we are working on implementing, including a top-to-bottom refresh that will make it much easier for us to update in the future.
