### ISSUE TITLE
Ledger Nano S & TREZOR initialized with same key but showing different addresses in MEW (via email from Rob)

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#332]
@runn1ng  @btchip -- Just received this (very well written) support request via email. Any insights?  Bold areas = key points.

> First of all, let me say thanks for making this integration a reality, it's great to see. You guys do great work.

> I've encountered some strange behavior though, that I'm hoping you can help clear up:

> I own both a Ledger Nano S and a Trezor. I also have a single 24-word recovery phrase. **Both of the hardware wallets are initialized using the single phrase. I can confirm that the key is the same because when I am using BTC (via Electrum or Ledger Bitcoin Chrome app), I see the same transaction history from either device.**

> **However, when using the devices for ETH, I am seeing two different addresses being generated.** I have tried with passphrase enabled on the Trezor (entering "" as passphrase), and I have also tried with passphrase disabled; both of these actions result in MEW showing me the same address. But this is not the same address that I see when I use MEW with my Ledger Nano S. The sequence of addresses is completely different.

> **From what I have read, both devices use the same derivation path (44’/60’/0'/0) for ETH. So how is it possible that I am not seeing the same sequence of ETH address from both devices, if they are initialized with an identical key?**

>Thanks for your time.

**Comment by kvhnuke** [comment]
Just noticed,  Trezor uses different path from Ledger [LN20](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L20) vs [LN23](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L23).

**Comment by prusnak** [comment]
That was what was the path discussion all about in https://github.com/kvhnuke/etherwallet/pull/330
I though you understood the issue and its implications.

**Comment by prusnak** [comment]
Key point is https://github.com/kvhnuke/etherwallet/pull/330#issuecomment-275202428 where @btchip agrees to change Ledger paths to be compatible with BIP-44 like most of the wallets.

**Comment by kvhnuke** [comment]
Yes for a second I completely forgot the whole path discussion, I think we can close this.
