### ISSUE TITLE
TREZOR:  Retyping passphrase for every transaction

### ISSUE THREAD

**Issue by mcgravier** [kvhnuke/etherwallet#333]
I noticed, that myetherwallet requires typing passphrase for every action - so if I want to make multiple transactions, I have to retype passphrase every time. 

On official wallet passphrase is required only once - until device is disconnected or timeout kicks in.
 It would be more convenient if myetherwallet worked in similar way

**Comment by tayvano** [comment]
For security reasons, we're going to leave this as is. Even if it's a pain, it's more secure and I'm okay with that.
