### ISSUE TITLE
Unusual capitalization of hex encoded ethereum address

### ISSUE THREAD

**Issue by iancoleman** [kvhnuke/etherwallet#337]
I'm unclear whether the hex encoding with unusual capitalization is intended and important, or is just an unusual side-effect with no consequence.

Steps to reproduce:

* navigate browser to https://www.myetherwallet.com/#view-wallet-info
* select mnemonic phrase
* enter `abandon abandon ability`
* click unlock
* see the first address is 0xe5815d5902Ad612d49283DEdEc02100Bd44C2772
* note the unusual capitalization, eg 'DEdEc'

I would expect hex encoding would be all upper or all lower case. Is there a particular reason for the mixture of capitalization in the address string?

**Comment by tayvano** [comment]
Capitalization simply means the address has a checksum. You should use the capitalization address because of this, but both will work.

https://github.com/ethereum/EIPs/issues/55
