### ISSUE TITLE
Add support for Classic Donations

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#343]
I usually don't have too much ETH on hand. An address for ETC donations would be helpful. Or if notice that MEW monitors the same address.

**Comment by tayvano** [comment]
All ETH/ETC/Tokens can go to the main donation address (0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8)

Every so often we divvy it up, decide how much we want to go to overhead like servers, and keep the rest for ourselves. That applies to everything in that account.

We considered making add'l addresses but decided against it as it would just be another thing to keep track of 📦

Thanks 😄

**Comment by ghost** [comment]
:-) Some ETC sent your way along with some BEC Token.

**Comment by tayvano** [comment]
Thank you - much appreciated!
