### ISSUE TITLE
(Fix modals) Cannot connect to Ledger Nano S from `Send Ether and Tokens` tab after having opened `View Wallet Info` tab

### ISSUE THREAD

**Issue by JanKalin** [kvhnuke/etherwallet#348]
A strange bug... Steps to reproduce:

- Navigate to `View Wallet Info` tab
- Navigate to `Send Ether and Tokens` tab
- Click on `Connect to Ledger Nano S`.
- The page goes grey and stays that way without ever connecting to Ledger.

The issue is resolved by reloading the `Send...` tab in the browser.

This is the only way of triggering this bug. I have only noticed it because I happen to have https://www.myetherwallet.com/#view-wallet-info bookmarked. However, it occurs any time you navigate first to `View...` and then to `Send...` tab.

This is reproducible on:
- my home and work PCs with Windows 7 + Firefox 51.0.1 + U2F plugin 1.0.1,
- my work PC with Windows 7 + latest Chrome and
- in a VirtualBox guest running clean install of Windows 7 + latest Chrome.

**Comment by tayvano** [comment]
Interesting. I'm guessing it has something to do with the modal. We had a couple things similar to this. You try to do X but the modal pops up on the View Wallet Info page so you can't see it. 

@kvhnuke Can we like.....fix the modals in general?

**Comment by tayvano** [comment]
Yeah this is also reproducible using any mnemonic key. Definitely the modal getting lost somewhere.
