### ISSUE TITLE
Unable to send any ALT coin with Ledger Nano S "insufficient balance for gas" but have over 100 ETH

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [kvhnuke/etherwallet#356]
I connect my Ledger Nano S (latest firmware: 1.3)

- Contract data is YES
- Browser Support is YES
- Over 100 ETH available in account

As soon as I change the coin type to anything but ETH I get:

> If you are getting an insufficient balance for gas ... error, you must have a small amount of ETH in your account in order to cover the cost of gas. Add 0.01 ETH to this account and try again.

If I **Generate Transaction** I can confirm on the Ledger Nano S but this does nothing, seems like all just hangs and after a few minutes I get the timeout error on the site.

_Below a gif of the issue:_

![ledger_help](https://cloud.githubusercontent.com/assets/725851/23451426/2c3ac136-fe60-11e6-8379-5133729c536e.gif)

**Comment by DESIGNfromWITHIN** [comment]
Really bad for me tried 3 computers and it does not work anywhere

**Comment by DESIGNfromWITHIN** [comment]
Using more gas does not help.

**Comment by kvhnuke** [comment]
> If you are getting an insufficient balance for gas ... error, you must have a small amount of ETH in your account in order to cover the cost of gas. Add 0.01 ETH to this account and try again.

that is just an info msg, not an actual error. 

However, nothing showing up is an error, I just tried both Firefox and chrome and was able to successfully transfer REP token. What operating system are you on? browser? if you are on chrome press ctrl+shift+j (this should open up the console window) let me know if it shows any errors.

**Comment by pollastri-pierre** [comment]
Hello this is an issue with your version of the Nano S Ethereum application. Please uninstall and reinstall it, it should solve the issue.

**Comment by DESIGNfromWITHIN** [comment]
Ok thanks will try

**Comment by DESIGNfromWITHIN** [comment]
@pollastri-pierre 
Thank you reinstalling did the trick!
