### ISSUE TITLE
Set Ropsten node to auto reset every 12 hours...or use geth

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#358]
Ropsten is currently having some difficulties due to some sort of network attacks or something, which is why we cannot stay in sync. 

If this is not solvable by switching to geth, please ghetto-rig it to restart if it's out of sync or every X hours so that it's not completely useless, 100% of the time

**Comment by kvhnuke** [comment]
couldn't get parity to sync, running geth now. Ropston is fully functional

**Comment by kvhnuke** [comment]
ignore the trace_call not found error until latest version goes live @tayvano
