### ISSUE TITLE
Not a valid ERC-20 token

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#359]
Hi, 

My token had been verified on etherscan as an ERC-20 token. However after adding the token in MEW, it shows 'Not a valid ERC-20 token'. 

Contract address : 0x8c859BD1c35A79f09c6e30E35FFAcf852014a264

Had the symbols and decimals similar with etherscan

Thank you

**Comment by tayvano** [comment]
@neowenyuan27 - Etherscan does not show this address as an ERC-20 address.

This one looks like the address you are looking for:

0x70a8629c1b9a50133c5325502232bd54447beee7
SOAR
decimals: 6

**Comment by ghost** [comment]
Sorry for my error @tayvano. Everything is fine now, thank you for your time

**Comment by sdangeva** [comment]
someone help me with getting my new CTX tokens -CARTAXI.  It shows not a valid ERC-20token on my there wallet?? I did everything right I think??  Please help
