### ISSUE TITLE
Encrypted Private Keys / Paper Wallets (use BIP38 spec)

### ISSUE THREAD

**Issue by abueesp** [kvhnuke/etherwallet#36]
After reading [this](https://www.reddit.com/r/ethereum/comments/41pug5/wondering_if_ukvhnuke_and_utayvano_are_around/cz5hfra), [this](https://bitcoinpaperwallet.com/bip38-password-encrypted-wallets/) came to my mind.

Pretty good wallet, by the way.

**Comment by tayvano** [comment]
Moved to v4

**Comment by infokiller** [comment]
@tayvano why was this issue closed, can you please clarify?

Thanks!

**Comment by tayvano** [comment]
@infokiller We are working with Nick Johnson and a few others to come up with a standard encrypted key standard for Ethereum that will be used for paper wallets, optionally, in the future. 

Right now people losing their passwords is a greater cause of loss than hacks of paper wallets. So, while we will have them at some point, there isn't a ton of urgency.

**Comment by infokiller** [comment]
Gotcha, thanks!
Any issue I can subscribe to for this feature?

**Comment by infokiller** [comment]
@tayvano any update?

Thanks!

**Comment by tayvano** [comment]
@infokiller Unfortunately no. Everything is in flux: https://github.com/satoshilabs/slips/issues/103
