### ISSUE TITLE
Send tx offline: Qrcode of signed tx 

### ISSUE THREAD

**Issue by gregbkr** [kvhnuke/etherwallet#37]
Hello,

We are using myetherwallet offline, in order to create wallet, and send offline tx. Works great thx guys!
# Step 3: Send / Publish Transaction (Online Computer):

Do you plan to implement a qrcode of the signed tx, in order to easily get it out of an airgap pc?
# Step 2: Generate Transaction (Offline Computer)

Same with entering a public address for payment, any way to avoid mistake and be able to scan a qrcode?
And a way to not mess up with so many digits in the gasprice, maybe some dot/coma, or a conversion in different ether units.

I understand I can do that with usb stick. Or do you recommend any other tools?

Thank you for your help! 
Good week!
Greg.

**Comment by tayvano** [comment]
Hey! So we're hoping to push a massive update to MyEtherWallet this weekend and we are including QR codes on the Offline tab!

I have one question for you.....how would you personally use the QR codes on the offline transaction tab? Do you have a QR code reader on both computers?

**Comment by kennyrowe** [comment]
Ideally I would like to scan the QR with my phone from the air gapped computer and send the signed transaction from my phone.

**Comment by kennyrowe** [comment]
p.s. @kumavis has a great idea for stuffing large amounts of data into a QR format (ie deploying a contract). The basic idea is the QR is an animated GIF that displays say 4 or 5 images in a loop.

The QR reader would need to be special in order to ready the QR code though.

**Comment by gregbkr** [comment]
Thank you, I saw the new version with qrcode of offline signed tx, that's great, already using it! ;-)

**Comment by tayvano** [comment]
This was implemented for Mew v2 at the end of May. Those are some fat QR codes but they work! 😝
