### ISSUE TITLE
Trezor functionality w/ local copy of repo/release, not working =(

### ISSUE THREAD

**Issue by GenTarkin** [kvhnuke/etherwallet#374]
I cant seem to get trezor working when I start index.html w/ a local copy of the repo/release.
It just gets stuck at the trezor login popup window, seems to never find trezor.
Is there any way to make it work or plans to fix?

Thanks

**Comment by tayvano** [comment]
I'm guessing this is due to not being connected via SSL. 

You will need to run MyEtherWallet locally over SSL. 

Not sure of your OS but you can google `ssl local dev` and there are a variety of guides on how to set it up.

**Comment by Premik** [comment]
Not sure if this is the same issue but I'm also unable to connect with Trezor on the [Send Ether](https://www.myetherwallet.com/#send-transaction) page now.
Js console shows this error:
```
Refused to load the script 'https://connect.trezor.io/1/popup/popup-dist.js' because it violates the following Content Security Policy directive: "script-src 'none'"
```
And the ```https://connect.trezor.io/1/popup/popup-dist.js``` js won't load. Which I guess is the reason the login dialog never finishes loading.

edit: Found out it works ok in Google Chrome. Only Goole Chromium is broken. Strange.

**Comment by tayvano** [comment]
see #558
