### ISSUE TITLE
Incorrect Wallet Password

### ISSUE THREAD

**Issue by thrillbit** [kvhnuke/etherwallet#378]
I am trying to transfer eth into my ledger nano s. I currently use myetherwallet to manage my eth. I created a new wallet on myetherwallet with my mnemonic that I was given from my ledger. It then asked me to create a password on myetherwallet. So I created a password, but now the password won't work. I sent 1 eth to it and I cannot access it. Can someone explain to me where I went wrong?

**Comment by tayvano** [comment]
Which page were you on when you said you created a new wallet with your mnemonic? Screenshot?

**Comment by thrillbit** [comment]
it was on my ledger nano s. I used that mnemonic to try and access it on myetherwallet

**Comment by thrillbit** [comment]
I got it all figured out thank you for you help!
