### ISSUE TITLE
Different public-adress - Lost 5 ETH

### ISSUE THREAD

**Issue by aresabi** [kvhnuke/etherwallet#379]
Last week, I decided to create a wallet on myetherwallet.com and send 5 ETH from btcdirect.eu
to the public address. After my registration, the public address was shown. I copied & pasted it.
Now the address under the same private key seems to be different and my balance is 0 ETH.
What to do now?

**Comment by tayvano** [comment]
Hi, please send us an email at myetherwallet @ gmail.com and send me your address so I can look into this. Thank you.

**Comment by aresabi** [comment]
Already sent you an email with both of the addresses 15 minutes ago. Thank you so far

**Comment by tayvano** [comment]
Okay - I'm answering emails from about 2 hours ago so I should get to you shortly. Constantly playing catchup in the inbox. Sorry for the delay!
