### ISSUE TITLE
Import/sweep from ETH paper wallet. Please tell how without blochain on my computer.

### ISSUE THREAD

**Issue by andropole** [kvhnuke/etherwallet#38]
Import/sweep from ETH paper wallet 
with private key but without blockchain on my computer.

What is the procedure to do it with Myehterwallet or anyother way?

Even with my time correct I am unable to download the blockchain to use in Ethereum-Wallet. Three weeks now and little progress.

Need to put paper wallet back into play by sweeping/importing to something that can then send to the exchange.
Thank you for any help you can offer.

**Comment by tayvano** [comment]
You can _access_ your wallet on MyEtherWallet via the send transaction tab. Simply upload your JSON or keystore file or paste your private key and then send the funds wherever you want (like an exchange address)

**Comment by andropole** [comment]
Thank you very much Tayvano.  Finally I can buy some ETH knowing it can be safely taken out to paper and retrieved.  Did a test out to paper into MyEtherWallet via the send tab which allowed me to put in the paper wallet's private key and send back to the exchange. 

Note: if someone reads this and runs a similar test make sure to send enough that the exchange will process the deposit. For Bittrex just now it must be more than .1 ETH.
