### ISSUE TITLE
wrong address

### ISSUE THREAD

**Issue by Antoniosss21** [kvhnuke/etherwallet#380]
Hello. I had an error buying etherium. I accidentally pointed out the wrong address. I do not know how it happened, but the translation did not come to my address.
My adress is 0xA6e5dd276Fa1dE00EF5926F3c124b252F2135Ac1
Tell me, could you transfer money to my account
![1](https://cloud.githubusercontent.com/assets/26594156/24190051/67569c10-0ef8-11e7-8d31-69bff6b6701c.png)
![2](https://cloud.githubusercontent.com/assets/26594156/24190052/6756b3bc-0ef8-11e7-8ee8-3d7e56528054.png)

I hope you can help me. Thank you.

https://etherscan.io/address/0xfcb9fa29fce2498025ac166d929c528aeba26209

**Comment by tayvano** [comment]
I’m really sorry but MyEtherWallet is not actually a "web wallet". You do not create an account or give us your Ether or any tokens to hold onto. We cannot access every address that exists on the Ethereum Blockchain

Without the private key to this account, no one can access that ETH. 

Please take some time to look over our getting started guides so you can get a better understanding of how this all works. Thank you. 

Our help page: https://www.myetherwallet.com/#help

**Comment by Antoniosss21** [comment]
So what should I do? I lost my money?

**Comment by tayvano** [comment]
Do you have the private key for the address 0xfcb9fa29fce2498025ac166d929c528aeba26209? 

Where did this address come from?

**Comment by Antoniosss21** [comment]
No, I do not, I do not know where. I have kept the revisions in a text document. And maybe I did not keep them right. Or something has casually changed.

**Comment by tayvano** [comment]
What do you mean by 'revisions'?

**Comment by Antoniosss21** [comment]
requisites*

**Comment by tayvano** [comment]
Please email myetherwallet @ gmail.com and we can dive deeper and see if we can help figure out what came from where. Thanks.

**Comment by Antoniosss21** [comment]
Probably this is my old address, but I have not saved it correctly, so I have another one.
![e1](https://cloud.githubusercontent.com/assets/26594156/24191863/29943cf6-0efe-11e7-8cfe-78ddfd01a5e1.png)
![e2](https://cloud.githubusercontent.com/assets/26594156/24191862/2992ccd6-0efe-11e7-8980-6a3bea7e1a0f.png)

**Comment by tayvano** [comment]
**Please** email us. I would rather not have you sending sensitive or secret information in a public forum.

**Comment by Antoniosss21** [comment]
ok, if you think that there is information on which someone can break my account, delete it

**Comment by Antoniosss21** [comment]
Sorry for the inconvenience, I found this key in other files. And thanks for the aging to help me. have a nice day
