### ISSUE TITLE
How can I send a tip to someone who doesn't own an ETH address?

### ISSUE THREAD

**Issue by Nogreedy** [kvhnuke/etherwallet#381]
Hello,
I'd like to send an ETH tip... but 99.99% of people doesn't own an ETH address.
How can I do with myetherwallet.com?  
Is it possible to obtain a URL link (to send to a recipient) from myetherwallet.com? 
When I used Bitcoins (in an other life) it was possible with ChangeTip, GoCoin, Blockchain.info, Coinbase.... but it was centralized...
I think the possibility to send Ethers to someone who doesn't own a wallet (and doesn't know what is Ethereum) would be very appealing and a great way to spread ETH.
Thanks in advance for your answer.
PS : with https://ethereumwallet.com , I can send a link (with a password) to a funded wallet, but it's not really connected to only one wallet... 
https://ethereumwallet.com/beta/index.html#dgDPW3BDrtalhWYnyhSq5DwMjge3wwE

**Comment by Nogreedy** [comment]
@tayvano @kvhnuke 
Please, answer my strange question.
Thanks.

**Comment by tayvano** [comment]
As we do not have servers or store any information this is not possible. You would have to create a wallet for the person and send it to them.

**Comment by linagee** [comment]
Also... ChangeTip is dead. The others you listed are not tip bots. I guess Coinbase allows an email address (I think?), but don't they also do ETH...?

**Comment by crptm** [comment]
Theoretically we can create new wallet, send eth there, give back qr-code or something with pkey+flag that it is a tip key. Then create another wallet when onboarding users with tips.

**Comment by Nogreedy** [comment]
@tayvano 
Hello,
perhaps with this?   ;)
https://www.reddit.com/r/ethereum/comments/6iqjaj/myetherwallet_contest_design_our_ether_cards_and/

**Comment by tayvano** [comment]
@Nogreedy See how things tend to come together even if I dont update each and every github issue? Tons and TONS of fun stuff in the works. 😃

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
