### ISSUE TITLE
www.myetherwallet.com is down??

### ISSUE THREAD

**Issue by GenTarkin** [kvhnuke/etherwallet#382]
Just wondering where the site went. I get err 404 =(

**Comment by kvhnuke** [comment]
We made some changes to our DNS settings and it might take some time to propergate through out the world. Until the main domain starts to work for you please feel free to use https://kvhnuke.github.io/etherwallet/. you can also try to reset your dns settings and try again

**Comment by GenTarkin** [comment]
Thanks for heads up! Site working now =)

**Comment by GenTarkin** [comment]
Seems the site is down again =(
update: nevermind, seems the www is required

**Comment by tayvano** [comment]
We haven't made any changes so whatever you did before to get it to work...try again?
