### ISSUE TITLE
i lost my Keystore File (UTC / JSON) in www.myetherwallet.com 

### ISSUE THREAD

**Issue by dyia40** [kvhnuke/etherwallet#383]
There is no other way to access my account except "Keystore File (UTC / JSON)",
What should do ?

**Comment by tayvano** [comment]
You can access your account via your private key. This private key comes in a number of forms and how you access you account depends on what private key format you saved.

What format did you save when you generated your wallet? Did you generate your wallet on MyEtherWallet.com?

**Comment by tayvano** [comment]
Please email us at support @ myetherwallet.com if you are still having issues.

**Comment by stanfordesign** [comment]
Hi Taylor,

It would be appreciated if you please let me know how we can send the btc in order to buy ETHG.

Thanks,
Mo
