### ISSUE TITLE
Unable to connect to node. See the help page for troubleshooting suggestions.

### ISSUE THREAD

**Issue by chicken84** [kvhnuke/etherwallet#384]
Hi!

I got some issues by visiting your site. I will attach a screenshot to show you my problem.

Things i tried to find a solution:

- Tried with Firefox (Screenshot)
- Tried with Firefox in Private mode
- Cleaning the Cookies
- Cleaning the Cache
- Tried with Internet Explorer

Still the same Problem. Only using the TOR-Browser to see if something wrong with my firefox does help.
I tried to mine some coins serval days ago with etherminer and geth as cloud mining and solo mining. I was searching for a solution if i made some troubles using geth and node, but i found nothing to help me. Nothing on the site is clickable. Every rolloutmenu is open below to the end of the site.

So... can you help me?

![unbenannt](https://cloud.githubusercontent.com/assets/26671913/24322189/d7635a26-115e-11e7-9a9b-0d99cc81edf6.png)

**Comment by tayvano** [comment]
It looks like you have Javascript disabled. Do you?
