### ISSUE TITLE
Sent testnet coins on Ropsten, not showing up

### ISSUE THREAD

**Issue by linagee** [kvhnuke/etherwallet#385]
https://testnet.etherscan.io/address/0x1ccd836bbee3584a62734ce120639f0725841508

How to reproduce:

- https://www.myetherwallet.com/#view-wallet-info
- Make sure you're on Ropsten in the upper right
- "View with Address Only"
- 0x1cCD836bBee3584a62734cE120639F0725841508

Still shows as zero balance.

Right now it shows "Latest Block#: 355480" (Jan-16-2017) on the bottom right of your page, but the transaction I'm looking for is in block 763133. Weird. If I'm just doing something incorrectly....?

Can you please kick your testnet node somehow or make sure it's synced? Thanks.

**Comment by kvhnuke** [comment]
Testnet is currently resyncing after removing all the spam blocks. However it seems like there are not many  nodes with the new version of the chain therefore it is taking little longer to sync. Please wait until it is fully synced before submitting txs

**Comment by kvhnuke** [comment]
we are back on track now.
