### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by botylev** [kvhnuke/etherwallet#386]
https://gastracker.io/addr/0x578a3514aa5e7def0b4dc35bec99bba738e90baa showing 0 ETH
https://etherscan.io/address/0x578a3514aa5e7def0b4dc35bec99bba738e90baa showing 0.26640072 ETH

i cant send ethers

**Comment by tayvano** [comment]
Gastracker.io is ETC. Etherscan.io is ETH. They are separate coins.

**Comment by tayvano** [comment]
You have to switch to the etc chain to send etc using the node switcher in the upper right corner
