### ISSUE TITLE
Encrypted private key not encrypted?

### ISSUE THREAD

**Issue by hkparker** [kvhnuke/etherwallet#39]
After generating a wallet on https://www.myetherwallet.com/#generate-wallet, there is an option to "Download JSON file - Geth/Mist Format (encrypted)".  The JSON file that is downloaded contains the key "Crypto", which contains the key "cyphertext".  The value is the unencrypted private key for the wallet.  I was expecting the value to be the encrypted private key for the wallet.

**Comment by tayvano** [comment]
While the cipher text may _look_ like a private key (and "be" a private key) it is not the private key / account that the JSON will unlock and it is not encrypted.

Every 64 hex string will open an account. In this case, that string is NOT the private key, but rather a value being used to check / decrypt the public key / private key derivation. You can read more about it here: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

I just generated a new wallet:
- Address: 0x2d9C9d03CD1544c86A99380D7aB837BD89Cc1205
- Unencrypted Private Key: 83d945cc6b0fd190a718ac337d50b9161f5610ddfdee78dd19dc83e4757a5411
- "ciphertext":"edcb70e842438e964799c825e23287c3948fcbf75999b6e88c791b5f1729ebd8"

If I paste the unencrypted private key or upload the JSON into view wallet details, it will unlock account 0x2d9C9d03CD1544c86A99380D7aB837BD89Cc1205

If I paste the cipher text, it will unlock 0x96d37eef645a8e582F212d4C17Dc0622Fa72dbA1, a completely different wallet.

**Comment by hkparker** [comment]
Ah, sorry for my ignorance, thanks for the information!  In the past when I've used etherwallet the private key was presented in what seems to be an openssl-friendly format beginning with "Salted_" (U2FsdGVkX1).  I've seen this in other wallet generators as well.  Was that ever a standard and is the community settled on an official technique?  I'm trying to understand what format would be best for a paper wallet.
