### ISSUE TITLE
Gas price unit on offline transactions at MEW

### ISSUE THREAD

**Issue by jmiehau** [kvhnuke/etherwallet#394]
If I want to make an Offline transaction at MEW, I would like to be sure on which unit the software is calculating the gas price. I'm only able to see this message: "This was displayed in Step 1 on your online computer".

Is it in Gwei or in Wei?  A link to http://ethgasstation.info would be perfect to know how much are we paying.

In the other hand, how it's calculated the gas price of a normal MEW transaction?

Congratulations for the work on MEW.

**Comment by tayvano** [comment]
Hi jmiehau,

The gas is in Wei. We manually set the gas price at this time and the gas price on the offline tab is the same price as the online tab. We have only changed the gas price once when it was recommended during the network attacks. At that time we increased the price to  41000000000.

The transaction fee is the gas price * gas limit. A default transaction has a gas limit of 21000. The current gas price we are using is 20000000000 (or	0.00000002 ETH).

21000 * 0.00000002 Ether = *0.00042 Ether ($0.02)*

You can typically see this by clicking on a recent transaction to our donation account (as those are almost always sent via MyEtherWallet: https://etherscan.io/tx/0x876b563ef7f45875df681fe1cbb97a7f713d3ece81648bd1323a27827dcfc56e
