### ISSUE TITLE
Error when trying to send GNT token: Invalid status 6a80

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#395]
Hi,

I cannot send my GNT token from my Ledger Nano S, when I try I get this error "Invalid status 6a80". Let know if you need any more info.

Thanks!

**Comment by tayvano** [comment]
Turn contract data on on your ledger device.

**Comment by ghost** [comment]
Sweet!! thanks a lot tayvano!!

**Comment by tayvano** [comment]
No problem!

**Comment by SiCkL3r** [comment]
It fixed my problem, but what exactly did it do? What does that setting change?
