### ISSUE TITLE
 Unencrypted private key always visible

### ISSUE THREAD

**Issue by Naigel56** [kvhnuke/etherwallet#399]
Once I click on "View Wallet Info" button and I unlock my wallet the second line display the unencrypted private key, big and visible. Wouldn't be better not to display the private key but only an obfuscated version with a "Show my private key" button?

When I create a new wallets and I save the crypted keys the first thing I try is to re-open the wallet, to be sure I entered the correct password and I can just access it again, but I don't want to display any private data. The same apply to qrcode on the left.

P.S. if you want I can spend a bit of time to try to implement a solution.

**Comment by tayvano** [comment]
This would definitely be a lower priority on the overall list but has been requested before. If you open a PR with it, we will certainly pull it in and there would be more than a few happy folks.

The one thing to be aware of is to make sure you test unlocking using both a private key, a keystore file, and the "Unlock with Address Only" options. Each of these show slightly different things based on what information is available to them. 

I also highly recommend getting a text expander where you can hold your testing / demo keys or you are going to get sick of copying and pasting a bazillion times. The enter key will also unlock if there is a valid private key in there. These to things alone have probably saved me hours and hours over time. 😂

Let me know if you need any testing keys that we don't generate. I've got lists all over the place. 

Thanks!
