### ISSUE TITLE
Reload balances in sidebar drtv ~15s after making a transaction, once every 5 minutes.

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#403]
> kryptopojken‏ 
> @kryptopojken
> @myetherwallet hey, is it possible to refresh myetherwallet without reloading my wallet from trezor? i just want to see if I received funds

**Comment by crptm** [comment]
We can try Etherscan websocet subscriptions https://etherscan.io/apis#websocket

**Comment by crptm** [comment]
But it wouldnt work for tokens, right? Because they have no transaction with user address involved.

**Comment by tayvano** [comment]
Apparently this is something to do with a recent parity update which will be solved when we finish updates for geth v1 6 and use that. Adding websockets to v4 list though. Love websockets.
