### ISSUE TITLE
Feature request: Extract release zips into a subdirectory

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#404]
The release zip archives should extract into a suitably-named subdirectory. E.g., dist‑v3.6.0.zip might extract into a subdirectory dist‑v3.6.0, and so on.

This will be useful for two reasons.

First, we can extract a new release and it automatically goes into its own unique subdirectory. We don't need to manually create a separate directory for it, and there is no risk of absent-mindedly extracting over the previous release and confusing ourselves about just what we did.

Second, due to the way Chrome OS devices (Chromebooks, Chromeboxes, ...) work, these zip archives are easy to extract and run locally with a single drag-and-drop if they are rooted at a single top-level directory. Otherwise we must use more tedious procedure to drag and drop each file or directory in the zip archive.

**Comment by tayvano** [comment]
https://github.com/kvhnuke/etherwallet/tree/mercury/releases

https://github.com/kvhnuke/etherwallet/blob/mercury/gulpfile.js#L254-L266

We are likely going to remove releases entirely from the repo. The releases page will have the release zips, generated and "released" automatically through travis. 

- People downloading `mercury` don't want to download a file twice as big to have a zip file anyways. 
- People cloning / forking `mercury` shouldnt have to deal with releases
- People who aren't developing should opt for downloading from the releases page or cloning / forking / downloading `gh-pages`.

**Comment by fortran77** [comment]
Thanks for the response, and I don't know how to interpret it. The first link you included gives me a zip archive dist-v3.6.0.zip that, like the ones I previously downloaded, doesn't extract into a unique subdirectory. In a tar archive context they call this a "tar-bomb".

**Comment by tayvano** [comment]
I was just linking the relevant files. 

Im wondering why you don't clone gh pages or use the releases page to track and download new versions?

**Comment by fortran77** [comment]
Yes I can use git clone, and I do when I need to.

You can often resolve an issue by getting the person reporting that issue to use a slightly different approach. But that doesn't necessarily negate the issue itself. I was hoping that the way I wrote this issue, it was not just about me.

Right now, people have limited choices. Windows is insecure, OS X is expensive, stable Linux (e.g., CentOS 7.x) is always out-of-date, up-to-date Linux (e.g., Ubuntu 16.x) is quite unstable. If I want to use or recommend to others a secure, reliable, and inexpensive platform that can be trusted with private keys, Chrome OS is the only one. Repackaging your archives the way I recommended will make them Chrome OS-compatible.

**Comment by tayvano** [comment]
I guess I'm just trying to figure out exactly what you want and what it solves. Cloning the repo gh pages and using git pull would allow you to have the most up to date release without any zip. 

Downloading the mercury branch so you only have the zip seems excessive when you could just download the zip to where ever you want, subdirectory or no subdirectory. Additionally, if you are downloading the mercury branch anyways there is no need for the zip as the dist folder *is* what is zipped. 

Im really not sure what you want me to *do*. As far as I know there's no way to change where a zip unzips to? On Mac it does unzip to its own folder.

**Comment by fortran77** [comment]
We get out of the zip whatever is in it. If there's a unique top-level directory in the zip, then when we extract we get that. If there is no top-level directory inside, then whether or not we get one upon extraction very much depends on whether the extraction program creates one anyway, and in many environments it doesn't. The only way to be sure that a top-level directory is created when the archive is extracted is to make sure the archive contains one.

Having a unique top-level directory inside the zip archive solves two problems: 1, We can download two different releases as zip archives, and extract them without one interfering with the other (and some people have recommended downloading an old version to withdraw DAO funds, so that is an actual use case); and 2. If I want to use or recommend to others a secure, reliable, and inexpensive platform that can be trusted with private keys, Chrome OS is the only one, and it has no provision for running git. Repackaging your archives the way I recommended will make them Chrome OS-compatible.

To make sure there's a top-level directory inside the zip, we start with a top-level directory containing our files, and we zip that. The transcript below shows the creation of a top-level directory called dist‑v3.6.0, the creation of a file README inside that directory, and the zipping of that directory. Then the transcript shows that we rm-rf that directory. When we unzip, the directory reappears, containing the README file.


    % mkdir dist‑v3.6.0
    % touch dist‑v3.6.0/README

    % zip -r dist‑v3.6.0.zip dist‑v3.6.0
    updating: dist‑v3.6.0/ (stored 0%)
    updating: dist‑v3.6.0/README (stored 0%)

    % unzip -v dist‑v3.6.0.zip
    Archive:  dist‑v3.6.0.zip
     Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
    --------  ------  ------- ---- ---------- ----- --------  ----
           0  Stored        0   0% 2017-04-05 00:43 00000000  dist‑v3.6.0/
           0  Stored        0   0% 2017-04-05 00:43 00000000  dist‑v3.6.0/README
    --------          -------  ---                            -------
           0                0   0%                            2 files

    % rm -rf dist‑v3.6.0

    % unzip dist‑v3.6.0.zip
    Archive:  dist‑v3.6.0.zip
       creating: dist‑v3.6.0/
     extracting: dist‑v3.6.0/README

**Comment by tayvano** [comment]
Wow, fuck that took me way too long for me to understand what we were going for here. #braindead 😑 🔫

Instead of zipping the dist folder, we need to zip a folder with a folder called `dist-v3.6.0` inside it. This should be.....maybe doable? Let me see what I can do. 

Sorry about that.

**Comment by fortran77** [comment]
Yes, "instead of zipping the dist folder, we need to zip a folder with a folder called dist-v3.6.0 inside it", that's what I meant, I should have been more clear. Thanks.

**Comment by tayvano** [comment]
I'm going to blame lack of sleep on this one, not you. :P
