### ISSUE TITLE
Safari 10.1 -- nodes forever balancing

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#405]
"Hi there

When I open myetherwallet on Safari 10.1using a mac 10.12.4.it says all the time loading and does not show my ether acount. Every time i delete the s on htttps it puts the s again. I also verified these points here and they work coorectly.

Verify geth is running with `geth --rpc --rpccorsdomain "null" --keystore "dont_put_secret_files_here_ever"` or parity is running with `parity --rpccorsdomain "*" --keys-path "dont_put_secret_files_here_ever"`

It used to run some 10 days ago but now not anymore.

**Comment by crptm** [comment]
This might be bignumber bug, OP should try using latest MEW version.

**Comment by tayvano** [comment]
I haven't had support requests for this in a while so I think that the bignumber fix fixed it. 👍
