### ISSUE TITLE
Newbs entering password on "Generate Wallet" when they have a hard wallet

### ISSUE THREAD

**Issue by linagee** [kvhnuke/etherwallet#410]
I've seen this referenced by someone, "Don't enter a password at the generate wallet screen if you have a hard wallet!"

Then I had a co-worker do it he was just trying to intuitively figure it out.

I had to kindly tell them "you shouldn't have done that!!!"

Can we make the instructions more Newb friendly please?

Maybe some gray text, "(If you have a Ledger or Trezor, don't generate a new wallet here.)"

**Comment by tayvano** [comment]
will be live in v3.6.4. thanks!
