### ISSUE TITLE
Regarding Integration in dapp

### ISSUE THREAD

**Issue by mariam-crissi** [kvhnuke/etherwallet#412]
I have developed a dapp using Truffle Framework.I am trying to integrate wallet for other users to pay ether in my dapp.How can i integrate the wallet in my dapp??

**Comment by tayvano** [comment]
You're going to want to encourage users to use [MetaMask](https://metamask.io/) or [Mist](https://github.com/ethereum/mist/releases). 

Dapps should not be managing keys / wallets for users. #trustless

**Comment by mariam-crissi** [comment]
Anyother way to integrate wallet interface in dapp?

**Comment by tayvano** [comment]
Instead of thinking about adding a wallet to the Dapp, think about it like adding the Dapp to the wallet. Please take a look at the links I provided. Both are trusted applications that allow users to have a wallet and interact with your dapp.

**Comment by mariam-crissi** [comment]
Okay.. Let me try using Metamask or Mist

**Comment by tayvano** [comment]
https://metamask.io/

https://github.com/ethereum/mist/releases

**Comment by mariam-crissi** [comment]
Okay ..Thankyou
