### ISSUE TITLE
Unable to print paper wallet in Chrome App on OS X

### ISSUE THREAD

**Issue by jclarkv** [kvhnuke/etherwallet#413]
Summary: In MyEtherWallet CX with Ledger Nano S attached and unlocked,  I can't print the paper wallet for external backups.

Steps to reproduce:
1. Launch MyEtherWallet CX Chrome app and choose 'My Wallets'.
2. In page that opens (showing my two wallets) I click eye icon under 'View' for either wallet.
3. I enter my wallet password successfully and see the "Viewing Wallet".  I **can** see the address and private key. I **can** download the Keystore File.
4. I click on 'Print'  under 'Print Paper Wallet'
5. A new browser window opens titled "about:blank". **No file downloads. No printer dialog is presented.**

Details:
MyEtherWallet CX v3.6.0
MacOS X 10.12.4
Chrome 57.0.2987.133 (64-bit) _with all extensions off except metamask and MyEtherWallet CX._

**Comment by crptm** [comment]
Looks like chrome CSP doesnt want to allow inline scripts from that page, we should try to white-list script hashes to see if policy gets inherited to new window.

ref https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-inline-script

**Comment by tayvano** [comment]
Just to clarify, are you trying to download your key for your Ledger? The private key shouldn't ever leave the Ledger, be accessible to the browser, or therefore be printable. I'm not sure how you are seeing a keystore file either?

**Comment by crptm** [comment]
Regardless of ledger usage, wallet printing from extension is broken in current chrome version and should be fixed.

**Comment by jclarkv** [comment]
Just trying to print a paper wallet to store remotely. Otherwise, what is the purpose of "Print a Paper Wallet"? I'm sorry if I misunderstood the purpose.

**Comment by tayvano** [comment]
@crptm I (obviously) haven't looked at it but if that's the case then yes, that is an issue worth resolving. 😬 

@jclarkv If you generate a new wallet, printing that wallet is a good way to back it up. However, if you have a Ledger Nano S, the key (24 word phrase) should be kept on the Ledger device itself, the 24 words written on the card they provide you, and that's it. It shouldn't ever touch an online computer. You could, in theory, print our a paper wallet but the key forms (single private key vs 24 word phrase / HD wallet) are simply different beasts. My question was: are you trying to print a paper wallet as a backup to your Ledger Nano S key, or a different wallet?

**Comment by tayvano** [comment]
@kvhnuke Can you take a couple seconds to look at this and see if it's a quick fix that you can knock out?

**Comment by jclarkv** [comment]
@tayvano Thank you for that explanation.  I didn't stop to think about the fact that the whole point of having the Nano S was that **IT** would manage those keys. [embarrassed]
