### ISSUE TITLE
all transactions were gone!!!

### ISSUE THREAD

**Issue by Overlok** [kvhnuke/etherwallet#418]
on testnet.etherscan.io all my transactions were gone, I transferred funds at a rate of about 0.66 ETH to the website ethtrade.org. my purse 0x9717Ac11cd65aF38Ca3be34eFF9E46434C61462d. Means haven't arrived to the recipient and after that all transactions were gone. In what the reason? Pomogiye to understand!

на testnet.etherscan.io пропали все мои транзакции, переводил средства в размере примерно 0.66 ETH на сайт ethtrade.org. мой кошелек 0x9717Ac11cd65aF38Ca3be34eFF9E46434C61462d. Средства не поступили получателю и после этого пропали все транзакции. В чем причина? Помогие разобраться!

**Comment by crptm** [comment]
I think you want to use etherscan.io not testnet.etherscan.io. Testnet is like name implies for ethereum testnet for developers. This is your transaction on mainnet https://etherscan.io/tx/0x1ce9b82286a328e6917a7d4e17ea38ddee113ee324adba8262ac29bac015ab90

**Comment by tayvano** [comment]
First, please check which node you are on vs which node your ETH is on. You should be on an ETH node, not a testnet, ropsten, or ETC node. You can switch between the two via the node switcher in the upper right corner of https://www.myetherwallet.com/

Secondly, if you did send ETH **to Ethtrade**, you need to contact them as they are the ones who have not credited your account. 

Lastly, we strongly recommend you google "ethtrade" and read user reviews. In fact, you should do this with any site you use to interact or store your cryptocurrencies. I personally would not choose to send my ETH there.
