### ISSUE TITLE
"Invalid status 6a80" when sending dgd with ledger nano s

### ISSUE THREAD

**Issue by sikaru** [kvhnuke/etherwallet#419]
i comes out when i click "generate transactionco"

**Comment by GriffGreen** [comment]
Hmmm I am also getting this error when i try to send REP. 

I can send ETH but when i try to send tokens i get the "Invalid status 6a80"

**Comment by kvhnuke** [comment]
You have to enable contract data on you ledger it is under ethereum settings

**Comment by GriffGreen** [comment]
Oh come on buddy ;-) i went thru all the advice i could find before having this issue

**Comment by kvhnuke** [comment]
Did you try doing it stranding upside down? Hehe

**Comment by kvhnuke** [comment]
You usually get it when you have contract data disabled, what else could be causing it?

**Comment by GriffGreen** [comment]
Hmmm maybe you are right! Sorry about that i was thinking about enabling the browser! I will try again tomorrow! I saw this quickly during easter dinner at the fams house... must have been under undue stress to respond like that ;-)

**Comment by sikaru** [comment]
@kvhnuke thanks!it works

**Comment by GriffGreen** [comment]
Yep enabling contract data was the secret sauce!

**Comment by kvhnuke** [comment]
C'mon @GriffGreen you should know this haha

**Comment by GriffGreen** [comment]
(How Embarrassing) 
Well now that I know how to send tokens (and I figured out how to do DASH as well... didn't bother testing BTC) I am buying 6 more ledger's using your awesome affiliate link :-D https://www.ledgerwallet.com/r/fa4b?path=/products/

The first 6 went way to fast ;-)
