### ISSUE TITLE
how to solve "Gas limit is too low" error

### ISSUE THREAD

**Issue by maraoz** [kvhnuke/etherwallet#42]
I'm getting this error when sending a tx, and have no idea how to increase the gas limit. Thanks!

**Comment by tayvano** [comment]
![screen shot 2016-06-13 at 2 44 30 pm](https://cloud.githubusercontent.com/assets/7924827/16024281/c4af2226-3175-11e6-91e4-f0fea052b9a8.jpg)

![screen shot 2016-06-13 at 2 44 35 pm](https://cloud.githubusercontent.com/assets/7924827/16024280/c4add042-3175-11e6-9d66-9e32ab7832b5.jpg)
