### ISSUE TITLE
Unintuitive switching to ETC Node

### ISSUE THREAD

**Issue by vojtacerny** [kvhnuke/etherwallet#420]
When switching to a different node ( e.g. ETH -> ETC) there's no pop-up, UI change or anything that would suggest that process was successful. Can you guys consider coming up with something? 

It could help a lot. 
Thx.

**Comment by tayvano** [comment]
@kvhnuke Please add a success notification upon node switch: "Node successfully switched to [Node name] [Node service]"

If it can't connect to the node, please show error notification instead (same as the header one)

**Comment by crptm** [comment]
We should also add some visual differentiation bw mainnet nodes and everything else while we are on it.

**Comment by tayvano** [comment]
@crptm I don't disagree. Any ideas? I was thinking maybe color coding or something the ETH \ ETC \ TESTETH variable that appears all over the site as it wouldn't be too overbearing.

**Comment by crptm** [comment]
I am not a designer :D

Was thinking about usual grouped dropdowns like:

**Mainnet**
--------

MEW
EtherScan

**Testnets**
-------

Blah
Blah

**Custom nodes**
-------

Add

**Comment by crptm** [comment]
Color coding UI is nice also, but it wouldnt work for new users as good as it would for returning ones.

**Comment by tayvano** [comment]
Would love feedback on this. I think it may need to be more obvious, but it may be just enough to give you that extra "hey wait why is there a yellow border......". Except for poor color blind people. I'll have to double-check colors and see. 

Maybe change the color of the "make transaction" button?

![screen shot 2017-04-28 at 5 03 36 am](https://cloud.githubusercontent.com/assets/7924827/25527968/2b3795a0-2bd0-11e7-908f-5fe4d06c5f19.jpg)
![screen shot 2017-04-28 at 5 03 44 am](https://cloud.githubusercontent.com/assets/7924827/25527972/2b3e111e-2bd0-11e7-8e90-d2544378b1a1.jpg)
![screen shot 2017-04-28 at 5 03 52 am](https://cloud.githubusercontent.com/assets/7924827/25527973/2b3efaa2-2bd0-11e7-8270-729537aa82ac.jpg)
![screen shot 2017-04-28 at 5 04 01 am](https://cloud.githubusercontent.com/assets/7924827/25527971/2b3c05cc-2bd0-11e7-8e72-72b981431bf1.jpg)
![screen shot 2017-04-28 at 5 04 07 am](https://cloud.githubusercontent.com/assets/7924827/25527970/2b3ba49c-2bd0-11e7-8364-77dec0a5bcfc.jpg)
![screen shot 2017-04-28 at 5 04 13 am](https://cloud.githubusercontent.com/assets/7924827/25527969/2b3b95d8-2bd0-11e7-948d-0032f1f89f21.jpg)

meh, I don't know. I don't expect people to understand the correlation, I just want people to take the extra 200ms to pause before sending something they don't usually send / want to send.....

**Comment by tayvano** [comment]
Calling this done. If anyone has any feedback or thinks it needs to be even more obvious, let me know.
