### ISSUE TITLE
MyEtherWallet sets invalid gas value, causes transactions to be rejected

### ISSUE THREAD

**Issue by miohtama** [kvhnuke/etherwallet#422]
MyEtherWallet sets an bad value to *Gas* field.

Steps to reproduce

- Send Ether & Token

- For address enter 0x3cd4351f3c962f871024efef2922ae39896e4761

- For gas enter 250000

- For data enter 0xa6f2ae3a

- Tab out from the data field

Expected result:

The transaction is send with a gas of 250000.

Actual outcome:

MyEtherWallet estimates the gas limit, but this estimation may still be wrong, overriding the given good value.

![myetherwallet-bug](https://cloud.githubusercontent.com/assets/49922/25074489/6acb7a08-2304-11e7-8e5f-0f62f2da5c9a.gif)

(Note: In the recorded example it sets the gas limit to a very high value, but sometimes this seems to be too low)

**Comment by kvhnuke** [comment]
Enter the data first then set the gas value, when you enter the data it tries to automatically calculate the estimated value.

**Comment by miohtama** [comment]
Yes. The current user interface logic is counter-intuitive, as we have instructed our users to enter the gas limit manually. They fill in the gas limit first and do not notice that the gas limit automatically changes, as they proceed to the data field that is next on the form.

My suggestions are

* Do not estimate the gas if the gas value field has been filled in by the user

* Fix the gas estimation (I do not know how it gets the value low  as  21700, because the actual value is in 200k range)

**Comment by kvhnuke** [comment]
it is not properly estimating because 0x381be84a2364f1a5e4b8df5c42e21b4853dae1f8 address is not a contract, https://etherscan.io/address/0x381be84a2364f1a5e4b8df5c42e21b4853dae1f8 and therefore data field is just considered as embedded data in the tx not a contract vm execution, please use the correct contract address

**Comment by miohtama** [comment]
@kvhnuke Had a copy paste error in the testing, updated the recording

**Comment by miohtama** [comment]
Looks like there is something else involved. Closing this for now. My fault.

**Comment by mrbrdo** [comment]
This is still an issue on the online version, it just happened to me (and kinda screwed me a bit).
For me it reduced the gas limit (I input 300000 and it reduced it to something like 20000, causing my TX to run out of gas and be reverted). I input the gas limit manually and AFTER entering the amount. The gas limit changed when I clicked Generate Transaction just like in the gif above.

**Comment by tayvano** [comment]
It is going to re-estimate your gas when you add data or change the value of the transaction. 

If you want to manually increase the gas, do so *last*.

**Comment by miohtama** [comment]
@tayvano Yes, that's how people should do it, as the last step as you mention.

However the current user interface is little confusing here because fields are in a wrong order for this workflow and it is easy for an average user to miss this, unless they have been noted about this behavior beforehand.

**Comment by tayvano** [comment]
Perhaps the folks who just raised 12M have a bit of extra time to write a line of code to fix it. Would have been nice if they had done it beforehand. Or not used a contract that didn't estimate correctly. Or maybe just shot us a note when they were making the tutorials. 

Nah. 

We'll just leave it and then blame MEW and roll around in our piles of money. 

Whatever. I'll push a update tonight for the next greedfest.

**Comment by mrbrdo** [comment]
Let's not get emotional :) My thoughts are that if the user fills the gas limit it shouldn't reset to something else, since he probably filled it with a reason (no matter of order of filling the fields). Also if memory serves right, the field updated for me after clicking generate transaction, which isn't that great either. To me it looked like it is not possible to use the gas limit I specified and I have no other option than to accept the new value. For me the best solution would be a prompt to confirm the "too high" gas limit upon clicking generate transaction.
Also of course we appreciate the work you guys are doing for free and I think etherwallet is a really cool project and I happily use it as my main wallet.

**Comment by miohtama** [comment]
@tayvano Good answer! :)

**Comment by miohtama** [comment]
Am I correct: Ultimately the estimator is in Geth/Parity and has to be fixed on little bit lower level?

**Comment by tayvano** [comment]
@mrbrdo Feel free to open a PR. This is exactly what I have on the todo list as a temp solution. We are trying to get ENS laucnhed. 

@miohtama Supposedly geth is better as they are literally brute forcing gas limits. Parity can have problems when there are multiple layers or something. 

Here's some interesting numbers for you:

**Here are their relative block number (first tx=0, last success=112) & block number for 94848 gas:**

33 3638498
40 3638505
46 3638511
46 3638511
47 3638512
50 3638515
50 3638515
60 3638525
60 3638525
60 3638525
60 3638525
61 3638526
63 3638528
75 3638540
75 3638540
77 3638542
78 3638543
80 3638545
80 3638545
82 3638547
82 3638547
87 3638552
87 3638552
94 3638559
94 3638559
94 3638559
97 3638562
105 3638570
107 3638572
110 3638575
110 3638575
113 3638578 - unsuccessful
113 3638578 - unsuccessful
115 3638580 - unsuccessful
115 3638580 - unsuccessful
141 3638606 - unsuccessful
144 3638609 - unsuccessful
162 3638627 - unsuccessful
162 3638627 - unsuccessful


**Here are their relative block number (first tx=0, last success=112) & block number for 100000 gas (100% unsuccessful):**

3 3638468 - unsuccessful
5 3638470 - unsuccessful
7 3638472 - unsuccessful
8 3638473 - unsuccessful
8 3638473 - unsuccessful
8 3638473 - unsuccessful
8 3638473 - unsuccessful
8 3638473 - unsuccessful
8 3638473 - unsuccessful
10 3638475 - unsuccessful
10 3638475 - unsuccessful
10 3638475 - unsuccessful
10 3638475 - unsuccessful
10 3638475 - unsuccessful
11 3638476 - unsuccessful
11 3638476 - unsuccessful
11 3638476 - unsuccessful
11 3638476 - unsuccessful
13 3638478 - unsuccessful
13 3638478 - unsuccessful
13 3638478 - unsuccessful
13 3638478 - unsuccessful
13 3638478 - unsuccessful
19 3638484 - unsuccessful
19 3638484 - unsuccessful
19 3638484 - unsuccessful
19 3638484 - unsuccessful
22 3638487 - unsuccessful
22 3638487 - unsuccessful
22 3638487 - unsuccessful
22 3638487 - unsuccessful
27 3638492 - unsuccessful
36 3638501 - unsuccessful
40 3638505 - unsuccessful
41 3638506 - unsuccessful
41 3638506 - unsuccessful
45 3638510 - unsuccessful
45 3638510 - unsuccessful
45 3638510 - unsuccessful
48 3638513 - unsuccessful
52 3638517 - unsuccessful
56 3638521 - unsuccessful
62 3638527 - unsuccessful
62 3638527 - unsuccessful
65 3638530 - unsuccessful
80 3638545 - unsuccessful
87 3638552 - unsuccessful
88 3638553 - unsuccessful
88 3638553 - unsuccessful
100 3638565 - unsuccessful
100 3638565 - unsuccessful
102 3638567 - unsuccessful

So tell me: why does 94.... work but 100k does not?
