### ISSUE TITLE
Trying to send GNT to my Ledger Nano S -- insufficient funds?

### ISSUE THREAD

**Issue by ckcollab** [kvhnuke/etherwallet#423]
First of all... thanks for this project! Really appreciate all the hard work.

I'm trying to send .99 GNT to my Poloniex deposit address. Everything seems fine, Gas gets set to ~56000 (I guess that's good?)  and I confirm the transaction on my Nano. However, I get this message:

![image](https://cloud.githubusercontent.com/assets/2185159/25098595/0b207eaa-235e-11e7-8e9a-03a4315649ea.png)

(For people googling in the future: *Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1134400000000000 and got: 0.*)

Is it maybe trying to send ETH instead of GNT? That's why it says I have 0? Could just be rounding my 0.9 GNT to 0, though?

Again, thanks for this project and all the hard work! Receiving GNT worked great.

**Comment by tayvano** [comment]
This means you do not have enough Ether in your account to cover the cost of gas. Each transaction (including token and contract transactions) require gas and that gas is paid in Ether. You can think of this like a transaction fee.

A standard TX will be 21000 gas & a gas price of 0.00000002 ETH so the total TX fee will be 0.00042 Ether. With tokens, the amount of gas is typically 50000 gas - 100000 gas, so the total TX fee increases to 0.001 ETH - 0.002 ETH.

The number displayed in that error message is the amount required to cover the cost of the transaction in Wei. Take that number, divide by 1000000000000000000. This will give you the amount of Ether you need to send to that account to make the transaction.

So sending GNT (any amount of GNT) will cost you 0.0011344 ETH in gas.

**Comment by ckcollab** [comment]
Thank ya! 

> *Take that number, divide by 1000000000000000000.*

That... seems weird, but cool, ok, thanks :)

**Comment by tayvano** [comment]
LOL - tell me about it. Unfortunately, that's an error from the client itself, not ours. Basically everything you do is actually calculated in Wei, not ETH. So you are essentially converting WEI -> ETH when you do that division. You can get a better idea of what you are doing with this tool: http://ether.fund/tool/converter
