### ISSUE TITLE
changed the number of the purse

### ISSUE THREAD

**Issue by VadimIsk** [kvhnuke/etherwallet#427]
Good day! I have the same situation. Created wallet. Copied account. Translated ETH . the money came partner gave the report. Go to your wallet there is no money and the score changed . The first time I created a wallet. Technical support is silent after clarifying the problem . Please help to return the money.

**Comment by tayvano** [comment]
@vadimlsk we have had an inordinate amount of folks from Russia \ Ukraine report similar issues which makes us believe that there is a service or phishing site right now. Unfortunately we have not been able to get necessary information like who or where this site is. 

Please go back through your history and show me the URL of the site you created your wallet on.

**Comment by VadimIsk** [comment]
my correspondence with technical support:

Good afternoon!

I created a purse at www.myetherwallet.com
On this site I copied the address 
And on this account sent the etherium
Now I open a purse, and he issues another account, but there is no money.

How can this be? Why my current account was changed?
Why my checking account has changed?

Суббота, 8 апреля 2017, 22:46 +05:00 от "Taylor @ MyEtherWallet.com" <support@myetherwallet.com>:


Hi Вадим, 

Can you do me a favor and walk me through how you generated the wallet?

1. Have you ever used MyEtherWallet to generate a wallet before the one in question? Did you generate multiple wallets?

2. What browser you were using? What OS are you on?

3. What day did you generate it?

4. Were you on MyEtherWallet.com or did you download the repo?

5. What versions of the private key did you save? Did you happen to save multiple versions? (e.g. Keystore file, private key, json file, paper wallet, QR code?)

6. What version of the private key are you using to access your wallet today?

We take reports of mismatched account information very seriously and do our best to determine what the cause of the issue is, so the more information you can provide, the better.

Thank you 
---

Taylor @ MyEtherWallet
Co-Founder & Answerer of Questions
MyEtherWallet.com • Chrome Extension
support@myetherwallet.com • Knowledge Base • Help Page
Slack • Github • Twitter •  Facebook
  
Вадим Искандаров on April 8, 2017 at 4:51am wrote:


Воскресенье, 9 апреля 2017, 16:58 +05:00 от Вадим Искандаров <vadimplus@list.ru>:

Good day
I will answer all questions. I will send the entire file. There is no money in the wallet..
1. First time. I created one purse.
2. Microsoft Edge 38.14393.0.0 Microsoft EdgeHTML 14.14393 Windows 10
3. I created the file attached to the application 06/04/2017
4. MyEtherWallet.com
5. All the files I attached to the letter everything that I saved
6. Work: "File Keystore (UTC / JSON)", "Private key" files are attached to the letter. More than that has not kept
I saved the purse account. When I made the transfer, I was shocked that the bill did not match my wallet.

**Comment by VadimIsk** [comment]
0x8c3b845CB261B3B6942398b112969058C7BE2FDC now the real account address

**Comment by kvhnuke** [comment]
Hi @vadimlsk can you please browse through your browser history to the day you generated the wallet and send us the link, we are pretty confident that there is a phishing site targeting users from Russia.

**Comment by VadimIsk** [comment]
If this is a phishing site, how can it give the keys, the file for access, the public key to the correct wallet. Left sites create that to take money, but the money lies there, and they will lie there because "no access" is not available to anyone. The address of the wallet simply can not be invented, there is no confirmation that the account belongs to my wallet. My wallet created the address (1), and then he changed it (2). The wallet opens the address (2). I will look at the history later. 06/03/17 created

**Comment by tayvano** [comment]
We do not know. Of all the reports we have received, NO ONE has managed to get us their actual history or provide additional information. 

Once we FIND the site that is causing these issues we can figure out what they are doing, how they are doing it, if there is a way to recover anything, and get their ass taken the fuck down to prevent this from happening anymore. 

So please, look at your actual history extremely carefully. Provide a screenshot.

**Comment by VadimIsk** [comment]
![4](https://cloud.githubusercontent.com/assets/27778614/25243969/5cf88a8a-2618-11e7-9196-f49bea1e57e8.png)
![1](https://cloud.githubusercontent.com/assets/27778614/25243971/5cf957e4-2618-11e7-8023-f39f1cccfdb5.png)
![2](https://cloud.githubusercontent.com/assets/27778614/25243972/5cfb07ce-2618-11e7-8ddc-3d6682ba5e8a.png)
![3](https://cloud.githubusercontent.com/assets/27778614/25243970/5cf9a636-2618-11e7-8c65-1466931ae5a8.png)

**Comment by VadimIsk** [comment]
all that is

**Comment by crptm** [comment]
@VadimIsk are you sure you saved private key the first time you generated the address?

**Comment by VadimIsk** [comment]
Yes of course and key with password and public key. alarming me the address, eth.pp.ru  I didn't go in it

**Comment by VadimIsk** [comment]
make a screenshot of the files in the keys folder the download later

**Comment by VadimIsk** [comment]
when I created the wallet. the site was like this. the account was copied and sent for payment. and I haven't checked my account (number) wallet as he changed I didn't notice

**Comment by VadimIsk** [comment]
![7](https://cloud.githubusercontent.com/assets/27778614/25497852/4e55d4ba-2b9f-11e7-9e80-4a0cb1aed821.png)
this is some nonsense

**Comment by tayvano** [comment]
I'm even more confused: that screenshot is NOT MyEtherWallet.com - it is Etheruem Wallet. 

**Where** did you generate the wallet?

**Comment by VadimIsk** [comment]
I did the import

**Comment by VadimIsk** [comment]
I made one purse two Keystore File (UTC / JSON). First correctly determined.  The second does not accept

**Comment by tayvano** [comment]
If it does not unlock it is because your password is incorrect.

**Comment by VadimIsk** [comment]
created     Illusory wealth   :-(((

**Comment by tayvano** [comment]
There is a new tool at the very bottom that could prove useful for anyone who hand-typed or wrote their private key: https://www.myetherwallet.com/helpers.html

Enter the address you sent to and the private key you saved and see if it can find it

**Comment by VadimIsk** [comment]
using this site, I tried ways to restore access to the address.
attempts were useless
a freelancer help in this matter?
