### ISSUE TITLE
When signing a message make the date optional, keep it empty when it is empty.

### ISSUE THREAD

**Issue by stefek99** [kvhnuke/etherwallet#436]
In the project I've been working on, we've forked MEW.

I've implemented a few customisations here and there.

Then I proceed to testing the **Sign Message** feature:

![image](https://cloud.githubusercontent.com/assets/249703/25520614/6c1c4fd8-2bf4-11e7-85a3-f444bf3dce0e.png)

I want to sign my email: `email@genesis.re`

Unfortunately the generated message (and subsequent signature) assumes: `email@genesis.re | `

My suggestion is to **make date optional** - so that if there is no date - it will create a signature of `email@genesis.re`

_(legitimate use case of proving ownership of the private key associated with an email)_

Alternatively, if that poses a security risk we can display a popup: 

> Date is recommended, are you sure...

---

Feedback from my boss:

> we will NOT support every wallet's proprietary signing feature

> it is really bad if everybody implements their own way of message signing

> reporting this as a bug, makes sense

---

It should be simple change in the code here: https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/signMsgCtrl.js#L24

**Comment by tayvano** [comment]
1. I wasn't aware there was a formal signing message spec. Can you please direct me?

1b. If you give users the opportunity to do something insecure, they will do it every time. While I agree that a date isn't necessary for every message, it would have prevented a number of scams, including the clusterfuck that was 'i am Satoshi here is a message'. I would recommend you keep that in mind when building anything. Users can do stupid shit, but usually you have the ability to do things to prevent it. 

2. Please let your boss know that we don't expect anyone to support anything, we aren't aware of many signing features beyond metamasks much more involved signing, which we will be using in mew v4, and that opening a PR with your fix would be much more productive and get what you want accomplished more quickly than reporting this as a bug. 

3. I think the best solution is to provide a better *out* version of the message. Its on the to-do list somewhere, but what prints out should be more similar to a pgp signed message, including a copy of the message you just signed with existing line breaks to ensure readability 

4. I think the easiest solution would be to just remove the fucking pipe. I'm not sure why it's there to begin with, why it doesn't disappear if there is no date. I'm fairly certain we don't make the date mandatory, but this also isn't a very widely used feature, nor one we get much feedback on so who knows. 

Honestly, I would pull just about anything in related to this feature. We don't have many opinions on what it should be. 

(From mobile. Sorry if typos)

**Comment by stefek99** [comment]
> just remove the fucking pipe

Sorry if typos too 😎

I edited source of the page directly using Chrome Dev Tools: http://stackoverflow.com/a/43631130/775359

>  I would pull just about anything

Pull in the context of Github usually means "Pull request" - is that what you mean?

> If you give users the opportunity to do something insecure

That's why:

> if that poses a security risk we can display a popup

Boom!
