### ISSUE TITLE
No response from support@myetherwallet.com

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#437]
Please answer for dtyz8@ukr.net about https://www.myetherwallet.com/#swap

**Comment by tayvano** [comment]
Both myself AND Bity have responded to you. Perhaps you need to check your email?

You sent ETC, not ETH. You can only Swap ETH as the system does not support ETC.

**Comment by ghost** [comment]
Is there an opportunity to return the ETC back?

**Comment by Guy-Leumi** [comment]
Hello,
I used Bity from myEtherwallet to swap ETH to BTC, the transaction is displaying complete
but I haven't received the BTC in my account and I still can see the pending transaction.

Please can someone have a look.

Regards
G
