### ISSUE TITLE
After transaction the amount of ETH visible on the screen should decrease?

### ISSUE THREAD

**Issue by stefek99** [kvhnuke/etherwallet#44]
I'm totally new to the scene, I decided to participate in the DAO hype and I would like to report some issues.
## 1 minute screencast: https://youtu.be/EhZWClglYIs

So I'm logged in and I confirm the transaction. The account balance in the upper left corner remains the same. It was confusing... Everywhere _(bank, PayPal, exchanges, other BTC wallets)_ after confirming transaction the balance should go down.

Luckily I was able to verify it: https://www.etherchain.org/tx/0x77562db0ca3c757d9d64c9eba7100756f5cd95d2cad30c6e3bfeb3c1539a1201

And check if DAO tokens were created: https://daohub.org/creation.html

![image](https://cloud.githubusercontent.com/assets/249703/15313982/f70456bc-1c06-11e6-96a0-2c8cc0875ee9.png)

---

Second issue related to that... Last night I did exactly the same process, transferring ETH to DAO address and... Nothing happened, only my balance decreased from **9.50** into **9.494118** - I have no idea why, as if some network fees were paid but no transfer was initiated...

_(that was last night, now we have 08:14am UK time and basically I'm a little bit confused / unsure so reporting the stuff so you can investigate)_

**Comment by tayvano** [comment]
> 9.50 into 9.494118 

That is because it used gas because you weren't actually able to send the tokens but it executed a bit of the contract before it errored out. You should be able to send now though.
