### ISSUE TITLE
estimateGas() for SWT is smokin' dope... or just very optimistic

### ISSUE THREAD

**Issue by GriffGreen** [kvhnuke/etherwallet#445]
The value I am getting is 25652

The Value needed is: 90972 for an account that has tokens already or 128167 for an account that has never received before.... so maybe over estimate with a 95k and 135k?

It's one of those stupid "MiniMe" tokens... 🙄  Unfortunately Aragon is going to use it too so might as well get this estimate gas thing working 🙄 

Oh and have I told you, lately, that I love you? ❤️

**Comment by tayvano** [comment]
Can you send us the address + recommended gas + ??? info so we can have it manually fill in the gas for those token addresses and not try to deal with it / estimate? It'll also reduce the # of calls to our server which saves us like 0.001 cent which doesn't matter until you get 1m requests / day.

You'll have to ask @kvhnuke what we are using for estimating gas that's failing so bad. Obviously not what everyone else is using. 

ilu2 💖 💖 💖 Are you coming here soon or are you already gone? Also, do you have a mewify error / bug list? We're looking to launch that next week but I can't find me todo list. 🙄

**Comment by GriffGreen** [comment]
hahahahah
Yeah the big todo list on Mewify is to make it not block me from using your node every time i turn it on!!!

I am still waiting on info from my lawyer, but i bet i make it down there in the next 6 days :-D

**Comment by GriffGreen** [comment]
token address: 0xb9e7f8568e08d5659f5d29c4997173d84cdf2607

Recommended gas depends on if the account has sent tokens or not: 
90972 for an account that has tokens already or 
128167 for an account that has never received before

Or to keep it simple, recommended gas 128167 + 10,000

:-D

Much love and see you soon!
;-)

**Comment by tayvano** [comment]
Okay I'll see if we can manually set it for now. Thanks  . Kvhnuke says it'll be better when we finish migration to geth after ens.

**Comment by tayvano** [comment]
@kvhnuke was this updated in the latest round?
