### ISSUE TITLE
How Do I Generate Keystore File (UTC / JSON)

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#449]
Hi - I love your service but I don't like having to cut/paste my private key whenever I want to use the UI. I can't figure out how to generate a Keystore File (UTC / JSON) from my private key. Do you have any guidance?

Thanks

**Comment by tayvano** [comment]
You can encrypt your private key by using our Chrome Extension, or importing your raw private key into geth.

**Chrome Extension**

- [Download and install our Chrome Extension](https://chrome.google.com/webstore/detail/myetherwallet-cx/nlbmnnijcnlegkjjpcfjclmcfggfefdm?hl=en): 

- Add a new wallet using your private key, enter a password, and save this wallet.
- Go to the "My Wallets" section and click the view icon.
- It will ask you for the password you just created. Enter it.
- More information regarding your account will show up below. You will be able to download the keystore file (encrypted) and use that + the password you just created to access your wallet in the future. 

You can choose to continue to use the Chrome Extension or go back to using the website. 

**Geth**
- [Instructions for Mac, PCs, and LInux can be found here](ethereum.stackexchange.com/questions/465/how-to-import-a-plain-private-key-into-geth-or-mist)

**Comment by ghost** [comment]
That worked, but I have to say that it felt very confusing from a UI perspective. First, having to click My Wallet in order to interact with it was not intuitive. Then, being bounced out to a browser window from within the extension felt odd and insecure. Finally I don't get why the download keystore UI only appears if launched from the extension. Food for thought!  Maybe I'll hack on this and submit a PR. :) Keep up the good work.

**Comment by hendynicholas** [comment]
i don't considerate my utc file.. i only can save my keystore in excel file.. how to get back utc file from excel file?

**Comment by cozza28kipa** [comment]
This is very confusing and im in the same boat with this problem!

**Comment by suyash644** [comment]
i need to generate a keystroke file when creating new wallet can anyone help me to code for this??
