### ISSUE TITLE
Transaction Error 

### ISSUE THREAD

**Issue by bitcometrader** [kvhnuke/etherwallet#45]
Trying to send some ETH from my account to another with ERROR MASSAGE :"was an error: no contract code at given address". 
Tried different addresses even the ETH donation address. 
Any ideas ?

**Comment by tayvano** [comment]
@bitcometrader Is this occurring on the Send Transaction page?

**Comment by bitcometrader** [comment]
Yes

**Comment by tayvano** [comment]
@bitcometrader Thank you -- looking into it right now. Sit tight.

**Comment by bitcometrader** [comment]
Thanks

**Comment by tayvano** [comment]
@bitcometrader What's your address you are trying to send from & to? I just had a transaction send successfully. It may be that our node is out of sync though?

**Comment by bitcometrader** [comment]
Hi Tayvano my address is : 0x60d90480e1973a186eb130e4cb3ff1bbec121b6b

**Comment by apobekiaris** [comment]
same error for me i try to send from 0xDE46B294cFF3dFdc3c09cAc26f6Ef348bCDDc993 to 0x797ff39aed3484bf2aa7e85a615a8157354a2488. In the past I was able to make that transaction with no issues

**Comment by tayvano** [comment]
Hi. We just pushed some updates. Can you try again and let me know if you are still seeing the error? Thank you!

**Comment by bitcometrader** [comment]
It is working now, thanks for the wallet its a good extension for chrome.
