### ISSUE TITLE
ENS clock wrong

### ISSUE THREAD

**Issue by rmerom** [kvhnuke/etherwallet#453]
Local time is 2017-05-07 11:38AM PDT
See image below:
![image](https://cloud.githubusercontent.com/assets/650968/25783947/aab9c8d4-3319-11e7-9ebc-2e30ff46d057.png)

The countdown clock is wrong (4 days from now would already be May 11).

**Comment by rmerom** [comment]
My mistake, now I understand the clock is until the whole auction ends? 
It might make sense to reconsider what the countdown is showing (users are likely interested when they can bid/reveal more than when someone wins, but I may be wrong of course)

**Comment by tayvano** [comment]
You are correct. I've updated the UI in v 3.7.0, and am continuing to make updates to make this all more obvious / clear.
