### ISSUE TITLE
Please save my Ether on MEW/ENS

### ISSUE THREAD

**Issue by linagee** [kvhnuke/etherwallet#455]
Please save my $0.07 of Ether on ENS. (And everyone else's 7 cents.) Could you just check to see if there is already a winning bid and warn the user that revealing their bid would be a waste of 7 cents for a transaction as there's already a higher bid out there? I just revealed several bids, then realized this afterward.

**Comment by linagee** [comment]
Also note: This only applies to the minimum bid of 0.1 ETH, I think you'd want to execute a reveal no matter what if you bid more, in order to get your money back. (But I'm not sure on that.)

**Comment by tayvano** [comment]
@Arachnid Would love your insights on this one...

@kvhnuke Do you know what is possible / not possible?

**Comment by linagee** [comment]
Please disregard. I have consulted people who know more than I know on ENS. You'll always want to reveal, even if you only had 0.1 ETH in the game and it costs you 7 cents.
