### ISSUE TITLE
ENS Already Owned By 0x0::0

### ISSUE THREAD

**Issue by MysticRyuujin** [kvhnuke/etherwallet#459]
This is what i'm seeing on MEW right now when trying to finalize my winning bid:

{DOMAIN}.eth is not available. It's already owned by 0x0000000000000000000000000000000000000000.
If you are the winner, you must finalize the auction to claim the name.

Mist browser shows my address as the winner.

**Comment by MysticRyuujin** [comment]
I should note that trying to finalize anyway results in:
Unlocked wallet doesn't match the owner address

**Comment by tayvano** [comment]
This was fixed about 19 Horus ago. Please let me know if still experiencing issues.

**Comment by tayvano** [comment]
10 hours*
