### ISSUE TITLE
the money did not come

### ISSUE THREAD

**Issue by ByJIbqp** [kvhnuke/etherwallet#46]
Good day, I transferred the money to the purse which sgeniriroval on your site, but money is not credited to him, tell me what is the reason, or they will soon be on the balance sheet?

**Comment by tayvano** [comment]
What is you address? Please check on http://etherscan.io/ -- we seem to be having intermintent issues with the balances displaying on myetherwallet.com.

We are trying to fix it, but http://etherscan.io/ will always show your correct balance
