### ISSUE TITLE
Swap order of Ether to Bitcoin got cancelled but my ether were not returned to my wallet

### ISSUE THREAD

**Issue by kalyanmeduri** [kvhnuke/etherwallet#461]
![1](https://cloud.githubusercontent.com/assets/13646701/25896775/d4f4063c-3585-11e7-93cf-a6905c65e1d1.jpg)
![2](https://cloud.githubusercontent.com/assets/13646701/25896776/d4f8d950-3585-11e7-8065-d3076e9e7e0c.jpg)

Pl help me complete the order to my paymium bitcoin wallet or else return my ether to my ethereum wallet. Thanks

**Comment by tayvano** [comment]
See that blue link below the thing that says "Issue with your Swap?"

Click it & press send.

**Comment by kalyanmeduri** [comment]
Wow that was express response thanks a ton. Done as suggested and awaiting support :)

**Comment by kalyanmeduri** [comment]
Please include the below if this issue is regarding your order.

REF ID#: BITYPKBRV2

Amount to send: 2.29000000 ETH

Amount to receive: 0.11556943 BTC

Payment Address: 0xef1f30ef93fb0058628f6bed5cfd8d98148efac0

Rate: 0.050628 ETH/BTC

<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by vvvmfu** [comment]
what is the finish of that history? I have the same problem

**Comment by vangugus** [comment]
I have the same problem :/

**Comment by vangugus** [comment]
Hello kalyanmeduri !
Were you able to find your ETH? Or have you finally received your BTC?

**Comment by tayvano** [comment]
GUYS CLICK THE ORANGE BUTTON AT THE BOTTOM OFTHE PAGE. SERIOUSLY.

Commenting here, or anywhere else for that matter does NOT put you in the queue to get it manually processed.

**Comment by vangugus** [comment]
Ok

Thank you

2017-06-17 19:51 GMT+02:00 Taylor Monahan <notifications@github.com>:

**Comment by kalyanmeduri** [comment]
Yes thank you.


<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*
