### ISSUE TITLE
Suggestion to not store Zip distribution binaries in the Git source control

### ISSUE THREAD

**Issue by jyap808** [kvhnuke/etherwallet#462]
This would make the repository smaller.

I purged some old Zips and rough numbers are the repo download went from 500 MB to 150 MB. Cleaned repo:
https://github.com/ubiq/pyruswallet

Suggest utilizing Github's Releases page:
https://github.com/kvhnuke/etherwallet/releases

**Comment by tayvano** [comment]
Yeah Im usually better at purging them. If you are cloning down, I recommend ignoring them so you don't ever have to dl future ones. At some point Travis will auto post with hashes to releases and we can just stop this process entirely. 

If you are just downloading \ cloning for local use, I recommend the gh-pages branch. Much smaller and you won't occasionally get a broken dev state like Mercury.

**Comment by jyap808** [comment]
It's kinda tricky but you actually need to re-write the repo history using something like this:
https://rtyley.github.io/bfg-repo-cleaner/

It's suggested to use a new repo but moving forward I'd suggest not committing binaries as it just continues to bloat the repo.

**Comment by tayvano** [comment]
I'll strip zips once we are no longer relying on this repo.

**Comment by jyap808** [comment]
Nice one @tayvano
