### ISSUE TITLE
ENS Reveal Transaction OOG Error

### ISSUE THREAD

**Issue by mattdf** [kvhnuke/etherwallet#464]
MEW allocated 90k gas when doing a reveal but that wasn't enough and I had to send a raw data tx with over 100k gas to actually get the reveal to go through.

See: https://etherchain.org/tx/0x7af3b69fde4c50112e8c32ad5d2033de5532b2bec4d9a1bde011ceb5fe07ade0

Total gas required seems to be over 90k, though after gas storage "refund" it's below 90k in "cost".

**Comment by tayvano** [comment]
@mattdf already pushed a fix for this. thats what i get for not testing numerous styles of reveals while trying to save ya'll some money

**Comment by stpaxoliydina66** [comment]
The wallet does not work. Recipient's address ..... amount to send ........ gas limit 21000 to form a transaction ......... send a deal ????????? The send button does not work.

**Comment by tayvano** [comment]
@stpaxoliydina66 Is this related to the ENS reveal saying "Out of Gas". 

If not, please open a new issue. Thank you.
