### ISSUE TITLE
Please help can not get into the wallet

### ISSUE THREAD

**Issue by arambala** [kvhnuke/etherwallet#467]
Hello! There were problems with the entrance to the purse, there Keystore File UTC came in repeatedly, now I enter the password and wrote that it is not true. Help to understand the problem, wrote in support, but so far in response to silence.

**Comment by arambala** [comment]
up

**Comment by arambala** [comment]
I understand that you probably will not help me, maybe your customers have already faced this and somehow solved this problem, I will be grateful, I have a programming experience, I'm noob

**Comment by tayvano** [comment]
Please enter your correct password or, if you saved the private key or paper wallet, try that.

We do not save, store, or transmit any sensitive information like your private key or password. We cannot recover or reset anything.

**Comment by tayvano** [comment]
Please reach out to support@myetherwallet.com if you need anymore help.
