### ISSUE TITLE
Contract functions don't update on contract tab

### ISSUE THREAD

**Issue by GriffGreen** [kvhnuke/etherwallet#469]
<img width="423" alt="screen shot 2017-05-16 at 4 51 45 pm" src="https://cloud.githubusercontent.com/assets/14945613/26133289/da546188-3a5a-11e7-94ea-40e3ade148ec.png">
This is a silly issue and super low priority

But check out the screen shot, and see that when I change the from using the ENS-Registry to using the ENS-Public Resolver the old function lingers.

Love this site, it is a life saver always.

Much Love, 
Griff

**Comment by kvhnuke** [comment]
you have to click "Access" @GriffGreen

**Comment by tayvano** [comment]
@GriffGreen fixed also need you to check eos on contracts page 💖
