### ISSUE TITLE
Has made an exchange and has not received bitcoin

### ISSUE THREAD

**Issue by Dmitry7na7** [kvhnuke/etherwallet#470]
Please help me to understand the exchange of eth / btc
I made an exchange, but I did not have enough for the commission, but still the transfer was made, later I sent more than needed to the commission and did not get my bitcoin. What to do ? help me please

**Comment by tayvano** [comment]
If you need help with a swap you need to go to https://www.myetherwallet.com/#swap and click the "Issue with your Swap? Contact support." button.
