### ISSUE TITLE
No "ENS" tab on local build?

### ISSUE THREAD

**Issue by cosmicscr** [kvhnuke/etherwallet#472]
Hi MEW people!

I built the latest MEW locally (v3.8.0) and it has no "ENS" tab.  Why is that?

I built on the mercury branch according to instructions:

`git pull`
`npm install`
`node ./node_modules/gulp/bin/gulp.js`
`node ./node_modules/gulp/bin/gulp.js clean`

The site says "v3.8.0" but it has no "ENS" tab.

Thanks for any help.

**Comment by kvhnuke** [comment]
ENS tab is only available if your node type is ETH, can you make sure you are on an ETH node

**Comment by cosmicscr** [comment]
Okay.  Why wouldn't the ENS tab work with or be compatible with a local custom Ethereum node?  Why does MEW force ENS queries to go through the trusted MEW node?

**Comment by kvhnuke** [comment]
Make sure your custom node type is ETH

**Comment by kvhnuke** [comment]
Let me know if it is ETH and still doesn't show up, I'll take a look

**Comment by cosmicscr** [comment]
I'm not sure I understand.  My custom node is a parity Ethereum node which I've named "parity" locally.  What do you mean by ETH?  Isn't this just an Ethereum wallet?  Parity is ETH no?

**Comment by kvhnuke** [comment]
interesting let me look into it mean time if you add #ens you can access the tab
https://localhost/mew/#ens

**Comment by cosmicscr** [comment]
One thing that might help:  after naming my custom node "parity" it's now listed in MEW as precisely "parity:eth".  Maybe it's an upper/lower case condition somewhere?  And also I created that on a slightly older version of MEW.  Also, #ens in the path works!  thx.

**Comment by kvhnuke** [comment]
No it was an issue in the code gosh it took me way too long to figure it out. haha it is fixed in the latest commit, please do a git pull and you dont have to type in #ens :)

**Comment by cosmicscr** [comment]
Okay cool.  I just confirmed it works.  Thanks a lot!
