### ISSUE TITLE
Notifications are janky and don't always stay up

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#473]
"When finalizing an ENS, about 25% of the time the orange bar shows up for less than 1 second and then disappears... 75% of the time it works fine... but 100% of the time the tx actually goes thru :-D"

**Comment by tayvano** [comment]
I've had this happen on reveal as well once or twice....was moving very fast though. Reveal is because we clear the notif for gas or something

**Comment by tayvano** [comment]
Now they stay up but the old one disappears. Someone please help. :( :( :(

**Comment by jackcasey** [comment]
Did you manage to test the ENS notifications? Is this issue solved?

**Comment by jackcasey** [comment]
@tayvano I know you're busy, but is this issue solved by #591 ? If not I can have another crack at it.

**Comment by tayvano** [comment]
@jackcasey I havent had any issues with it lately nor received reports so lets call it fixed. Have you? Do I owe you some ETH? I think I do!

https://etherscan.io/tx/0xadb8fdff37c1f20d67ec2a6383e9d93b03d0c419e7eb94862d713fed3c547c63

😃

**Comment by jackcasey** [comment]
Great, cheers!
[edit] FYI I've not had any issues, but haven't tested ENS workflow directly. Maybe I'll register some domains that have since become available.
