### ISSUE TITLE
guide to transfer ownership ens

### ISSUE THREAD

**Issue by typoinadvance** [kvhnuke/etherwallet#474]
hi myetherwallet...
can u please guide the noob me how to transfer ens ownership via https://www.myetherwallet.com/#contracts ?? i dont understand what is "node bytes 32" under the setOwner function. ty

**Comment by tayvano** [comment]
I haven't done it yet either. I'm still trying to catch up with people revealing.  :( :( :(

node bytes32 == your namehash. 

If you type your name it on https://www.myetherwallet.com/#ens itll tell you your name hash. 

For example: 

> Namehash (mewtopia.eth): 0xcf0a2ffe7a8b82882c51f40a71b74dd52e1d0702d284855e3e6b58741d86e541

Is there another field that you need?

**Comment by typoinadvance** [comment]
Thanks you so much @tayvano  for the reply... i think the last field "owner address",  is the ether address of the new owner.

**Comment by tayvano** [comment]
@typoinadvance Yup yup. You should have it then. Let me know if you have any issues :)

**Comment by typoinadvance** [comment]
all is good .. @tayvano  tyuu huyaa!!!

**Comment by nrhirsch** [comment]
If you have a JSON file from Chome/Metamask for a given bid and you want to try to reveal the bid on MyEtherWallet, what do you put in the long string and which field in the JSON file is the one to put in the "secret phrase", or alternatively do you recommend going to: https://www.myetherwallet.com/#ens and use one of the fields there or if the one you need is in both places?  This is assuming one knows the name and the amount bid (but that is in JSON file anyway).

**Comment by tayvano** [comment]
@typoinadvance https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-change-the-ens-owner-address

@nrhirsch We currently recommend manually copying and pasting the bid amount / secret.

**Comment by nrhirsch** [comment]
https://medium.com/@nhirsch/importing-a-bid-created-in-mew-into-ens-and-vice-versa-60b31a174e98
