### ISSUE TITLE
ENS reveal phase error - Please enter valid amount.

### ISSUE THREAD

**Issue by jc-jnet** [kvhnuke/etherwallet#478]
Hello, I am trying to reveal a bid. I enter the Long string of text I copied. It populates the Name:, Bid Amount: and Secret Phrase: correctly. I click Reveal Your Bid and it reports the error "Please enter valid amount".

But I have entered the correct bid amount. If I hover my mouse over the Bid Amount field, it says "Please enter a valid value. The two nearest valid values are 0 and 1".

**Comment by crptm** [comment]
Your bid is < 0.01

**Comment by jc-jnet** [comment]
No, my bid is 0.0.1 exactly. Plus 0.01 to hide the bid.

**Comment by tayvano** [comment]
I thought we fixed this? Do you have less than .01 eth in your account currently?

**Comment by crptm** [comment]
Any chance you can share the name?

**Comment by crptm** [comment]
Do you use MEW 3.8.0?

**Comment by jc-jnet** [comment]
Nope using MEW 3.7.8. Yes I have less than 0.01 ETH. I will add some more and try again.

**Comment by tayvano** [comment]
Ahh. Yeah, either update MEW or add 0.01 ETH to your account. This was such a weird mismatched error message

**Comment by jc-jnet** [comment]
OK it worked with extra ETH in the wallet. Thanks. I like MEW. Have installed 3.8.0 on another Chrome instance and will upgrade this one too.

**Comment by leongaban** [comment]
Hey guys I have .01 ETH in my account, and trying to make a bid of .01 for my .eth domain name, but I keep getting the message requesting a valid amount.

What is the valid amount??

**Comment by leongaban** [comment]
I don't get this.

Ok I have 0.01 in my account, I made the Bid Mask 0.05 and it turned green, however no number I enter in the actual Bid amount works, if I go above .05 both turn red?

What are the rules for this?

**Comment by leongaban** [comment]
Ok I added another .005 and now it works, BUT it's now asking for another 0.01 to cover the cost off the Gas. Wish it had mentioned that before hand :(

This is one expensive domain name

**Comment by NetOpWibby** [comment]
Ah, so this "Gas" thing is the issue, gotcha. I have 0.002 ETH in my account and this wasn't making any sense. The website should be updated to reflect this.
