### ISSUE TITLE
CRITICAL: Windows defender detects last release v3.8.1 as Trojan!

### ISSUE THREAD

**Issue by jpeletier** [kvhnuke/etherwallet#481]
Hello,

First of all, thank you for this great app.

After downloading dist-v3.8.1.zip, Windows Defender (Windows 10) popped up and prevented access to the downloaded file: 

![image](https://cloud.githubusercontent.com/assets/11574521/26279666/0547e5ce-3dba-11e7-8c82-df0e63c8e631.png)

Tested in two different computers. Please check this, as this may scare people off, and rightly so!

Cheers,
Javier

**Comment by kvhnuke** [comment]
https://www.virustotal.com/en/file/810ea90cd6375579033ea06bcbfa1dc535a9aac9506d51c2ef0cbcc744b38470/analysis/1495319712/

I would go ahead and do a full scan on your computer it is highly likely your computer might be infected. Let me know how it goes. Mean time I'll try to get someone with Windows scan it too

**Comment by tayvano** [comment]
@jpeletier Have you ever downloaded other versions from the repo and encountered similar issues?

@kvhnuke I don't understand viruses. Is this unrelated to our download, something new in our repo that's throwing a false positive, or a real virus or something?

**Comment by jpeletier** [comment]
I had the same issue with 3.8.0. I am pretty sure my PC is not infected, tried with two different unrelated machines. Take a look at windows defender report, it complains about `bin/startMEW.js`

This is a false positive obviously, the question is why... 

Let me know how can I help. 

Regards, 
Javier

**Comment by tayvano** [comment]
Here is the entirety of startMEW.js:

```
#! /usr/bin/env node

var open = require("open");
var separator = process.platform=="win32" ? "\\" : "/";
open(require('path').dirname(require.main.filename)+separator+".."+separator+"index.html");
```

Not sure what it's detecting in there....

**Comment by kvhnuke** [comment]
it might be due the "open" library since it checks for the default browser, im wondering why virustotal not showing it

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
