### ISSUE TITLE
Error when attempting to send ETH or tokens using the chrome extension

### ISSUE THREAD

**Issue by tomisme** [kvhnuke/etherwallet#483]
Hi guys, I get the error below when trying to send from one of my accounts in the chrome extension. 

> Error: plus() number type has more than 15 significant digits: 46935799.99999997

Stack trace looks like:

![image](https://cloud.githubusercontent.com/assets/7482194/26284482/1d76fddc-3e6f-11e7-8506-3edde7f41bd4.png)

Let me known if there's anything else I can provide :)

**Comment by crptm** [comment]
Update to 3.8.x should solve this for you
