### ISSUE TITLE
Illegal value for Message.Field .EthereumSignTx.chain_id of type uint32: string (not an integer)

### ISSUE THREAD

**Issue by prusnak** [kvhnuke/etherwallet#487]
When I use custom node and use custom ChainId, the sending of transaction fails because of the error in title. I suspect this is because user-entered chainId is stored as string, not as integer.

**Comment by bt** [comment]
Having some issues trying to reproduce this.

Did you tick the `Support EIP-155` checkbox? If so, what did you put in there?

Also, what node are you connecting to? Geth / Parity?

**Comment by sheab** [comment]
Sorry @bt! I only saw your comment just as I was submitting my PR :P

I wasn't able to reproduce that exact error message ( since it likely was outputted by geth / parity and I used https://api.myetherapi.com ), but I did reproduce & fix the error sending the transaction. See my PR :)

**Comment by bt** [comment]
Oh I see the issue! Good job 👍

**Comment by prusnak** [comment]
I set EIP-155 value 31
