### ISSUE TITLE
Feature Request: Show mnemonic (with optional passphrase) among wallet info

### ISSUE THREAD

**Issue by Engelberg** [kvhnuke/etherwallet#493]
It's nice to be able to print out a paper wallet comprised of the mnemonic words, where the optional passphrase is a piece of info that you don't print out, but is only in your head, making the paper wallet less useful to those who get a view of it.

Since etherwallet can import such things, it would be great if it could generate it as well.

**Comment by tayvano** [comment]
Generating wallets is no joke and requires extensive testing. We are no longer touching derivation on MEW v3. 

We have discussed generating mnemonics in a future version of MEW but it will not be a feature on this version. We prioritize certainty that there are no derivation errors over usability in this particular case.
