### ISSUE TITLE
Gas Estimate Issues Master Thread

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#494]
Poloniex
https://etherscan.io/tx/0x053551b272251ff7c167dde42887e9c0891e21755976486cc59bfb40766e96f5
https://etherscan.io/tx/0x461c7bb64eba6ff910a6639c01f0610f48ed7d6bc9e81123a6fe5d66fbce504a
https://etherscan.io/tx/0x542b23110bb90c14f152d9c5f723502cb1d1ebb0331b7a4efdd6e5023f0608c7

???
https://etherscan.io/tx/0xb4485b51e7d66c02a5fdc58f31e46dc9178370ea793ca90208f9f54b08e462f6

STORJ?
https://etherscan.io/tx/0x2d18fa175fb61b87e7bc7a8a488fde691abfcfce2bc4aa801d4c6495bd560039

GNT + moar
https://etherscan.io/address/0x4f7e0853ae1932290db5d4452ee10a87ba10eb6b

Sending REP?
https://etherscan.io/tx/0xbc814149973c8c9ff0db2e543a3508edc8a191e5a19dd8dfe66fdd85c6ecb2b6
https://etherscan.io/tx/0xdbac07aa88bc9e2ce24ecce72d6be23638365a983c53595e366c5531206aebfd

Sending SNGLS
https://etherscan.io/tx/0xea682c5c1c70737819519533f2d90a5f55c259e712d4b3e34da85edbe437ae77 

TKN
https://etherscan.io/tx/0xc2ed0e207b85b364072cf9571a6193e461089f07c631612e9ca3712e174d2f88

## Multisigs

- Estimating >4M (-1): https://etherscan.io/tx/0xe434c49b1ac30559d15bc161b9b708983920fe9653dd195e12635d8dac8a3787

- https://etherscan.io/tx/0xacb2070d19d9972f40181553b90fe850d707c264a55c093de8f27294fb769afa

- SEND ANT == -1

-

## Non-Tokens Not Estimating Correctly

- https://etherscan.io/tx/0xeaeb3039a11ea1bc50c0b29035158935febef20791f44e805ed0dc9860e59ac1

## Tokens Not Estimating Correctly

- https://etherscan.io/tx/0xb5352cada151debac6914346dd5c322d8778e57b7e04e84af6203d14a1c35b53

#### BAT - needs 250000

- https://etherscan.io/tx/0x89c5920590c9ae740135923bf323903a01b6be2b50ee188e2fea70e77ad542fa

- https://etherscan.io/tx/0x4994f7e2a79a51540b43458c97d810b2481d67397e3e2ad191ae2c5a7ce900b2

- https://etherscan.io/tx/0xbb234c8187dadf11ce7dd8772651737e4067f7af742f406c9e968fbe805e0e63

#### HMQ - needs 400000?

- https://etherscan.io/tx/0xa5b6dd9d625b153d89719727ba9c3725f432eba49723af8ba445e3642f1f4f90

- https://etherscan.io/tx/0x83aae1fa84ee81910ef2d13bb90679d83d44a356b50c0b6106a181593cf0482e

#### SWT - needs 260000??

- https://etherscan.io/tx/0x0707cc5087b7e7ff3e7f0c30fdc4f1a251ba0478399a58d22387347712580518

--

## 6/6/2017

0x4542b18ce2e5bca6bec254b8d2e3e7478ed7c8277f590e69d42b90a36b6928ac

https://etherscan.io/tx/0xa62e6d3ff3948c55aa80f10b88087b184e0a64c4b21121cb29f0ab2464092623

https://etherscan.io/tx/0x7f07682299ce6e8686ae8effb2309e71a99ff3e51d60ee39755c617f85eb4862

**TRUSTCOIN**

- https://etherscan.io/tx/0x548d7a830386c268e98c53dd11fcbf74e354d745ad91ee1f26f42190342297c4

**Comment by tayvano** [comment]
@kvhnuke ^^^^^^^^^^^^^^^^

**Comment by crptm** [comment]
@kvhnuke pretty sure initial implementation with recursive search for max gas spent in vm trace was correct one. Why we moved away from it?

**Comment by kvhnuke** [comment]
hi @crptm it didnt work for certain cases which i dont recall now :(

**Comment by tayvano** [comment]
v3.8.4, hopefully
