### ISSUE TITLE
As the balance of ETH in the watch list. From watch list to bring?

### ISSUE THREAD

**Issue by wladim31** [kvhnuke/etherwallet#500]
I can't use my Eth in Appendix MyEtherWallet CX, as it is in the tracking list. How to get him back from the watch list?

**Comment by tayvano** [comment]
You need to use your private key in order to use any account to send ETH or Tokens.

**Comment by wladim31** [comment]
# How can I recover the Private Key if it is lost?

**Comment by tayvano** [comment]
Please read [I no longer have my private key. What can I do](https://myetherwallet.groovehq.com/knowledge_base/topics/i-only-have-my-address-and-password-can-i-access-my-account)

**Comment by wladim31** [comment]
# I found a copy of the key, but what to do with it I don't know? Tell me what do I do with it?
# A copy of the key on a sheet of paper photocopies.
![i3](https://cloud.githubusercontent.com/assets/28957434/26832259/8ff0cd24-4ad7-11e7-94c0-6d42c227f3cb.jpg)

**Comment by tayvano** [comment]
[How to access your wallet](https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-verify-i-have-access-to-my-new-wallet?from_search=true)

**Comment by wladim31** [comment]
**Tell me how to scan a Private Key what program?**
