### ISSUE TITLE
Token Unverified

### ISSUE THREAD

**Issue by jorghem** [kvhnuke/etherwallet#506]
16,000 chips were sent to Myetherwallet. Perform the smart contract with RiptoBux. My files are displayed in my wallet but after a few days they are gone. I check the transaction and there it is but next it says: ERC20-TOKEN Ripto Bux (* Unverified). What does it mean?

**Comment by tayvano** [comment]
1. That seems like a UI message from etherscan.io, not MyEtherWallet. It just means that Etherscan things it's "Ripto Bux" but hasn't verified this fact. 

2. Any questions regarding any tokens or chips or whatever need to be directed to the creators of that token. We are not experts in any tokens and cannot keep up with the 100+ active tokens currently available via our interface. Sorry!

**Comment by jorghem** [comment]
The chips came to my Myetherwallet wallet. I saw the chips. I even created a smart contract with RiptoBux. But then they disappeared from my wallet.

**Comment by jorghem** [comment]
The chips came to my Myetherwallet wallet. I saw the chips. I even created a smart contract with RiptoBux. But then they disappeared from my wallet.

**Comment by jorghem** [comment]
Here I show a screenshot of the transactions made.
http://prntscr.com/fcw9g8

**Comment by jeffanthony** [comment]
None of this is myetherwallet issue and in analyzing there is also no problem? You have your tokens as expected and you even mentioned finding the 'ERC20-TOKEN Ripto Bux (* Unverified)' page where you can see said tokens.

**Comment by crptm** [comment]
@jorghem you probably need to add it as a custom token https://myetherwallet.groovehq.com/knowledge_base/topics/how-to-see-a-new-token-in-myetherwallet
