### ISSUE TITLE
Wrong ENS contract address for testnets

### ISSUE THREAD

**Issue by Deozaan** [kvhnuke/etherwallet#509]
Consider this low-priority since it has to do with testnet.

I wanted to test ENS on a testnet (Rinkeby) so I used MEW to check if a domain was available. It told me it was available and allowed me to place a bid. After confirmation I realized my ETH got sent to the ENS address for mainnet, which is not associated with the ENS contract on the testnet. I was careless and sent a large amount of ETH because I was expecting to get most of the ETH back once the auction closed.

No real loss to me since the test ETH isn't worth anything, but maybe MEW shouldn't allow the ENS tab to work if a testnet is selected from the dropdown menu. Or the contract address should be updated to use the [correct testnet addresses](http://docs.ens.domains/en/latest/introduction.html#ens-on-ethereum).

Mainnet: 0x314159265dd8dbb310642f98f50c066173c1259b
Rinkeby: 0xe7410170f87102df0055eb195163a03b7f2bff4a
Ropsten: 0x112234455c3a32fd11230c42e7bccd4a84e02010

**Comment by tayvano** [comment]
FML, thank you for catching this. Will updated ASAP and get live in the AM.

**Comment by tayvano** [comment]
@kvhnuke 

1. I'm 99.999999999999% I wrote some ghetto code to prevent ENS from showing on any pages except for Ropsten and ETH. When did this get changed?

2. Does this mean that ETC people can be accidentally bidding on names via bad addresses as well?!

3. Your list is growing. 300 open tickets or fixing this stuff: the choice is yours and yours alone. Muahahhhahahahhaha 🙉 🙈 🙊

**Comment by kvhnuke** [comment]
@Deozaan I believe the problem is you selected the changed the node while on the ENS tab, for example you had the mainnet node and went to ENS tab then changed to Rinkeyby. 
let me see what I can do about this. 
FYI
auctions are only available on mainnet and ropsten. Rinkeby only has FIFS registrar.

**Comment by kvhnuke** [comment]
it show an error message now when you change the node

**Comment by Deozaan** [comment]
@kvhnuke 
> I believe the problem is you selected the changed the node while on the ENS tab, for example you had the mainnet node and went to ENS tab then changed to Rinkeyby.

Yes, that does sound like what I did. I guess I was expecting a more AJAX-y interface where changing things in the middle of the process would update everything appropriately behind the scenes.

> FYI auctions are only available on mainnet and ropsten. Rinkeby only has FIFS registrar.

And yes, I realize that now. :)

> it show an error message now when you change the node

Thank you very much. I appreciate the time and effort you and @tayvano put into this.
