### ISSUE TITLE
Gas Limit

### ISSUE THREAD

**Issue by FrankHold** [kvhnuke/etherwallet#516]
Hi, was there a change in the calculation of the "Gas Limit" for https://www.myetherwallet.com/#contracts?
I get much higher values (4 387 669) which might be above the the Avg GasLimit. This morning it worked just fine. Or I made a mistake. 
Thanks your franky

**Comment by tayvano** [comment]
Yes, we pushed an update to estimate gas this morning...maybe an hour before you commented? This has resulted in much more accurate gas estimations for sending tokens so far.

You can download v3.7.3 to use old estimate, but I'm curious if it is estimating incorrectly now, or was estimating incorrectly before?

Can you provide further details on the contract and what you are trying to do and let me know if its working on 3.7.3? We will make adjustments based on your feedback.

Thank you!

**Comment by crptm** [comment]
I guess 3.7.3 should be 3.8.3 :)

**Comment by tayvano** [comment]
Yes - thank you. And thank goodness someone around here has some brain left. 😜

**Comment by FrankHold** [comment]
Good Morning!
Thank you for the reply! Here is what I did. https://drive.google.com/file/d/0Bzjj9RC5wV6Kb2dmZTZyOFpKNEE/view?usp=sharing
In the end there is nothing on the block chain
https://etherscan.io/tx/0x95ea035f58d979e6d655970ff3158aaab50cc0ca443dbe65101161700c11b511
In the next step I will try it with the version 3.8.3
Have a nice day!

**Comment by tayvano** [comment]
Hey - I just got a similar thing when I was sending to a contract that fails due to bad instruction or something else. We are going to update so that if it's that high, it throws an error to let you know. I'm still curious if yours doesn't fail and is showing that large though, if you are down. Please note your gas price before hand and perhaps lower it. Txs like these are getting bloody expensive!

**Comment by FrankHold** [comment]
Cool! Yes the gas is expensive - I reduce it normally to 9 GWei. Just tried it again with the same result. (Is it not in the middle of the night for you?)
* The transaction only costs 0.00146048 ETH (It shows 0.038848041 ETH as maximum)

**Comment by tayvano** [comment]
@FrankHold just pushed 3.8.5. Let's see if that works?

And yes, its now 5am. However working a real job with 4 ICOs in one week doesn't leave much time for sleep. I'm never going to catch up.

**Comment by FrankHold** [comment]
"Gas limit" is now -1   (sorryy)

**Comment by tayvano** [comment]
Yeah, thats to prevent people from sending failing TXs with 4M gas (during BAT ICO in 3 hours)

What contract are you interacting with?

**Comment by FrankHold** [comment]
Get some rest!
https://etherscan.io/address/0xFAcf5dd6Cb88F5409e1B85c140084DEA8cf6DcA3
I did the exactly the same 2 days ago
https://etherscan.io/tx/0x99610ec0963102fa2fce07b35dd596bbabcda43f2f56b7ab5146e9091c75c89a
Gas Used By Txn: 162276
BUT - It is not so important right now.

**Comment by tayvano** [comment]
So it seems the problem lies somewhere in the multisigs. 

@kvhnuke my multisig confirms for ENS are estimating 4M as well, but went through successfully.

here's my tx hash that was estimating 4m but worked when i manually set it
https://etherscan.io/tx/0xacb2070d19d9972f40181553b90fe850d707c264a55c093de8f27294fb769afa

**Comment by FrankHold** [comment]
Thank you for the tip - if I just set it manually it works!
First the calculated value is -1
then I change it to 1000000
I activate my trezor and the value springs back to -1
then I change it to 1000000 again
AND it worked! https://etherscan.io/tx/0xe434c49b1ac30559d15bc161b9b708983920fe9653dd195e12635d8dac8a3787
Gas Used By Txn: 172287
Thank you! https://etherscan.io/tx/0xdb88672388f71053802203e945407bdf2a140ef5d4a8285be589443205e95349

**Comment by tayvano** [comment]
Other one that's estimating incorrectly:

> In the contracts tab for: 
> Set the Resolver for your Name
> When Generate and sending the tx, the gas limit portion is -1?

**Comment by tayvano** [comment]
Another incorrectly estimate - but not a -1 - just wrong.

https://etherscan.io/tx/0xb5352cada151debac6914346dd5c322d8778e57b7e04e84af6203d14a1c35b53

**Comment by GriffGreen** [comment]
https://github.com/ConsenSys/MultiSigWallet/issues/68

Made an issue...

**Comment by GriffGreen** [comment]
oh! Look at how smart github is :-D I didnt even have to report here manually... man, who ever is making this github magic should do a fucking ICO and buy an island. This website is incredible.

**Comment by tayvano** [comment]
😂😂😂😂

**Comment by tayvano** [comment]
It's a problem with geths estimate function actually. There's gunna need to be some teamwork here

**Comment by tayvano** [comment]
moving back to #494 so we can just resolve all the issues
