### ISSUE TITLE
myetherwallet.com/* redirects to www.myetherwallet.com (without wildcard)

### ISSUE THREAD

**Issue by Deozaan** [kvhnuke/etherwallet#519]
This is a minor, low-priority quibble, but it can be annoying to experience nonetheless. And I think it should be a quick and easy fix.

Recently you announced the [MEW Helpers](https://www.myetherwallet.com/helpers.html) page. I was trying to access it but couldn't find a link to it on the site, so I opened a new tab and took a guess, typing in [myetherwallet.com/helpers.html](https://myetherwallet.com/helpers.html) into the address bar.

The page loaded, and I was happy.

But then almost immediately after that, the page redirected to the main www.myetherwallet.com page. This was confusing and annoying.

In my opinion, the site should either:

1. Not require the `www.` to be at the front of the domain name in the address bar.
2. Uses a wildcard when redirecting to `www.` so that a user on, e.g.,  `myetherwallet.com/helpers.html` ends up on `www.myetherwallet.com/helpers.html` after being redirected.

Thank you.

**Comment by tayvano** [comment]
You are absolutely correct. I'm 99% certain this was an oversight as I can't imagine anyone would do this on purpose. I know we are making some other URL changes now and I'm sure @kvhnuke can squeeze this fix in as well.

Thank you for bringing it to our attention
