### ISSUE TITLE
Add nodes for Musicoin.

### ISSUE THREAD

**Issue by trustfarm-dev** [kvhnuke/etherwallet#520]
Hi Kvhnuke,

How about adds musicoin wallet?
It has based on geth , and wallet json is compatible with geth and musicoin.
I'm also using myetherwallet wallet with musicoin.

https://musicoin.org/wallet.html

thanks,

**Comment by tayvano** [comment]
We would gladly accept a PR with this, but none of us are familiar with musicoin and, frankly, this is never going to make it to the top of the todo list.

**Comment by trustfarm-dev** [comment]
I'll contact them , musicoin developers.
Thanks ^^
