### ISSUE TITLE
Shouldn't require SSL if running locally

### ISSUE THREAD

**Issue by knocte** [kvhnuke/etherwallet#521]
I've tried to run MEW locally (with a file:/// URL) with my Ledger Nano today, and I can't, because it tells me this message in red:

```
1. Re-open MyEtherWallet on a secure (SSL) connection
```

This check should only be there when running on-line, not locally from an index.html saved on the computer.

**Comment by tayvano** [comment]
This is a limitation of the U2F protocol and not something we nor Ledger control. In order to use U2F the browser requires it to be over a secure connection. 

You can read more about how to connect locally here: https://github.com/benjaminion/eth-parity-qnap/wiki/Connecting-to-MyEtherWallet
