### ISSUE TITLE
My Minereum is gone

### ISSUE THREAD

**Issue by kamuflage** [kvhnuke/etherwallet#522]
I do not find my minereum in myetherwallet. When I go to etherscan I see I have 0 in my balance. I'm 100% sure I had 49 MNE a couple of days ago

**Comment by tayvano** [comment]
Please check on ethplorer.io and check all your addresses.

**Comment by kamuflage** [comment]
Checked it, nothing's there

**Comment by kamuflage** [comment]
Nevermind, I found it, I apologize for any inconvenience!
