### ISSUE TITLE
Gas Price slider overwrites Send Offline Gas Price?

### ISSUE THREAD

**Issue by sir-laurens** [kvhnuke/etherwallet#524]
I have reasons to suspect that the gas price set using the slider in the footer is always used, even if you set a different gas price in the Send Offline screen.

I participated the BAT ICO and my transaction never showed.  The transaction kept showing"Unable to locate Transaction entry" on Etherscan. I am 100% certain I set the gas price very high (I even took a screenshot before generating the transaction). Apparently, I played around with the slider a few days earlier and left it at a very low value... I didn't think this was going to matter since in the Send Offline screen, you can set the Gas Price manually.
After the ICO, I wanted to move my ETH to another wallet, and the same message appeared on all my transactions. (not found) At first I thought it was latency because of all the activity caused by the ICO, but then I tried after moving the slider, and finally that transaction did show up...

Since the slide is a new feature, I have a feeling this might be a bug.
If that's the case, I'd be really sad this is the reason I missed the ICO. But, I would like to have this looked into to prevent it from happening again.

Thanks in advance!

**Comment by sir-laurens** [comment]
I still have the original transaction (signed). So if it's possible to get the gas price out of a signed transaction hex, please let me know. Then we can confirm what gas price was in the output.

**Comment by tayvano** [comment]
I agree that this is an issue, however it is not the reason you didn't get in. Unless you set your gas price to 2000 GWEI manually AND sent it at the exact right time, you would still be with the 99% who didn't make it

https://docs.google.com/spreadsheets/d/1JyPMEcXJpeXCSEhI9rp0QxKZHc64P98dKH8_xwT8RVA/edit#gid=1492751600

**Comment by sir-laurens** [comment]
Thank you for your answer and the very interesting spreadsheet!
I did multiple ICOs before and always ended up in 1st or 2nd block. My gas price was 240 gwei, and I see it would have been high enough only if I made the first block. Pretty sure this time it would have been the second, so you are right. Anyway, I love MEW and am happy to be able to support it this way.

**Comment by tayvano** [comment]
My apologies for underestimating you. You are correct, and on point. 

I believe you can use the hex -> decimal converter here near the bottom to confirm if you really want to know gas price (or ever check in future). https://www.myetherwallet.com/helpers.html

I believe @kvhnuke fixed a couple hours ago.

**Comment by sir-laurens** [comment]
I saw the commit, top! Thanks a lot!
