### ISSUE TITLE
ENS error Owner & Highest Bidder missing as of 3.8.5

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#525]
Up to MEW 3.8.4, going to the ENS tab and entering the name of an already-registered domain would print the Owner and Highest Bidder (Deed Owner), along with other information. As of 3.8.5, these two fields are empty. As a result, attempting to finalize a domain after a winning bid results in an error message: `This account is not the owner of xxx.eth. Please unlock the Owner Account in order to resolve`.

**Comment by crptm** [comment]
@fortran77 i believe the issue is with MEW node, try using etherscan

**Comment by fortran77** [comment]
You're right, using Etherscan.io as the node makes it work correctly, thanks.

It's odd, though, that using a local copy of MEW 3.8.4 and letting it point to the default MyEtherWallet node also makes it work correctly.

**Comment by tayvano** [comment]
@kvhnuke

**Comment by tayvano** [comment]
We had changed the calls to reduce to amount of requests to the server and unintentionally broke this. It's fixed now.
