### ISSUE TITLE
Gas Price Slider Doesn't Work When Finalizing ENS Auctions

### ISSUE THREAD

**Issue by DutchBoyd** [kvhnuke/etherwallet#527]
Title pretty much sums it up. I love MEW and the slider has been a huge benefit and has saved me tons of gas. But the gas price slider doesn't seem to work when making a finalize name transaction. I just slid it down to 10 before sending a finalize and the txn went through at 22 gwei.

**Comment by tayvano** [comment]
fixed last night.
