### ISSUE TITLE
Swap order of Ether to Bitcoin got cancelled but my ether were not returned to my wallet

### ISSUE THREAD

**Issue by vvvmfu** [kvhnuke/etherwallet#528]
Help me to understand the proces and what happened with my transaction!!! How much i need to wait and where my ether?
My ether gone
![image](https://cloud.githubusercontent.com/assets/29120050/26675985/a3a59b7c-46ce-11e7-9425-09cced6c4775.png)
![image](https://cloud.githubusercontent.com/assets/29120050/26676001/b4fbb032-46ce-11e7-9116-360e1b080950.png)

**Comment by tayvano** [comment]
Please EMAIL support@bity.com and support@myetherwallet.com so that we may determine what happened and resolve this in a timely manner for you. Thank you.
