### ISSUE TITLE
Swap order of Ether to Bitcoin got cancelled but my ether were not returned to my wallet 

### ISSUE THREAD

**Issue by Ramzramzik** [kvhnuke/etherwallet#529]
What happened with my transaction!!! How much i need to wait and where my ether?
My ether gone
REF ID#: BITYTQMXAV

Amount to send: 8.97323732 ETH

Amount to receive: 0.80000000 BTC

Payment Address: 0x76b7b147427bf0b83f35b9347e3c392045c4dda7

Rate: 0.08982 ETH/BTC

![img_1859](https://cloud.githubusercontent.com/assets/29078393/26703177/0bd89e9e-4731-11e7-908d-77df0a7928a4.PNG)
![img_1862](https://cloud.githubusercontent.com/assets/29078393/26703179/0c00d198-4731-11e7-8b44-569b4749958a.PNG)
![img_1864](https://cloud.githubusercontent.com/assets/29078393/26703178/0bfef86e-4731-11e7-9f87-9b6fcee6857c.PNG)

**Comment by tayvano** [comment]
Please **EMAIL** support@bity.com and support@myetherwallet.com so that we may determine what happened and resolve this in a timely manner for you. Thank you.
