### ISSUE TITLE
 DAO tokens 

### ISSUE THREAD

**Issue by leadilara** [kvhnuke/etherwallet#53]
I need help My nerves are blank. I see my DAO tokens at Block Chain explorer. I use Ethereum Wallet 0.7.1. Contract created. Observed but I see no Dao.
So I now have a DAO tokens created .How do I get in Taos "myetherwallet"?

**Comment by tayvano** [comment]
If you see them on etherscan then just do what you want to do. It's just a display issue on MyEtherWallet.com

**Comment by saazaan** [comment]
I have a similar problem. My ETH anв DAO balances are positive:
http://etherscan.io/address/0xdECAEc123a47eA55eaf7c8404FF12E97cB5F68F5
but nothing in my wallet
<img width="1205" alt="screen shot 2016-06-23 at 14 34 18" src="https://cloud.githubusercontent.com/assets/17524792/16302109/ff32a966-3951-11e6-84b2-67338bb2abe5.png">

and i cant send DAO or ETH anywhere!!!

this is really frustrating !!!

**Comment by leadilara** [comment]
Hi,

you need ether when will send Dao.
Have you make an constract ?

Am 23.06.2016 um 13:52 schrieb saazaan notifications@github.com:
