### ISSUE TITLE
MEW private key changes when pressing return.

### ISSUE THREAD

**Issue by Tycer** [kvhnuke/etherwallet#531]
I have a myetherwallet paper wallet whose private key changes when I hit the return button. Last weekend I was out of town without my computer and wanted to access the wallet. I went to MEW and entered my private key and it opened someone else's wallet. A series of characters in the center of the string morphed from what I entered to something else. I lost my mask on an ENS sale which kind of sucked. When I got home I was able to replicate the error every time. The Keystone file works flawlessly to open the wallet and other than the lost 0.4 mask I was able to transfer the ETH out. This error happens on the MEW website via Windows 8, Windows 10, IOS, Mac OS. Safari, Chrome and Firefox.
Any ideas?

**Comment by tayvano** [comment]
Very intriguing. Can you email me at taylor@myetherwallet.com so we don't accidentally blast private keys out in public. I'm online now.

**Comment by kvhnuke** [comment]
can you paste 5610253bcb7acf7f80e6f9bfb87b1fcfa1963516320255071abe4ccc6cda70af private key and check which address you get?

It should be 0x9e50E3065e9e499B2B5C06b1F84e93223Dfa1073

**Comment by tayvano** [comment]
@kvhnuke look in groove under the Taylor email

**Comment by Tycer** [comment]
Works as it should. 

Kind regards,

Tycer Lewis

Dictated to and sent from my Phone

**Comment by tayvano** [comment]
@Tycer FYI, you should generate a new wallet and not use this one.

https://myetherwallet.groovehq.com/knowledge_base/categories/getting-started-443
