### ISSUE TITLE
Is it possible to obtain mnemonic phrase for existing wallet?

### ISSUE THREAD

**Issue by stefek99** [kvhnuke/etherwallet#536]
You allow loggingin with mnemonic...

How do I do in reverse?

Have an existing wallet but want to save 12 words for security...

Related: https://www.reddit.com/r/ethereum/comments/61t7gy/mnemonic_seed_for_myetherwallet/

**THANKS**

**Comment by tayvano** [comment]
All mnemonics can go to keys but you can't go from key -> mnemonic. 

We will eventually allow derivation of mnemonic phrases via MEW but it requires extensive testing to ensure there are no errors that would prevent a certain address from being unspendable. It's a really really really big deal and something that we don't take lightly. 

If you want words, you can create words elsewhere (MetaMask, Jaxx) and use them via MEW. We'll add to generation when we are certain it's ready.
