### ISSUE TITLE
Do you support testnet? (Kovan, Ropsten)

### ISSUE THREAD

**Issue by stefek99** [kvhnuke/etherwallet#537]
I'm experimenting with stuff.

Initially I couldn't find a way to swtich to testnet.

So I've experimented on the mainnet.

Don't want to spam the thing.

So on second thoughts - is there a way to switch to one of the testnets?

**Comment by tayvano** [comment]
Etherscan.io has been kind enough to provide nodes for all the testnets. You can switch between them via the Node Switcher in the upper right corner. :)
