### ISSUE TITLE
Provide an easy way to generate encoded transaction data for offline signing

### ISSUE THREAD

**Issue by yudilevi** [kvhnuke/etherwallet#539]
Currently, offline signing expects the user to provide the transaction data by himself/herself.
Would be useful to generate the data automatically by allowing the user to provide the contract abi + arg values - similar to the input when interacting with contracts.

**Comment by tayvano** [comment]
This will be possible in version 4. We aren't adding new features like this to v3 anymore. Sit tight, it'll be here soon enough.
