### ISSUE TITLE
ETC - Not showing up on Trezor wallet

### ISSUE THREAD

**Issue by dsingh21** [kvhnuke/etherwallet#541]
Hi - I sent an email to support@... but wasn't sure if it was received. 

I transferred some ETC to my Trezor wallet. It's confirmed on the blockchain that is in the address shown in my ETC wallet. However, the ETC doesn't show up in MEW when I login using my Trezor (address shows zero balance) and I am unable to transfer any ETC out of the address (saying there is insufficient funds). Any thoughts on how to fix this problem?

**Comment by crptm** [comment]
Select ETC (Epool.io) node. Node selector is in header.

**Comment by dsingh21** [comment]
Thanks!

**Comment by dsingh21** [comment]
Thanks. I must have missed that step in previous guides. Thanks for educating me and responding so quickly. I appreciate it!

**Comment by Janet-Yellen** [comment]
Dear crptm THANKS - seriously man, thanks - I was panicking at having thought I'd lost teh lost - and found your post via google. I specifically joined guthub just so i'd be able to post this thank you message (BTW, I'm not really Janet Yellen - lol) - Simon
