### ISSUE TITLE
Transferring to a different wallet  

### ISSUE THREAD

**Issue by johnmed26** [kvhnuke/etherwallet#546]
Hi! I need help i have created a wallet in my ether wallet i tried to transfer etherium to a different wallet in etherwallet but when click on generate it doesnt generate i tried sending 0.01 i didnt change the gas limit. because i dont know what to put. please help me

**Comment by tayvano** [comment]
The gas limit should estimate automatically.  If it shows -1 it is showing that because the TX would fail, or could not be completed.

https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-send-ether-from-one-wallet-to-another

https://myetherwallet.groovehq.com/knowledge_base/topics/what-is-gas

**Comment by sonic1111** [comment]
Hi, i wish to send VSL for my etherwallet to my account to Liqui exchange but sistem write me that "-1Gas" but i have 0.444eth what can i do? how can i send VSL?  "Could not estimate gas. There are not enough funds in the account, or the receiving contract address would throw an error. Feel free to manually set the gas and proceed. The error message upon sending may be more informative."

**Comment by sonic1111** [comment]
How much ETH do i need to have in my ballance to sent 50000VSL????

**Comment by sonic1111** [comment]
Is it problem with the myetherwallet or with the metwork?

**Comment by kvhnuke** [comment]
try adjusting the gaslimit manually, if I have to take a guess I would set the gas limit to 200000 and try again

**Comment by tayvano** [comment]
Gas Estimation has been fixed in 3.8.9
