### ISSUE TITLE
Lost all ETH by a weird transaction to a strange wallet

### ISSUE THREAD

**Issue by rambochoi** [kvhnuke/etherwallet#548]
Anyone was encountering this case? Please support! Much appreciated!

My wallet: https://etherscan.io/address/0x1472fe9e401520efcf0767065bf75ec1672e971a
to strange wallet: https://etherscan.io/address/0xbcd206ffea46894fa3f912cb34e5ee57f67a91c2

![image](https://user-images.githubusercontent.com/29133126/26836174-58a6523a-4b04-11e7-8d33-b8424e992fb6.png)

**Comment by tayvano** [comment]
I'm really sorry but it appears your funds have been robbed. 

Did you use Ethereum Chamber dot net?

**Comment by rambochoi** [comment]
I read an article introduced that ethereumchamber.net and I thought it was your site with new RED look. I did not log in. How can they can do that? Has your site been changed the address column from left to right?

This news from bitcoin.com and now they removed it.

https://webcache.googleusercontent.com/search?q=cache:HmnP7ZIcfN8J:https://news.bitcoin.com/ethereumchamber-a-new-ethereum-wallet/+&cd=1&hl=vi&ct=clnk&gl=vn

**Comment by kaprikor** [comment]
I sent the ETH to the address. But nothing happened. The transfer was lost, the ETH did not come http://prntscr.com/fgszlf  http://prntscr.com/fgtphj

**Comment by tayvano** [comment]
Please read:

[My ETH & Tokens were transferred out of my account. What can I do?](https://myetherwallet.groovehq.com/knowledge_base/topics/i-just-checked-my-account-and-all-my-eth-were-transferred-out-and-i-didnt-do-it)

[Protecting yourself and your funds](https://myetherwallet.groovehq.com/knowledge_base/topics/protecting-yourself-and-your-funds)

If you have questions about your specific case, please email us at support@myetherwallet.com. 

Thank you.
