### ISSUE TITLE
Contract deploy address displayed in the notification is wrong

### ISSUE THREAD

**Issue by karalabe** [kvhnuke/etherwallet#552]
I've just deployed a contract via MEW on Ropsten and saw that the contract address MEW gave me didn't match the one actually deployed:

This is the transaction: https://ropsten.etherscan.io/tx/0xdba1f65a880a424351618b91d1d1e72a7ffa79b24ead6e2188ee380e6eb0b44d

MEW displayed this address for the new contract: https://ropsten.etherscan.io/address/0x0bc3764efe148a9f2855304cc81d0e6d555581ee

The real deploy address is: https://ropsten.etherscan.io/address/0xae287510a5b2e1ecd9538e75dc0beff1b0e671c8

![screenshot from 2017-06-07 14-13-50](https://user-images.githubusercontent.com/129561/26875699-db82e4a2-4b8b-11e7-8d26-2fbad1c52c57.png)

**Comment by kvhnuke** [comment]
This might have to do with nonce not getting updated, let me check

**Comment by tayvano** [comment]
@kvhnuke I need an update on this.

**Comment by karalabe** [comment]
Btw, the second deploy displayed the correct address, so you might want to
look into if nonce 0 is acting up.

**Comment by tayvano** [comment]
@kvhnuke today

**Comment by tayvano** [comment]
v3.9.2
