### ISSUE TITLE
Address derivation differs between 3.8.5 and 3.8.9

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#557]
Going from 3.8.5 to 3.8.9, I'm observing that the same seed words and password yield different addresses. This could be a serious problem, as users who derived addresses with older versions of MyEtherWallet might be unable to access them with the latest version.

Here is a test case.

Seed words =
long robust trouble help poet staff bunker floor paddle elegant rich home

Password =
ether

With MyEtherWallet revisions 3.7.9 and 3.8.5, the derived addresses are as shown below.

path = m/44'/60'/0'/0
1st address = 0x9B04Ee4bBDe5C45A23aF2D21Db7D23c76c2D661D

path = m/44'/60'/0'
1st address = 0x251EdBff348e40da9118b0D064dF6f914A683E20

Revision 3.8.9 gives different addresses.

path = m/44'/60'/0'/0
1st address = 0xb31d472C81a12a25DaC3cd5293628ad3234B287C

path = m/44'/60'/0'
1st address = 0xEF0175a677979C7Dce1A3b86453A24bd1e3b17Bd

**Comment by fortran77** [comment]
I had barely finished submitting this and 55 seconds later I see "kvhnuke was assigned by tayvano a minute ago," Near-real-time, impressive.

**Comment by tayvano** [comment]
@fortran77 Are you running locally?   I'm getting 

```
path = m/44'/60'/0'/0
1st address = 0x9B04Ee4bBDe5C45A23aF2D21Db7D23c76c2D661D

path = m/44'/60'/0'
1st address = 0x251EdBff348e40da9118b0D064dF6f914A683E20
```
on MyEtherWallet.com

**Comment by fortran77** [comment]
For these tests I accessed 3.8.9 both https-locally and by accessing https://www.myetherwallet.com/ .

The older versions I accessed https-locally.

In both cases above "https-locally" means via a tiny https server written in python.

Note that I've been accessing MyEtherWallet only over the Internet as https://www.myetherwallet.com/ for a few weeks, and today for the first time I began getting the wrong addresses for my seed words. So I tested with the older releases as described above, and found that they gave me the correct seed words. So it looks like something has changed recently.

I am accessing MyEtherWallet with the Chrome browser built into Chrome OS.

Version 58.0.3029.140 (64-bit)
Platform 9334.72.0 (Official Build) stable-channel stumpy
Firmware Google_Stumpy.2.102.0.

The tiny https server is essentially the one found at:

https://www.piware.de/2011/01/creating-an-https-server-in-python/

**Comment by tayvano** [comment]
@fortran77 I just went through all the releases and could not recreate. Will you please double-check that this is happening for the keys above?  I'm quite confused.

**Comment by fortran77** [comment]
Here is one more data point.

Using 3.8.5 via my tiny https server, after I enter the same seed words and password as in my original report, I see that the default path m/44'/60'/0'/0 is already selected, and the 1st address is:

0xb31d472C81a12a25DaC3cd5293628ad3234B287C

Now I click on m/44'/60'/0' and then click again on m/44'/60'/0'/0. So now m/44'/60'/0'/0 shows as selected, as it was above by default, but the 1st address has now changed to:

0x9B04Ee4bBDe5C45A23aF2D21Db7D23c76c2D661D

If I try the same experiment with 3.8.9, clicking on  m/44'/60'/0' then on m/44'/60'/0'/0 gives me consistent results and the 1st address is always 0xb31d472C81a12a25DaC3cd5293628ad3234B287C.

So maybe the radio buttons for selecting the paths are not behaving identically between 3.8.5 and 3.8.9.

I'll try to get you more info as I can acquire it.

**Comment by fortran77** [comment]
And furthermore, if I use the same seed but leave out the password, then for path m/44'/60'/0' the 1st address is:

0x9B04Ee4bBDe5C45A23aF2D21Db7D23c76c2D661D

So clicking on m/44'/60'/0' then on m/44'/60'/0'/0 seems to erase the password when I use 3.8.5, but not when I use 3.8.9.

**Comment by fortran77** [comment]
OK, so it appears that in MEW up to 3.8.5, selecting the second path (hence not the default path) causes the password to clear. And the addresses are derived as if no password had been typed. In MEW 3.8.9 the password remains intact. That would explain everything I saw. If you can reproduce this, then maybe we have isolated the problem.

**Comment by tayvano** [comment]
@kvhnuke do you know anything about this? 😒

**Comment by kvhnuke** [comment]
Yes this is me fixing issue #534

**Comment by fortran77** [comment]
I missed that one -- so my issue report is largely a duplicate, now that I know what caused it.

**Comment by tayvano** [comment]
Okay but do people HAVE addresses in the unfixed versions? How long was this live for? There are people that email me every day that they have "mismatched" addresses. Now, admittedly, most have an 0x00 (parity) address or suddenly realize that they were using the wrong file, but these are the things I need to be aware of in order to save people's freaking ETH.

People do absurd things all day to lose, destroy, fuck themselves. We cannot be aiding to that absurdity. Especially since the line between "user error" and "something weird on the site" is a much finer than I originally thought....

**Comment by tayvano** [comment]
@kvhnuke I need a response on this.

**Comment by kvhnuke** [comment]
I think it is safe to close this
