### ISSUE TITLE
Can't connect to TREZOR (etherwallet offline)

### ISSUE THREAD

**Issue by tecpointgrip** [kvhnuke/etherwallet#558]
Hi,

I'm using latest dist-v3.8.9 and running it locally like this:

    >> chromium index.html #or
    >> google-chrome index.html #or
    >> firefox index.html

After selecting "View Wallet Info" and then "TREZOR", popup window will show, with the address

    https://connect.trezor.io/1/popup/popup.html

TREZOR's logo in the left upper corner and the 'Loading...' text field in the middle. It stays like that, no matter if I connect TREZOR or not. Output from developer console from chromium or google-chrome is following:

    Uncaught TypeError: Cannot read property 'substring' of undefined
    at parseIdentity (popup-dist.js:1259)
    at onMessage (popup-dist.js:1259)
    Failed to load resource: the server responded with a status of 404 () /favicon.ico 

and from the Firefox, it's quite different (I'm not aware of JS language):

    Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” 
    id=“toggleReaderMode”  
    browser.xul
    Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” 
    id=“key_browserToolbox”  browser.xul

    **TypeError: t[1] is undefined  popup-dist.js:1259:1672** <--- HERE something relevant

    Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” 
    id=“toggleReaderMode”  browser.xul
    Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” 
    id=“key_browserToolbox”  browser.xul

Additional information:

    Linux user;
    Mozilla Firefox 53.0.3
    Chromium 58.0.3029.110
    Latest dev branch of Google Chrome

When I select to connect to the TREZOR in the online version of myethwallet, mentioned errors are not visible and TREZOR is detected.
I'll try Opera in a moment, but I think this is something to investigate.

**Comment by tayvano** [comment]
You have to be connected via SSL in order to use hardware wallets. This is a requirement of the U2F protocol that the browser uses. If you want to do it local, you have to use USB (e.g. a chrome *app* or regular application) or set up a local sign-signed certificate

**Comment by tayvano** [comment]
Oh and Firefox doesn't support U2F so I don't think that Firefox works online either?

**Comment by tecpointgrip** [comment]
On Firefox with online version of MEW, I'm getting:



    To use your TREZOR device, proceed with instructions at TREZOR Wallet and try again afterwards.

    What is TREZOR?

So looks like you are correct.
Is there any tutorial how to setup self-signed certificate for MEW purposes? Or ideally, some ready to use Docker container? Don't get me wrong, but I think that while MEW is one of the most popular ethereum wallet with offline capabilities, this setup should be as easy as going to myethwallet.com. I'd like to not to go in 2 hours setup to do this:/

**Comment by tayvano** [comment]
@tecpointgrip I understand your frustration but I'm going to reiterate one more time:

This is something at the browser level and not a decision we made:

- The browser doesn't have access to USB devices

- A chrome extension doesn't have access to USB devices

- A chrome app does

- In the browser you can communicate via a thing called u2f

- Only some browsers support u2f

- The browsers that support u2f require that it be done securely via SSL

Feel free to open an issue on Chrome or Firefox as they are the ones who have the power to change this.

There are heaps of guides out there with varying degrees of difficulty for every OS:

https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-apache-in-ubuntu-16-04

I use an npm for local servers which you can set up to take a cert you generate:

https://stackoverflow.com/questions/35127383/npm-http-server-with-ssl

Lastly, your  TREZOR's purpose is  to  keep your keys offline. That's what it does. So what you are doing is doubling the offline-ness...which is fine...but if your only purpose is  to keep your keys offline...they already are.

**Comment by tecpointgrip** [comment]
Thanks for detailed explanations.

> Lastly, your TREZOR's purpose is to keep your keys offline. That's what it does. So what you are doing is doubling the offline-ness...which is fine...but if your only purpose is to keep your keys offline...they already are.

I understand your point. However, myethwallet is one and only tool which is officially recommend by TREZOR team - in online version, as far as I can see. But, how can I be sure that MEW online will be available in 3 years from now? That's why I'd like to have some offline way to get to my keys. If there would be some other application just to see my keys and allow basic view/send/receive functionality, I'd use it instead of MEW offline. I don't know any of such tool and it looks like guys from TREZOR don't know either.

**Comment by fortran77** [comment]
In Issue #557 I mention a tiny https server written in Python. It's very convenient for executing MyEtherWallet locally when you want to use a hardware wallet. You can find this tiny https server at:

     https://www.piware.de/2011/01/creating-an-https-server-in-python/

For your convenience I'm pasting the code below.

You can generate a self-signed SSL certificate with this command line and hit Enter in answer to every question (or maybe answer only the Common Name question with 'localhost'):

     openssl req -new -x509 -keyout localhost.pem -out localhost.pem -days 3650 -nodes

Run the https server after you cd into the directory that contains your index.html file. Then point your Chrome web browser to https://127.0.0.1:4443/ and skip past the various warnings (they mean nothing since you are running the https server on your own machine).

Both Python and Openssl are widely available for all common platforms.

Server code is below. Edit the path of the SSL certificate (see 'certfile') to point to wherever you have put the localhost.pem file that you got from the openssl command above.

    import BaseHTTPServer, SimpleHTTPServer
    import ssl

    httpd = BaseHTTPServer.HTTPServer(('localhost', 4443), 
    SimpleHTTPServer.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket (httpd.socket, certfile='path/to/localhost.pem', server_side=True)
    httpd.serve_forever()

**Comment by tayvano** [comment]
Let me know if anyone needs further help regarding this.
