### ISSUE TITLE
Ethereum Chambers took EVERYTHING - Help ME!

### ISSUE THREAD

**Issue by Abudinho** [kvhnuke/etherwallet#559]
I was hacked by ethereum chambers

All my ETH, ICOs, ERC Tokens - ALL GONE!

Is everything gone for good or there is any slim chance of getting anything back?

I have sent series of emails - no response.

Also sent DMs on twitter, got replies for a few, but no replies anymore!

Please help me! please!

**Comment by Longnguyeneth** [comment]
I had the same Abudinho! All my ETH had gone and no way to take it back! We have to start over, those ETH are my family's saving for the future.

**Comment by Abudinho** [comment]
Life !

3-4 years of patience - ALL Gone!
Even the future gone too with the ICOs
Must be something to become a millionaire in secs/hours just by hacking/scam!

I thank GOD for everything (good or bad)

**Comment by Longnguyeneth** [comment]
Best way is now to buy a Ledger Nano S to store crypto coins and still put ICOs on MEW but authenticate by the Ledger Nano S. This should be fine for future!

Don't trust any press release any more or you can use another PC to read those news. The PC for coins MUST BE clean.

**Comment by tayvano** [comment]
Please read:

[My ETH & Tokens were transferred out of my account. What can I do?](https://myetherwallet.groovehq.com/knowledge_base/topics/i-just-checked-my-account-and-all-my-eth-were-transferred-out-and-i-didnt-do-it)

[Protecting yourself and your funds](https://myetherwallet.groovehq.com/knowledge_base/topics/protecting-yourself-and-your-funds)

If you have questions about your specific case, please email us at support@myetherwallet.com. 

Thank you.
