### ISSUE TITLE
Importing from Icebox

### ISSUE THREAD

**Issue by Canalytic** [kvhnuke/etherwallet#56]
I am trying to figure out how to import a wallet from Icebox: https://github.com/ConsenSys/icebox

The encrypted wallet does not seem to be JSON or Keystore or Plain text private key.

**Comment by tayvano** [comment]
Do you have the seed or the file that ends with `................"nonce":"pNUG73rsX5igxYKDj9upXzQUAXfCNm3+"},"version":2}`?

**Comment by Canalytic** [comment]
Yes I have the seed.  and I also have a text that ends with "nonce"........"version":2}  What do I save text as in order to load it in myextherwallet?  When I save the text as .json, for example I am told that `this is not a valid wallet file`.  Also get the same error when I save as .txt file.

**Comment by kvhnuke** [comment]
Can you shoot us an email to myetherwallet@gmail.com I'll be happy to help you out

**Comment by tayvano** [comment]
For future people -- please email us if you somehow got your hands on a V2 JSON file and we'll help you out. It's not the easiest thing in the world.

We have no plans of adding derivation or decryption of v2 keys as they were only used for a few weeks.

**Comment by Canalytic** [comment]
I've still never gotten the v2 JSON file to import , unfortunately ...

**Comment by tayvano** [comment]
Shit... I thought we converted it for you? Or were you the one who found a different version of the key? 

Or are you still trapped in the v2 wallet?

Regardless, shoot us an email and we'll try to actually help you out this time.

**Comment by tayvano** [comment]
Future peeps: Please start a new issue or email us if you have a v2 keystore file that cannot be unlocked.
