### ISSUE TITLE
MyEtherWallet CX Chrome extension 3.8.9 ignores selected path

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#567]
This might be related to issue #557 (or maybe not).

Using the MyEtherWallet CX Chrome extension (installed from the Chrome Web Store, version 3.8.91), which identifies itself as 3.8.9, I added a wallet using this mnemonic phrase:

     long robust trouble help poet staff bunker floor paddle elegant rich home

The next screen asks me to select the path. But I notice that the generated addresses don't change with the selected path. Also entering a custom path doesn't change addresses. It's as if only the path m/44'/60'/0'/0 is actually used and any other selected/entered path is ignored.

Also, entering a custom path results in two radio buttons becoming selected at the same time.

**Comment by tayvano** [comment]
Its actually related to #569

The CX is not set up in the most ideal way for mnemonics but we're focusing on v4. Gotta sit tight until the transition occurs.

**Comment by tayvano** [comment]
merging with #569 for sanity
