### ISSUE TITLE
Making mnemonic-based wallet adding in CX more usable

### ISSUE THREAD

**Issue by leafcutterant** [kvhnuke/etherwallet#569]
MyEtherWallet CX 3.8.9
Chromium portable 60.0.3112.10

When I try to add a wallet via a mnemonic phrase, no button ever appears, but if I press enter while within the textbox, it displays the derived addresses. Most importantly, it's ambiguous because it's visible that a line-break is added before showing the addresses, and it's not clear whether the line-break is part of the seed or not. Also, it's unclear what derivation method is used to generate the addresses.

I'd suggest doing it with a button and adding similar derivation path choices as in the dist release would make it more reliable.

---

from #567 (related)

"I added a wallet using this mnemonic phrase:

     `long robust trouble help poet staff bunker floor paddle elegant rich home`

The next screen asks me to select the path. But I notice that the generated addresses don't change with the selected path. Also entering a custom path doesn't change addresses. It's as if only the path m/44'/60'/0'/0 is actually used and any other selected/entered path is ignored.

Also, entering a custom path results in two radio buttons becoming selected at the same time.

**Comment by tayvano** [comment]
The codebase for v3 is locked for features like these but I'll make a note of it for v4 👍

**Comment by leafcutterant** [comment]
Thank you very much!

**Comment by tayvano** [comment]
1 eth bounty for fixing bugs. 

2 eth if you make it work really well

**Comment by domalaq** [comment]
Hey! Fixed some of the issues mentioned above plus some more.

Couldn't reproduce the problem with disappearing button though, the bug might still be there.

**Comment by Zwilla** [comment]
ok, can I take the job?

**Comment by tayvano** [comment]
@Zwilla DM me on slack. There are like 60 issues on github. Which one's interest you most?

**Comment by tayvano** [comment]
@domalak Thank you -- I'll review in Am.
