### ISSUE TITLE
MyEtherWallet performing transactions on its own

### ISSUE THREAD

**Issue by baobabKoodaa** [kvhnuke/etherwallet#57]
I tried moving 0.1 ETH between my own accounts on MyEtherWallet on Google Chrome (via browser without the extension). I only tried to make 1 transaction, but somehow it performed 6 transactions, moving a total of 0.30122718 ETH into my other account. You can see these transactions listed here:

http://etherscan.io/address/0xd87dfb24fefd44e5d1f441fa086c724e53a73dfb

How is this even possible?

**Comment by tayvano** [comment]
Were you on MyEtherWallet.com?

Is the address above the address you were sending from or to?

**Comment by baobabKoodaa** [comment]
Yes, I was on MyEtherWallet.com. The linked address is the receiving address (the "to" address).

**Comment by baobabKoodaa** [comment]
I just realized something... earlier in the day I was trying to make transactions with Mist Wallet and none of them were going through (they showed up at 0 confirmations for 5 minutes, then just disappeared). The additional 5 transactions must be the ones I was trying to make with Mist Wallet!

So basicly, when I made a transaction on MyEtherWallet hours later, it somehow caused all the earlier transaction attempts to get executed as well?

**Comment by tayvano** [comment]
I'm not sure how transactions in Mist would relate to MyEtherWallet, or how one would cause the others to be sent. It may just be that your Mist finally got synced up or something with the network and they happened to be at similar times?

**Comment by baobabKoodaa** [comment]
All of the transactions show the exact same timestamp, down to the second. It would be a pretty odd coincedence if after hours of waiting Mist finally got synced up the exact same time that MyEtherWallet transaction goes through. In any case I realize this is likely a Mist / Ethereum issue. Thanks for the fast responses and sorry about wasting your time.

**Comment by jgeewax** [comment]
Seems like we should close this issue out? (It's scary to see this as an open issue -- I was glad to see that it wasn't really a bug !)
