### ISSUE TITLE
How can i use API etherwallet with C#?

### ISSUE THREAD

**Issue by 30amak** [kvhnuke/etherwallet#572]
Hi to all.
I'm C# programmer.
How can use API etherwallet with c#?For example (Send ETH)
Thank you.

**Comment by tayvano** [comment]
These are the JSON-RPC methods available for Ethereum and are how you make calls to a node: https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-methods

Your question is far outside the scope of this MyEtherWallet.com repo though so I suggest you join a community on gitter where a lot of Ethereum developers hang out as they will likely provide you with more guidance than we can here.
