### ISSUE TITLE
Incorrect public address shown after generating wallet offline

### ISSUE THREAD

**Issue by stuartbennett** [kvhnuke/etherwallet#573]
I cloned this repository and used it on an airgapped machine to generate a new wallet. After generation, the PDF was downloaded (which showed the private key and public address) but the public address that was shown in the web interface did NOT match. As I trusted the public address that was shown in the web interface, I copied and pasted that for use in a transaction, resulting in a loss of Ether. There must be a bug with how the public address is generated/shown in the interface.

**Comment by stuartbennett** [comment]
I also found https://github.com/kvhnuke/etherwallet/issues/360 which appears to be due to the same bug.

**Comment by tayvano** [comment]
Please email me (taylor @ myetherwallet dot com) the key and addresses and photo of your paper wallet. We have a backlog in the support inbox due to Bancor this morning.

99% of the time people say this they are noticing the difference in checksum vs non-checksum

Or you mis-typed the private key when you enter it back on web.

2 people in issue 360 found their correct address, 1 was on a fake MEW site, and 2 never gave me understandable details or keys, and 1 had copied the cipher text the first time and used that as the key and then returned to using the keystore file, which produced two different wallets.

**Comment by tayvano** [comment]
@stuartbennett Did you email me?

**Comment by stuartbennett** [comment]
Thanks @tayvano but I managed to resolve this myself. After your response I started to question whether I may have incorrectly typed the private key the second time round. I knew the public wallet address which contained the ether, but didn't know what the private key would be. In the hope that I had only made a single mistake while typing the private key, I wrote a node script that tried all possible combinations and this found my private key for me!

For anyone else that hits this same problem, here is my code that saved the day:

```
const hdkey = require('ethereumjs-wallet/hdkey');
const util = require('ethereumjs-util');
const Wallet = require('ethereumjs-wallet');

var characters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];

var basePrivateKey = 'THE_KEY_YOU_THINK_YOU_TYPED';
var targetPublicAddress = 'THE_PUBLIC_WALLET_ADDRESS_WHICH_CONTAINS_YOUR_ETHER';

for(var keyPosition = 0; keyPosition < basePrivateKey.length; keyPosition++){
	for(var character = 0; character < characters.length; character++){
		try{
			var privateKeyGuess = setCharAt(basePrivateKey, keyPosition, characters[character]);
			var wallet = Wallet.fromPrivateKey(new Buffer(privateKeyGuess, "hex"));
			var publicAddress = util.bufferToHex(wallet.getAddress());
			if(publicAddress.toLowerCase() == targetPublicAddress.toLowerCase()){
				console.log('*** FOUND PRIVATE KEY: ' + privateKeyGuess);
				process.exit();
			}
		}catch(e){
			// Invalid character
		}
	}
}

function setCharAt(str,index,chr) {
    if(index > str.length-1) return str;
    return str.substr(0,index) + chr + str.substr(index+1);
}
```

**Comment by tayvano** [comment]
Thank you for this. Glad you got it sorted, and I have no doubt that this will prove useful for someone in the future. Counting down to the day where we have QR codes on all the inputs :)

**Comment by isnead9** [comment]
hi, I have this same issue. But I do not know how to input the code or to run the code so that it will try each version of the key. Thanks!

**Comment by stuartbennett** [comment]
This can be closed now as @isnead9 has recovered what he lost (he emailed me).

For anyone else, MyEtherWallet is now using my script (https://myetherwallet.github.io/knowledge-base/private-keys-passwords/accessing-different-address-same-private-key-ether.html) and you can quickly use it from your browser at https://www.myetherwallet.com/helpers.html.

@tayvano does that mean I qualify for MEW stickers? :)

**Comment by hcarkeet** [comment]
@tayvano Hi Tayvano

I have had the same issue as https://github.com/kvhnuke/etherwallet/issues/360

I followed the steps 100% to get my account. I copied and pasted the private key into a notepad. My account number originally was different to what is in my UTC file. I only have one UTC file. I never downloaded any second one for any different account. 

Checked all of my PC including temp files and webdl files and no other private key or utc. 

I created a meta mask account but those addresses are different.

I have tried Stuart Bennett's algo and no luck. Genuinely feel ripped off. 

Are you able to help me? Is there a way to try every single possible private key and check it to the account where my coins are? I feel there must be someway of getting into an account just sitting there.

Also tried your support team

**Comment by numero41** [comment]
Hello @hcarkeet , I also have the same issue, but with Ledger, I don't have the same public address when I connect to Mew. Did you all find out a solution?

Here is my ticket (it's long thread, because at the beginning everyone told me I made a mistake, so I conviced myself I did, but I'm 100% sure I did NOT) :
#1528

And a post on Reddit :
https://www.reddit.com/r/ledgerwallet/comments/7rd798/should_we_be_concerned_about_the_ledger/

**Comment by numero41** [comment]
https://ethereum.stackexchange.com/questions/35062/myetherwallet-is-giving-me-another-address

**Comment by numero41** [comment]
https://www.reddit.com/r/Wavesplatform/comments/7qpjkv/same_seed_different_wallet_address/
