### ISSUE TITLE
how is double account avoided? 

### ISSUE THREAD

**Issue by pctripsesp** [kvhnuke/etherwallet#574]
sorry if it is an stupid question, but i am trying to understand how it checks if there already exists a private key in use before giving it to the user when creates a new wallet, if there are no servers checking.
in case is not checked, it is posible to give the same key to different users?

**Comment by tayvano** [comment]
This thread covers it: 
https ://www.reddit.com/r/ethereum/comments/6fr2lx/updated_its_time_to_get_real_stop_relying_on/diki8iz/

**Comment by tayvano** [comment]
adding stuff about this here: https://myetherwallet.groovehq.com/knowledge_base/categories/offline
