### ISSUE TITLE
Last 3 releases missing from releases page (and gas issue)

### ISSUE THREAD

**Issue by ccampbell** [kvhnuke/etherwallet#576]
According to https://github.com/kvhnuke/etherwallet/releases, the last version is 3.8.9, but on myetherwallet.com it is running 3.8.95.

I just finalized an ENS bid (running 3.8.9 locally) with the gas meter set at 1 Gwei, but the transaction was processed at 21 Gwei.

According to #527, this was fixed 11 days ago. Since 3.8.9 was released 6 days ago, I assumed the fix would be included. Is it possible it was deployed after 3.8.9?

Thanks!

**Comment by tayvano** [comment]
Apparently I need to update Travis. Sorry about that! Just manually added releases. 

I'm almost positive gas price fix was in 3.8.9 and all these little shits are tokens and stuff but maybe I'm wrong.

https://github.com/kvhnuke/etherwallet/releases/tag/v3.8.95

Regardless, here is the latest and greatest.

**Comment by ccampbell** [comment]
Thanks so much for the quick turnaround! I have another auction ending soon so I will try out the gas thing again using 3.8.95

**Comment by tayvano** [comment]
Please let me know. We keep going in circles with the gas thing. The all-star team is focused on V4 so I'm trying to keep things like this off their plate as much as possible.

**Comment by ccampbell** [comment]
It worked in 3.8.95! Took 30 mins for the first confirmation, but much much cheaper. Thanks again!
