### ISSUE TITLE
Hard fork and local wallet

### ISSUE THREAD

**Issue by richhorn** [kvhnuke/etherwallet#58]
Hi,

Sorry if this has been answered .. I did look elsewhere.

Is my myetherwallet wallet safe as is, on my pc (and backed-up), with the hard fork coming?
Should I do anything to protect it?

Thanks,
Rich.

**Comment by tayvano** [comment]
Yes and yes. No need to do anything. More info here: https://www.reddit.com/r/ethereum/comments/4tjrqs/myetherwalletcom_hf_dao_withdrawal_questions/

**Comment by richhorn** [comment]
Fantastic work! Congrats on the awesome project. Will send tip soon.

And congrats too, on your marriage. All the best,
