### ISSUE TITLE
5 ETH lost during wallet-creation on iOS

### ISSUE THREAD

**Issue by aresabi** [kvhnuke/etherwallet#584]
Hello guys,

i've purchased 5 ETH on btcdirect.eu. I've created a wallet on myetherwallet.com with my iPhone and safed the private key. Immediately after creating a wallet, i've copied the adress and pasted it on btcdirect.eu.
The ETHs were successfully sent https://etherscan.io/address/0xf17c2bf4dc47a0d7fe8ced6e6b344eb4fd4908a4

After typing the Private Key on myetherwallet.com, i get logged in to another wallet with no transactions and a different adress. 

I've checked for the dates, for every single character and made sure i've done it right.
But still no coins.

Any idea how to get my ETHs out of there?

**Comment by tayvano** [comment]
Please EMAIL US so that we can talk without comprising your security.

support at myetherwallet.com. Put URGENT in the subject line, but I'll be on the lookout.

**Comment by PepperParapente** [comment]
I have done EXACTLY the same thing as the guy above... I'm not sure if I should email the same person?
