### ISSUE TITLE
Withdraw Ethereum to different wallet address was generated by wrong private key

### ISSUE THREAD

**Issue by k-a-s-o-u** [kvhnuke/etherwallet#585]
Hello,
I used MyEthereumWallet and login by secret key but I mistyped it ( I noticed it after) and took it as true and sent my Ethereum from Bittrex.
After withdraw I re-login to MyEthereumWallet to type secret key but no deposit despite having waited for a long time.
I know here is the forum for Ethereum.js but I asked Bittrex but no help, also sent message to MyEtherWallet customer support last night.
I tried to re-login to another MyEtherWallet address I've withdrew to try to reappear my mistyped private key but have been unsuccessful to reappear 15 keys I generated so far...

I'm very sorry if this post is out of place here but please help me any advise is fine.
I've got transaction id and wrong wallet address and screen capture of withdraw on Bittrex as evidence.(I can send them to administrator in DM if they need.)

I'd like to know if there's decoding way to open the "wrong address" I've withdrew or would like to know efficiently generate mistyped key to use this links https://myetherwallet.groovehq.com/knowledge_base/topics/i-entered-my-private-key-but-it-opened-a-different-wallet-that-isnt-mine
But I'm not expert of js.(I just understood basic concept of Python.)

Sincerely,

**Comment by tayvano** [comment]
https://myetherwallet.groovehq.com/knowledge_base/topics/i-entered-my-private-key-but-it-opened-a-different-wallet-that-isnt-mine

If you want our assistance with private key matters your *need* to email us. I will not assist you here because it ultimately puts your private key in PUBLIC.

**Comment by k-a-s-o-u** [comment]
as I described I've sent message last night(2 days ago) to the team on your referred link. But no response so far. I haven't got even auto reply after sending message.
I will send request again now. Hopefully I would receive assist message from the team.
Thank you.

**Comment by tayvano** [comment]
We are a free service trying our very best to keep up with the 500+ emails coming in a day. Our average response time is 72 hours and we answer in the order they arrive. Please be patient.

**Comment by k-a-s-o-u** [comment]
Okay. I will wait patiently but in case I will send same request as I described here.
Now I'm trying to figure out analyzing Firefox forms log in .sql files but no information of MyEtherWallet.
I'm wishing to get back my withdrew Ethereum...
Thank you

**Comment by k-a-s-o-u** [comment]
Hi,
I've sent you documents,pics you asked me 1week ago already by e-mail and I've sent you message at 21st, 23th in order to ask its progress but no response.
So I came here to get contact you again.
How is it? I'm trusting you to solve this problem.
Thank you.
