### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by mrstormlars** [kvhnuke/etherwallet#593]
New versions of MEW sometimes contains new text in English, which isn't added to the translation files. Eg. new help-section to the right, and info-text at the bottom. Not a critical issue, but would be nice to have a clean page with only one language at a time...

**Comment by tayvano** [comment]
I try not to add to the translation files until I'm happy with the English. I think I've changed all that copy every update for the last 6 updates or so. :/

I can add under a [WIP] header. At least then if you are busy or whatever you will know that its not urgent and may change. 🤔

I'll go top to bottom soon regardless. There are a lot of little things.

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
