### ISSUE TITLE
Issue :Not a valid ERC-20 token

### ISSUE THREAD

**Issue by sanjeev2k12** [kvhnuke/etherwallet#595]
Hi !

I added iDice as a symbol and address is 0x5a84969bb663fb64F6d015DcF9F622Aedc796750

But i can see error ( Not a valid ERC-20 token ). Can you tell me , how i can fix this ?

**Comment by tayvano** [comment]
https://ethplorer.io/address/0x5a84969bb663fb64f6d015dcf9f622aedc796750

0x5a84969bb663fb64F6d015DcF9F622Aedc796750

dec  18

name idice
