### ISSUE TITLE
Input addres is not checksummed during BITY swap

### ISSUE THREAD

**Issue by wojtasss** [kvhnuke/etherwallet#598]
I can not do swap by BITY, after pass BTC address and encrypt wallet, on bottom pop up this info, after sent transaction nothing happen, probably something is wrong with new version of etherwallet

**Comment by tayvano** [comment]
@wojtasss Blockchain is clogged with ICOs. Things are taken hours to send. Please be patient and wait. We're doing our best to try to help network / mew get back on it's feet. Thank you
