### ISSUE TITLE
Trezor is not working locally

### ISSUE THREAD

**Issue by lx-production** [kvhnuke/etherwallet#601]
It works on the live website. But when I tried to run it locally connecting to my own Parity node, the option is there but the pop-up windows doesn't show up when clicked.

**Comment by tayvano** [comment]
This is a dupe but I'm on mobile. Try searching?

Basically you need to run a local SSL to use the U2F functionality to connect to your TREZOR

The easiest way is a self signed cert via node.js or python localhost.

**Comment by tayvano** [comment]
Duplicate #558 & #541
