### ISSUE TITLE
New "Check TX Status" Page

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#632]
1. Check Transaction Status (match "Create New Wallet" panel
    - TX hash -- input form-control
      - validate # characters, hex
    - Check TX Status - btn primary
    - ["How does it work?"](https://myetherwallet.groovehq.com/knowledge_base/topics/how-can-i-check-on-the-status-of-my-transaction-can-i-cancel-override-overwrite-replace-or-do-anything-once-a-transaction-has-been-sent)

2. If Mined
    - Pull copy from [How to Check The Status # 4 - first 3 bullets](https://myetherwallet.groovehq.com/knowledge_base/topics/how-can-i-check-on-the-status-of-my-transaction-can-i-cancel-override-overwrite-replace-or-do-anything-once-a-transaction-has-been-sent). 

3. If not found in TX Pool
    - Pull copy from [How to Check The Status # 4 - 4th bullet](https://myetherwallet.groovehq.com/knowledge_base/topics/how-can-i-check-on-the-status-of-my-transaction-can-i-cancel-override-overwrite-replace-or-do-anything-once-a-transaction-has-been-sent). 

4. If found in TX Pool
    - Pull copy from from [How to Check The Status # 4 - 5th bullet](https://myetherwallet.groovehq.com/knowledge_base/topics/how-can-i-check-on-the-status-of-my-transaction-can-i-cancel-override-overwrite-replace-or-do-anything-once-a-transaction-has-been-sent). 
        - TX Hash: { Link to Etherscan }
        - To Address: { }
        - From Address: { }
        - Nonce: { }
        - Gas Limit: { }
        - Gas Price: { }
    - "There is a chance you can cancel this transaction or replace it with a new one. If you wish to do so, please unlock the wallet you sent this transaction from".
    - ["How does it work?"](https://myetherwallet.groovehq.com/knowledge_base/topics/how-can-i-check-on-the-status-of-my-transaction-can-i-cancel-override-overwrite-replace-or-do-anything-once-a-transaction-has-been-sent)

4b. Wallet Decrypt Drtv

4c. Replace TX
    - "Warning: This features is in BETA. Use at your own risk."
    - "Warning: Do NOT change the value of these fields (unless you know what you are doing). If you do so, it could result in a more complex, expensive situation. These fields have been pre-filled for you & will attempt to effectively "cancel" your transaction."
    - ["How does it work?"](https://myetherwallet.groovehq.com/knowledge_base/topics/how-can-i-check-on-the-status-of-my-transaction-can-i-cancel-override-overwrite-replace-or-do-anything-once-a-transaction-has-been-sent)

    - To Address field - prefilled with from address of TXHASH
    - Amount  - prefilled with 0
    - Gas Limit   - prefilled with 21000
    - Gas Price - prefilled with gas price from TXHASH + 10 GWEI
    - Nonce - prefilled with nonce from TXHASH
    - Send Transaction Button
    - Confirmation Dialog (match from send transaction but with add'l fields)

![img_20170623_022022](https://user-images.githubusercontent.com/7924827/27479594-60a8d2c4-57c9-11e7-9022-d379fb67b5b6.jpg)

**Comment by obscuren** [comment]
> Gas Price - prefilled with gas price from TXHASH + 10 GWEI

I think you should make that **10%** (and double check this with other client implementations). I know that `geth` will only overwrite the transaction if the gas price is at least 10% higher than the previous one.

**Comment by tayvano** [comment]
@obscuren THANK YOU! @kvhnuke note this please

**Comment by tayvano** [comment]
v3.9.6
