### ISSUE TITLE
Cant print on chrome extension again

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#643]
> Chrome Paper Wallet

> I am trying to generate a Chrome Extension paper wallet, but it only produces a blank page and I am unable to generate it for a hard copy backup. Am I doing something wrong or is there a bug in the extension? I am using MyEtherWallet CX 3.9.3.

**Comment by Zwilla** [comment]
.nav-container {
    display: none!important;
  }
on print.less. Line 100

I use this only if no trusted printer is detected.

**Comment by crptm** [comment]
ref https://github.com/kvhnuke/etherwallet/pull/417

**Comment by tayvano** [comment]
3.9.9.7
