### ISSUE TITLE
Please provide a way of invoking this online wallet via https://github.com/ ...

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#66]
If possible, please provide some way of invoking this online wallet via a URL beginning with `https://github.com/...` (or, failing that, `https://<subdomain>.github.io/...`).

I don't mean a URL that merely redirects, but rather, a URL that remains in the address bar.

This provides a URL path that one can use with some assurance that one has not reached a hijacked domain. Also, should the SSL certificate for  `https://www.myetherwallet.com/` ever be found to be expired, the option to use `https://github.com/...` or `https://<subdomain>.github.io/...` will be helpful.

**Comment by tayvano** [comment]
Apparently we can't do this bc Github doesn't let you if you have a custom domain. 😞

So we can either have a custom domain on a different host, or serve to MyEtherWallet.com directly via github. 

If anyone knows a way to do this, please shoot me some links or add'l info.
