### ISSUE TITLE
Fallback URL keyed off github.com or github.io

### ISSUE THREAD

**Issue by fortran77** [kvhnuke/etherwallet#667]
Previously, I had proposed that MyEtherWallet be made available at a fallback URL keyed off github.com or github.io. See Issues #66 and #229.

Recently, somebody used social engineering to hijack the domain classicetherwallet.com which holds the official JavaScript wallet for Ethereum Classic, forked from MyEtherWallet.

     [reddit.com : ATTENTION: Classicetherwallet.com has been hijacked](https://www.reddit.com/r/EthereumClassic/comments/6kcwmi/attention_classicetherwalletcom_has_been_hijacked/)

Since we have a real example of this type of problem now, this would be a good time to reconsider my original proposal.

Fortunately they have an alternative URL where the same JavaScript wallet can be accessed:

     https://ethereumproject.github.io/etherwallet/

Maybe a corresponding github-based URL for MyEtherWallet could be implemented in the same manner.

**Comment by tayvano** [comment]
like https://kvhnuke.github.io/etherwallet/?

**Comment by fortran77** [comment]
Looks good, I had no idea it was there.

**Comment by tayvano** [comment]
Yeah basically shit goes in the back of my mind and then it gets done at some point and i forget to follow up. will add to footer under links too
