### ISSUE TITLE
How can i generate Eth address for my client?

### ISSUE THREAD

**Issue by 30amak** [kvhnuke/etherwallet#669]
Hello to all.
How can i generate Eth address for every my client?I want to separate every transaction my client.
Best regards.

**Comment by tayvano** [comment]
Your best bet is to use a custom script + etheruemjs libraries to work for your custom use-case. Finding a JS developer in this space isn't too hard -- just post a listing here https://ethlance.com/

**Comment by 30amak** [comment]
**Thank you dear developer.**
