### ISSUE TITLE
Add new Testnet Nodes for Infura.io. Check etherscan.io Ropsten node

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#675]

**Comment by moneroexamples** [comment]
Ropsten Revival node seems not to work. Will this be the new node?

**Comment by tayvano** [comment]
I'm waiting to hear back from Matt from etherscan about ropsten's status. We have infura testnet nodes coming too - not entirely sure what they have available. Hopefully it'll suit your needs though!

**Comment by kvhnuke** [comment]
@moneroexamples our ropsten node is back online

**Comment by moneroexamples** [comment]
@kvhnuke 

Thanks! :-)
