### ISSUE TITLE
Send Offline Tab Generates Address Validation Failure Message On Every Keystroke

### ISSUE THREAD

**Issue by Complexity** [kvhnuke/etherwallet#677]
Looks like the **Send Offline** address validation for the two address fields (**From Address** and **To Address**) is set to validate on every keystroke change.

<input class="form-control ng-pristine ng-valid ng-empty ng-touched" type="text" placeholder="0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8" ng-model="tx.from" **ng-change="validateAddress(tx.from,'')"**>

However, when an address is invalid, it generates an **danger** error alert, to which **uiFuncs.notifier** gives a duration of 0, which means it hangs around forever. As this is happening on every keystroke, the screen fills with errors.

Maybe it would be better to validate on submit? **On a related note**, there is no error message if an invalid address is entered and the **Generate Information** button is pressed - instead nothing happens. Validate on submit would kill two birds with one stone.

**Reproduce**

Navigate to the **Send Offline** tab and begin typing into either the **From Address** or **To Address** fields. (Or paste a valid address and edit it in some way to make it invalid.)

**Expected Behaviour:**

Validation of address generates one informative error whilst you are typing. It eventually disappears.

**Current Behaviour:**

OMG it's full of bars.

<img width="1329" alt="screen shot 2017-07-02 at 09 26 03" src="https://user-images.githubusercontent.com/756897/27768460-79d03cfe-5f14-11e7-9dea-1b8e6f474ea5.png">

[MEWValidation1.mov.zip](https://github.com/kvhnuke/etherwallet/files/1117692/MEWValidation1.mov.zip)

**Comment by Complexity** [comment]
Damn you guys are quick. ;)

**Comment by tayvano** [comment]
If I can fix it, I try to do it right away or else itll never get done 😂

Also made the to address field ENS-compatible finally. Yay!
