### ISSUE TITLE
Bulk paper wallet page break

### ISSUE THREAD

**Issue by realcodywburns** [kvhnuke/etherwallet#68]
![screenshot](https://cloud.githubusercontent.com/assets/13103499/17864788/2a5f3afe-6865-11e6-946e-3440b586e8c1.png)
![screen shot2](https://cloud.githubusercontent.com/assets/13103499/17864789/2a607f0e-6865-11e6-9bcf-c3bff0adf939.png)

This issue I am having is when printing bulk wallets the `function generateWallets()` does not recognize page breaks.

adding something like:
`if (i-1) % 3 == 0{ <div class="pagebreak" style="page-break-after: always;"></div>}`
in the [globalFuncs.js](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/globalFuncs.js#L12) might fix it, but i haven't had time to test it yet.

**Comment by tayvano** [comment]
kvhnuke just added some bottom padding so that 3 fit per page. the page-break thing seemed to not be consistent. Apparently, this is a new thing that I screwed up when I switched the placement of the notes with the rightmost QR code. Whoops.
