### ISSUE TITLE
ENS Ropsten -- Registry requiring owner does not show account information

### ISSUE THREAD

**Issue by Nammalvar** [kvhnuke/etherwallet#689]
Hello,

I made a bid on ropsten with myetherwallet and went thru. On contract address `0x112234455c3a32fd11230c42e7bccd4a84e02010` when I request the owner of `0x8338ce36960756c347537badd974579a9e627fa8febe6523b9e426f40008d165` via `https://www.myetherwallet.com/#contracts` I get address `0x0000000000000000000000000000000000000000`. 

On the contrary when I do the same request via `https://ropsten.etherscan.io/address/0x112234455c3a32fd11230c42e7bccd4a84e02010#readContract` I have the response I wish, i.e. `0xa32cf44585bc9891586734fc2ee87c5ef09d7a8c`, the bidding account. 

By chance this account is the second ETH account of a ledger nano S (I don't think this last precision is of any interest but...)

**Comment by tayvano** [comment]
@Arachnid Do we have outdated Ropsten information somewhere?

Configs Folder: https://github.com/kvhnuke/etherwallet/tree/mercury/app/scripts/ensConfigs

Ropsten: https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/ensConfigs/ROPConfig.json

```
{
    "public": {
        "resolver": "0x4c641fb9bad9b60ef180c31f56051ce826d21a9a",
        "reverse": "0xdb6cead81ce14a63c284728eed17738a81327ff0",
        "ethAuction": "0xc19fd9004b5c9789391679de6d766b981db94610"
    },
    "registry": "0x112234455c3a32fd11230c42e7bccd4a84e02010"
}
```

**Comment by Arachnid** [comment]
The registry address is correct, which is all it should be touching here.

**Comment by kvhnuke** [comment]
Ropsten node was waaaaaay behind, it caught up now. Problem solved :+1:
