### ISSUE TITLE
"My Wallets"

### ISSUE THREAD

**Issue by JohnDoe389** [kvhnuke/etherwallet#691]
Perhaps I'm not properly understanding the distinction between 'wallet' and 'account'.   

A wallet as I understand the term is an interface to manage one or more accounts.   An account is a set of keys to control funds on a blockchain.

An installation of MyEtherWallet is a wallet.  It lets me manage multiple accounts.  If I want to add an additional account to that wallet, I should see a command "Add account" not "Add wallet", and if I want to manage them the tab should say "My accounts" not "My wallets".

Or not?

**Comment by tayvano** [comment]
Yeah I'm doing that next. This is one of the reasons for the
definitions post. Wanted to wrap my head around everything and circle back and update  😂

**Comment by JohnDoe389** [comment]
tx
