### ISSUE TITLE
API endpoint issue when is used from Web3.js library

### ISSUE THREAD

**Issue by jarenal** [kvhnuke/etherwallet#697]
Hi there @kvhnuke @tayvano 

I've noticed that now your API endpoint...

https://api.myetherapi.com/eth

Now requires in all the requests to add a "Origin" header for works correctly.

Some examples:

Before this call works fine:

`curl -H 'content-type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8", "pending"],"id":1}' https://api.myetherapi.com/eth`

But now only works if you add the origin header:

`curl -H 'content-type: application/json' -H 'origin: https://www.myetherwallet.com' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8", "pending"],"id":1}' https://api.myetherapi.com/eth`

If you don't use the origin header the API endpoint return the next error:

`{"errorMessage":"Cannot read property 'match' of undefined"}`

Finally the issue is that you can't use the Javascript library https://github.com/ethereum/web3.js/ for to connect to your API endpoint https://api.myetherapi.com/eth

**Comment by kvhnuke** [comment]
fixed, thanks for letting us know

**Comment by MIGUELWAXX** [comment]
all the best!
