### ISSUE TITLE
The action could not be processed due to a server overload.

### ISSUE THREAD

**Issue by jamesray1** [kvhnuke/etherwallet#724]
The bane of centralization:
![2017-07-11 19_26_33-myetherwallet_ open-source client-side ether wallet](https://user-images.githubusercontent.com/16969914/28061750-ee385336-666e-11e7-9721-ebdc96611629.png)

Occurs after loading a keystore file and entering the password.

**Comment by tayvano** [comment]
@jamesray1 You need to move all your funds in that account now. 

We don't have servers that get overloaded. That is a phishing site.

MyEtherWallet is a _client-side wallet_, which means you hold your keys. If someone gets your private key (keystore file, mnemonic, passwords), they have complete access to your funds. There is no stopping transactions, canceling transactions, or resetting passwords.  *You are responsible for your safety and security*

*  Never enter your private keys, passwords, sensitive data on a website that you were sent via message (right now the scams are targeting MyEtherWallet. Tomorrow it may be Kraken or Paypal)

*  ONLY unlock your wallet when you want to _send a transaction_. Check your balance via https://etherscan.io/, https://ethplorer.io/

*  Do not trust messages or addresses or URLs sent via private message. Always verify information w/ a secondary source. 

*  Always check that you are on the correct URL. (myetherwallet*.com*)

*  Get a hardware wallet, like Ledger or Trezor or Keepkey or Digital Bitbox: https://myetherwallet.groovehq.com/knowledge_base/topics/hardware-wallet-recommends

*  We have a Chrome Extension that will warn you if you attempt to navigate to a malicious site: https://chrome.google.com/webstore/detail/etheraddresslookup/pdknmigbbbhmllnmgdfalmedcmcefdfn

*  We have the MyEtherWallet Chrome Extension: https://chrome.google.com/webstore/detail/myetherwallet-cx/nlbmnnijcnlegkjjpcfjclmcfggfefdm

*  You can run MEW locally and avoid the website URL situation entirely: https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-run-myetherwallet-dot-com-offline-slash-locally

*  More best-practices can be found here: https://myetherwallet.groovehq.com/knowledge_base/topics/protecting-yourself-and-your-funds

*  Consider following us on Twitter for up-to-date warnings and information: https://twitter.com/myetherwallet

Please, be careful out there. 💖 🙏

**Comment by jamesray1** [comment]
@tayvano I haven't deposited any funds on that site. The site was http://myetherwallet.com.de. But I did use the keystore file on that site, so I won't use the actual wallet and delete the keystore file so I don't use it again.

**Comment by jamesray1** [comment]
I have a comment on this:
https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-run-myetherwallet-dot-com-offline-slash-locally
https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-safely-slash-offline-slash-cold-storage-with-myetherwallet

Getting another computer is expensive. I think I'll just put the zip file on a USB and then plug in the USB when I need to use the wallet. But I guess the wallet could still be hacked when plugged in.

I'll just get a hardware wallet.
