### ISSUE TITLE
A FUN token showed up with error

### ISSUE THREAD

**Issue by aericson** [kvhnuke/etherwallet#746]
Hello,

I've claimed an `EOS` token and after I did it (and before adding a custom token) a `FUN` token appeared. This `FUN` token shows a `Not a valid ERC-20 token` instead of the number of tokens.

I ignored it and went ahead and added the `EOS` token:
Address: 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0
Token Symbol: EOS
Decimals: 18

And now both are showing up. To be clear, I did not purchase a `FUN` token.

![screen shot 2017-07-14 at 22 23 14](https://user-images.githubusercontent.com/692542/28235387-13e809e8-68e3-11e7-90f3-beb08e5345de.png)

Is there anything wrong with my wallet? Can I ignore it?

Thanks!

**Comment by tayvano** [comment]
FUN wasn't a valid ERC token. It's fixed now.
