### ISSUE TITLE
Myetherwallet ID hacked!

### ISSUE THREAD

**Issue by ncyber527** [kvhnuke/etherwallet#756]
I didn't send my ethereum yesterday!
But yesterday someone transfered my ether!
I didn't know who he is!
And i never signed in that time!

Receiver id is 0x858457daA7e087ad74cDeeCEAb8419079bC2cA03

And my id is 0xf2f2904E4f9FA57a7db9fc39D8934bE558182B6E

Please help me.. i need my ether back!

My emailnis ncyber527@gmail.com

Please let me know!!

**Comment by tayvano** [comment]
Please be careful!

What to do if you got phished:
https://myetherwallet.github.io/knowledge-base/security/phish-hacks-thefts-and-stolen-funds-due-to-phishing.html

Protecting yourself and your funds: 
https://myetherwallet.github.io/knowledge-base/getting-started/protecting-yourself-and-your-funds.html

**Comment by ncyber527** [comment]
Thx for your reply.
But is there any way to retrieve my ether?!

I affix some screenshots.
I really need that ether..

My id is 0xf2f2904E4f9FA57a7db9fc39D8934bE558182B6E

His id is 0x858457daA7e087ad74cDeeCEAb8419079bC2cA03

It was stolen between 7. 17-7.18


Please..please!

**Comment by ncyber527** [comment]
2017년 7월 18일 (화) 오후 5:04, SeungWook Choi <ncyber527@gmail.com>님이 작성:

> Thx for your reply.
> But is there any way to retrieve my ether?!
>
> I affix some screenshots.
> I really need that ether..
>
> My id is 0xf2f2904E4f9FA57a7db9fc39D8934bE558182B6E
>
> His id is 0x858457daA7e087ad74cDeeCEAb8419079bC2cA03
>
> It was stolen between 7. 17-7.18
>
>
> Please..please!
>
mine is 5.4 ethereum.

>
>
>

**Comment by ncyber527** [comment]
I tried to find where i linked.
But i coudn't find. Cuz i always remain
Etherwallet.com on my cellphone.

How.. could it happen!

**Comment by meanaverage** [comment]
You've fallen for a scam, ncyber527. It is extremely unlikely that they will be returned to you. You should also not use that wallet ever again as the private keys are compromised.  
  
Please see here for others who have been scammed by the same link (funds sent to same address): 
https://etherscan.io/address/0x858457daa7e087ad74cdeeceab8419079bc2ca03#comments

**Comment by ncyber527** [comment]
So you mean i can not get my ethereum back??
There are so many people same like me!

It is an one of technical problems!
You also have responsibility about this!!

It is unfair!!

**Comment by meanaverage** [comment]
How would you propose you get it back? You entered your private keys into a site pretending to be myetherwallet and they've taken your money. Why would someone who would do something so malicious give you your money back?

I agree, it is unfair that people are being scammed out of their money, but people also need to stop falling for scams. You need to be careful when dealing with private keys. Don't use untrusted wifi. Don't click on any links pretending to be myetherwallet. Don't mistype the domain in the url bar, etc.

You are lucky it was only 4 ether. Look at the transaction below yours for 105 ether from just a couple hours ago. That person likely feels a little worse. Every single person on this transaction list has been scammed in the same way, and you are stating that this is a glitch and you did nothing to fall for this scam?

Also, I have no responsibility in this. I have no connection with the scammers. I'm just a person reading github passing by and saw a unfortunate cry for help.

**Comment by ncyber527** [comment]
You are not relative to myetherwallet?!
I thought you are the operator or developer of myetherwallet.

So who are you?!

**Comment by MrLuit** [comment]
Your money is gone. Nothing we can do about it.

**Comment by ncyber527** [comment]
OMG; you are so irresponsible.

Why do your company exist?
What is your site function?

I think nothing.
Just store other people's ethereum without any security system and any
responsibility.

I am really disappointed with your company!

I will tell everyone who i know,
Do not use your system.

**Comment by MrLuit** [comment]
We don't store your ether. You do. It's your responsibility to keep your private key safe.

**Comment by ncyber527** [comment]
Yes. But your company also have a responsibility to keep my ether safe!

**Comment by ncyber527** [comment]
Not only my ether, but also your customers!

But you just try to avoid your responsibility.

**Comment by polynamaude** [comment]
@ncyber527 You don't seem to understand much about how the system works. The basis is a irreversible ledger so how could magic give you back your ether. Also you're so ignorant that you're getting mad at a pure stranger who only did the mistake of wanting to give you information about what just happened to you.

**Comment by etheroid** [comment]
if you need your stolen or lost bitcoins , ethereum and other cryptocurrency recovered, contact recovercoins(@)consultant.com, their team of hackers can trace lost or stolen crypto and get it back fast.

**Comment by MrLuit** [comment]
Don't contact anyone claiming they can recover your coins, there's a very high chance they are only out to get your private key and take your remaining coins.

@kvhnuke (likely) a scam ^

**Comment by hackmod** [comment]
![image](https://user-images.githubusercontent.com/32324335/42735415-660e6dd6-888e-11e8-8469-ffea0f9fa624.png)

**Comment by topacs1985** [comment]
Please this address 0xac98BbbcD883f46B97F94746B24F6d757f6263c9 has been used in a phishing scam he's made away with my tokens and he's stealing many more token, please kindly assist in stopping it before he harm many more individuals.. Below are the coins he's stolen from me..
![Scam](https://user-images.githubusercontent.com/39902590/58407136-04abdb00-8063-11e9-8b99-5d51073c1583.jpg)
