### ISSUE TITLE
Missing Etherscan Explorer links on View Wallet Info

### ISSUE THREAD

**Issue by mtbitcoin** [kvhnuke/etherwallet#757]
When using a hardware wallet (i.e Trezor or Ledger) and clicking on the the Connect to <device> which will then show a list of addresses tied to that hardware wallet, the Etherscan Explorer link is missing from the page of corresponding addresses. 

https://prnt.sc/fx1quj

Only the ethplorer link is shown which does not show the complete list of transactions related to that address

**Comment by tayvano** [comment]
Weird. I will link the ETH balance param to etherscan again.

**Comment by tayvano** [comment]
v3.9.9.7
