### ISSUE TITLE
Unlock wallet and send transaction with string url

### ISSUE THREAD

**Issue by 30amak** [kvhnuke/etherwallet#764]
Hello.
How can i unlock my wallet automate  and send transaction with string url?
I must to add my private key manually?
Best regards.

**Comment by tayvano** [comment]
Yes, you must add your private key manually. In v3.10 this will be a bit more automated luckily, but you will always have to add your private key as otherwise it would be in a URI and that's a truly insecure way of doing things. :)

**Comment by 30amak** [comment]
Thank you for your reply.
Can i add private key in URL string and post it?

**Comment by tayvano** [comment]
no

your private key is sacred. if anyone gets access to your pk they **can take all your ETH AND TOKENS!**

Never put it in a URL. Ever.

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
