### ISSUE TITLE
"Add custom token" should support ENS names in the address field

### ISSUE THREAD

**Issue by Arachnid** [kvhnuke/etherwallet#774]

**Comment by tayvano** [comment]
v3.9.9.7

**Comment by Arachnid** [comment]
Have I ever mentioned how awesome you guys are?

**Comment by tayvano** [comment]
I still cant figure out the get decimals thing though 😒

**Comment by Arachnid** [comment]
There's an _optional_ feature of ERC20, `function decimals() returns (uint8)`. I was suggesting calling that on the entered name/address and, if it returns a valid value, using that.

**Comment by tayvano** [comment]
Yeah I got that far....a lot of contracts seem to use name / symbol too so we could check all of them.

The think I'm having trouble with is the actual calling part. I tried to just rework from ENS or contracts page but it didn't work out. I'll try again tomorrow. :)
