### ISSUE TITLE
Small Error in Typography

### ISSUE THREAD

**Issue by Varunram** [kvhnuke/etherwallet#783]
<img width="1280" alt="screen shot 2017-07-26 at 9 59 37 pm" src="https://user-images.githubusercontent.com/18598959/28634703-ae74deac-7255-11e7-98e6-5b4ca2964593.png">
Not much of an issue, just a small typo :)

**Comment by tayvano** [comment]
🤦 Thanks for letting us know. Let me know if you see anymore.
