### ISSUE TITLE
Add Custom Token: "Not a valid ERC-20 token"

### ISSUE THREAD

**Issue by chrishobcroft** [kvhnuke/etherwallet#787]
Address: 0x4FcFE848AB0eE7f57c2ecf9BA7C88FE20BC169f3

I added "TVC" as a token and it is saying "Not a valid ERC-20 token".

Please can you help me to understand what I do next on this platform?

Thanks, Chris

**Comment by tayvano** [comment]
https://ethplorer.io/address/0x4fcfe848ab0ee7f57c2ecf9ba7c88fe20bc169f3

This is not a token. What is the token's address?

**Comment by chrishobcroft** [comment]
Hmm, I don't understand :|

I'm trying to create a custom token called "TVC".

I use myetherwallet.com to try to do this - inside a wallet with address 0x4fcfe848ab0ee7f57c2ecf9ba7c88fe20bc169f3 (see screenshot).

But perhaps this isn't the way to do it?
![myetherwallet marked up](https://user-images.githubusercontent.com/2212651/28779956-50bf90d2-7605-11e7-913e-a4513a46320f.png)

**Comment by tayvano** [comment]
I can't seem to find TVC on ethplorer. What is the website / name / anything of the token?

The address and decimals are written into the tokens contract code. You need these pieces of information in order to add the token and interact with it.

**Comment by Catspro** [comment]
...This was how i got it resolved. I created a private network,mined,got some ethers, created a erc20 token contract.Afterwards,I came back to myetherwallet.com and did as instructed and it worked.

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
