### ISSUE TITLE
Unable to open index.html on chrome

### ISSUE THREAD

**Issue by pgvenu** [kvhnuke/etherwallet#820]
Hi ,
am new to cryptocurrency. was trying to generate offline MEW from the latest release of etherwallet. when clicking on index.html file and opening on chrome - not showing the MEW wallet generator web page - shows webpage with just content without any graphics or tabs or links.  Is there some extension i should install on chrome . Tried mozilla and IE too . not working - can somebody suggest a solution. Am i missing something here? see the screenshot attached below.
![screenshot 2017-08-06 at 3 15 25 pm](https://user-images.githubusercontent.com/30780905/29006675-2ac6c7d8-7aba-11e7-8f66-b6fe89bb4b78.png)

Thanks in advance

**Comment by tayvano** [comment]
You need to right click on folder, click extract, and then double click on index.html.

**Comment by pgvenu** [comment]
got it , thank you so much :-)
