### ISSUE TITLE
wallet files folder

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#823]
Hi.
First of all thank you for doing such great project. It's really helpful.
I have a few question about Chrome extension: 
1. When i create new wallet in ,  json key file creates automatically? Or only when i choose to save it?
2. In what folder stores wallet files? Is it encrypted?

**Comment by tayvano** [comment]
1. Yes, keystore / JSON is created automatically 

2. Saved in chrome.storage which is like local storage but for chrome extensions. It's encrypted with the password of your choosing and then chrome.storage is encrypted by your google password if you are signed in to Chrome. 

You need to back it up though to your computer though.

**Comment by ghost** [comment]
Thank you a lot :+1:
