### ISSUE TITLE
GasLimit always coming as -1

### ISSUE THREAD

**Issue by farhankhwaja** [kvhnuke/etherwallet#866]
When I am trying to execute my contracts function, the gas estimate is coming as -1 and thus I am not able to execute my function.

Here's your Modal View:
![image](https://user-images.githubusercontent.com/956024/29195401-2fcc3304-7de3-11e7-8057-e088cd2faceb.png)

Please if you can help me with this.

**Comment by tayvano** [comment]
You can manuallly change it but it means that you the contract you are attempting to interact with will throw and there will be an error.

**Comment by farhankhwaja** [comment]
Oh ohk. Cool thanks. How do you find out whether the contract will give an error before execution??

**Comment by gamalielhere** [comment]
Closing this issue. Don't hesitate to reopen if needed.
