### ISSUE TITLE
Double transaction with MyEtherwallet chrome plugin

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#887]
"please check you quick send option in the chrome plugin. When making a quick send transaction, the message returns that the transaction is broadcasted but it also still show the 'send transaction' button and pass word field. This allows for a double transaction and causes confusion if the transaction is actually started. It happened to me that I send an amount twice.

Thank you"

**Comment by Zwilla** [comment]
at quickSendCtrl.js past this on line 93

```
    $scope.selectedWallet = "";
    $scope.password = "";
    $scope.$parent.selectedWallet ="";
    $scope.tx.to = "";
    $scope.tx.value = "";
```

**Comment by tayvano** [comment]
Done. Thanks
