### ISSUE TITLE
Token Balances No Longer Displayed 

### ISSUE THREAD

**Issue by montehansen** [kvhnuke/etherwallet#894]
The production version as of today is not displaying my token balances when online or offline. Older versions display my tokens offline without any trouble (for instance, v3.9.9.7).

This is frustrating because in this case the wallet is located on a Trezor device and I am NOT able to send my tokens. I can look, but I cannot touch.

Monte

**Comment by montehansen** [comment]
I neglected to mention I am on macOS Sierra v10.12.5 and Chrome Version v60.0.3112.90 (Official Build) (64-bit)

**Comment by montehansen** [comment]
Not sure why, but it turns out I needed to manually add the token contract addresses of interest. "Display All" would display none. Although I am able to work around the issue, it is still an issue. That is, something about either this wallet or the latest version of MEW is failing to fetch or mask the well-known list of token addresses.

Shouldn't matter but just in case, the wallet is managed by Trezor.

Thanks,

Monte

**Comment by stefek99** [comment]
I was going to open an issue...

(you were 2 hours earlier)

Something not right.

![image](https://user-images.githubusercontent.com/249703/29341526-c81b14a8-821c-11e7-8e12-f4a323c3d1f2.png)

**Comment by 2pizzas** [comment]
The same happens to me, version 3.10.2 was OK but with 3.10.2.1 it is no more possible to view or send tokens. Both tested with Chromium and Firefox under Ubuntu 16.04.3 LTS 32 bits. Seems not being platform dependent.

**Comment by Zwilla** [comment]
I can confirm this, also.

**Comment by Zwilla** [comment]
I was working today on merging mew old commits (+-5days) into myTokenWallet.com, and during this work I had to fix many problems and I remember that I had before some ours the same problem. But at moment mtw works for me and shows all tokens. 

If you want to test it your are welcome at: https://mytokenwallet.com 
On the toolbox menu I have a Mnemonic Code Converter (it is set by default to ETH) so you can play and test if it is network problem. Remember: Security is hard!

Now I will dig into mew also to find the bug

**Comment by montehansen** [comment]
They are appearing for me now (under v3.10.2.2).

Thanks for looking into it.

Monte

**Comment by kevinmonahan** [comment]
The tokens were taken down due to an exorbitant amount of calls due to Ox ico irresponsibly handling their deployment. They are back up now.

**Comment by 0xcaff** [comment]
https://ethereum.stackexchange.com/questions/24428/using-trezor-my-list-of-tokens-is-gone-and-my-alt-coins-do-not-appear-in-myethe/24429#comment25567_24429
