### ISSUE TITLE
Tried to send a token with too little gas 

### ISSUE THREAD

**Issue by aakashshiv** [kvhnuke/etherwallet#895]
Tried to send 336 HMQ to liqui. Set way too little gas. The transaction failed but more than 336 HMQ has left my wallet. Where is it? Thanks.

**Comment by kevinmonahan** [comment]
This belongs in support, not github @aakashshiv support@myetherwallet.com

**Comment by tayvano** [comment]
When you send a transaction with two little gas, the funds never leave your account. So, they are still in your account, unless you have sent a subsequent valid transaction with enough gas. You can learn more here: https://myetherwallet.groovehq.com/knowledge_base/topics/what-is-gas
