### ISSUE TITLE
Security Warning! Uninstall MetaMask - injecting JavaScript into MEW and MTW

### ISSUE THREAD

**Issue by Zwilla** [kvhnuke/etherwallet#904]
### 17. August 2017
* uninstall MetaMask Wallet, this software wallet is injecting inpage.js:36 into
  [MyTokenWallet](https://mytokenwallet.com) and [MyEtherWallet](https://myetherwallet.com) !
    * proof 1: ![](https://goo.gl/pxaav2)
    * proof 2: ![](https://goo.gl/8RYS4j)
    * proof 3: ![](https://goo.gl/o2rA38)

more warnings here: [Warnings](https://github.com/Zwilla/mytokenwallet.com/blob/master/docs/1-Security-Warnings.md)

MetaMask: current state: NO 0-Trust Model Wallet
read more about: [0-Trust](https://goo.gl/yQr47K)

I just mean, today this script and tomorrow the app is hacked and than ???

**Comment by 0xcaff** [comment]
Wrong place for this issue. How else is MetaMask suppoused to inject a web3 provider into pages then?

**Comment by Zwilla** [comment]
let me inject a script into your wallet:

```
if (user has more than 0.01 ETH on his wallet) { 
send me the private key;
transfer all the money to my wallet;
}
```
ok?

**Comment by tayvano** [comment]
Not sure why this is here. You can talk with MetaMask about their security model.

**Comment by Zwilla** [comment]
Because you added this insecure model into your wallet. Without any warning to the users. MEW is your baby and not MetaMask’s. Sorry but I’m missing the security warnings!

**Comment by tayvano** [comment]
Literally nothing has changed. You severely misunderstand what MetaMask did before and what it does now. 

If you do not like MetaMask security model, do not use MetaMask. Problem solved.
