### ISSUE TITLE
I got ERROR:Invaild sender on my private chain 

### ISSUE THREAD

**Issue by soy-sauce-rice** [kvhnuke/etherwallet#921]
I connected the etherwallet to my private chain.Now,i can check my balances,but when i wanna send a transaction,i got an error like this.
my command is ```geth --identity "development"  --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --rpccorsdomain "null"  --datadir "./node1" --port "30303" --rpcapi "personal,db,eth,net,web3"    --networkid 999  console```
![2017-08-23 23-57-48](https://user-images.githubusercontent.com/27428177/29625817-5c87e038-885f-11e7-8c74-f406044887c5.png)

**Comment by tayvano** [comment]
Please select the "custom" radio button in the add custom node popup. This should resolve this issue, I hope.

**Comment by anna-mo** [comment]
@tayvano i have the same question, but i always in a custom node which select ELP-155 to make sure the chainId will not be 1, but once send transaction the raw transaction will occurs, always show that chainid=1 ,and comes an invalid sender error, i don't know what's wrong

**Comment by tayvano** [comment]
Can you please try on https://mycrypto.com and let me know if you have the same issue.
