### ISSUE TITLE
Tokens that not listed 

### ISSUE THREAD

**Issue by d1my4n** [kvhnuke/etherwallet#945]
Hello, I have few questions about the ERC20 tokens
I have the offline wallet, and i wanted to send there a token that is not listed in the default token list
what happens when I send that tokens to the wallet that tokens are not listed in?
Do they dissapear? 
lets say they are not dissapear , if i come back after a year and making "custom add" , will it recognize them?

and the last question is, could you add IFT (investfeed token) to the default list in the next update?

Thx
 good day

**Comment by tayvano** [comment]
You tokens are held on the blockchain and adding a token to MEW is simply adding it to the user interface. You can access any tokens on MEW via our interface or another interface at any time via the add custom token.

**Comment by tayvano** [comment]
You can read about how to add a new default token here: https://myetherwallet.groovehq.com/knowledge_base/topics/i-just-created-a-new-token-can-you-add-it-to-mew
