### ISSUE TITLE
 Not a valid ERC-20 token | MCI

### ISSUE THREAD

**Issue by montehansen** [kvhnuke/etherwallet#954]
I have 2 wallets that magically appeared sometime past midnight last night:

Not a valid ERC-20 token | MCI

I did not purchase anything by the name of MCI.

**Comment by montehansen** [comment]
This appears even on a fresh wallet. I suspect the list of tokens is a magic/well-known list being populated at runtime, and one of the token addresses is bad. 

MCI
https://ethplorer.io/address/0x138a8752093f4f9a79aaedf48d4b9248fab93c9c

**Comment by tayvano** [comment]
fixed—will be live shortly
