### ISSUE TITLE
When decrypting new JSON/Keystore file, the page doesn't update with new wallet's info or update existing wallet's info.

### ISSUE THREAD

**Issue by sabr-p** [kvhnuke/etherwallet#96]
preconditions:
a - wallet with JSON key, and encripted.
b - open the "view details" of any wallet (using the JSON option, i did not test the plain text option)
c - note the values shown
these steps setup the required state to reproduce. note, i'm using the wallet locally (files cloned from github) not the .com address. should not make any difference.

now, reproduce:
1- keep the page open. do not touch it ;)
2 - make a transfer using an external tool. i tested with an inbound Tx, from an online wallet.
3 - wait for the block confirmations
4 - at the open page, click to open the JSON file
5 - delete the password, rewrite it again
6 - click the "unlock wallet" button
7 - bug: the wallet details remain with the same values as point c. above

note: the first time i "got" this bug, an incoming Tx of 50ETH was not showing, i panicked. had to hit reload on etherscan a few times to check the confirmations increasing. only then i could breathe again ;)

**Comment by tayvano** [comment]
Fixed
