### ISSUE TITLE
Not a valid ERC-20 Token when adding custom MTH Token

### ISSUE THREAD

**Issue by Birdeyman** [kvhnuke/etherwallet#966]
Hi,

I'm trying to add a custom token with the following details:
Address: 0xaF4DcE16Da2877f8c9e00544c93B62Ac40631F16
Decimals: 5
Token symbol: MTH

Once added, it shows Not a valid ERC-20 token rather than the balance.
Thanks

**Comment by tayvano** [comment]
You will have to ask Monetha. I have no idea. That's what it looks like it should be from etherscan. Perhaps they changed the contract?
