### ISSUE TITLE
Can not show token balances when using Chrome translation.

### ISSUE THREAD

**Issue by sot528** [kvhnuke/etherwallet#972]
When I use Google Chrome(60.0.3112.113) and his translation function, I can not show ERC20 token balances correctly.
![2017-09-04 13 42 15](https://user-images.githubusercontent.com/2289647/30011977-1e1bec06-9177-11e7-9c89-4ef490010abf.png)

This example is English to Japanese.
**読み込み中** means **loading** .
It will not finish.

**Comment by tayvano** [comment]
Change the node in the upper right to a different node.

**Comment by sot528** [comment]
@tayvano 
Thank you for your reply ;)
However if I do not use translate, then this problem was not happen.

So I thought this is kind of a bug.
Is this specification?

**Comment by tayvano** [comment]
It happens for me on English too. Sometimes the token balances do not load. This is a separate issue that will be resolved in v4

**Comment by sot528** [comment]
@tayvano 
Thank you for your answer. ;)
