### ISSUE TITLE
BLX Blockchain index vs BLX Bullioncoin

### ISSUE THREAD

**Issue by brossetti1** [kvhnuke/etherwallet#974]
Hey everyone,

jsut wanted to point out that the BLX being tracked in myethereum wallet is pointed to the Bullioncoin contract. I could be wrong about this but I cant find any site that uses BLX to describe Bullioncoin. So the issue may be two things:

1) BLX Blockchain index is not currently tracked on myetherwallet. Blockchain index should be added under altcoins, preferrably as BLX, unless Bullioncoin is still active.
2) BLX Bullioncoin is quiet possibly inactive or not being used and should be removed.

I noticed this when transferring BLX to my cold storage and then trying to check that the balance went through. looks like others are having the same issue, if you have further input on this [stack exchange](https://ethereum.stackexchange.com/questions/25808/please-help-i-dont-know-how-to-access-the-blx-i-sent-to-myetherwallet-it-say/25815#25815), it would be welcomed.

I looked over the code and it doesnt seem too hard to add the new ticker, I can complete the pull request if its similar to https://github.com/kvhnuke/etherwallet/pull/939.

**Comment by tayvano** [comment]
It is the communities responsibility to add, remove, or alter tokens. With as many as 20 tokens per day, we simply do not have the time nor willingness to give a shit about any of these tokens. You can find instructions on how to add token and token-sale related items to MEW here: 
https://myetherwallet.github.io/knowledge-base/tokens/token-creators-add-your-token-to-myetherwallet.html

**Comment by brossetti1** [comment]
well alright then, makes sense, thanks!
