### ISSUE TITLE
cant send ether using myetherwallet.com

### ISSUE THREAD

**Issue by laurencefass** [kvhnuke/etherwallet#980]
Urgent assistance required. I can't send ether from my wallet! Im using firefox. I'm running in firefox.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.myetherapi.com/eth. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

TypeError: data[0] is undefined
Stack trace:
[57]</customNode.prototype.getTransactionData/<@https://www.myetherwallet.com/js/etherwallet-master.js:6017:9
[57]</customNode.prototype.rawPost/<@https://www.myetherwallet.com/js/etherwallet-master.js:6074:9
processQueue@https://www.myetherwallet.com/js/etherwallet-master.js:46360:39
scheduleProcessQueue/<@https://www.myetherwallet.com/js/etherwallet-master.js:46405:9
$digest@https://www.myetherwallet.com/js/etherwallet-master.js:47517:17
$apply@https://www.myetherwallet.com/js/etherwallet-master.js:47807:15
done@https://www.myetherwallet.com/js/etherwallet-master.js:41949:38
completeRequest@https://www.myetherwallet.com/js/etherwallet-master.js:42168:9
requestError@https://www.myetherwallet.com/js/etherwallet-master.js:42107:11
 Possibly unhandled rejection: {}

**Comment by laurencefass** [comment]
the ETH balance is also not updating.

**Comment by maddog972** [comment]
i have the exact same issue

**Comment by mike-foucault** [comment]
Same issue ( using Chrome )

**Comment by tayvano** [comment]
Run your own node

Connect to that node in top right

Stop doing ICOs

The amount of traffic is like a badass mofo Russian DDOS except its all people who want to throw money at people without demanding anything in return. Jeez.
