### ISSUE TITLE
ETH balance not updating and not able to send from wallet

### ISSUE THREAD

**Issue by maddog972** [kvhnuke/etherwallet#982]
This was working fine last night.  I tried test transaction with my tokens also and clicking the generate button does nothing

**Comment by laurencefass** [comment]
whats the dev's policy on ensuring against breaking changes? i've been relying on this to make real transfers. is there a more reliable wallet available?

**Comment by tayvano** [comment]
The fact that all ya'll are so obsessed with ICOs that you take down the nodes and crash everything is not a "breaking" change on our end. 

Solution

- Run your own node

- Connect to that node in top right

- Stop doing ICOs

**Comment by laurencefass** [comment]
hi are you a dev? im not doing anything with ICO's... please can you assist to find a solution. is this a software problem, or a node problem? some saying things worked ok last night... we are not all ethereum tech experts. thanks.

**Comment by laurencefass** [comment]
the software isn't reporting any problems... certainly not in a user friendly manner... it just isn't working. i had to delve into javascript console logs to see there are problems. even then i can't determine if its a problem with a node or the software...

**Comment by laurencefass** [comment]
can i change the node from myetherwallet.com?

**Comment by maddog972** [comment]
top right corner laurencefass.
